// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        6u8, 23u8, 131u8, 79u8, 87u8, 228u8, 250u8, 90u8, 212u8, 176u8, 205u8, 16u8, 58u8, 25u8,
        220u8, 191u8, 107u8, 224u8, 72u8, 69u8, 10u8, 168u8, 97u8, 171u8, 230u8, 141u8, 107u8,
        232u8, 119u8, 52u8, 235u8, 226u8, 4u8, 139u8, 128u8, 189u8, 191u8, 107u8, 46u8, 131u8,
        112u8, 76u8, 228u8, 204u8, 68u8, 180u8, 46u8, 213u8, 143u8, 92u8, 235u8, 239u8, 80u8,
        196u8, 245u8, 86u8, 165u8, 185u8, 166u8, 80u8, 147u8, 26u8, 207u8, 93u8,
    ],
    [
        4u8, 213u8, 72u8, 162u8, 126u8, 118u8, 210u8, 81u8, 167u8, 20u8, 75u8, 84u8, 20u8, 7u8,
        98u8, 62u8, 54u8, 87u8, 75u8, 224u8, 73u8, 242u8, 70u8, 43u8, 108u8, 208u8, 32u8, 197u8,
        21u8, 132u8, 204u8, 79u8, 44u8, 137u8, 159u8, 243u8, 56u8, 42u8, 51u8, 109u8, 13u8, 73u8,
        11u8, 172u8, 27u8, 189u8, 111u8, 72u8, 24u8, 112u8, 5u8, 123u8, 175u8, 242u8, 80u8, 120u8,
        147u8, 138u8, 107u8, 44u8, 250u8, 25u8, 10u8, 87u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        14u8, 108u8, 249u8, 23u8, 101u8, 159u8, 130u8, 129u8, 138u8, 179u8, 17u8, 219u8, 150u8,
        155u8, 50u8, 151u8, 229u8, 32u8, 213u8, 144u8, 186u8, 240u8, 200u8, 169u8, 179u8, 100u8,
        192u8, 19u8, 16u8, 225u8, 80u8, 89u8, 11u8, 88u8, 63u8, 126u8, 159u8, 172u8, 189u8, 206u8,
        132u8, 167u8, 252u8, 245u8, 109u8, 194u8, 16u8, 199u8, 229u8, 73u8, 157u8, 205u8, 106u8,
        242u8, 79u8, 140u8, 76u8, 185u8, 18u8, 174u8, 163u8, 253u8, 57u8, 226u8,
    ],
    vk_beta_g2: [
        7u8, 45u8, 152u8, 5u8, 48u8, 195u8, 121u8, 199u8, 69u8, 131u8, 244u8, 144u8, 51u8, 33u8,
        91u8, 117u8, 131u8, 3u8, 189u8, 112u8, 17u8, 116u8, 174u8, 220u8, 65u8, 53u8, 14u8, 130u8,
        102u8, 140u8, 42u8, 216u8, 3u8, 201u8, 194u8, 124u8, 247u8, 191u8, 144u8, 196u8, 131u8,
        19u8, 103u8, 61u8, 50u8, 76u8, 217u8, 206u8, 116u8, 197u8, 6u8, 48u8, 39u8, 209u8, 32u8,
        84u8, 150u8, 252u8, 228u8, 35u8, 219u8, 73u8, 218u8, 132u8, 4u8, 189u8, 65u8, 67u8, 80u8,
        191u8, 53u8, 68u8, 95u8, 51u8, 213u8, 168u8, 199u8, 12u8, 112u8, 179u8, 116u8, 191u8,
        198u8, 178u8, 3u8, 95u8, 34u8, 48u8, 45u8, 76u8, 104u8, 2u8, 193u8, 218u8, 111u8, 240u8,
        45u8, 214u8, 46u8, 85u8, 169u8, 34u8, 39u8, 199u8, 204u8, 116u8, 7u8, 62u8, 153u8, 141u8,
        128u8, 153u8, 61u8, 98u8, 119u8, 167u8, 22u8, 33u8, 73u8, 180u8, 208u8, 193u8, 51u8, 117u8,
        163u8, 174u8, 1u8, 204u8,
    ],
    vk_gamma_g2: [
        28u8, 17u8, 150u8, 7u8, 192u8, 91u8, 144u8, 194u8, 234u8, 177u8, 15u8, 34u8, 246u8, 69u8,
        63u8, 154u8, 203u8, 161u8, 206u8, 193u8, 25u8, 132u8, 243u8, 31u8, 195u8, 156u8, 162u8,
        46u8, 96u8, 55u8, 156u8, 84u8, 15u8, 123u8, 168u8, 198u8, 69u8, 48u8, 167u8, 159u8, 59u8,
        136u8, 197u8, 200u8, 227u8, 233u8, 7u8, 23u8, 99u8, 220u8, 151u8, 72u8, 119u8, 160u8, 10u8,
        19u8, 2u8, 24u8, 105u8, 250u8, 193u8, 115u8, 69u8, 209u8, 1u8, 220u8, 76u8, 98u8, 57u8,
        52u8, 68u8, 188u8, 116u8, 117u8, 38u8, 27u8, 185u8, 114u8, 70u8, 250u8, 165u8, 222u8, 23u8,
        36u8, 29u8, 75u8, 114u8, 181u8, 231u8, 94u8, 234u8, 225u8, 198u8, 68u8, 205u8, 25u8, 17u8,
        154u8, 24u8, 225u8, 171u8, 134u8, 240u8, 14u8, 18u8, 35u8, 153u8, 36u8, 1u8, 170u8, 114u8,
        154u8, 223u8, 233u8, 52u8, 210u8, 178u8, 223u8, 152u8, 174u8, 242u8, 99u8, 211u8, 28u8,
        164u8, 196u8, 93u8, 214u8,
    ],
    vk_delta_g2: [
        3u8, 197u8, 41u8, 55u8, 182u8, 34u8, 167u8, 104u8, 135u8, 153u8, 114u8, 215u8, 49u8, 14u8,
        182u8, 230u8, 77u8, 54u8, 239u8, 242u8, 171u8, 231u8, 164u8, 155u8, 243u8, 151u8, 26u8,
        229u8, 32u8, 64u8, 160u8, 90u8, 9u8, 174u8, 169u8, 29u8, 84u8, 206u8, 176u8, 242u8, 117u8,
        231u8, 22u8, 135u8, 116u8, 119u8, 29u8, 88u8, 251u8, 223u8, 68u8, 26u8, 68u8, 95u8, 229u8,
        167u8, 25u8, 143u8, 136u8, 116u8, 109u8, 155u8, 104u8, 110u8, 24u8, 60u8, 189u8, 44u8,
        214u8, 50u8, 36u8, 72u8, 27u8, 199u8, 163u8, 135u8, 245u8, 132u8, 141u8, 70u8, 169u8,
        234u8, 4u8, 208u8, 187u8, 172u8, 211u8, 214u8, 60u8, 118u8, 42u8, 160u8, 193u8, 87u8, 47u8,
        242u8, 10u8, 249u8, 164u8, 199u8, 178u8, 71u8, 227u8, 132u8, 20u8, 206u8, 103u8, 226u8,
        160u8, 4u8, 143u8, 97u8, 53u8, 20u8, 192u8, 200u8, 175u8, 162u8, 252u8, 84u8, 227u8, 50u8,
        52u8, 232u8, 239u8, 81u8, 206u8, 192u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [89u8, 158u8, 168u8, 223u8, 3u8, 10u8, 37u8, 214u8, 10u8, 95u8, 98u8, 73u8, 186u8, 253u8, 221u8, 77u8, 89u8, 44u8, 178u8, 195u8, 104u8, 74u8, 235u8, 139u8, 14u8, 124u8, 237u8, 61u8, 33u8, 61u8, 63u8, 162u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_cc5387d5f75cc1f0")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00599ea8df030a25d60a5f6249bafddd4d592cb2c3684aeb8b0e7ced3d213d3fa2\x00=======END GROTH16 VK SETUP V1=======\x00";
