// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        33u8, 50u8, 3u8, 158u8, 48u8, 88u8, 152u8, 40u8, 124u8, 158u8, 18u8, 10u8, 121u8, 12u8,
        52u8, 147u8, 130u8, 27u8, 243u8, 70u8, 112u8, 132u8, 22u8, 253u8, 117u8, 79u8, 130u8,
        172u8, 218u8, 107u8, 246u8, 165u8, 8u8, 211u8, 228u8, 69u8, 255u8, 143u8, 195u8, 199u8,
        198u8, 199u8, 161u8, 183u8, 240u8, 157u8, 206u8, 247u8, 45u8, 69u8, 73u8, 18u8, 87u8,
        111u8, 151u8, 165u8, 183u8, 232u8, 66u8, 178u8, 110u8, 160u8, 99u8, 172u8,
    ],
    [
        3u8, 78u8, 112u8, 223u8, 229u8, 14u8, 90u8, 143u8, 47u8, 139u8, 142u8, 210u8, 159u8, 234u8,
        248u8, 143u8, 127u8, 61u8, 166u8, 40u8, 185u8, 116u8, 45u8, 75u8, 149u8, 223u8, 162u8,
        151u8, 61u8, 164u8, 243u8, 248u8, 34u8, 17u8, 2u8, 64u8, 244u8, 66u8, 78u8, 164u8, 116u8,
        116u8, 233u8, 240u8, 1u8, 187u8, 211u8, 52u8, 229u8, 66u8, 249u8, 125u8, 134u8, 193u8,
        35u8, 172u8, 111u8, 80u8, 112u8, 138u8, 65u8, 202u8, 253u8, 169u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        17u8, 109u8, 17u8, 130u8, 224u8, 165u8, 63u8, 40u8, 200u8, 219u8, 108u8, 185u8, 16u8, 91u8,
        28u8, 78u8, 9u8, 204u8, 47u8, 32u8, 85u8, 208u8, 31u8, 179u8, 246u8, 129u8, 29u8, 142u8,
        144u8, 15u8, 178u8, 145u8, 1u8, 189u8, 82u8, 234u8, 206u8, 210u8, 165u8, 9u8, 14u8, 114u8,
        70u8, 80u8, 76u8, 190u8, 135u8, 160u8, 34u8, 138u8, 222u8, 135u8, 188u8, 17u8, 98u8, 72u8,
        38u8, 184u8, 83u8, 172u8, 216u8, 70u8, 188u8, 65u8,
    ],
    vk_beta_g2: [
        11u8, 39u8, 100u8, 128u8, 189u8, 11u8, 76u8, 196u8, 57u8, 186u8, 165u8, 90u8, 99u8, 161u8,
        255u8, 112u8, 16u8, 19u8, 12u8, 64u8, 176u8, 113u8, 166u8, 246u8, 166u8, 178u8, 232u8,
        162u8, 23u8, 44u8, 210u8, 123u8, 5u8, 190u8, 95u8, 133u8, 151u8, 84u8, 116u8, 100u8, 94u8,
        139u8, 186u8, 179u8, 249u8, 59u8, 230u8, 119u8, 233u8, 223u8, 179u8, 212u8, 212u8, 94u8,
        147u8, 210u8, 209u8, 31u8, 79u8, 94u8, 75u8, 56u8, 97u8, 160u8, 9u8, 205u8, 72u8, 0u8,
        241u8, 90u8, 181u8, 198u8, 255u8, 221u8, 93u8, 197u8, 8u8, 40u8, 85u8, 133u8, 95u8, 124u8,
        202u8, 83u8, 190u8, 32u8, 130u8, 229u8, 60u8, 7u8, 174u8, 192u8, 159u8, 175u8, 183u8, 47u8,
        6u8, 110u8, 158u8, 60u8, 120u8, 22u8, 216u8, 80u8, 42u8, 190u8, 131u8, 169u8, 94u8, 36u8,
        80u8, 75u8, 123u8, 85u8, 251u8, 226u8, 118u8, 66u8, 234u8, 43u8, 6u8, 175u8, 166u8, 189u8,
        207u8, 180u8, 3u8, 131u8,
    ],
    vk_gamma_g2: [
        31u8, 243u8, 87u8, 13u8, 204u8, 245u8, 129u8, 217u8, 22u8, 140u8, 27u8, 158u8, 235u8,
        163u8, 151u8, 118u8, 119u8, 85u8, 55u8, 130u8, 115u8, 233u8, 38u8, 126u8, 128u8, 173u8,
        43u8, 229u8, 199u8, 138u8, 164u8, 125u8, 37u8, 111u8, 226u8, 249u8, 21u8, 246u8, 148u8,
        126u8, 132u8, 188u8, 154u8, 141u8, 120u8, 6u8, 34u8, 69u8, 200u8, 144u8, 235u8, 20u8,
        101u8, 247u8, 89u8, 107u8, 107u8, 72u8, 245u8, 233u8, 226u8, 46u8, 125u8, 169u8, 28u8,
        54u8, 162u8, 212u8, 11u8, 18u8, 143u8, 9u8, 238u8, 85u8, 89u8, 103u8, 2u8, 150u8, 90u8,
        68u8, 245u8, 224u8, 235u8, 172u8, 232u8, 43u8, 221u8, 136u8, 218u8, 67u8, 236u8, 179u8,
        111u8, 216u8, 114u8, 42u8, 2u8, 64u8, 69u8, 238u8, 37u8, 155u8, 5u8, 231u8, 192u8, 94u8,
        19u8, 106u8, 142u8, 22u8, 213u8, 209u8, 209u8, 60u8, 70u8, 135u8, 192u8, 156u8, 201u8,
        246u8, 28u8, 102u8, 46u8, 2u8, 180u8, 236u8, 254u8, 166u8,
    ],
    vk_delta_g2: [
        14u8, 197u8, 240u8, 138u8, 183u8, 172u8, 82u8, 192u8, 27u8, 43u8, 28u8, 201u8, 100u8, 58u8,
        148u8, 66u8, 16u8, 231u8, 155u8, 168u8, 231u8, 134u8, 108u8, 0u8, 249u8, 192u8, 126u8,
        204u8, 241u8, 101u8, 68u8, 165u8, 34u8, 164u8, 9u8, 214u8, 169u8, 219u8, 210u8, 114u8,
        44u8, 244u8, 60u8, 73u8, 183u8, 234u8, 241u8, 82u8, 243u8, 231u8, 239u8, 107u8, 135u8,
        42u8, 156u8, 53u8, 50u8, 91u8, 182u8, 148u8, 60u8, 154u8, 126u8, 196u8, 46u8, 222u8, 7u8,
        222u8, 117u8, 71u8, 243u8, 146u8, 199u8, 78u8, 242u8, 114u8, 17u8, 228u8, 66u8, 101u8,
        105u8, 236u8, 94u8, 80u8, 133u8, 82u8, 141u8, 121u8, 192u8, 188u8, 3u8, 61u8, 39u8, 86u8,
        98u8, 209u8, 23u8, 13u8, 245u8, 86u8, 41u8, 203u8, 164u8, 26u8, 34u8, 26u8, 83u8, 86u8,
        221u8, 47u8, 153u8, 214u8, 254u8, 214u8, 222u8, 98u8, 219u8, 152u8, 202u8, 251u8, 172u8,
        61u8, 207u8, 235u8, 46u8, 48u8, 80u8, 226u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [251u8, 85u8, 81u8, 109u8, 85u8, 158u8, 198u8, 109u8, 140u8, 179u8, 18u8, 175u8, 22u8, 129u8, 179u8, 225u8, 225u8, 19u8, 127u8, 49u8, 238u8, 2u8, 75u8, 29u8, 204u8, 237u8, 56u8, 30u8, 119u8, 73u8, 102u8, 148u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_68dee00ba9171344")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00fb55516d559ec66d8cb312af1681b3e1e1137f31ee024b1dcced381e77496694\x00=======END GROTH16 VK SETUP V1=======\x00";
