// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        45u8, 226u8, 187u8, 62u8, 36u8, 48u8, 201u8, 31u8, 74u8, 241u8, 226u8, 203u8, 155u8, 1u8,
        241u8, 0u8, 163u8, 163u8, 135u8, 143u8, 100u8, 191u8, 111u8, 172u8, 182u8, 55u8, 229u8,
        187u8, 221u8, 48u8, 201u8, 113u8, 17u8, 122u8, 217u8, 151u8, 237u8, 7u8, 216u8, 25u8, 37u8,
        35u8, 244u8, 129u8, 219u8, 140u8, 232u8, 201u8, 222u8, 139u8, 114u8, 240u8, 123u8, 152u8,
        36u8, 10u8, 122u8, 138u8, 174u8, 84u8, 162u8, 253u8, 136u8, 101u8,
    ],
    [
        8u8, 217u8, 230u8, 246u8, 252u8, 110u8, 125u8, 163u8, 19u8, 98u8, 53u8, 28u8, 69u8, 59u8,
        229u8, 109u8, 28u8, 173u8, 41u8, 121u8, 130u8, 176u8, 140u8, 102u8, 209u8, 23u8, 59u8,
        194u8, 149u8, 93u8, 57u8, 212u8, 1u8, 92u8, 164u8, 58u8, 9u8, 114u8, 20u8, 135u8, 52u8,
        25u8, 154u8, 6u8, 217u8, 139u8, 167u8, 53u8, 97u8, 248u8, 251u8, 4u8, 125u8, 114u8, 10u8,
        49u8, 236u8, 180u8, 159u8, 42u8, 150u8, 119u8, 7u8, 138u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        12u8, 25u8, 0u8, 25u8, 7u8, 23u8, 134u8, 34u8, 142u8, 185u8, 101u8, 199u8, 156u8, 228u8,
        39u8, 33u8, 135u8, 137u8, 61u8, 20u8, 242u8, 91u8, 100u8, 135u8, 129u8, 6u8, 37u8, 130u8,
        164u8, 147u8, 99u8, 73u8, 15u8, 33u8, 192u8, 120u8, 208u8, 254u8, 85u8, 83u8, 126u8, 96u8,
        57u8, 149u8, 236u8, 196u8, 189u8, 38u8, 182u8, 94u8, 249u8, 102u8, 197u8, 120u8, 40u8,
        123u8, 182u8, 168u8, 225u8, 107u8, 202u8, 249u8, 243u8, 194u8,
    ],
    vk_beta_g2: [
        47u8, 118u8, 210u8, 56u8, 6u8, 227u8, 153u8, 50u8, 80u8, 189u8, 137u8, 85u8, 2u8, 123u8,
        71u8, 107u8, 3u8, 70u8, 90u8, 75u8, 51u8, 247u8, 45u8, 141u8, 231u8, 20u8, 200u8, 242u8,
        9u8, 99u8, 74u8, 109u8, 22u8, 176u8, 223u8, 188u8, 252u8, 141u8, 19u8, 191u8, 146u8, 147u8,
        91u8, 69u8, 253u8, 122u8, 50u8, 108u8, 91u8, 228u8, 133u8, 176u8, 228u8, 172u8, 128u8,
        179u8, 243u8, 170u8, 79u8, 11u8, 115u8, 119u8, 215u8, 249u8, 42u8, 133u8, 159u8, 195u8,
        179u8, 190u8, 69u8, 247u8, 175u8, 45u8, 15u8, 93u8, 251u8, 17u8, 155u8, 72u8, 247u8, 138u8,
        94u8, 54u8, 24u8, 19u8, 244u8, 22u8, 198u8, 26u8, 178u8, 254u8, 118u8, 236u8, 5u8, 21u8,
        48u8, 91u8, 50u8, 24u8, 113u8, 183u8, 40u8, 189u8, 91u8, 11u8, 152u8, 143u8, 101u8, 36u8,
        32u8, 251u8, 146u8, 123u8, 71u8, 204u8, 143u8, 16u8, 98u8, 134u8, 43u8, 93u8, 238u8, 172u8,
        143u8, 196u8, 143u8, 241u8,
    ],
    vk_gamma_g2: [
        16u8, 139u8, 234u8, 187u8, 249u8, 182u8, 165u8, 75u8, 144u8, 105u8, 142u8, 179u8, 78u8,
        252u8, 231u8, 30u8, 54u8, 93u8, 126u8, 66u8, 117u8, 157u8, 74u8, 35u8, 191u8, 244u8, 142u8,
        243u8, 255u8, 99u8, 10u8, 119u8, 6u8, 131u8, 142u8, 84u8, 56u8, 216u8, 13u8, 199u8, 94u8,
        135u8, 112u8, 17u8, 248u8, 138u8, 118u8, 113u8, 88u8, 67u8, 197u8, 175u8, 154u8, 80u8,
        170u8, 140u8, 253u8, 112u8, 20u8, 120u8, 73u8, 146u8, 175u8, 136u8, 5u8, 70u8, 126u8, 82u8,
        245u8, 141u8, 111u8, 158u8, 83u8, 128u8, 72u8, 247u8, 80u8, 80u8, 62u8, 58u8, 192u8, 111u8,
        165u8, 5u8, 18u8, 35u8, 205u8, 230u8, 218u8, 75u8, 121u8, 15u8, 174u8, 40u8, 106u8, 61u8,
        43u8, 237u8, 37u8, 161u8, 185u8, 10u8, 252u8, 121u8, 33u8, 133u8, 208u8, 81u8, 130u8,
        143u8, 38u8, 210u8, 193u8, 210u8, 140u8, 231u8, 135u8, 252u8, 43u8, 94u8, 62u8, 65u8,
        106u8, 183u8, 59u8, 178u8, 137u8, 31u8,
    ],
    vk_delta_g2: [
        20u8, 168u8, 173u8, 6u8, 209u8, 35u8, 190u8, 149u8, 62u8, 122u8, 48u8, 113u8, 141u8, 239u8,
        39u8, 86u8, 44u8, 195u8, 224u8, 197u8, 146u8, 200u8, 35u8, 244u8, 40u8, 147u8, 22u8, 140u8,
        33u8, 126u8, 227u8, 247u8, 5u8, 81u8, 246u8, 116u8, 62u8, 240u8, 56u8, 162u8, 6u8, 167u8,
        114u8, 225u8, 122u8, 212u8, 255u8, 156u8, 29u8, 146u8, 253u8, 164u8, 91u8, 67u8, 16u8,
        211u8, 105u8, 147u8, 234u8, 66u8, 138u8, 239u8, 191u8, 203u8, 35u8, 163u8, 40u8, 67u8,
        194u8, 145u8, 145u8, 79u8, 150u8, 14u8, 228u8, 201u8, 26u8, 151u8, 49u8, 15u8, 228u8, 48u8,
        8u8, 76u8, 89u8, 21u8, 129u8, 216u8, 167u8, 92u8, 231u8, 77u8, 117u8, 187u8, 45u8, 149u8,
        3u8, 180u8, 1u8, 56u8, 96u8, 30u8, 88u8, 0u8, 152u8, 155u8, 169u8, 208u8, 179u8, 192u8,
        143u8, 177u8, 239u8, 197u8, 79u8, 115u8, 22u8, 97u8, 74u8, 217u8, 212u8, 43u8, 245u8, 70u8,
        4u8, 79u8, 169u8, 224u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [65u8, 213u8, 121u8, 104u8, 79u8, 181u8, 143u8, 205u8, 2u8, 235u8, 211u8, 138u8, 81u8, 212u8, 33u8, 245u8, 113u8, 69u8, 115u8, 160u8, 230u8, 162u8, 186u8, 254u8, 204u8, 188u8, 214u8, 141u8, 217u8, 117u8, 217u8, 167u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_1063318087dab383")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x0041d579684fb58fcd02ebd38a51d421f5714573a0e6a2bafeccbcd68dd975d9a7\x00=======END GROTH16 VK SETUP V1=======\x00";
