// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        19u8, 89u8, 247u8, 133u8, 96u8, 148u8, 53u8, 219u8, 217u8, 167u8, 147u8, 27u8, 157u8,
        230u8, 189u8, 42u8, 136u8, 219u8, 62u8, 74u8, 232u8, 205u8, 74u8, 102u8, 244u8, 50u8,
        123u8, 71u8, 143u8, 205u8, 227u8, 133u8, 42u8, 237u8, 202u8, 154u8, 139u8, 165u8, 61u8,
        93u8, 167u8, 124u8, 26u8, 195u8, 27u8, 158u8, 105u8, 254u8, 123u8, 215u8, 236u8, 233u8,
        101u8, 247u8, 232u8, 92u8, 170u8, 71u8, 139u8, 155u8, 154u8, 237u8, 26u8, 30u8,
    ],
    [
        27u8, 48u8, 57u8, 110u8, 7u8, 115u8, 234u8, 43u8, 89u8, 199u8, 208u8, 240u8, 237u8, 17u8,
        207u8, 59u8, 189u8, 149u8, 182u8, 254u8, 99u8, 79u8, 231u8, 141u8, 0u8, 73u8, 175u8, 73u8,
        210u8, 96u8, 117u8, 71u8, 27u8, 137u8, 128u8, 65u8, 50u8, 32u8, 44u8, 181u8, 27u8, 48u8,
        201u8, 248u8, 58u8, 152u8, 138u8, 45u8, 78u8, 144u8, 62u8, 86u8, 182u8, 216u8, 82u8, 174u8,
        15u8, 41u8, 91u8, 69u8, 66u8, 212u8, 83u8, 245u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        13u8, 194u8, 71u8, 52u8, 135u8, 18u8, 47u8, 229u8, 120u8, 65u8, 150u8, 25u8, 140u8, 156u8,
        72u8, 88u8, 55u8, 133u8, 56u8, 66u8, 173u8, 170u8, 27u8, 69u8, 207u8, 191u8, 252u8, 58u8,
        23u8, 155u8, 251u8, 120u8, 10u8, 169u8, 174u8, 9u8, 254u8, 104u8, 135u8, 249u8, 153u8,
        19u8, 152u8, 165u8, 108u8, 139u8, 97u8, 217u8, 144u8, 9u8, 8u8, 177u8, 28u8, 3u8, 178u8,
        135u8, 150u8, 4u8, 189u8, 91u8, 181u8, 178u8, 174u8, 84u8,
    ],
    vk_beta_g2: [
        35u8, 2u8, 239u8, 114u8, 61u8, 52u8, 28u8, 140u8, 8u8, 206u8, 151u8, 208u8, 144u8, 232u8,
        30u8, 90u8, 154u8, 30u8, 85u8, 196u8, 181u8, 45u8, 76u8, 47u8, 16u8, 215u8, 91u8, 229u8,
        233u8, 124u8, 9u8, 208u8, 42u8, 240u8, 180u8, 193u8, 191u8, 164u8, 63u8, 160u8, 214u8,
        235u8, 67u8, 162u8, 42u8, 237u8, 145u8, 10u8, 183u8, 248u8, 113u8, 164u8, 231u8, 122u8,
        233u8, 82u8, 231u8, 53u8, 78u8, 137u8, 114u8, 149u8, 78u8, 53u8, 15u8, 196u8, 6u8, 232u8,
        69u8, 243u8, 224u8, 87u8, 97u8, 159u8, 196u8, 122u8, 205u8, 175u8, 253u8, 101u8, 178u8,
        8u8, 48u8, 38u8, 114u8, 200u8, 27u8, 34u8, 111u8, 112u8, 91u8, 97u8, 113u8, 175u8, 146u8,
        21u8, 27u8, 44u8, 167u8, 57u8, 168u8, 80u8, 229u8, 42u8, 94u8, 39u8, 79u8, 131u8, 228u8,
        143u8, 201u8, 55u8, 83u8, 124u8, 251u8, 30u8, 26u8, 227u8, 141u8, 184u8, 134u8, 18u8, 76u8,
        72u8, 35u8, 165u8, 104u8, 105u8,
    ],
    vk_gamma_g2: [
        10u8, 251u8, 96u8, 214u8, 120u8, 126u8, 213u8, 233u8, 164u8, 80u8, 215u8, 193u8, 191u8,
        218u8, 194u8, 186u8, 161u8, 173u8, 148u8, 15u8, 178u8, 243u8, 56u8, 54u8, 159u8, 31u8,
        118u8, 20u8, 48u8, 157u8, 207u8, 17u8, 21u8, 139u8, 40u8, 83u8, 78u8, 36u8, 96u8, 106u8,
        132u8, 0u8, 188u8, 203u8, 153u8, 94u8, 13u8, 55u8, 125u8, 192u8, 78u8, 107u8, 49u8, 228u8,
        111u8, 69u8, 206u8, 253u8, 25u8, 59u8, 96u8, 10u8, 38u8, 20u8, 7u8, 239u8, 227u8, 219u8,
        184u8, 204u8, 248u8, 38u8, 155u8, 159u8, 5u8, 15u8, 223u8, 145u8, 189u8, 166u8, 76u8,
        126u8, 80u8, 199u8, 184u8, 249u8, 217u8, 167u8, 183u8, 169u8, 102u8, 147u8, 206u8, 216u8,
        142u8, 131u8, 30u8, 114u8, 137u8, 60u8, 51u8, 48u8, 124u8, 108u8, 188u8, 92u8, 255u8, 25u8,
        83u8, 239u8, 89u8, 141u8, 242u8, 10u8, 23u8, 129u8, 153u8, 223u8, 187u8, 133u8, 201u8,
        216u8, 86u8, 251u8, 251u8, 59u8, 39u8, 201u8,
    ],
    vk_delta_g2: [
        31u8, 246u8, 155u8, 171u8, 242u8, 113u8, 97u8, 97u8, 249u8, 74u8, 169u8, 224u8, 122u8,
        211u8, 173u8, 112u8, 128u8, 172u8, 78u8, 77u8, 57u8, 130u8, 23u8, 145u8, 217u8, 14u8, 58u8,
        9u8, 253u8, 16u8, 57u8, 80u8, 33u8, 97u8, 87u8, 148u8, 57u8, 89u8, 213u8, 187u8, 14u8,
        248u8, 145u8, 180u8, 191u8, 19u8, 172u8, 23u8, 74u8, 181u8, 213u8, 45u8, 213u8, 131u8,
        222u8, 101u8, 149u8, 116u8, 184u8, 60u8, 169u8, 222u8, 6u8, 107u8, 11u8, 185u8, 132u8,
        192u8, 65u8, 112u8, 67u8, 230u8, 232u8, 87u8, 50u8, 226u8, 116u8, 113u8, 185u8, 75u8, 90u8,
        146u8, 228u8, 207u8, 158u8, 198u8, 174u8, 123u8, 130u8, 117u8, 97u8, 68u8, 48u8, 213u8,
        128u8, 244u8, 5u8, 166u8, 179u8, 79u8, 248u8, 120u8, 245u8, 51u8, 4u8, 157u8, 81u8, 21u8,
        41u8, 13u8, 131u8, 47u8, 187u8, 128u8, 164u8, 183u8, 110u8, 169u8, 239u8, 243u8, 57u8,
        208u8, 238u8, 87u8, 222u8, 109u8, 97u8, 222u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [184u8, 37u8, 72u8, 85u8, 94u8, 68u8, 229u8, 232u8, 37u8, 33u8, 15u8, 238u8, 240u8, 172u8, 89u8, 81u8, 9u8, 92u8, 120u8, 39u8, 233u8, 93u8, 106u8, 185u8, 227u8, 86u8, 34u8, 62u8, 153u8, 135u8, 214u8, 205u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_51173eacffe42914")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00b82548555e44e5e825210feef0ac5951095c7827e95d6ab9e356223e9987d6cd\x00=======END GROTH16 VK SETUP V1=======\x00";
