// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        20u8, 214u8, 179u8, 70u8, 8u8, 222u8, 24u8, 99u8, 186u8, 48u8, 149u8, 175u8, 111u8, 41u8,
        154u8, 163u8, 209u8, 154u8, 124u8, 175u8, 58u8, 244u8, 142u8, 118u8, 254u8, 139u8, 205u8,
        167u8, 224u8, 134u8, 123u8, 157u8, 4u8, 9u8, 114u8, 73u8, 211u8, 159u8, 216u8, 71u8, 28u8,
        127u8, 128u8, 139u8, 117u8, 183u8, 12u8, 78u8, 30u8, 206u8, 103u8, 239u8, 24u8, 170u8,
        129u8, 111u8, 189u8, 163u8, 204u8, 221u8, 249u8, 254u8, 87u8, 131u8,
    ],
    [
        37u8, 135u8, 57u8, 22u8, 61u8, 224u8, 30u8, 25u8, 105u8, 248u8, 51u8, 85u8, 73u8, 84u8,
        141u8, 129u8, 170u8, 179u8, 119u8, 145u8, 200u8, 237u8, 223u8, 24u8, 28u8, 16u8, 183u8,
        90u8, 162u8, 120u8, 68u8, 52u8, 0u8, 1u8, 159u8, 112u8, 28u8, 162u8, 241u8, 59u8, 215u8,
        184u8, 30u8, 199u8, 254u8, 214u8, 93u8, 156u8, 60u8, 163u8, 2u8, 29u8, 152u8, 219u8, 143u8,
        94u8, 178u8, 41u8, 217u8, 214u8, 190u8, 26u8, 144u8, 134u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        8u8, 127u8, 3u8, 255u8, 77u8, 147u8, 159u8, 203u8, 199u8, 39u8, 252u8, 115u8, 235u8, 24u8,
        84u8, 8u8, 202u8, 115u8, 173u8, 112u8, 168u8, 36u8, 160u8, 134u8, 132u8, 248u8, 79u8, 13u8,
        206u8, 139u8, 102u8, 7u8, 25u8, 136u8, 8u8, 193u8, 72u8, 205u8, 218u8, 127u8, 125u8, 146u8,
        96u8, 154u8, 241u8, 238u8, 191u8, 201u8, 0u8, 78u8, 211u8, 22u8, 6u8, 5u8, 179u8, 254u8,
        119u8, 152u8, 97u8, 37u8, 49u8, 178u8, 225u8, 245u8,
    ],
    vk_beta_g2: [
        33u8, 48u8, 248u8, 173u8, 196u8, 255u8, 108u8, 242u8, 20u8, 109u8, 66u8, 56u8, 205u8, 87u8,
        138u8, 135u8, 124u8, 122u8, 237u8, 158u8, 199u8, 13u8, 127u8, 100u8, 161u8, 243u8, 48u8,
        69u8, 25u8, 129u8, 53u8, 69u8, 10u8, 93u8, 63u8, 14u8, 27u8, 59u8, 64u8, 18u8, 88u8, 82u8,
        251u8, 28u8, 103u8, 61u8, 93u8, 141u8, 15u8, 158u8, 23u8, 253u8, 198u8, 152u8, 66u8, 181u8,
        239u8, 196u8, 34u8, 2u8, 238u8, 166u8, 113u8, 33u8, 12u8, 75u8, 37u8, 34u8, 12u8, 24u8,
        171u8, 15u8, 82u8, 158u8, 166u8, 117u8, 247u8, 66u8, 81u8, 141u8, 57u8, 141u8, 92u8, 192u8,
        215u8, 115u8, 85u8, 220u8, 167u8, 162u8, 247u8, 203u8, 3u8, 76u8, 126u8, 244u8, 11u8,
        219u8, 213u8, 72u8, 157u8, 82u8, 228u8, 75u8, 226u8, 136u8, 8u8, 147u8, 13u8, 37u8, 81u8,
        41u8, 133u8, 134u8, 65u8, 190u8, 194u8, 209u8, 69u8, 60u8, 57u8, 116u8, 82u8, 19u8, 25u8,
        211u8, 242u8, 219u8,
    ],
    vk_gamma_g2: [
        14u8, 13u8, 9u8, 247u8, 168u8, 72u8, 108u8, 48u8, 82u8, 254u8, 236u8, 192u8, 162u8, 95u8,
        153u8, 140u8, 105u8, 212u8, 13u8, 67u8, 228u8, 135u8, 246u8, 146u8, 46u8, 82u8, 86u8,
        215u8, 170u8, 143u8, 12u8, 198u8, 33u8, 8u8, 46u8, 127u8, 218u8, 48u8, 161u8, 64u8, 97u8,
        199u8, 91u8, 138u8, 185u8, 147u8, 61u8, 217u8, 210u8, 137u8, 194u8, 17u8, 55u8, 231u8,
        52u8, 55u8, 92u8, 97u8, 2u8, 134u8, 158u8, 72u8, 80u8, 135u8, 42u8, 165u8, 100u8, 108u8,
        47u8, 12u8, 176u8, 229u8, 207u8, 98u8, 15u8, 156u8, 9u8, 224u8, 19u8, 137u8, 182u8, 94u8,
        11u8, 143u8, 220u8, 110u8, 45u8, 165u8, 13u8, 11u8, 172u8, 194u8, 217u8, 205u8, 165u8,
        106u8, 19u8, 193u8, 33u8, 229u8, 79u8, 31u8, 127u8, 0u8, 125u8, 24u8, 218u8, 228u8, 105u8,
        81u8, 8u8, 177u8, 21u8, 146u8, 3u8, 40u8, 2u8, 58u8, 134u8, 26u8, 0u8, 235u8, 69u8, 59u8,
        117u8, 191u8, 44u8, 148u8,
    ],
    vk_delta_g2: [
        10u8, 115u8, 141u8, 176u8, 17u8, 210u8, 88u8, 107u8, 244u8, 181u8, 48u8, 180u8, 50u8,
        101u8, 156u8, 104u8, 48u8, 84u8, 11u8, 221u8, 219u8, 40u8, 63u8, 143u8, 82u8, 181u8, 189u8,
        47u8, 181u8, 145u8, 248u8, 222u8, 26u8, 216u8, 74u8, 7u8, 81u8, 247u8, 218u8, 225u8, 63u8,
        144u8, 235u8, 237u8, 191u8, 193u8, 215u8, 106u8, 80u8, 238u8, 214u8, 242u8, 189u8, 249u8,
        157u8, 62u8, 117u8, 97u8, 201u8, 50u8, 40u8, 50u8, 42u8, 232u8, 35u8, 240u8, 156u8, 187u8,
        179u8, 253u8, 4u8, 2u8, 145u8, 243u8, 248u8, 215u8, 130u8, 73u8, 117u8, 227u8, 194u8,
        188u8, 215u8, 14u8, 113u8, 51u8, 131u8, 77u8, 131u8, 161u8, 65u8, 34u8, 144u8, 74u8, 10u8,
        10u8, 12u8, 58u8, 218u8, 97u8, 19u8, 119u8, 97u8, 175u8, 227u8, 244u8, 83u8, 52u8, 212u8,
        229u8, 90u8, 39u8, 138u8, 138u8, 209u8, 185u8, 74u8, 38u8, 123u8, 175u8, 53u8, 35u8, 187u8,
        83u8, 125u8, 0u8, 144u8, 18u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [223u8, 161u8, 116u8, 73u8, 204u8, 90u8, 21u8, 209u8, 85u8, 255u8, 120u8, 133u8, 35u8, 189u8, 185u8, 13u8, 16u8, 125u8, 27u8, 187u8, 138u8, 62u8, 194u8, 175u8, 204u8, 246u8, 96u8, 74u8, 169u8, 108u8, 118u8, 170u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_04ba16e9aa0daddd")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00dfa17449cc5a15d155ff788523bdb90d107d1bbb8a3ec2afccf6604aa96c76aa\x00=======END GROTH16 VK SETUP V1=======\x00";
