// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        11u8, 0u8, 143u8, 125u8, 120u8, 201u8, 47u8, 111u8, 223u8, 97u8, 27u8, 85u8, 255u8, 23u8,
        91u8, 91u8, 245u8, 150u8, 100u8, 171u8, 166u8, 160u8, 228u8, 47u8, 246u8, 221u8, 87u8,
        140u8, 228u8, 214u8, 183u8, 4u8, 40u8, 155u8, 186u8, 63u8, 103u8, 53u8, 56u8, 192u8, 162u8,
        25u8, 128u8, 21u8, 209u8, 203u8, 80u8, 160u8, 117u8, 81u8, 143u8, 41u8, 71u8, 112u8, 66u8,
        219u8, 131u8, 210u8, 225u8, 75u8, 73u8, 94u8, 255u8, 47u8,
    ],
    [
        20u8, 51u8, 86u8, 26u8, 75u8, 41u8, 254u8, 141u8, 218u8, 251u8, 166u8, 220u8, 218u8, 73u8,
        10u8, 126u8, 214u8, 194u8, 127u8, 67u8, 197u8, 246u8, 8u8, 34u8, 130u8, 197u8, 166u8,
        221u8, 115u8, 153u8, 113u8, 240u8, 41u8, 153u8, 186u8, 241u8, 95u8, 225u8, 210u8, 45u8,
        244u8, 90u8, 64u8, 148u8, 34u8, 69u8, 20u8, 196u8, 220u8, 37u8, 19u8, 117u8, 99u8, 30u8,
        159u8, 73u8, 222u8, 154u8, 140u8, 55u8, 17u8, 203u8, 194u8, 83u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        12u8, 170u8, 113u8, 17u8, 77u8, 139u8, 113u8, 19u8, 139u8, 207u8, 195u8, 30u8, 101u8, 20u8,
        194u8, 101u8, 184u8, 109u8, 231u8, 108u8, 72u8, 23u8, 56u8, 72u8, 172u8, 50u8, 55u8, 179u8,
        201u8, 55u8, 140u8, 104u8, 29u8, 115u8, 89u8, 90u8, 149u8, 209u8, 72u8, 68u8, 39u8, 198u8,
        109u8, 139u8, 96u8, 127u8, 188u8, 246u8, 67u8, 213u8, 87u8, 23u8, 112u8, 35u8, 50u8, 74u8,
        3u8, 187u8, 36u8, 190u8, 68u8, 192u8, 29u8, 44u8,
    ],
    vk_beta_g2: [
        22u8, 141u8, 35u8, 19u8, 253u8, 240u8, 74u8, 195u8, 157u8, 131u8, 177u8, 204u8, 231u8, 8u8,
        57u8, 29u8, 150u8, 202u8, 196u8, 134u8, 108u8, 244u8, 204u8, 174u8, 187u8, 58u8, 87u8,
        63u8, 227u8, 11u8, 39u8, 193u8, 38u8, 94u8, 243u8, 221u8, 244u8, 20u8, 84u8, 232u8, 40u8,
        47u8, 123u8, 61u8, 119u8, 105u8, 244u8, 209u8, 116u8, 212u8, 81u8, 53u8, 34u8, 75u8, 50u8,
        17u8, 42u8, 99u8, 120u8, 225u8, 97u8, 241u8, 47u8, 140u8, 2u8, 103u8, 201u8, 30u8, 138u8,
        203u8, 116u8, 162u8, 117u8, 135u8, 148u8, 60u8, 45u8, 244u8, 120u8, 175u8, 28u8, 148u8,
        125u8, 134u8, 117u8, 53u8, 222u8, 237u8, 91u8, 210u8, 110u8, 33u8, 3u8, 63u8, 193u8, 123u8,
        40u8, 52u8, 8u8, 169u8, 243u8, 184u8, 0u8, 249u8, 72u8, 203u8, 214u8, 146u8, 168u8, 69u8,
        94u8, 246u8, 16u8, 117u8, 46u8, 202u8, 14u8, 90u8, 153u8, 124u8, 115u8, 155u8, 228u8, 70u8,
        168u8, 142u8, 101u8, 247u8,
    ],
    vk_gamma_g2: [
        28u8, 0u8, 45u8, 50u8, 238u8, 57u8, 205u8, 28u8, 115u8, 217u8, 219u8, 14u8, 236u8, 153u8,
        79u8, 215u8, 124u8, 71u8, 154u8, 172u8, 140u8, 212u8, 98u8, 38u8, 236u8, 182u8, 117u8,
        164u8, 164u8, 152u8, 209u8, 12u8, 1u8, 194u8, 9u8, 196u8, 220u8, 157u8, 18u8, 31u8, 157u8,
        34u8, 28u8, 49u8, 176u8, 196u8, 143u8, 248u8, 106u8, 211u8, 182u8, 173u8, 179u8, 225u8,
        153u8, 74u8, 108u8, 61u8, 251u8, 139u8, 133u8, 172u8, 80u8, 152u8, 40u8, 21u8, 227u8,
        216u8, 68u8, 126u8, 203u8, 49u8, 145u8, 122u8, 52u8, 222u8, 102u8, 64u8, 192u8, 78u8,
        190u8, 93u8, 19u8, 93u8, 213u8, 10u8, 126u8, 55u8, 228u8, 192u8, 158u8, 120u8, 209u8,
        212u8, 185u8, 112u8, 8u8, 18u8, 250u8, 232u8, 147u8, 238u8, 86u8, 74u8, 98u8, 192u8, 23u8,
        217u8, 77u8, 6u8, 86u8, 85u8, 63u8, 51u8, 123u8, 12u8, 221u8, 20u8, 78u8, 6u8, 253u8, 45u8,
        191u8, 235u8, 148u8, 109u8, 107u8, 189u8,
    ],
    vk_delta_g2: [
        18u8, 44u8, 180u8, 33u8, 185u8, 248u8, 11u8, 155u8, 78u8, 58u8, 188u8, 38u8, 140u8, 121u8,
        31u8, 32u8, 226u8, 5u8, 16u8, 110u8, 253u8, 40u8, 197u8, 157u8, 124u8, 241u8, 244u8, 196u8,
        199u8, 86u8, 132u8, 19u8, 32u8, 130u8, 185u8, 116u8, 185u8, 170u8, 195u8, 60u8, 1u8, 63u8,
        51u8, 223u8, 92u8, 122u8, 157u8, 94u8, 33u8, 149u8, 173u8, 194u8, 209u8, 200u8, 107u8,
        159u8, 216u8, 33u8, 193u8, 116u8, 11u8, 196u8, 62u8, 34u8, 29u8, 100u8, 32u8, 33u8, 41u8,
        109u8, 138u8, 191u8, 107u8, 186u8, 133u8, 190u8, 139u8, 99u8, 77u8, 67u8, 194u8, 195u8,
        60u8, 151u8, 74u8, 54u8, 78u8, 5u8, 29u8, 213u8, 186u8, 75u8, 27u8, 54u8, 171u8, 15u8,
        36u8, 157u8, 74u8, 224u8, 238u8, 53u8, 171u8, 62u8, 254u8, 214u8, 96u8, 29u8, 38u8, 165u8,
        130u8, 253u8, 233u8, 10u8, 164u8, 230u8, 189u8, 70u8, 222u8, 7u8, 231u8, 195u8, 201u8,
        54u8, 181u8, 248u8, 176u8, 131u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [111u8, 155u8, 9u8, 161u8, 202u8, 82u8, 44u8, 76u8, 168u8, 156u8, 117u8, 223u8, 86u8, 150u8, 149u8, 184u8, 32u8, 79u8, 74u8, 92u8, 8u8, 244u8, 255u8, 56u8, 119u8, 33u8, 67u8, 25u8, 134u8, 175u8, 18u8, 10u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_76012ccc06ab8114")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x006f9b09a1ca522c4ca89c75df569695b8204f4a5c08f4ff387721431986af120a\x00=======END GROTH16 VK SETUP V1=======\x00";
