// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        2u8, 181u8, 124u8, 136u8, 251u8, 124u8, 97u8, 120u8, 233u8, 3u8, 29u8, 157u8, 88u8, 230u8,
        63u8, 228u8, 211u8, 15u8, 34u8, 117u8, 138u8, 19u8, 72u8, 227u8, 58u8, 96u8, 171u8, 105u8,
        101u8, 157u8, 38u8, 82u8, 34u8, 210u8, 46u8, 48u8, 131u8, 84u8, 138u8, 91u8, 196u8, 91u8,
        143u8, 34u8, 141u8, 211u8, 17u8, 67u8, 154u8, 10u8, 209u8, 190u8, 77u8, 51u8, 253u8, 24u8,
        232u8, 91u8, 34u8, 183u8, 160u8, 238u8, 225u8, 7u8,
    ],
    [
        13u8, 116u8, 30u8, 231u8, 163u8, 176u8, 82u8, 255u8, 175u8, 211u8, 15u8, 58u8, 170u8,
        208u8, 43u8, 13u8, 131u8, 117u8, 58u8, 73u8, 58u8, 206u8, 149u8, 77u8, 190u8, 123u8, 64u8,
        85u8, 251u8, 129u8, 183u8, 170u8, 39u8, 202u8, 72u8, 170u8, 211u8, 86u8, 191u8, 129u8,
        168u8, 148u8, 140u8, 178u8, 111u8, 255u8, 93u8, 38u8, 208u8, 62u8, 160u8, 26u8, 141u8,
        190u8, 209u8, 197u8, 159u8, 153u8, 68u8, 131u8, 2u8, 4u8, 163u8, 99u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        25u8, 151u8, 92u8, 228u8, 181u8, 238u8, 245u8, 212u8, 232u8, 104u8, 124u8, 117u8, 97u8,
        124u8, 41u8, 48u8, 180u8, 2u8, 127u8, 129u8, 90u8, 223u8, 117u8, 164u8, 26u8, 224u8, 101u8,
        162u8, 70u8, 153u8, 176u8, 236u8, 33u8, 67u8, 252u8, 243u8, 52u8, 15u8, 190u8, 251u8,
        132u8, 106u8, 199u8, 185u8, 192u8, 84u8, 223u8, 215u8, 94u8, 174u8, 35u8, 66u8, 72u8,
        154u8, 21u8, 9u8, 227u8, 148u8, 151u8, 23u8, 6u8, 186u8, 142u8, 66u8,
    ],
    vk_beta_g2: [
        16u8, 176u8, 213u8, 176u8, 41u8, 106u8, 30u8, 116u8, 42u8, 252u8, 55u8, 204u8, 82u8, 60u8,
        49u8, 189u8, 167u8, 168u8, 188u8, 143u8, 105u8, 117u8, 12u8, 35u8, 150u8, 252u8, 154u8,
        205u8, 196u8, 195u8, 65u8, 13u8, 28u8, 174u8, 96u8, 37u8, 104u8, 147u8, 172u8, 233u8,
        228u8, 138u8, 113u8, 66u8, 92u8, 240u8, 255u8, 219u8, 109u8, 81u8, 124u8, 72u8, 246u8,
        226u8, 103u8, 73u8, 110u8, 60u8, 112u8, 121u8, 19u8, 132u8, 213u8, 237u8, 40u8, 99u8,
        106u8, 238u8, 89u8, 246u8, 137u8, 219u8, 146u8, 142u8, 6u8, 207u8, 77u8, 18u8, 195u8, 85u8,
        154u8, 170u8, 78u8, 159u8, 50u8, 107u8, 48u8, 76u8, 36u8, 234u8, 117u8, 187u8, 5u8, 79u8,
        245u8, 119u8, 19u8, 15u8, 144u8, 17u8, 114u8, 24u8, 53u8, 114u8, 15u8, 119u8, 166u8, 234u8,
        87u8, 42u8, 244u8, 80u8, 135u8, 175u8, 156u8, 66u8, 26u8, 22u8, 74u8, 164u8, 68u8, 73u8,
        56u8, 200u8, 246u8, 234u8, 42u8, 85u8,
    ],
    vk_gamma_g2: [
        36u8, 239u8, 62u8, 41u8, 60u8, 158u8, 220u8, 233u8, 199u8, 22u8, 54u8, 43u8, 122u8, 182u8,
        190u8, 210u8, 198u8, 161u8, 87u8, 225u8, 216u8, 15u8, 193u8, 230u8, 81u8, 125u8, 214u8,
        143u8, 97u8, 213u8, 244u8, 247u8, 45u8, 41u8, 186u8, 126u8, 136u8, 210u8, 132u8, 38u8,
        158u8, 194u8, 253u8, 243u8, 108u8, 69u8, 91u8, 140u8, 83u8, 116u8, 147u8, 71u8, 130u8,
        180u8, 105u8, 195u8, 96u8, 120u8, 225u8, 32u8, 73u8, 251u8, 42u8, 196u8, 44u8, 8u8, 127u8,
        50u8, 212u8, 82u8, 230u8, 183u8, 61u8, 148u8, 160u8, 52u8, 82u8, 96u8, 171u8, 182u8, 201u8,
        130u8, 56u8, 58u8, 18u8, 174u8, 244u8, 208u8, 89u8, 250u8, 77u8, 69u8, 136u8, 233u8, 221u8,
        58u8, 42u8, 106u8, 167u8, 57u8, 182u8, 101u8, 149u8, 248u8, 226u8, 66u8, 127u8, 152u8,
        105u8, 226u8, 73u8, 131u8, 148u8, 189u8, 254u8, 156u8, 12u8, 159u8, 118u8, 203u8, 34u8,
        104u8, 121u8, 205u8, 102u8, 53u8, 2u8, 45u8,
    ],
    vk_delta_g2: [
        36u8, 248u8, 83u8, 150u8, 196u8, 66u8, 235u8, 9u8, 90u8, 75u8, 178u8, 194u8, 25u8, 113u8,
        0u8, 16u8, 146u8, 46u8, 115u8, 242u8, 72u8, 7u8, 59u8, 185u8, 142u8, 159u8, 93u8, 36u8,
        125u8, 106u8, 32u8, 209u8, 4u8, 170u8, 235u8, 246u8, 76u8, 147u8, 248u8, 94u8, 138u8, 17u8,
        154u8, 10u8, 184u8, 47u8, 34u8, 111u8, 121u8, 164u8, 94u8, 249u8, 50u8, 216u8, 205u8,
        242u8, 107u8, 45u8, 221u8, 65u8, 10u8, 187u8, 73u8, 255u8, 21u8, 191u8, 62u8, 88u8, 155u8,
        166u8, 204u8, 68u8, 210u8, 4u8, 196u8, 99u8, 114u8, 255u8, 232u8, 182u8, 139u8, 89u8,
        129u8, 175u8, 109u8, 231u8, 102u8, 146u8, 74u8, 214u8, 66u8, 105u8, 130u8, 94u8, 249u8,
        194u8, 41u8, 178u8, 252u8, 220u8, 196u8, 170u8, 29u8, 185u8, 102u8, 84u8, 30u8, 113u8,
        142u8, 207u8, 62u8, 239u8, 106u8, 133u8, 108u8, 254u8, 19u8, 104u8, 51u8, 22u8, 210u8,
        142u8, 86u8, 13u8, 67u8, 107u8, 81u8, 139u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [160u8, 127u8, 49u8, 98u8, 234u8, 7u8, 113u8, 143u8, 104u8, 33u8, 7u8, 251u8, 71u8, 16u8, 73u8, 64u8, 27u8, 15u8, 97u8, 188u8, 25u8, 210u8, 245u8, 75u8, 163u8, 117u8, 63u8, 99u8, 30u8, 149u8, 48u8, 219u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_bbfd149cff078979")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00a07f3162ea07718f682107fb471049401b0f61bc19d2f54ba3753f631e9530db\x00=======END GROTH16 VK SETUP V1=======\x00";
