// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        31u8, 49u8, 138u8, 227u8, 183u8, 39u8, 104u8, 138u8, 99u8, 58u8, 1u8, 144u8, 200u8, 195u8,
        16u8, 199u8, 158u8, 144u8, 181u8, 177u8, 17u8, 23u8, 245u8, 106u8, 125u8, 147u8, 133u8,
        248u8, 146u8, 77u8, 208u8, 17u8, 28u8, 58u8, 202u8, 159u8, 191u8, 83u8, 149u8, 202u8, 3u8,
        144u8, 162u8, 168u8, 245u8, 97u8, 247u8, 251u8, 164u8, 119u8, 86u8, 101u8, 70u8, 183u8,
        34u8, 200u8, 251u8, 56u8, 0u8, 65u8, 166u8, 10u8, 211u8, 32u8,
    ],
    [
        5u8, 222u8, 223u8, 211u8, 75u8, 37u8, 51u8, 196u8, 143u8, 67u8, 113u8, 8u8, 65u8, 120u8,
        231u8, 201u8, 88u8, 13u8, 11u8, 89u8, 64u8, 39u8, 94u8, 196u8, 50u8, 96u8, 248u8, 247u8,
        154u8, 22u8, 121u8, 86u8, 33u8, 111u8, 113u8, 37u8, 28u8, 244u8, 180u8, 196u8, 212u8,
        102u8, 61u8, 197u8, 251u8, 217u8, 250u8, 9u8, 211u8, 236u8, 184u8, 205u8, 38u8, 94u8,
        178u8, 186u8, 92u8, 197u8, 201u8, 176u8, 105u8, 209u8, 11u8, 0u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        18u8, 246u8, 167u8, 184u8, 176u8, 8u8, 51u8, 46u8, 147u8, 107u8, 40u8, 58u8, 150u8, 85u8,
        243u8, 173u8, 166u8, 97u8, 196u8, 167u8, 82u8, 254u8, 104u8, 183u8, 178u8, 172u8, 42u8,
        194u8, 47u8, 145u8, 71u8, 113u8, 16u8, 128u8, 232u8, 209u8, 8u8, 73u8, 119u8, 14u8, 113u8,
        7u8, 8u8, 245u8, 174u8, 6u8, 221u8, 150u8, 103u8, 33u8, 179u8, 185u8, 180u8, 201u8, 15u8,
        6u8, 216u8, 76u8, 124u8, 251u8, 214u8, 182u8, 36u8, 22u8,
    ],
    vk_beta_g2: [
        45u8, 121u8, 133u8, 115u8, 221u8, 41u8, 79u8, 89u8, 151u8, 144u8, 90u8, 128u8, 193u8,
        131u8, 186u8, 129u8, 144u8, 34u8, 116u8, 202u8, 229u8, 252u8, 116u8, 102u8, 169u8, 215u8,
        162u8, 142u8, 185u8, 232u8, 185u8, 180u8, 32u8, 137u8, 62u8, 66u8, 180u8, 172u8, 11u8,
        237u8, 109u8, 156u8, 30u8, 175u8, 160u8, 231u8, 154u8, 69u8, 208u8, 114u8, 127u8, 143u8,
        218u8, 153u8, 18u8, 246u8, 12u8, 223u8, 102u8, 200u8, 161u8, 222u8, 250u8, 176u8, 5u8,
        148u8, 24u8, 218u8, 160u8, 168u8, 253u8, 217u8, 132u8, 160u8, 110u8, 213u8, 43u8, 151u8,
        59u8, 114u8, 175u8, 100u8, 79u8, 37u8, 245u8, 124u8, 249u8, 249u8, 92u8, 179u8, 16u8, 90u8,
        123u8, 31u8, 128u8, 8u8, 20u8, 195u8, 166u8, 207u8, 83u8, 27u8, 221u8, 2u8, 215u8, 133u8,
        6u8, 104u8, 62u8, 117u8, 31u8, 109u8, 81u8, 123u8, 160u8, 107u8, 250u8, 162u8, 20u8, 71u8,
        148u8, 230u8, 4u8, 83u8, 39u8, 96u8, 40u8, 89u8,
    ],
    vk_gamma_g2: [
        35u8, 187u8, 79u8, 143u8, 230u8, 101u8, 19u8, 223u8, 114u8, 163u8, 15u8, 223u8, 243u8,
        93u8, 130u8, 108u8, 109u8, 170u8, 157u8, 114u8, 240u8, 142u8, 32u8, 195u8, 221u8, 53u8,
        222u8, 60u8, 65u8, 57u8, 139u8, 168u8, 26u8, 40u8, 229u8, 151u8, 137u8, 41u8, 26u8, 191u8,
        191u8, 215u8, 4u8, 210u8, 128u8, 221u8, 194u8, 162u8, 154u8, 221u8, 106u8, 89u8, 140u8,
        63u8, 47u8, 89u8, 224u8, 34u8, 94u8, 187u8, 227u8, 131u8, 60u8, 244u8, 46u8, 218u8, 218u8,
        18u8, 237u8, 58u8, 67u8, 157u8, 209u8, 62u8, 130u8, 207u8, 26u8, 8u8, 20u8, 90u8, 210u8,
        151u8, 141u8, 135u8, 182u8, 44u8, 99u8, 252u8, 2u8, 118u8, 216u8, 101u8, 173u8, 106u8,
        212u8, 193u8, 27u8, 13u8, 194u8, 159u8, 27u8, 97u8, 95u8, 157u8, 153u8, 4u8, 68u8, 172u8,
        95u8, 189u8, 120u8, 136u8, 46u8, 23u8, 222u8, 111u8, 174u8, 133u8, 176u8, 39u8, 206u8, 3u8,
        138u8, 53u8, 132u8, 119u8, 54u8, 73u8,
    ],
    vk_delta_g2: [
        0u8, 217u8, 191u8, 98u8, 106u8, 102u8, 194u8, 82u8, 126u8, 27u8, 89u8, 138u8, 103u8, 145u8,
        4u8, 138u8, 139u8, 7u8, 83u8, 10u8, 222u8, 199u8, 22u8, 168u8, 76u8, 164u8, 98u8, 89u8,
        219u8, 18u8, 178u8, 136u8, 26u8, 109u8, 1u8, 40u8, 47u8, 144u8, 89u8, 246u8, 186u8, 226u8,
        21u8, 168u8, 0u8, 40u8, 151u8, 215u8, 225u8, 103u8, 84u8, 159u8, 30u8, 65u8, 208u8, 60u8,
        1u8, 127u8, 27u8, 184u8, 140u8, 138u8, 175u8, 156u8, 29u8, 168u8, 77u8, 177u8, 181u8, 1u8,
        245u8, 117u8, 64u8, 171u8, 200u8, 116u8, 164u8, 71u8, 250u8, 137u8, 212u8, 243u8, 136u8,
        39u8, 145u8, 210u8, 247u8, 58u8, 39u8, 236u8, 170u8, 136u8, 10u8, 254u8, 28u8, 204u8, 42u8,
        85u8, 41u8, 189u8, 220u8, 56u8, 215u8, 193u8, 81u8, 157u8, 7u8, 51u8, 207u8, 97u8, 247u8,
        166u8, 189u8, 31u8, 54u8, 103u8, 98u8, 155u8, 100u8, 236u8, 8u8, 12u8, 241u8, 233u8, 176u8,
        87u8, 177u8, 137u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [192u8, 93u8, 198u8, 19u8, 206u8, 136u8, 55u8, 114u8, 225u8, 192u8, 86u8, 71u8, 55u8, 45u8, 62u8, 108u8, 60u8, 75u8, 98u8, 85u8, 32u8, 199u8, 12u8, 153u8, 240u8, 235u8, 210u8, 249u8, 107u8, 3u8, 37u8, 102u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_1f49f0298c2893af")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00c05dc613ce883772e1c05647372d3e6c3c4b625520c70c99f0ebd2f96b032566\x00=======END GROTH16 VK SETUP V1=======\x00";
