// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        9u8, 226u8, 89u8, 42u8, 78u8, 197u8, 63u8, 64u8, 43u8, 249u8, 179u8, 97u8, 106u8, 251u8,
        1u8, 110u8, 229u8, 218u8, 48u8, 226u8, 97u8, 252u8, 108u8, 248u8, 217u8, 113u8, 165u8,
        61u8, 32u8, 40u8, 159u8, 153u8, 28u8, 247u8, 69u8, 207u8, 128u8, 114u8, 149u8, 168u8,
        234u8, 136u8, 97u8, 12u8, 139u8, 150u8, 75u8, 114u8, 93u8, 254u8, 25u8, 248u8, 88u8, 194u8,
        176u8, 20u8, 63u8, 171u8, 130u8, 113u8, 163u8, 224u8, 191u8, 128u8,
    ],
    [
        2u8, 0u8, 59u8, 13u8, 154u8, 36u8, 10u8, 96u8, 238u8, 163u8, 109u8, 156u8, 39u8, 173u8,
        37u8, 169u8, 174u8, 145u8, 246u8, 23u8, 188u8, 17u8, 44u8, 123u8, 244u8, 124u8, 0u8, 48u8,
        131u8, 77u8, 231u8, 127u8, 39u8, 36u8, 199u8, 84u8, 123u8, 37u8, 39u8, 198u8, 41u8, 167u8,
        161u8, 82u8, 73u8, 5u8, 99u8, 148u8, 120u8, 128u8, 224u8, 243u8, 103u8, 142u8, 152u8, 20u8,
        39u8, 220u8, 4u8, 20u8, 152u8, 28u8, 34u8, 157u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        42u8, 220u8, 13u8, 150u8, 209u8, 88u8, 123u8, 123u8, 236u8, 135u8, 16u8, 252u8, 176u8,
        187u8, 67u8, 152u8, 78u8, 20u8, 183u8, 55u8, 25u8, 65u8, 56u8, 126u8, 151u8, 151u8, 57u8,
        243u8, 204u8, 179u8, 232u8, 1u8, 29u8, 225u8, 254u8, 68u8, 237u8, 43u8, 43u8, 38u8, 235u8,
        233u8, 142u8, 56u8, 106u8, 120u8, 37u8, 20u8, 216u8, 110u8, 75u8, 69u8, 58u8, 169u8, 150u8,
        243u8, 2u8, 243u8, 170u8, 249u8, 71u8, 62u8, 25u8, 10u8,
    ],
    vk_beta_g2: [
        8u8, 189u8, 32u8, 214u8, 64u8, 189u8, 69u8, 107u8, 233u8, 182u8, 114u8, 23u8, 146u8, 93u8,
        182u8, 16u8, 111u8, 173u8, 48u8, 137u8, 251u8, 13u8, 236u8, 172u8, 63u8, 174u8, 44u8,
        163u8, 200u8, 118u8, 228u8, 156u8, 30u8, 191u8, 168u8, 77u8, 201u8, 119u8, 87u8, 117u8,
        150u8, 158u8, 38u8, 54u8, 231u8, 195u8, 76u8, 37u8, 96u8, 20u8, 115u8, 30u8, 91u8, 179u8,
        135u8, 32u8, 194u8, 199u8, 36u8, 179u8, 226u8, 98u8, 151u8, 9u8, 8u8, 218u8, 29u8, 142u8,
        171u8, 229u8, 110u8, 237u8, 5u8, 34u8, 136u8, 175u8, 121u8, 193u8, 255u8, 201u8, 39u8,
        187u8, 226u8, 56u8, 195u8, 60u8, 86u8, 49u8, 247u8, 105u8, 195u8, 15u8, 33u8, 168u8, 163u8,
        40u8, 37u8, 202u8, 84u8, 60u8, 241u8, 223u8, 249u8, 41u8, 88u8, 120u8, 135u8, 179u8, 164u8,
        179u8, 44u8, 183u8, 65u8, 144u8, 190u8, 201u8, 207u8, 229u8, 200u8, 223u8, 32u8, 8u8,
        139u8, 245u8, 25u8, 79u8, 124u8, 140u8,
    ],
    vk_gamma_g2: [
        13u8, 124u8, 107u8, 82u8, 227u8, 37u8, 166u8, 94u8, 248u8, 221u8, 137u8, 136u8, 110u8,
        153u8, 218u8, 91u8, 196u8, 207u8, 133u8, 117u8, 104u8, 152u8, 158u8, 52u8, 210u8, 120u8,
        173u8, 95u8, 239u8, 159u8, 188u8, 21u8, 3u8, 246u8, 108u8, 100u8, 74u8, 205u8, 208u8, 56u8,
        136u8, 231u8, 162u8, 110u8, 253u8, 22u8, 178u8, 193u8, 123u8, 162u8, 62u8, 246u8, 86u8,
        174u8, 26u8, 30u8, 188u8, 13u8, 6u8, 238u8, 166u8, 161u8, 32u8, 90u8, 43u8, 225u8, 143u8,
        156u8, 77u8, 80u8, 191u8, 75u8, 226u8, 0u8, 80u8, 123u8, 69u8, 58u8, 170u8, 34u8, 155u8,
        90u8, 244u8, 142u8, 191u8, 42u8, 172u8, 30u8, 88u8, 232u8, 180u8, 192u8, 3u8, 163u8, 221u8,
        102u8, 15u8, 56u8, 19u8, 112u8, 205u8, 74u8, 54u8, 144u8, 25u8, 217u8, 232u8, 171u8, 196u8,
        93u8, 140u8, 170u8, 41u8, 107u8, 161u8, 75u8, 3u8, 66u8, 242u8, 67u8, 19u8, 198u8, 106u8,
        64u8, 169u8, 98u8, 75u8, 56u8,
    ],
    vk_delta_g2: [
        31u8, 45u8, 54u8, 192u8, 255u8, 173u8, 35u8, 183u8, 28u8, 156u8, 38u8, 157u8, 235u8, 230u8,
        158u8, 127u8, 42u8, 133u8, 88u8, 5u8, 51u8, 250u8, 13u8, 33u8, 179u8, 175u8, 181u8, 91u8,
        5u8, 157u8, 192u8, 107u8, 2u8, 53u8, 30u8, 128u8, 31u8, 16u8, 139u8, 83u8, 85u8, 121u8,
        2u8, 186u8, 102u8, 112u8, 94u8, 71u8, 144u8, 6u8, 39u8, 46u8, 112u8, 47u8, 22u8, 110u8,
        131u8, 80u8, 151u8, 26u8, 19u8, 49u8, 1u8, 69u8, 10u8, 126u8, 179u8, 249u8, 135u8, 229u8,
        124u8, 135u8, 236u8, 66u8, 24u8, 142u8, 161u8, 59u8, 52u8, 73u8, 121u8, 42u8, 193u8, 165u8,
        177u8, 148u8, 53u8, 20u8, 234u8, 174u8, 241u8, 88u8, 9u8, 129u8, 56u8, 176u8, 47u8, 67u8,
        107u8, 197u8, 161u8, 215u8, 162u8, 162u8, 201u8, 207u8, 123u8, 142u8, 13u8, 39u8, 180u8,
        200u8, 85u8, 83u8, 223u8, 168u8, 184u8, 218u8, 148u8, 236u8, 124u8, 110u8, 232u8, 145u8,
        204u8, 55u8, 144u8, 210u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [176u8, 106u8, 164u8, 72u8, 14u8, 99u8, 18u8, 106u8, 122u8, 237u8, 10u8, 107u8, 73u8, 81u8, 82u8, 161u8, 133u8, 183u8, 190u8, 204u8, 66u8, 152u8, 112u8, 125u8, 143u8, 187u8, 59u8, 28u8, 84u8, 204u8, 194u8, 96u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_1516e7f07517597f")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00b06aa4480e63126a7aed0a6b495152a185b7becc4298707d8fbb3b1c54ccc260\x00=======END GROTH16 VK SETUP V1=======\x00";
