// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        30u8, 144u8, 60u8, 239u8, 132u8, 48u8, 32u8, 13u8, 249u8, 167u8, 73u8, 175u8, 220u8, 149u8,
        69u8, 216u8, 219u8, 149u8, 71u8, 10u8, 83u8, 154u8, 181u8, 186u8, 224u8, 223u8, 236u8,
        104u8, 223u8, 91u8, 1u8, 24u8, 34u8, 36u8, 157u8, 207u8, 188u8, 206u8, 1u8, 186u8, 124u8,
        23u8, 247u8, 148u8, 215u8, 240u8, 12u8, 243u8, 233u8, 23u8, 98u8, 0u8, 155u8, 153u8, 241u8,
        240u8, 54u8, 32u8, 222u8, 186u8, 240u8, 170u8, 187u8, 93u8,
    ],
    [
        43u8, 11u8, 255u8, 70u8, 245u8, 188u8, 113u8, 232u8, 181u8, 13u8, 72u8, 255u8, 117u8,
        255u8, 240u8, 4u8, 198u8, 255u8, 76u8, 108u8, 191u8, 98u8, 227u8, 40u8, 53u8, 177u8, 127u8,
        209u8, 244u8, 139u8, 124u8, 197u8, 13u8, 152u8, 254u8, 182u8, 66u8, 207u8, 68u8, 92u8,
        182u8, 225u8, 8u8, 124u8, 81u8, 13u8, 29u8, 232u8, 224u8, 30u8, 26u8, 111u8, 237u8, 203u8,
        127u8, 194u8, 19u8, 121u8, 20u8, 232u8, 195u8, 135u8, 237u8, 230u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        28u8, 249u8, 114u8, 125u8, 104u8, 165u8, 119u8, 143u8, 213u8, 80u8, 57u8, 124u8, 95u8,
        215u8, 198u8, 28u8, 80u8, 33u8, 126u8, 204u8, 149u8, 199u8, 4u8, 36u8, 66u8, 57u8, 162u8,
        148u8, 122u8, 149u8, 17u8, 188u8, 40u8, 84u8, 108u8, 5u8, 76u8, 50u8, 223u8, 48u8, 70u8,
        144u8, 92u8, 23u8, 97u8, 63u8, 189u8, 49u8, 91u8, 56u8, 208u8, 53u8, 88u8, 109u8, 91u8,
        76u8, 55u8, 205u8, 241u8, 212u8, 40u8, 210u8, 178u8, 152u8,
    ],
    vk_beta_g2: [
        11u8, 11u8, 183u8, 30u8, 131u8, 252u8, 171u8, 244u8, 167u8, 213u8, 239u8, 158u8, 11u8,
        214u8, 153u8, 74u8, 42u8, 247u8, 18u8, 110u8, 35u8, 100u8, 135u8, 191u8, 167u8, 235u8,
        228u8, 154u8, 222u8, 106u8, 201u8, 156u8, 9u8, 41u8, 113u8, 152u8, 235u8, 92u8, 102u8,
        20u8, 167u8, 135u8, 89u8, 219u8, 121u8, 102u8, 6u8, 219u8, 108u8, 6u8, 212u8, 14u8, 74u8,
        110u8, 211u8, 221u8, 182u8, 179u8, 120u8, 148u8, 198u8, 126u8, 26u8, 103u8, 17u8, 107u8,
        238u8, 161u8, 115u8, 34u8, 127u8, 135u8, 223u8, 105u8, 202u8, 111u8, 39u8, 192u8, 56u8,
        153u8, 225u8, 23u8, 98u8, 38u8, 195u8, 63u8, 72u8, 220u8, 125u8, 89u8, 99u8, 73u8, 155u8,
        101u8, 19u8, 235u8, 1u8, 169u8, 143u8, 186u8, 81u8, 155u8, 186u8, 124u8, 182u8, 86u8, 13u8,
        174u8, 82u8, 34u8, 161u8, 7u8, 143u8, 165u8, 249u8, 220u8, 14u8, 194u8, 20u8, 131u8, 116u8,
        130u8, 231u8, 179u8, 111u8, 43u8, 81u8, 98u8,
    ],
    vk_gamma_g2: [
        9u8, 199u8, 247u8, 189u8, 109u8, 30u8, 37u8, 123u8, 192u8, 120u8, 30u8, 66u8, 220u8, 155u8,
        105u8, 150u8, 88u8, 21u8, 35u8, 82u8, 185u8, 63u8, 157u8, 217u8, 174u8, 187u8, 110u8, 87u8,
        14u8, 86u8, 195u8, 193u8, 6u8, 207u8, 116u8, 213u8, 41u8, 219u8, 107u8, 65u8, 113u8, 4u8,
        175u8, 233u8, 54u8, 144u8, 239u8, 0u8, 29u8, 50u8, 239u8, 45u8, 58u8, 228u8, 65u8, 21u8,
        136u8, 22u8, 28u8, 207u8, 184u8, 190u8, 141u8, 7u8, 44u8, 128u8, 48u8, 170u8, 171u8, 124u8,
        190u8, 207u8, 254u8, 189u8, 6u8, 63u8, 45u8, 245u8, 197u8, 171u8, 228u8, 10u8, 247u8,
        163u8, 99u8, 33u8, 31u8, 229u8, 119u8, 32u8, 103u8, 205u8, 234u8, 171u8, 52u8, 102u8, 34u8,
        142u8, 167u8, 17u8, 101u8, 77u8, 161u8, 44u8, 110u8, 184u8, 73u8, 137u8, 62u8, 95u8, 251u8,
        131u8, 215u8, 221u8, 27u8, 129u8, 190u8, 114u8, 203u8, 39u8, 213u8, 188u8, 249u8, 139u8,
        144u8, 234u8, 202u8, 198u8,
    ],
    vk_delta_g2: [
        15u8, 98u8, 157u8, 120u8, 215u8, 253u8, 90u8, 115u8, 196u8, 69u8, 44u8, 116u8, 107u8, 60u8,
        162u8, 89u8, 155u8, 93u8, 195u8, 51u8, 193u8, 32u8, 69u8, 171u8, 40u8, 67u8, 15u8, 38u8,
        17u8, 106u8, 243u8, 15u8, 9u8, 39u8, 31u8, 208u8, 236u8, 227u8, 195u8, 66u8, 240u8, 76u8,
        212u8, 212u8, 171u8, 49u8, 230u8, 24u8, 142u8, 229u8, 87u8, 75u8, 208u8, 43u8, 139u8,
        105u8, 130u8, 100u8, 51u8, 90u8, 159u8, 29u8, 112u8, 5u8, 41u8, 188u8, 166u8, 93u8, 197u8,
        115u8, 128u8, 111u8, 126u8, 250u8, 114u8, 149u8, 18u8, 78u8, 18u8, 216u8, 205u8, 200u8,
        164u8, 88u8, 16u8, 192u8, 54u8, 111u8, 143u8, 42u8, 77u8, 133u8, 205u8, 109u8, 121u8,
        162u8, 45u8, 87u8, 29u8, 57u8, 88u8, 50u8, 149u8, 251u8, 141u8, 108u8, 210u8, 202u8, 173u8,
        121u8, 173u8, 61u8, 207u8, 36u8, 61u8, 72u8, 100u8, 80u8, 205u8, 173u8, 74u8, 182u8, 131u8,
        21u8, 10u8, 85u8, 254u8, 199u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [187u8, 29u8, 166u8, 17u8, 60u8, 228u8, 242u8, 12u8, 252u8, 6u8, 39u8, 3u8, 167u8, 200u8, 110u8, 120u8, 165u8, 218u8, 204u8, 113u8, 35u8, 168u8, 227u8, 243u8, 157u8, 235u8, 63u8, 10u8, 25u8, 253u8, 105u8, 252u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_287ec9b683a279be")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00bb1da6113ce4f20cfc062703a7c86e78a5dacc7123a8e3f39deb3f0a19fd69fc\x00=======END GROTH16 VK SETUP V1=======\x00";
