// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        44u8, 43u8, 213u8, 226u8, 162u8, 182u8, 44u8, 130u8, 193u8, 128u8, 77u8, 132u8, 36u8, 82u8,
        134u8, 204u8, 191u8, 57u8, 145u8, 215u8, 232u8, 255u8, 231u8, 49u8, 127u8, 17u8, 186u8,
        124u8, 92u8, 28u8, 192u8, 170u8, 13u8, 161u8, 169u8, 8u8, 12u8, 39u8, 184u8, 123u8, 49u8,
        30u8, 81u8, 44u8, 216u8, 160u8, 213u8, 246u8, 217u8, 205u8, 247u8, 39u8, 236u8, 100u8,
        118u8, 181u8, 216u8, 48u8, 84u8, 233u8, 1u8, 249u8, 80u8, 105u8,
    ],
    [
        28u8, 71u8, 137u8, 225u8, 3u8, 37u8, 103u8, 231u8, 177u8, 38u8, 188u8, 170u8, 175u8, 111u8,
        106u8, 166u8, 4u8, 189u8, 147u8, 29u8, 32u8, 126u8, 114u8, 214u8, 18u8, 248u8, 231u8,
        138u8, 69u8, 109u8, 74u8, 18u8, 34u8, 196u8, 44u8, 141u8, 105u8, 210u8, 119u8, 126u8,
        222u8, 49u8, 250u8, 187u8, 129u8, 103u8, 164u8, 49u8, 109u8, 224u8, 39u8, 96u8, 29u8,
        253u8, 103u8, 140u8, 16u8, 233u8, 224u8, 219u8, 28u8, 167u8, 229u8, 172u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        45u8, 183u8, 226u8, 189u8, 17u8, 137u8, 26u8, 64u8, 226u8, 222u8, 19u8, 197u8, 243u8,
        145u8, 104u8, 250u8, 0u8, 181u8, 130u8, 103u8, 0u8, 230u8, 171u8, 27u8, 197u8, 209u8, 98u8,
        35u8, 234u8, 142u8, 156u8, 197u8, 9u8, 76u8, 84u8, 249u8, 0u8, 26u8, 80u8, 72u8, 227u8,
        60u8, 55u8, 186u8, 132u8, 45u8, 151u8, 51u8, 246u8, 204u8, 173u8, 250u8, 195u8, 82u8, 92u8,
        78u8, 70u8, 210u8, 63u8, 162u8, 246u8, 159u8, 141u8, 29u8,
    ],
    vk_beta_g2: [
        36u8, 217u8, 172u8, 0u8, 47u8, 73u8, 12u8, 92u8, 152u8, 129u8, 220u8, 181u8, 223u8, 245u8,
        135u8, 174u8, 114u8, 167u8, 39u8, 16u8, 70u8, 239u8, 57u8, 19u8, 203u8, 252u8, 128u8,
        100u8, 233u8, 252u8, 38u8, 239u8, 25u8, 193u8, 169u8, 71u8, 40u8, 109u8, 68u8, 26u8, 73u8,
        29u8, 207u8, 127u8, 186u8, 27u8, 159u8, 118u8, 22u8, 61u8, 113u8, 184u8, 113u8, 127u8,
        46u8, 202u8, 0u8, 215u8, 198u8, 40u8, 139u8, 127u8, 7u8, 119u8, 23u8, 215u8, 160u8, 22u8,
        191u8, 44u8, 19u8, 22u8, 150u8, 131u8, 161u8, 35u8, 95u8, 95u8, 142u8, 146u8, 241u8, 217u8,
        82u8, 249u8, 132u8, 103u8, 157u8, 97u8, 197u8, 96u8, 235u8, 149u8, 88u8, 240u8, 150u8,
        178u8, 42u8, 29u8, 77u8, 224u8, 217u8, 246u8, 189u8, 33u8, 61u8, 81u8, 93u8, 194u8, 131u8,
        28u8, 114u8, 243u8, 34u8, 166u8, 249u8, 7u8, 76u8, 131u8, 195u8, 82u8, 78u8, 213u8, 133u8,
        64u8, 192u8, 150u8, 82u8, 49u8,
    ],
    vk_gamma_g2: [
        27u8, 111u8, 2u8, 194u8, 17u8, 248u8, 20u8, 216u8, 175u8, 62u8, 103u8, 148u8, 32u8, 124u8,
        98u8, 99u8, 151u8, 29u8, 14u8, 185u8, 66u8, 113u8, 39u8, 71u8, 93u8, 37u8, 98u8, 246u8,
        227u8, 190u8, 226u8, 251u8, 39u8, 236u8, 250u8, 9u8, 128u8, 122u8, 183u8, 212u8, 14u8,
        189u8, 153u8, 123u8, 68u8, 109u8, 91u8, 111u8, 192u8, 17u8, 215u8, 143u8, 154u8, 145u8,
        101u8, 226u8, 114u8, 34u8, 77u8, 191u8, 25u8, 107u8, 185u8, 98u8, 28u8, 191u8, 169u8, 16u8,
        10u8, 235u8, 252u8, 217u8, 113u8, 188u8, 93u8, 170u8, 117u8, 34u8, 158u8, 58u8, 230u8,
        126u8, 69u8, 196u8, 158u8, 35u8, 108u8, 42u8, 63u8, 58u8, 132u8, 95u8, 239u8, 168u8, 27u8,
        216u8, 39u8, 129u8, 183u8, 25u8, 254u8, 134u8, 95u8, 180u8, 66u8, 29u8, 79u8, 182u8, 246u8,
        162u8, 230u8, 246u8, 207u8, 122u8, 79u8, 216u8, 148u8, 203u8, 189u8, 80u8, 5u8, 185u8,
        255u8, 112u8, 148u8, 185u8, 212u8, 111u8,
    ],
    vk_delta_g2: [
        9u8, 235u8, 170u8, 237u8, 128u8, 172u8, 63u8, 97u8, 78u8, 114u8, 193u8, 9u8, 115u8, 65u8,
        107u8, 160u8, 188u8, 61u8, 125u8, 160u8, 202u8, 218u8, 110u8, 185u8, 133u8, 10u8, 228u8,
        84u8, 20u8, 147u8, 216u8, 122u8, 32u8, 216u8, 145u8, 147u8, 240u8, 165u8, 7u8, 18u8, 48u8,
        75u8, 108u8, 190u8, 119u8, 232u8, 32u8, 10u8, 218u8, 186u8, 66u8, 178u8, 174u8, 140u8,
        32u8, 94u8, 64u8, 171u8, 18u8, 207u8, 118u8, 172u8, 84u8, 97u8, 32u8, 187u8, 19u8, 220u8,
        222u8, 91u8, 243u8, 84u8, 91u8, 182u8, 238u8, 24u8, 32u8, 140u8, 41u8, 66u8, 149u8, 91u8,
        225u8, 196u8, 104u8, 202u8, 1u8, 127u8, 31u8, 10u8, 185u8, 157u8, 180u8, 48u8, 190u8,
        189u8, 23u8, 149u8, 116u8, 164u8, 138u8, 170u8, 94u8, 204u8, 149u8, 46u8, 81u8, 9u8, 159u8,
        244u8, 187u8, 170u8, 145u8, 39u8, 33u8, 99u8, 80u8, 31u8, 219u8, 216u8, 230u8, 81u8, 18u8,
        22u8, 35u8, 232u8, 208u8, 18u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [247u8, 126u8, 71u8, 83u8, 85u8, 14u8, 36u8, 41u8, 1u8, 195u8, 123u8, 46u8, 65u8, 240u8, 52u8, 238u8, 82u8, 182u8, 107u8, 49u8, 70u8, 136u8, 109u8, 244u8, 116u8, 237u8, 212u8, 71u8, 152u8, 220u8, 141u8, 113u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_dff8082824a2bf88")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00f77e4753550e242901c37b2e41f034ee52b66b3146886df474edd44798dc8d71\x00=======END GROTH16 VK SETUP V1=======\x00";
