// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        16u8, 212u8, 221u8, 89u8, 137u8, 216u8, 203u8, 135u8, 112u8, 135u8, 27u8, 38u8, 137u8,
        241u8, 178u8, 245u8, 96u8, 218u8, 45u8, 22u8, 51u8, 157u8, 134u8, 235u8, 221u8, 150u8,
        102u8, 13u8, 255u8, 250u8, 126u8, 190u8, 26u8, 157u8, 231u8, 108u8, 172u8, 163u8, 242u8,
        227u8, 183u8, 109u8, 107u8, 134u8, 230u8, 68u8, 168u8, 222u8, 85u8, 185u8, 189u8, 2u8,
        107u8, 217u8, 38u8, 43u8, 93u8, 231u8, 243u8, 230u8, 238u8, 179u8, 29u8, 115u8,
    ],
    [
        25u8, 11u8, 14u8, 158u8, 212u8, 97u8, 207u8, 179u8, 180u8, 121u8, 0u8, 2u8, 125u8, 185u8,
        176u8, 94u8, 26u8, 200u8, 203u8, 37u8, 153u8, 25u8, 50u8, 231u8, 100u8, 144u8, 107u8,
        195u8, 206u8, 13u8, 109u8, 114u8, 12u8, 78u8, 141u8, 14u8, 32u8, 81u8, 224u8, 202u8, 131u8,
        1u8, 14u8, 128u8, 197u8, 136u8, 158u8, 90u8, 221u8, 82u8, 102u8, 229u8, 250u8, 57u8, 208u8,
        210u8, 13u8, 103u8, 196u8, 192u8, 217u8, 237u8, 153u8, 47u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        47u8, 45u8, 210u8, 222u8, 19u8, 69u8, 114u8, 10u8, 23u8, 109u8, 93u8, 139u8, 211u8, 128u8,
        70u8, 241u8, 125u8, 56u8, 166u8, 125u8, 209u8, 87u8, 250u8, 27u8, 33u8, 13u8, 38u8, 191u8,
        123u8, 93u8, 16u8, 250u8, 23u8, 131u8, 91u8, 42u8, 11u8, 120u8, 90u8, 73u8, 64u8, 54u8,
        12u8, 142u8, 5u8, 118u8, 248u8, 6u8, 17u8, 38u8, 73u8, 49u8, 189u8, 66u8, 76u8, 29u8,
        189u8, 39u8, 117u8, 124u8, 171u8, 67u8, 170u8, 149u8,
    ],
    vk_beta_g2: [
        48u8, 44u8, 225u8, 215u8, 238u8, 215u8, 4u8, 202u8, 167u8, 223u8, 230u8, 166u8, 45u8,
        222u8, 200u8, 237u8, 128u8, 185u8, 221u8, 17u8, 34u8, 167u8, 125u8, 206u8, 197u8, 10u8,
        44u8, 20u8, 138u8, 133u8, 157u8, 59u8, 7u8, 20u8, 53u8, 177u8, 75u8, 52u8, 221u8, 98u8,
        152u8, 126u8, 120u8, 211u8, 8u8, 82u8, 149u8, 157u8, 38u8, 156u8, 153u8, 111u8, 219u8,
        87u8, 36u8, 239u8, 255u8, 54u8, 250u8, 12u8, 178u8, 70u8, 215u8, 129u8, 18u8, 222u8, 202u8,
        141u8, 210u8, 128u8, 85u8, 92u8, 152u8, 56u8, 163u8, 112u8, 59u8, 176u8, 215u8, 48u8, 7u8,
        121u8, 157u8, 254u8, 21u8, 73u8, 232u8, 105u8, 195u8, 174u8, 133u8, 90u8, 81u8, 199u8,
        250u8, 214u8, 10u8, 125u8, 240u8, 104u8, 105u8, 120u8, 6u8, 186u8, 122u8, 239u8, 13u8,
        172u8, 204u8, 208u8, 167u8, 194u8, 140u8, 233u8, 168u8, 133u8, 214u8, 64u8, 59u8, 61u8,
        193u8, 140u8, 227u8, 159u8, 66u8, 250u8, 54u8, 157u8,
    ],
    vk_gamma_g2: [
        15u8, 243u8, 136u8, 103u8, 14u8, 102u8, 167u8, 28u8, 128u8, 252u8, 90u8, 119u8, 40u8,
        197u8, 112u8, 222u8, 228u8, 161u8, 64u8, 254u8, 164u8, 240u8, 17u8, 79u8, 39u8, 103u8,
        251u8, 71u8, 149u8, 22u8, 179u8, 37u8, 45u8, 171u8, 187u8, 244u8, 99u8, 26u8, 96u8, 98u8,
        63u8, 247u8, 115u8, 137u8, 255u8, 112u8, 117u8, 11u8, 164u8, 139u8, 150u8, 73u8, 14u8,
        11u8, 118u8, 191u8, 176u8, 231u8, 231u8, 59u8, 120u8, 196u8, 221u8, 88u8, 44u8, 68u8, 77u8,
        123u8, 84u8, 7u8, 220u8, 89u8, 86u8, 11u8, 201u8, 87u8, 135u8, 85u8, 57u8, 199u8, 53u8,
        191u8, 119u8, 86u8, 211u8, 2u8, 28u8, 231u8, 81u8, 8u8, 237u8, 10u8, 16u8, 43u8, 51u8,
        23u8, 24u8, 111u8, 48u8, 249u8, 15u8, 3u8, 78u8, 178u8, 131u8, 81u8, 230u8, 104u8, 166u8,
        18u8, 242u8, 131u8, 36u8, 239u8, 140u8, 90u8, 35u8, 100u8, 230u8, 190u8, 64u8, 159u8, 81u8,
        251u8, 232u8, 140u8, 216u8, 112u8,
    ],
    vk_delta_g2: [
        11u8, 180u8, 116u8, 101u8, 153u8, 177u8, 45u8, 47u8, 110u8, 209u8, 71u8, 12u8, 49u8, 184u8,
        193u8, 99u8, 205u8, 224u8, 59u8, 81u8, 242u8, 19u8, 250u8, 67u8, 66u8, 115u8, 189u8, 50u8,
        75u8, 61u8, 150u8, 1u8, 2u8, 172u8, 111u8, 112u8, 228u8, 178u8, 104u8, 64u8, 104u8, 176u8,
        144u8, 2u8, 19u8, 37u8, 193u8, 103u8, 174u8, 122u8, 150u8, 60u8, 160u8, 98u8, 87u8, 59u8,
        154u8, 155u8, 39u8, 124u8, 244u8, 21u8, 37u8, 147u8, 7u8, 177u8, 116u8, 170u8, 41u8, 118u8,
        121u8, 235u8, 245u8, 79u8, 95u8, 6u8, 234u8, 82u8, 252u8, 150u8, 164u8, 147u8, 132u8,
        150u8, 140u8, 29u8, 228u8, 29u8, 134u8, 88u8, 11u8, 173u8, 210u8, 84u8, 202u8, 50u8, 22u8,
        135u8, 151u8, 13u8, 10u8, 219u8, 54u8, 69u8, 49u8, 159u8, 32u8, 42u8, 15u8, 6u8, 43u8,
        93u8, 92u8, 156u8, 72u8, 193u8, 84u8, 41u8, 25u8, 220u8, 27u8, 249u8, 3u8, 76u8, 120u8,
        210u8, 171u8, 110u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [9u8, 190u8, 151u8, 31u8, 161u8, 36u8, 51u8, 251u8, 93u8, 135u8, 52u8, 52u8, 209u8, 173u8, 13u8, 95u8, 32u8, 122u8, 62u8, 121u8, 223u8, 64u8, 160u8, 127u8, 3u8, 87u8, 152u8, 235u8, 102u8, 93u8, 34u8, 0u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_27fd657d4572bb06")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x0009be971fa12433fb5d873434d1ad0d5f207a3e79df40a07f035798eb665d2200\x00=======END GROTH16 VK SETUP V1=======\x00";
