// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        23u8, 106u8, 101u8, 216u8, 231u8, 137u8, 0u8, 127u8, 49u8, 200u8, 160u8, 251u8, 67u8,
        164u8, 111u8, 127u8, 26u8, 247u8, 171u8, 59u8, 142u8, 118u8, 136u8, 242u8, 11u8, 123u8,
        65u8, 85u8, 100u8, 19u8, 109u8, 54u8, 47u8, 163u8, 199u8, 88u8, 108u8, 240u8, 134u8, 119u8,
        48u8, 59u8, 114u8, 229u8, 254u8, 193u8, 168u8, 175u8, 220u8, 74u8, 54u8, 47u8, 96u8, 143u8,
        194u8, 12u8, 202u8, 238u8, 131u8, 119u8, 63u8, 145u8, 63u8, 114u8,
    ],
    [
        19u8, 34u8, 164u8, 140u8, 62u8, 27u8, 115u8, 220u8, 199u8, 69u8, 99u8, 159u8, 101u8, 166u8,
        104u8, 233u8, 61u8, 142u8, 12u8, 86u8, 86u8, 87u8, 142u8, 110u8, 240u8, 83u8, 172u8, 11u8,
        7u8, 240u8, 19u8, 96u8, 15u8, 12u8, 247u8, 153u8, 1u8, 203u8, 230u8, 140u8, 6u8, 198u8,
        69u8, 19u8, 144u8, 68u8, 160u8, 28u8, 45u8, 168u8, 62u8, 57u8, 40u8, 108u8, 141u8, 220u8,
        217u8, 45u8, 118u8, 38u8, 249u8, 130u8, 96u8, 165u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        22u8, 57u8, 201u8, 158u8, 40u8, 175u8, 124u8, 130u8, 113u8, 78u8, 219u8, 201u8, 1u8, 209u8,
        48u8, 191u8, 171u8, 114u8, 22u8, 234u8, 109u8, 150u8, 109u8, 98u8, 44u8, 134u8, 66u8,
        214u8, 181u8, 190u8, 91u8, 34u8, 38u8, 80u8, 237u8, 154u8, 206u8, 59u8, 72u8, 116u8, 47u8,
        41u8, 16u8, 32u8, 238u8, 55u8, 78u8, 212u8, 220u8, 254u8, 221u8, 97u8, 208u8, 80u8, 206u8,
        24u8, 138u8, 146u8, 99u8, 129u8, 74u8, 169u8, 0u8, 146u8,
    ],
    vk_beta_g2: [
        35u8, 139u8, 20u8, 244u8, 83u8, 30u8, 114u8, 132u8, 10u8, 173u8, 238u8, 255u8, 229u8, 12u8,
        185u8, 4u8, 60u8, 203u8, 50u8, 165u8, 126u8, 161u8, 34u8, 69u8, 109u8, 84u8, 250u8, 139u8,
        101u8, 172u8, 37u8, 147u8, 39u8, 126u8, 125u8, 138u8, 195u8, 239u8, 62u8, 178u8, 92u8,
        14u8, 199u8, 234u8, 101u8, 208u8, 152u8, 219u8, 82u8, 17u8, 237u8, 33u8, 215u8, 232u8,
        36u8, 13u8, 95u8, 216u8, 191u8, 233u8, 193u8, 151u8, 32u8, 87u8, 30u8, 63u8, 141u8, 166u8,
        10u8, 13u8, 161u8, 47u8, 28u8, 192u8, 54u8, 46u8, 36u8, 76u8, 42u8, 139u8, 230u8, 16u8,
        116u8, 150u8, 247u8, 31u8, 47u8, 172u8, 175u8, 98u8, 227u8, 168u8, 154u8, 77u8, 117u8,
        109u8, 30u8, 82u8, 254u8, 106u8, 81u8, 230u8, 96u8, 142u8, 23u8, 98u8, 207u8, 102u8, 237u8,
        63u8, 11u8, 239u8, 227u8, 127u8, 176u8, 208u8, 12u8, 226u8, 194u8, 42u8, 12u8, 24u8, 158u8,
        38u8, 221u8, 126u8, 61u8, 167u8,
    ],
    vk_gamma_g2: [
        37u8, 123u8, 131u8, 203u8, 234u8, 178u8, 192u8, 188u8, 36u8, 193u8, 127u8, 123u8, 113u8,
        55u8, 90u8, 70u8, 154u8, 129u8, 27u8, 152u8, 188u8, 164u8, 67u8, 200u8, 210u8, 226u8, 80u8,
        88u8, 239u8, 126u8, 253u8, 140u8, 21u8, 36u8, 114u8, 245u8, 123u8, 35u8, 55u8, 47u8, 206u8,
        18u8, 38u8, 27u8, 215u8, 210u8, 246u8, 224u8, 138u8, 162u8, 134u8, 43u8, 229u8, 20u8, 46u8,
        102u8, 151u8, 77u8, 63u8, 58u8, 178u8, 100u8, 114u8, 149u8, 47u8, 64u8, 30u8, 244u8, 226u8,
        166u8, 135u8, 234u8, 189u8, 139u8, 111u8, 98u8, 176u8, 73u8, 160u8, 37u8, 99u8, 20u8,
        199u8, 40u8, 15u8, 253u8, 26u8, 111u8, 147u8, 79u8, 54u8, 43u8, 243u8, 122u8, 188u8, 210u8,
        31u8, 38u8, 53u8, 103u8, 126u8, 49u8, 220u8, 208u8, 43u8, 68u8, 207u8, 172u8, 191u8, 187u8,
        211u8, 221u8, 239u8, 7u8, 131u8, 237u8, 37u8, 146u8, 196u8, 141u8, 192u8, 12u8, 253u8,
        174u8, 178u8, 96u8, 124u8, 147u8,
    ],
    vk_delta_g2: [
        37u8, 149u8, 197u8, 84u8, 148u8, 174u8, 160u8, 44u8, 138u8, 56u8, 85u8, 97u8, 15u8, 184u8,
        156u8, 158u8, 31u8, 185u8, 177u8, 204u8, 40u8, 10u8, 167u8, 118u8, 1u8, 28u8, 120u8, 67u8,
        156u8, 148u8, 158u8, 152u8, 6u8, 9u8, 140u8, 237u8, 130u8, 93u8, 224u8, 249u8, 95u8, 82u8,
        83u8, 187u8, 245u8, 51u8, 135u8, 81u8, 255u8, 124u8, 237u8, 15u8, 108u8, 9u8, 39u8, 212u8,
        5u8, 54u8, 128u8, 182u8, 0u8, 60u8, 164u8, 252u8, 17u8, 188u8, 243u8, 147u8, 109u8, 43u8,
        202u8, 7u8, 20u8, 21u8, 66u8, 193u8, 3u8, 7u8, 165u8, 120u8, 248u8, 115u8, 220u8, 70u8,
        81u8, 87u8, 18u8, 114u8, 123u8, 175u8, 163u8, 52u8, 43u8, 151u8, 188u8, 17u8, 27u8, 64u8,
        218u8, 219u8, 17u8, 22u8, 186u8, 239u8, 203u8, 42u8, 5u8, 5u8, 0u8, 227u8, 159u8, 39u8,
        120u8, 225u8, 228u8, 175u8, 206u8, 14u8, 199u8, 161u8, 137u8, 68u8, 221u8, 134u8, 61u8,
        55u8, 139u8, 81u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [202u8, 139u8, 236u8, 174u8, 33u8, 230u8, 4u8, 70u8, 127u8, 116u8, 88u8, 22u8, 4u8, 190u8, 44u8, 137u8, 49u8, 14u8, 75u8, 90u8, 99u8, 58u8, 87u8, 211u8, 51u8, 70u8, 150u8, 133u8, 9u8, 131u8, 253u8, 2u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_7e9b19b2f97f63f5")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00ca8becae21e604467f74581604be2c89310e4b5a633a57d3334696850983fd02\x00=======END GROTH16 VK SETUP V1=======\x00";
