// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        3u8, 191u8, 221u8, 5u8, 198u8, 24u8, 167u8, 141u8, 142u8, 34u8, 121u8, 192u8, 228u8, 137u8,
        169u8, 212u8, 90u8, 50u8, 99u8, 101u8, 103u8, 201u8, 142u8, 197u8, 77u8, 79u8, 100u8,
        182u8, 225u8, 54u8, 219u8, 19u8, 13u8, 184u8, 101u8, 2u8, 172u8, 215u8, 24u8, 137u8, 191u8,
        62u8, 101u8, 158u8, 29u8, 99u8, 166u8, 58u8, 108u8, 236u8, 155u8, 173u8, 30u8, 200u8,
        105u8, 223u8, 120u8, 64u8, 247u8, 187u8, 254u8, 95u8, 197u8, 253u8,
    ],
    [
        19u8, 75u8, 126u8, 156u8, 242u8, 215u8, 250u8, 101u8, 153u8, 189u8, 208u8, 44u8, 28u8,
        132u8, 79u8, 169u8, 130u8, 65u8, 103u8, 75u8, 169u8, 184u8, 243u8, 212u8, 236u8, 118u8,
        42u8, 217u8, 51u8, 17u8, 34u8, 117u8, 22u8, 216u8, 196u8, 5u8, 170u8, 118u8, 253u8, 33u8,
        177u8, 4u8, 167u8, 195u8, 187u8, 200u8, 116u8, 199u8, 81u8, 236u8, 38u8, 24u8, 231u8, 23u8,
        98u8, 28u8, 212u8, 231u8, 28u8, 182u8, 143u8, 208u8, 172u8, 17u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        13u8, 19u8, 232u8, 221u8, 28u8, 105u8, 229u8, 14u8, 10u8, 88u8, 90u8, 129u8, 137u8, 3u8,
        31u8, 7u8, 234u8, 36u8, 82u8, 124u8, 112u8, 159u8, 181u8, 247u8, 225u8, 190u8, 51u8, 155u8,
        0u8, 9u8, 144u8, 255u8, 31u8, 139u8, 177u8, 174u8, 39u8, 232u8, 252u8, 230u8, 254u8, 192u8,
        170u8, 179u8, 119u8, 215u8, 127u8, 31u8, 194u8, 201u8, 159u8, 177u8, 163u8, 16u8, 169u8,
        217u8, 171u8, 225u8, 94u8, 32u8, 160u8, 40u8, 157u8, 127u8,
    ],
    vk_beta_g2: [
        40u8, 70u8, 159u8, 192u8, 254u8, 110u8, 236u8, 64u8, 119u8, 98u8, 147u8, 146u8, 232u8,
        68u8, 255u8, 183u8, 213u8, 70u8, 211u8, 104u8, 123u8, 215u8, 138u8, 117u8, 98u8, 48u8,
        74u8, 177u8, 59u8, 238u8, 0u8, 247u8, 31u8, 199u8, 10u8, 113u8, 164u8, 26u8, 231u8, 134u8,
        247u8, 186u8, 75u8, 195u8, 227u8, 201u8, 151u8, 223u8, 20u8, 108u8, 250u8, 247u8, 26u8,
        173u8, 85u8, 47u8, 224u8, 110u8, 147u8, 8u8, 96u8, 181u8, 95u8, 131u8, 32u8, 116u8, 221u8,
        81u8, 45u8, 106u8, 71u8, 120u8, 131u8, 186u8, 108u8, 137u8, 227u8, 76u8, 207u8, 14u8, 18u8,
        240u8, 168u8, 208u8, 148u8, 72u8, 77u8, 169u8, 200u8, 80u8, 239u8, 186u8, 4u8, 189u8, 41u8,
        213u8, 33u8, 241u8, 209u8, 216u8, 148u8, 82u8, 83u8, 42u8, 251u8, 68u8, 244u8, 109u8,
        232u8, 97u8, 63u8, 191u8, 51u8, 215u8, 100u8, 27u8, 35u8, 237u8, 228u8, 3u8, 219u8, 246u8,
        186u8, 64u8, 113u8, 175u8, 132u8, 240u8,
    ],
    vk_gamma_g2: [
        26u8, 105u8, 25u8, 157u8, 170u8, 228u8, 162u8, 150u8, 23u8, 94u8, 6u8, 23u8, 159u8, 134u8,
        75u8, 180u8, 30u8, 185u8, 241u8, 237u8, 139u8, 103u8, 68u8, 72u8, 85u8, 160u8, 112u8,
        109u8, 228u8, 254u8, 68u8, 220u8, 12u8, 239u8, 237u8, 178u8, 92u8, 102u8, 139u8, 99u8,
        188u8, 136u8, 237u8, 197u8, 78u8, 15u8, 73u8, 255u8, 201u8, 195u8, 201u8, 223u8, 108u8,
        148u8, 64u8, 129u8, 235u8, 108u8, 253u8, 120u8, 61u8, 176u8, 169u8, 109u8, 21u8, 54u8,
        237u8, 154u8, 113u8, 64u8, 116u8, 249u8, 135u8, 41u8, 147u8, 71u8, 29u8, 249u8, 1u8, 218u8,
        95u8, 33u8, 227u8, 103u8, 122u8, 224u8, 48u8, 145u8, 161u8, 246u8, 52u8, 10u8, 188u8, 3u8,
        191u8, 73u8, 44u8, 91u8, 153u8, 239u8, 230u8, 70u8, 127u8, 73u8, 91u8, 31u8, 243u8, 141u8,
        197u8, 154u8, 15u8, 182u8, 197u8, 107u8, 42u8, 176u8, 235u8, 204u8, 127u8, 9u8, 124u8, 5u8,
        215u8, 91u8, 203u8, 129u8, 241u8, 150u8,
    ],
    vk_delta_g2: [
        46u8, 7u8, 187u8, 200u8, 233u8, 91u8, 154u8, 170u8, 220u8, 243u8, 131u8, 5u8, 67u8, 2u8,
        67u8, 1u8, 132u8, 136u8, 198u8, 167u8, 209u8, 205u8, 124u8, 104u8, 108u8, 20u8, 132u8,
        144u8, 164u8, 167u8, 107u8, 95u8, 1u8, 182u8, 65u8, 63u8, 225u8, 101u8, 236u8, 169u8,
        140u8, 93u8, 3u8, 27u8, 215u8, 106u8, 178u8, 136u8, 78u8, 9u8, 21u8, 241u8, 11u8, 212u8,
        48u8, 245u8, 17u8, 37u8, 65u8, 1u8, 131u8, 149u8, 241u8, 67u8, 27u8, 220u8, 47u8, 103u8,
        134u8, 160u8, 133u8, 143u8, 58u8, 34u8, 40u8, 62u8, 9u8, 153u8, 192u8, 14u8, 92u8, 130u8,
        160u8, 253u8, 172u8, 152u8, 54u8, 139u8, 184u8, 43u8, 150u8, 251u8, 101u8, 161u8, 212u8,
        2u8, 16u8, 43u8, 195u8, 123u8, 223u8, 162u8, 19u8, 81u8, 53u8, 59u8, 140u8, 64u8, 192u8,
        134u8, 191u8, 209u8, 0u8, 158u8, 64u8, 208u8, 61u8, 89u8, 70u8, 2u8, 229u8, 225u8, 67u8,
        74u8, 4u8, 225u8, 163u8, 58u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [233u8, 169u8, 176u8, 236u8, 57u8, 239u8, 185u8, 170u8, 199u8, 33u8, 134u8, 132u8, 62u8, 229u8, 172u8, 100u8, 16u8, 67u8, 79u8, 39u8, 20u8, 211u8, 143u8, 60u8, 94u8, 246u8, 245u8, 140u8, 137u8, 157u8, 207u8, 171u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_0fc97dd08f147f83")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00e9a9b0ec39efb9aac72186843ee5ac6410434f2714d38f3c5ef6f58c899dcfab\x00=======END GROTH16 VK SETUP V1=======\x00";
