// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        17u8, 169u8, 158u8, 63u8, 254u8, 211u8, 48u8, 25u8, 68u8, 243u8, 216u8, 35u8, 224u8, 195u8,
        219u8, 150u8, 95u8, 230u8, 116u8, 32u8, 136u8, 54u8, 36u8, 81u8, 14u8, 177u8, 167u8, 71u8,
        110u8, 129u8, 138u8, 66u8, 44u8, 72u8, 122u8, 11u8, 185u8, 248u8, 196u8, 85u8, 111u8,
        139u8, 210u8, 235u8, 67u8, 14u8, 211u8, 11u8, 181u8, 146u8, 213u8, 101u8, 71u8, 141u8,
        158u8, 236u8, 20u8, 26u8, 225u8, 102u8, 239u8, 197u8, 183u8, 15u8,
    ],
    [
        13u8, 174u8, 19u8, 193u8, 49u8, 80u8, 167u8, 54u8, 24u8, 212u8, 225u8, 50u8, 174u8, 193u8,
        23u8, 192u8, 112u8, 230u8, 196u8, 164u8, 41u8, 223u8, 72u8, 120u8, 44u8, 115u8, 113u8,
        233u8, 101u8, 89u8, 18u8, 174u8, 22u8, 223u8, 82u8, 85u8, 234u8, 6u8, 23u8, 92u8, 204u8,
        9u8, 126u8, 209u8, 229u8, 9u8, 116u8, 182u8, 175u8, 187u8, 161u8, 100u8, 138u8, 3u8, 38u8,
        53u8, 166u8, 16u8, 56u8, 32u8, 8u8, 36u8, 251u8, 81u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        10u8, 229u8, 191u8, 196u8, 7u8, 152u8, 4u8, 245u8, 237u8, 246u8, 209u8, 235u8, 173u8, 27u8,
        72u8, 175u8, 31u8, 73u8, 227u8, 233u8, 151u8, 36u8, 2u8, 218u8, 16u8, 245u8, 205u8, 190u8,
        1u8, 240u8, 64u8, 87u8, 39u8, 106u8, 188u8, 156u8, 169u8, 167u8, 126u8, 54u8, 199u8, 119u8,
        45u8, 71u8, 56u8, 70u8, 122u8, 228u8, 82u8, 116u8, 20u8, 55u8, 69u8, 176u8, 75u8, 171u8,
        69u8, 254u8, 218u8, 25u8, 254u8, 23u8, 10u8, 190u8,
    ],
    vk_beta_g2: [
        19u8, 121u8, 124u8, 26u8, 248u8, 163u8, 6u8, 41u8, 205u8, 143u8, 63u8, 9u8, 143u8, 180u8,
        16u8, 70u8, 141u8, 55u8, 186u8, 42u8, 212u8, 54u8, 224u8, 216u8, 252u8, 9u8, 3u8, 90u8,
        56u8, 2u8, 9u8, 112u8, 13u8, 87u8, 178u8, 178u8, 222u8, 217u8, 29u8, 206u8, 15u8, 65u8,
        204u8, 86u8, 22u8, 80u8, 46u8, 187u8, 110u8, 115u8, 235u8, 214u8, 158u8, 17u8, 28u8, 125u8,
        226u8, 126u8, 95u8, 31u8, 175u8, 156u8, 4u8, 54u8, 45u8, 152u8, 110u8, 216u8, 126u8, 87u8,
        84u8, 26u8, 44u8, 217u8, 254u8, 217u8, 29u8, 111u8, 26u8, 121u8, 64u8, 42u8, 151u8, 45u8,
        92u8, 151u8, 49u8, 68u8, 42u8, 160u8, 100u8, 52u8, 215u8, 197u8, 242u8, 46u8, 3u8, 68u8,
        35u8, 107u8, 213u8, 120u8, 53u8, 103u8, 212u8, 254u8, 194u8, 145u8, 97u8, 174u8, 114u8,
        20u8, 247u8, 6u8, 50u8, 139u8, 103u8, 110u8, 199u8, 251u8, 101u8, 128u8, 239u8, 199u8,
        60u8, 65u8, 143u8, 128u8,
    ],
    vk_gamma_g2: [
        38u8, 136u8, 82u8, 68u8, 14u8, 118u8, 251u8, 101u8, 201u8, 94u8, 30u8, 225u8, 100u8, 102u8,
        180u8, 189u8, 204u8, 10u8, 198u8, 96u8, 28u8, 88u8, 212u8, 139u8, 165u8, 243u8, 0u8, 64u8,
        73u8, 226u8, 123u8, 228u8, 40u8, 13u8, 2u8, 182u8, 89u8, 159u8, 26u8, 65u8, 187u8, 100u8,
        184u8, 241u8, 210u8, 75u8, 213u8, 178u8, 211u8, 206u8, 63u8, 247u8, 22u8, 7u8, 199u8,
        216u8, 82u8, 117u8, 109u8, 244u8, 58u8, 95u8, 190u8, 158u8, 5u8, 57u8, 52u8, 14u8, 186u8,
        103u8, 218u8, 103u8, 45u8, 87u8, 206u8, 14u8, 234u8, 176u8, 211u8, 149u8, 145u8, 164u8,
        77u8, 121u8, 216u8, 52u8, 142u8, 196u8, 21u8, 132u8, 233u8, 45u8, 26u8, 4u8, 165u8, 32u8,
        0u8, 146u8, 148u8, 190u8, 45u8, 171u8, 28u8, 253u8, 170u8, 86u8, 126u8, 21u8, 191u8, 72u8,
        69u8, 18u8, 210u8, 160u8, 85u8, 204u8, 255u8, 106u8, 85u8, 156u8, 239u8, 242u8, 128u8,
        34u8, 192u8, 91u8, 49u8, 220u8,
    ],
    vk_delta_g2: [
        48u8, 15u8, 89u8, 200u8, 228u8, 56u8, 230u8, 85u8, 80u8, 114u8, 42u8, 125u8, 99u8, 171u8,
        217u8, 0u8, 33u8, 4u8, 132u8, 33u8, 111u8, 152u8, 34u8, 133u8, 152u8, 178u8, 15u8, 122u8,
        191u8, 206u8, 74u8, 122u8, 7u8, 22u8, 227u8, 117u8, 80u8, 105u8, 16u8, 45u8, 81u8, 146u8,
        141u8, 247u8, 125u8, 188u8, 133u8, 189u8, 18u8, 3u8, 202u8, 91u8, 14u8, 99u8, 174u8, 182u8,
        133u8, 103u8, 172u8, 66u8, 142u8, 217u8, 227u8, 82u8, 33u8, 163u8, 0u8, 17u8, 206u8, 109u8,
        96u8, 165u8, 190u8, 159u8, 192u8, 102u8, 19u8, 94u8, 160u8, 94u8, 40u8, 254u8, 43u8, 240u8,
        239u8, 242u8, 203u8, 46u8, 175u8, 47u8, 197u8, 189u8, 48u8, 87u8, 41u8, 144u8, 18u8, 204u8,
        60u8, 101u8, 76u8, 70u8, 97u8, 160u8, 161u8, 219u8, 52u8, 27u8, 178u8, 164u8, 18u8, 105u8,
        254u8, 155u8, 137u8, 6u8, 40u8, 248u8, 64u8, 153u8, 120u8, 159u8, 190u8, 213u8, 177u8,
        85u8, 254u8, 184u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [87u8, 103u8, 185u8, 17u8, 178u8, 239u8, 143u8, 109u8, 5u8, 254u8, 138u8, 58u8, 15u8, 12u8, 198u8, 129u8, 237u8, 100u8, 87u8, 148u8, 71u8, 142u8, 101u8, 161u8, 228u8, 157u8, 252u8, 162u8, 98u8, 151u8, 92u8, 72u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_de45fd06d68cb830")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x005767b911b2ef8f6d05fe8a3a0f0cc681ed645794478e65a1e49dfca262975c48\x00=======END GROTH16 VK SETUP V1=======\x00";
