// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        4u8, 73u8, 182u8, 71u8, 132u8, 246u8, 241u8, 106u8, 54u8, 220u8, 35u8, 140u8, 63u8, 103u8,
        241u8, 74u8, 61u8, 132u8, 48u8, 183u8, 170u8, 111u8, 167u8, 216u8, 44u8, 71u8, 120u8,
        100u8, 10u8, 111u8, 61u8, 34u8, 14u8, 177u8, 39u8, 145u8, 151u8, 47u8, 215u8, 144u8, 100u8,
        140u8, 247u8, 81u8, 145u8, 56u8, 227u8, 57u8, 145u8, 133u8, 191u8, 71u8, 88u8, 47u8, 110u8,
        105u8, 98u8, 103u8, 226u8, 86u8, 168u8, 20u8, 5u8, 145u8,
    ],
    [
        3u8, 231u8, 142u8, 45u8, 35u8, 248u8, 42u8, 30u8, 192u8, 151u8, 228u8, 102u8, 214u8, 205u8,
        71u8, 109u8, 51u8, 130u8, 87u8, 156u8, 95u8, 24u8, 123u8, 114u8, 230u8, 42u8, 137u8, 239u8,
        42u8, 82u8, 216u8, 28u8, 44u8, 152u8, 33u8, 210u8, 19u8, 186u8, 11u8, 98u8, 66u8, 58u8,
        162u8, 199u8, 116u8, 50u8, 224u8, 32u8, 26u8, 35u8, 80u8, 195u8, 76u8, 58u8, 143u8, 188u8,
        211u8, 113u8, 163u8, 86u8, 71u8, 70u8, 119u8, 132u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        20u8, 132u8, 247u8, 147u8, 231u8, 80u8, 151u8, 65u8, 242u8, 22u8, 85u8, 101u8, 91u8, 112u8,
        88u8, 128u8, 28u8, 159u8, 151u8, 151u8, 195u8, 14u8, 56u8, 102u8, 238u8, 4u8, 107u8, 189u8,
        172u8, 97u8, 10u8, 47u8, 18u8, 161u8, 17u8, 94u8, 58u8, 193u8, 83u8, 175u8, 87u8, 84u8,
        46u8, 194u8, 131u8, 205u8, 147u8, 206u8, 106u8, 130u8, 231u8, 145u8, 100u8, 169u8, 72u8,
        251u8, 103u8, 166u8, 73u8, 166u8, 194u8, 94u8, 107u8, 213u8,
    ],
    vk_beta_g2: [
        43u8, 196u8, 237u8, 154u8, 197u8, 126u8, 71u8, 170u8, 190u8, 103u8, 40u8, 42u8, 96u8,
        177u8, 125u8, 185u8, 10u8, 14u8, 171u8, 229u8, 54u8, 44u8, 236u8, 117u8, 89u8, 135u8,
        189u8, 233u8, 1u8, 138u8, 124u8, 19u8, 27u8, 107u8, 205u8, 22u8, 154u8, 43u8, 14u8, 174u8,
        245u8, 155u8, 106u8, 24u8, 238u8, 144u8, 17u8, 153u8, 20u8, 67u8, 122u8, 119u8, 206u8,
        215u8, 202u8, 213u8, 35u8, 35u8, 122u8, 13u8, 91u8, 6u8, 156u8, 46u8, 18u8, 239u8, 77u8,
        125u8, 210u8, 114u8, 132u8, 199u8, 154u8, 240u8, 15u8, 116u8, 161u8, 95u8, 197u8, 8u8,
        225u8, 210u8, 115u8, 234u8, 241u8, 117u8, 80u8, 170u8, 156u8, 166u8, 223u8, 57u8, 104u8,
        55u8, 137u8, 248u8, 32u8, 187u8, 46u8, 231u8, 95u8, 78u8, 249u8, 79u8, 230u8, 24u8, 108u8,
        226u8, 174u8, 222u8, 210u8, 68u8, 76u8, 117u8, 133u8, 211u8, 248u8, 202u8, 80u8, 57u8,
        248u8, 24u8, 109u8, 110u8, 229u8, 253u8, 136u8, 201u8,
    ],
    vk_gamma_g2: [
        7u8, 188u8, 205u8, 249u8, 172u8, 3u8, 122u8, 86u8, 201u8, 71u8, 18u8, 111u8, 183u8, 137u8,
        239u8, 233u8, 189u8, 175u8, 86u8, 25u8, 203u8, 219u8, 54u8, 233u8, 128u8, 57u8, 224u8,
        15u8, 45u8, 50u8, 188u8, 177u8, 23u8, 232u8, 80u8, 4u8, 218u8, 192u8, 188u8, 67u8, 41u8,
        227u8, 85u8, 157u8, 247u8, 96u8, 66u8, 48u8, 237u8, 62u8, 240u8, 221u8, 143u8, 213u8,
        108u8, 0u8, 6u8, 37u8, 154u8, 139u8, 246u8, 146u8, 241u8, 64u8, 37u8, 24u8, 30u8, 42u8,
        15u8, 173u8, 202u8, 226u8, 235u8, 53u8, 115u8, 253u8, 51u8, 32u8, 56u8, 181u8, 218u8, 38u8,
        120u8, 76u8, 193u8, 162u8, 147u8, 138u8, 222u8, 1u8, 62u8, 89u8, 77u8, 19u8, 144u8, 5u8,
        46u8, 142u8, 186u8, 174u8, 235u8, 82u8, 64u8, 210u8, 31u8, 203u8, 46u8, 82u8, 246u8, 69u8,
        106u8, 47u8, 40u8, 164u8, 137u8, 168u8, 221u8, 231u8, 174u8, 82u8, 167u8, 81u8, 67u8, 57u8,
        10u8, 154u8, 112u8, 243u8,
    ],
    vk_delta_g2: [
        11u8, 174u8, 123u8, 46u8, 206u8, 98u8, 6u8, 35u8, 234u8, 0u8, 140u8, 155u8, 67u8, 86u8,
        253u8, 235u8, 57u8, 202u8, 237u8, 31u8, 118u8, 116u8, 249u8, 217u8, 149u8, 30u8, 202u8,
        72u8, 166u8, 40u8, 104u8, 37u8, 20u8, 210u8, 154u8, 3u8, 236u8, 18u8, 134u8, 234u8, 29u8,
        242u8, 128u8, 234u8, 40u8, 16u8, 249u8, 38u8, 190u8, 9u8, 88u8, 158u8, 181u8, 199u8, 45u8,
        63u8, 159u8, 131u8, 171u8, 156u8, 226u8, 119u8, 81u8, 170u8, 3u8, 190u8, 147u8, 0u8, 176u8,
        89u8, 30u8, 68u8, 6u8, 181u8, 126u8, 128u8, 176u8, 67u8, 120u8, 165u8, 198u8, 72u8, 67u8,
        79u8, 192u8, 233u8, 32u8, 176u8, 89u8, 183u8, 178u8, 66u8, 68u8, 105u8, 162u8, 1u8, 24u8,
        52u8, 127u8, 57u8, 36u8, 21u8, 127u8, 17u8, 216u8, 235u8, 21u8, 79u8, 181u8, 234u8, 68u8,
        163u8, 188u8, 124u8, 148u8, 13u8, 99u8, 62u8, 136u8, 154u8, 78u8, 76u8, 0u8, 206u8, 80u8,
        25u8, 141u8, 138u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [104u8, 202u8, 194u8, 66u8, 183u8, 241u8, 248u8, 34u8, 110u8, 37u8, 81u8, 197u8, 223u8, 24u8, 137u8, 71u8, 248u8, 159u8, 202u8, 143u8, 177u8, 16u8, 246u8, 147u8, 192u8, 228u8, 227u8, 199u8, 151u8, 46u8, 213u8, 195u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_23fb3e84aaa88d1c")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x0068cac242b7f1f8226e2551c5df188947f89fca8fb110f693c0e4e3c7972ed5c3\x00=======END GROTH16 VK SETUP V1=======\x00";
