// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        42u8, 167u8, 57u8, 23u8, 6u8, 188u8, 181u8, 86u8, 240u8, 145u8, 105u8, 128u8, 5u8, 145u8,
        105u8, 139u8, 108u8, 51u8, 162u8, 142u8, 2u8, 233u8, 235u8, 207u8, 99u8, 74u8, 64u8, 1u8,
        16u8, 235u8, 35u8, 6u8, 2u8, 138u8, 204u8, 10u8, 196u8, 191u8, 181u8, 14u8, 0u8, 20u8,
        149u8, 86u8, 233u8, 238u8, 170u8, 113u8, 204u8, 181u8, 219u8, 79u8, 236u8, 203u8, 8u8,
        244u8, 172u8, 98u8, 180u8, 102u8, 121u8, 193u8, 148u8, 93u8,
    ],
    [
        11u8, 208u8, 5u8, 216u8, 3u8, 191u8, 206u8, 133u8, 121u8, 146u8, 202u8, 125u8, 238u8,
        198u8, 90u8, 76u8, 236u8, 39u8, 71u8, 254u8, 190u8, 63u8, 196u8, 207u8, 252u8, 43u8, 5u8,
        34u8, 193u8, 250u8, 67u8, 222u8, 33u8, 187u8, 80u8, 179u8, 230u8, 98u8, 25u8, 188u8, 0u8,
        188u8, 66u8, 104u8, 40u8, 28u8, 118u8, 73u8, 226u8, 60u8, 81u8, 119u8, 155u8, 190u8, 145u8,
        244u8, 243u8, 78u8, 135u8, 42u8, 190u8, 227u8, 58u8, 129u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        41u8, 227u8, 157u8, 192u8, 224u8, 152u8, 208u8, 98u8, 186u8, 175u8, 137u8, 141u8, 116u8,
        149u8, 131u8, 124u8, 221u8, 0u8, 40u8, 174u8, 250u8, 59u8, 216u8, 200u8, 176u8, 140u8,
        65u8, 211u8, 77u8, 176u8, 19u8, 125u8, 43u8, 49u8, 13u8, 215u8, 170u8, 199u8, 187u8, 242u8,
        140u8, 4u8, 61u8, 26u8, 26u8, 8u8, 192u8, 66u8, 50u8, 17u8, 242u8, 183u8, 47u8, 231u8,
        147u8, 187u8, 233u8, 237u8, 200u8, 8u8, 87u8, 236u8, 142u8, 43u8,
    ],
    vk_beta_g2: [
        6u8, 56u8, 234u8, 214u8, 9u8, 48u8, 205u8, 67u8, 16u8, 204u8, 25u8, 242u8, 67u8, 121u8,
        151u8, 182u8, 92u8, 122u8, 254u8, 134u8, 234u8, 231u8, 211u8, 142u8, 196u8, 135u8, 163u8,
        135u8, 53u8, 14u8, 28u8, 238u8, 33u8, 90u8, 150u8, 101u8, 126u8, 194u8, 253u8, 185u8,
        230u8, 175u8, 24u8, 87u8, 190u8, 225u8, 57u8, 56u8, 220u8, 232u8, 69u8, 22u8, 155u8, 163u8,
        33u8, 8u8, 50u8, 130u8, 102u8, 208u8, 237u8, 44u8, 171u8, 144u8, 20u8, 155u8, 60u8, 243u8,
        83u8, 175u8, 183u8, 47u8, 32u8, 188u8, 242u8, 201u8, 196u8, 145u8, 192u8, 232u8, 240u8,
        153u8, 23u8, 255u8, 187u8, 248u8, 95u8, 242u8, 241u8, 63u8, 176u8, 214u8, 70u8, 201u8,
        114u8, 189u8, 32u8, 125u8, 145u8, 243u8, 97u8, 165u8, 144u8, 20u8, 222u8, 6u8, 188u8,
        162u8, 177u8, 106u8, 221u8, 199u8, 64u8, 35u8, 36u8, 47u8, 200u8, 135u8, 241u8, 76u8, 28u8,
        136u8, 84u8, 194u8, 39u8, 84u8, 255u8, 180u8,
    ],
    vk_gamma_g2: [
        25u8, 72u8, 227u8, 184u8, 12u8, 238u8, 35u8, 173u8, 129u8, 186u8, 69u8, 221u8, 100u8, 74u8,
        18u8, 26u8, 165u8, 173u8, 78u8, 17u8, 57u8, 20u8, 40u8, 232u8, 164u8, 49u8, 105u8, 113u8,
        194u8, 52u8, 121u8, 109u8, 20u8, 44u8, 158u8, 234u8, 253u8, 200u8, 147u8, 222u8, 108u8,
        0u8, 239u8, 202u8, 95u8, 122u8, 84u8, 91u8, 142u8, 39u8, 2u8, 9u8, 126u8, 160u8, 156u8,
        41u8, 180u8, 121u8, 47u8, 76u8, 89u8, 12u8, 1u8, 220u8, 36u8, 129u8, 129u8, 223u8, 156u8,
        230u8, 18u8, 201u8, 19u8, 45u8, 141u8, 138u8, 244u8, 188u8, 187u8, 105u8, 225u8, 182u8,
        220u8, 59u8, 76u8, 61u8, 56u8, 157u8, 208u8, 234u8, 163u8, 190u8, 11u8, 138u8, 148u8, 82u8,
        43u8, 106u8, 86u8, 90u8, 123u8, 216u8, 220u8, 221u8, 137u8, 108u8, 38u8, 58u8, 27u8, 112u8,
        66u8, 6u8, 30u8, 114u8, 105u8, 201u8, 22u8, 129u8, 17u8, 21u8, 72u8, 107u8, 43u8, 227u8,
        30u8, 138u8, 202u8, 169u8,
    ],
    vk_delta_g2: [
        34u8, 107u8, 109u8, 52u8, 231u8, 32u8, 105u8, 160u8, 174u8, 161u8, 146u8, 134u8, 145u8,
        157u8, 201u8, 52u8, 74u8, 185u8, 60u8, 138u8, 232u8, 181u8, 100u8, 187u8, 38u8, 232u8,
        244u8, 28u8, 242u8, 3u8, 206u8, 238u8, 39u8, 28u8, 145u8, 36u8, 47u8, 203u8, 46u8, 207u8,
        30u8, 50u8, 95u8, 15u8, 227u8, 135u8, 72u8, 121u8, 7u8, 218u8, 231u8, 146u8, 192u8, 17u8,
        179u8, 142u8, 70u8, 164u8, 81u8, 159u8, 205u8, 59u8, 3u8, 230u8, 25u8, 3u8, 67u8, 9u8,
        176u8, 125u8, 86u8, 102u8, 126u8, 71u8, 7u8, 160u8, 164u8, 222u8, 23u8, 111u8, 115u8,
        252u8, 143u8, 240u8, 236u8, 153u8, 59u8, 145u8, 77u8, 234u8, 121u8, 201u8, 57u8, 183u8,
        195u8, 66u8, 20u8, 180u8, 26u8, 16u8, 238u8, 155u8, 234u8, 11u8, 155u8, 243u8, 40u8, 199u8,
        13u8, 21u8, 211u8, 32u8, 223u8, 247u8, 110u8, 149u8, 183u8, 41u8, 146u8, 249u8, 199u8,
        130u8, 28u8, 193u8, 39u8, 34u8, 84u8, 85u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [83u8, 160u8, 127u8, 137u8, 125u8, 34u8, 216u8, 35u8, 234u8, 105u8, 71u8, 72u8, 80u8, 177u8, 32u8, 27u8, 31u8, 240u8, 89u8, 121u8, 10u8, 217u8, 171u8, 15u8, 82u8, 106u8, 137u8, 42u8, 48u8, 192u8, 243u8, 229u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_9d44c18bc924ec51")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x0053a07f897d22d823ea69474850b1201b1ff059790ad9ab0f526a892a30c0f3e5\x00=======END GROTH16 VK SETUP V1=======\x00";
