// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        33u8, 116u8, 92u8, 11u8, 32u8, 140u8, 40u8, 234u8, 212u8, 4u8, 110u8, 74u8, 162u8, 181u8,
        38u8, 45u8, 88u8, 151u8, 105u8, 125u8, 53u8, 209u8, 122u8, 32u8, 16u8, 46u8, 215u8, 77u8,
        76u8, 138u8, 93u8, 165u8, 7u8, 27u8, 24u8, 154u8, 175u8, 102u8, 231u8, 154u8, 75u8, 93u8,
        89u8, 91u8, 25u8, 30u8, 144u8, 35u8, 54u8, 185u8, 122u8, 229u8, 178u8, 175u8, 169u8, 246u8,
        206u8, 75u8, 239u8, 218u8, 130u8, 8u8, 115u8, 142u8,
    ],
    [
        1u8, 45u8, 62u8, 26u8, 179u8, 14u8, 52u8, 254u8, 111u8, 14u8, 241u8, 118u8, 103u8, 178u8,
        2u8, 211u8, 178u8, 249u8, 66u8, 29u8, 244u8, 176u8, 36u8, 7u8, 107u8, 180u8, 147u8, 217u8,
        248u8, 132u8, 228u8, 54u8, 4u8, 85u8, 195u8, 85u8, 54u8, 146u8, 252u8, 188u8, 39u8, 208u8,
        150u8, 120u8, 230u8, 186u8, 72u8, 164u8, 106u8, 143u8, 55u8, 233u8, 60u8, 36u8, 175u8,
        147u8, 198u8, 200u8, 52u8, 54u8, 159u8, 88u8, 32u8, 10u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        47u8, 53u8, 206u8, 1u8, 161u8, 245u8, 101u8, 36u8, 227u8, 66u8, 134u8, 102u8, 202u8, 56u8,
        72u8, 254u8, 76u8, 210u8, 200u8, 142u8, 40u8, 99u8, 224u8, 31u8, 57u8, 153u8, 219u8, 59u8,
        75u8, 43u8, 134u8, 217u8, 15u8, 189u8, 143u8, 20u8, 90u8, 228u8, 161u8, 32u8, 13u8, 188u8,
        80u8, 156u8, 137u8, 186u8, 108u8, 105u8, 106u8, 123u8, 123u8, 76u8, 162u8, 110u8, 58u8,
        165u8, 39u8, 70u8, 242u8, 110u8, 109u8, 204u8, 21u8, 235u8,
    ],
    vk_beta_g2: [
        38u8, 86u8, 185u8, 144u8, 75u8, 63u8, 66u8, 121u8, 231u8, 200u8, 219u8, 117u8, 50u8, 110u8,
        152u8, 224u8, 98u8, 229u8, 42u8, 131u8, 31u8, 200u8, 50u8, 41u8, 168u8, 181u8, 178u8,
        179u8, 140u8, 128u8, 160u8, 1u8, 16u8, 167u8, 89u8, 57u8, 166u8, 28u8, 95u8, 195u8, 132u8,
        207u8, 50u8, 202u8, 59u8, 191u8, 95u8, 121u8, 75u8, 171u8, 185u8, 108u8, 224u8, 248u8,
        99u8, 12u8, 165u8, 35u8, 115u8, 110u8, 199u8, 2u8, 68u8, 32u8, 46u8, 167u8, 201u8, 108u8,
        17u8, 110u8, 154u8, 163u8, 175u8, 19u8, 12u8, 32u8, 49u8, 112u8, 63u8, 30u8, 122u8, 246u8,
        220u8, 207u8, 107u8, 78u8, 59u8, 204u8, 154u8, 236u8, 241u8, 255u8, 171u8, 3u8, 43u8,
        114u8, 38u8, 141u8, 137u8, 135u8, 201u8, 221u8, 75u8, 60u8, 120u8, 201u8, 111u8, 0u8,
        179u8, 58u8, 88u8, 221u8, 164u8, 23u8, 205u8, 156u8, 120u8, 150u8, 202u8, 126u8, 74u8,
        227u8, 137u8, 109u8, 248u8, 225u8, 255u8, 252u8,
    ],
    vk_gamma_g2: [
        44u8, 200u8, 216u8, 125u8, 211u8, 136u8, 200u8, 169u8, 192u8, 218u8, 154u8, 89u8, 158u8,
        56u8, 228u8, 30u8, 255u8, 21u8, 127u8, 166u8, 215u8, 14u8, 168u8, 98u8, 20u8, 35u8, 103u8,
        58u8, 204u8, 140u8, 35u8, 217u8, 8u8, 219u8, 242u8, 2u8, 57u8, 255u8, 94u8, 134u8, 105u8,
        106u8, 67u8, 187u8, 38u8, 115u8, 102u8, 12u8, 66u8, 104u8, 192u8, 111u8, 212u8, 42u8,
        106u8, 31u8, 40u8, 192u8, 247u8, 194u8, 77u8, 107u8, 159u8, 98u8, 31u8, 218u8, 84u8, 89u8,
        198u8, 83u8, 52u8, 54u8, 139u8, 45u8, 80u8, 94u8, 242u8, 128u8, 92u8, 183u8, 154u8, 159u8,
        249u8, 110u8, 69u8, 0u8, 52u8, 200u8, 50u8, 115u8, 158u8, 208u8, 151u8, 65u8, 51u8, 84u8,
        8u8, 21u8, 88u8, 7u8, 51u8, 200u8, 201u8, 215u8, 16u8, 250u8, 153u8, 94u8, 5u8, 10u8,
        223u8, 211u8, 242u8, 230u8, 138u8, 201u8, 43u8, 135u8, 104u8, 221u8, 18u8, 233u8, 98u8,
        42u8, 51u8, 53u8, 144u8, 5u8,
    ],
    vk_delta_g2: [
        35u8, 248u8, 74u8, 46u8, 179u8, 197u8, 107u8, 16u8, 230u8, 248u8, 214u8, 204u8, 171u8,
        246u8, 151u8, 11u8, 53u8, 241u8, 227u8, 23u8, 10u8, 193u8, 127u8, 47u8, 155u8, 177u8,
        244u8, 141u8, 1u8, 60u8, 196u8, 242u8, 31u8, 91u8, 84u8, 145u8, 16u8, 86u8, 88u8, 7u8,
        157u8, 109u8, 124u8, 15u8, 106u8, 253u8, 231u8, 109u8, 58u8, 166u8, 200u8, 194u8, 208u8,
        206u8, 216u8, 30u8, 155u8, 124u8, 124u8, 188u8, 44u8, 27u8, 227u8, 133u8, 24u8, 59u8, 80u8,
        169u8, 254u8, 128u8, 95u8, 4u8, 170u8, 120u8, 133u8, 128u8, 126u8, 177u8, 161u8, 234u8,
        88u8, 203u8, 168u8, 254u8, 136u8, 222u8, 64u8, 209u8, 118u8, 98u8, 131u8, 42u8, 44u8, 67u8,
        193u8, 48u8, 27u8, 150u8, 159u8, 190u8, 223u8, 59u8, 141u8, 86u8, 46u8, 254u8, 155u8, 57u8,
        228u8, 55u8, 239u8, 122u8, 32u8, 23u8, 188u8, 90u8, 203u8, 15u8, 5u8, 133u8, 164u8, 194u8,
        68u8, 147u8, 192u8, 80u8, 177u8, 27u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [83u8, 6u8, 78u8, 66u8, 77u8, 1u8, 103u8, 14u8, 218u8, 136u8, 99u8, 253u8, 118u8, 141u8, 194u8, 40u8, 185u8, 57u8, 155u8, 242u8, 221u8, 130u8, 39u8, 50u8, 40u8, 133u8, 3u8, 4u8, 169u8, 81u8, 85u8, 69u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_587ec294e8519cf3")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x0053064e424d01670eda8863fd768dc228b9399bf2dd82273228850304a9515545\x00=======END GROTH16 VK SETUP V1=======\x00";
