// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        28u8, 48u8, 137u8, 9u8, 206u8, 219u8, 10u8, 116u8, 120u8, 53u8, 165u8, 228u8, 103u8, 109u8,
        214u8, 161u8, 103u8, 184u8, 190u8, 139u8, 212u8, 193u8, 29u8, 241u8, 145u8, 248u8, 132u8,
        178u8, 160u8, 96u8, 229u8, 4u8, 34u8, 162u8, 248u8, 17u8, 164u8, 83u8, 189u8, 24u8, 192u8,
        131u8, 165u8, 161u8, 111u8, 138u8, 9u8, 185u8, 145u8, 235u8, 107u8, 68u8, 112u8, 42u8,
        90u8, 222u8, 235u8, 185u8, 166u8, 108u8, 175u8, 11u8, 105u8, 223u8,
    ],
    [
        2u8, 34u8, 219u8, 51u8, 27u8, 159u8, 2u8, 232u8, 189u8, 126u8, 90u8, 190u8, 173u8, 125u8,
        163u8, 178u8, 198u8, 64u8, 19u8, 175u8, 198u8, 188u8, 208u8, 156u8, 191u8, 172u8, 88u8,
        2u8, 182u8, 194u8, 204u8, 176u8, 11u8, 28u8, 223u8, 216u8, 27u8, 255u8, 199u8, 187u8, 20u8,
        110u8, 225u8, 243u8, 59u8, 23u8, 207u8, 150u8, 248u8, 7u8, 138u8, 34u8, 123u8, 174u8,
        135u8, 106u8, 144u8, 4u8, 43u8, 21u8, 36u8, 189u8, 87u8, 199u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        37u8, 68u8, 118u8, 93u8, 8u8, 247u8, 180u8, 139u8, 0u8, 228u8, 6u8, 126u8, 82u8, 149u8,
        66u8, 57u8, 54u8, 45u8, 99u8, 108u8, 158u8, 122u8, 72u8, 223u8, 37u8, 189u8, 239u8, 51u8,
        31u8, 216u8, 71u8, 32u8, 6u8, 244u8, 230u8, 167u8, 28u8, 134u8, 7u8, 6u8, 46u8, 102u8, 2u8,
        235u8, 154u8, 83u8, 182u8, 80u8, 203u8, 48u8, 143u8, 82u8, 144u8, 111u8, 139u8, 143u8,
        242u8, 124u8, 34u8, 104u8, 135u8, 27u8, 195u8, 92u8,
    ],
    vk_beta_g2: [
        23u8, 12u8, 204u8, 208u8, 110u8, 97u8, 123u8, 84u8, 122u8, 39u8, 33u8, 84u8, 67u8, 23u8,
        163u8, 17u8, 7u8, 23u8, 255u8, 174u8, 196u8, 78u8, 74u8, 126u8, 243u8, 172u8, 5u8, 67u8,
        178u8, 39u8, 153u8, 61u8, 15u8, 77u8, 88u8, 134u8, 107u8, 175u8, 187u8, 9u8, 14u8, 33u8,
        188u8, 67u8, 111u8, 244u8, 58u8, 53u8, 94u8, 31u8, 54u8, 169u8, 70u8, 144u8, 35u8, 83u8,
        231u8, 91u8, 188u8, 143u8, 46u8, 169u8, 237u8, 21u8, 44u8, 96u8, 216u8, 181u8, 223u8,
        242u8, 152u8, 74u8, 32u8, 19u8, 161u8, 73u8, 163u8, 183u8, 242u8, 111u8, 24u8, 86u8, 148u8,
        232u8, 119u8, 65u8, 105u8, 45u8, 100u8, 224u8, 202u8, 58u8, 218u8, 60u8, 123u8, 61u8, 47u8,
        133u8, 154u8, 237u8, 96u8, 185u8, 217u8, 3u8, 87u8, 203u8, 212u8, 20u8, 139u8, 86u8, 187u8,
        128u8, 130u8, 93u8, 38u8, 153u8, 136u8, 44u8, 124u8, 225u8, 143u8, 51u8, 30u8, 185u8,
        152u8, 129u8, 229u8, 148u8,
    ],
    vk_gamma_g2: [
        5u8, 101u8, 86u8, 117u8, 82u8, 242u8, 108u8, 243u8, 100u8, 38u8, 2u8, 224u8, 128u8, 233u8,
        28u8, 62u8, 28u8, 107u8, 214u8, 153u8, 146u8, 245u8, 58u8, 81u8, 125u8, 4u8, 251u8, 30u8,
        243u8, 200u8, 158u8, 239u8, 41u8, 149u8, 74u8, 220u8, 228u8, 163u8, 86u8, 222u8, 109u8,
        93u8, 0u8, 142u8, 158u8, 161u8, 220u8, 202u8, 133u8, 229u8, 18u8, 179u8, 10u8, 235u8,
        186u8, 18u8, 136u8, 221u8, 58u8, 61u8, 38u8, 213u8, 116u8, 198u8, 13u8, 195u8, 107u8,
        189u8, 101u8, 1u8, 100u8, 63u8, 53u8, 45u8, 70u8, 137u8, 55u8, 116u8, 26u8, 41u8, 9u8,
        152u8, 161u8, 70u8, 43u8, 142u8, 221u8, 59u8, 60u8, 169u8, 47u8, 205u8, 170u8, 208u8, 12u8,
        135u8, 7u8, 38u8, 97u8, 201u8, 25u8, 47u8, 78u8, 40u8, 13u8, 29u8, 158u8, 98u8, 145u8,
        43u8, 72u8, 131u8, 95u8, 30u8, 131u8, 163u8, 133u8, 104u8, 76u8, 161u8, 172u8, 39u8, 58u8,
        31u8, 114u8, 198u8, 206u8, 144u8,
    ],
    vk_delta_g2: [
        41u8, 65u8, 162u8, 30u8, 246u8, 108u8, 23u8, 239u8, 36u8, 225u8, 10u8, 228u8, 94u8, 8u8,
        31u8, 182u8, 196u8, 138u8, 105u8, 236u8, 193u8, 192u8, 148u8, 155u8, 205u8, 125u8, 53u8,
        219u8, 136u8, 195u8, 2u8, 247u8, 38u8, 232u8, 90u8, 14u8, 217u8, 22u8, 26u8, 153u8, 21u8,
        145u8, 149u8, 210u8, 133u8, 165u8, 109u8, 234u8, 216u8, 229u8, 52u8, 205u8, 174u8, 126u8,
        202u8, 189u8, 45u8, 235u8, 195u8, 208u8, 137u8, 132u8, 154u8, 35u8, 44u8, 106u8, 146u8,
        236u8, 133u8, 56u8, 20u8, 239u8, 161u8, 185u8, 166u8, 189u8, 158u8, 17u8, 187u8, 186u8,
        202u8, 119u8, 105u8, 242u8, 33u8, 195u8, 188u8, 239u8, 81u8, 222u8, 248u8, 48u8, 245u8,
        97u8, 70u8, 37u8, 37u8, 177u8, 5u8, 34u8, 68u8, 190u8, 25u8, 254u8, 149u8, 218u8, 231u8,
        222u8, 42u8, 82u8, 183u8, 243u8, 32u8, 225u8, 138u8, 124u8, 195u8, 149u8, 173u8, 24u8,
        233u8, 104u8, 159u8, 148u8, 236u8, 228u8, 148u8, 68u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [182u8, 213u8, 142u8, 49u8, 160u8, 58u8, 187u8, 4u8, 64u8, 50u8, 232u8, 68u8, 23u8, 124u8, 56u8, 4u8, 230u8, 216u8, 114u8, 153u8, 112u8, 84u8, 62u8, 37u8, 131u8, 9u8, 71u8, 32u8, 193u8, 54u8, 174u8, 111u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_b1e6cdf16abbed90")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00b6d58e31a03abb044032e844177c3804e6d8729970543e2583094720c136ae6f\x00=======END GROTH16 VK SETUP V1=======\x00";
