// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        35u8, 136u8, 96u8, 147u8, 166u8, 234u8, 167u8, 53u8, 17u8, 36u8, 76u8, 168u8, 66u8, 99u8,
        95u8, 178u8, 81u8, 82u8, 77u8, 181u8, 199u8, 172u8, 100u8, 97u8, 86u8, 221u8, 188u8, 177u8,
        156u8, 191u8, 63u8, 25u8, 45u8, 63u8, 84u8, 100u8, 108u8, 79u8, 33u8, 181u8, 246u8, 217u8,
        218u8, 40u8, 47u8, 6u8, 182u8, 254u8, 199u8, 167u8, 255u8, 237u8, 66u8, 96u8, 46u8, 146u8,
        250u8, 58u8, 255u8, 13u8, 196u8, 36u8, 168u8, 121u8,
    ],
    [
        5u8, 91u8, 132u8, 190u8, 221u8, 138u8, 235u8, 172u8, 233u8, 34u8, 108u8, 236u8, 153u8,
        150u8, 176u8, 135u8, 127u8, 228u8, 83u8, 245u8, 109u8, 80u8, 100u8, 210u8, 1u8, 11u8,
        230u8, 162u8, 153u8, 195u8, 42u8, 106u8, 25u8, 223u8, 111u8, 175u8, 252u8, 145u8, 200u8,
        70u8, 21u8, 218u8, 151u8, 216u8, 84u8, 255u8, 145u8, 42u8, 44u8, 246u8, 204u8, 85u8, 106u8,
        4u8, 124u8, 127u8, 110u8, 164u8, 68u8, 247u8, 201u8, 137u8, 194u8, 155u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        38u8, 25u8, 28u8, 213u8, 228u8, 73u8, 239u8, 13u8, 120u8, 253u8, 202u8, 127u8, 13u8, 98u8,
        9u8, 21u8, 238u8, 146u8, 71u8, 237u8, 73u8, 110u8, 190u8, 9u8, 213u8, 25u8, 165u8, 197u8,
        41u8, 24u8, 76u8, 134u8, 24u8, 149u8, 192u8, 68u8, 159u8, 75u8, 97u8, 119u8, 126u8, 85u8,
        148u8, 184u8, 173u8, 179u8, 184u8, 23u8, 234u8, 12u8, 252u8, 70u8, 74u8, 44u8, 115u8, 99u8,
        17u8, 185u8, 224u8, 102u8, 235u8, 253u8, 160u8, 165u8,
    ],
    vk_beta_g2: [
        6u8, 11u8, 44u8, 141u8, 117u8, 165u8, 217u8, 46u8, 133u8, 240u8, 100u8, 188u8, 65u8, 39u8,
        41u8, 223u8, 71u8, 34u8, 105u8, 88u8, 70u8, 142u8, 1u8, 49u8, 213u8, 27u8, 36u8, 97u8,
        244u8, 4u8, 158u8, 24u8, 14u8, 213u8, 0u8, 110u8, 219u8, 20u8, 81u8, 12u8, 193u8, 100u8,
        179u8, 74u8, 152u8, 69u8, 102u8, 248u8, 152u8, 103u8, 171u8, 16u8, 7u8, 90u8, 206u8, 119u8,
        188u8, 228u8, 211u8, 241u8, 74u8, 225u8, 8u8, 123u8, 41u8, 135u8, 224u8, 60u8, 128u8, 1u8,
        86u8, 239u8, 141u8, 222u8, 73u8, 134u8, 16u8, 32u8, 60u8, 195u8, 31u8, 171u8, 60u8, 142u8,
        99u8, 37u8, 216u8, 16u8, 77u8, 109u8, 198u8, 129u8, 78u8, 221u8, 62u8, 159u8, 14u8, 120u8,
        84u8, 120u8, 82u8, 194u8, 0u8, 202u8, 41u8, 116u8, 97u8, 111u8, 208u8, 208u8, 236u8, 36u8,
        36u8, 120u8, 211u8, 18u8, 119u8, 131u8, 85u8, 205u8, 141u8, 109u8, 236u8, 157u8, 6u8,
        100u8, 102u8, 204u8,
    ],
    vk_gamma_g2: [
        46u8, 191u8, 207u8, 224u8, 211u8, 78u8, 204u8, 71u8, 47u8, 228u8, 126u8, 28u8, 162u8, 93u8,
        164u8, 212u8, 123u8, 238u8, 122u8, 171u8, 234u8, 102u8, 124u8, 142u8, 254u8, 206u8, 19u8,
        221u8, 185u8, 125u8, 222u8, 69u8, 1u8, 62u8, 111u8, 248u8, 125u8, 95u8, 44u8, 8u8, 131u8,
        54u8, 136u8, 170u8, 147u8, 15u8, 99u8, 56u8, 218u8, 4u8, 66u8, 20u8, 243u8, 235u8, 164u8,
        10u8, 42u8, 180u8, 166u8, 122u8, 167u8, 161u8, 186u8, 67u8, 0u8, 113u8, 90u8, 32u8, 2u8,
        97u8, 167u8, 149u8, 174u8, 164u8, 149u8, 149u8, 49u8, 76u8, 189u8, 168u8, 49u8, 55u8, 25u8,
        148u8, 94u8, 210u8, 30u8, 43u8, 108u8, 125u8, 7u8, 113u8, 125u8, 209u8, 130u8, 153u8, 18u8,
        230u8, 135u8, 93u8, 196u8, 165u8, 26u8, 206u8, 209u8, 149u8, 32u8, 28u8, 173u8, 79u8, 23u8,
        23u8, 127u8, 31u8, 238u8, 240u8, 25u8, 107u8, 150u8, 161u8, 145u8, 240u8, 15u8, 227u8,
        67u8, 102u8, 74u8, 220u8,
    ],
    vk_delta_g2: [
        21u8, 178u8, 166u8, 123u8, 78u8, 146u8, 157u8, 1u8, 10u8, 183u8, 75u8, 121u8, 6u8, 105u8,
        2u8, 225u8, 173u8, 28u8, 117u8, 172u8, 46u8, 180u8, 164u8, 76u8, 151u8, 7u8, 103u8, 52u8,
        244u8, 78u8, 51u8, 135u8, 34u8, 157u8, 53u8, 68u8, 197u8, 10u8, 109u8, 141u8, 196u8, 64u8,
        124u8, 162u8, 67u8, 198u8, 66u8, 101u8, 24u8, 151u8, 130u8, 23u8, 212u8, 122u8, 85u8, 4u8,
        116u8, 41u8, 181u8, 74u8, 27u8, 7u8, 82u8, 91u8, 0u8, 117u8, 82u8, 178u8, 117u8, 186u8,
        0u8, 218u8, 138u8, 45u8, 81u8, 81u8, 32u8, 72u8, 82u8, 55u8, 156u8, 5u8, 55u8, 183u8,
        136u8, 80u8, 194u8, 2u8, 116u8, 97u8, 47u8, 239u8, 138u8, 51u8, 245u8, 127u8, 11u8, 156u8,
        30u8, 133u8, 103u8, 42u8, 69u8, 246u8, 30u8, 217u8, 212u8, 89u8, 127u8, 192u8, 114u8, 90u8,
        148u8, 228u8, 8u8, 19u8, 205u8, 159u8, 186u8, 210u8, 225u8, 247u8, 176u8, 56u8, 142u8,
        233u8, 13u8, 28u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [17u8, 229u8, 5u8, 166u8, 98u8, 183u8, 206u8, 252u8, 169u8, 219u8, 117u8, 112u8, 73u8, 195u8, 32u8, 68u8, 9u8, 107u8, 43u8, 242u8, 141u8, 44u8, 236u8, 254u8, 171u8, 66u8, 232u8, 46u8, 115u8, 177u8, 66u8, 174u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_d25613796f4241b4")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x0011e505a662b7cefca9db757049c32044096b2bf28d2cecfeab42e82e73b142ae\x00=======END GROTH16 VK SETUP V1=======\x00";
