// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        32u8, 219u8, 191u8, 126u8, 56u8, 67u8, 34u8, 213u8, 28u8, 190u8, 165u8, 95u8, 62u8, 254u8,
        237u8, 100u8, 145u8, 57u8, 214u8, 221u8, 103u8, 83u8, 113u8, 159u8, 195u8, 82u8, 136u8,
        52u8, 7u8, 197u8, 220u8, 143u8, 41u8, 149u8, 251u8, 111u8, 216u8, 239u8, 48u8, 15u8, 226u8,
        185u8, 5u8, 236u8, 81u8, 211u8, 250u8, 230u8, 107u8, 80u8, 2u8, 197u8, 12u8, 218u8, 135u8,
        244u8, 9u8, 174u8, 163u8, 108u8, 80u8, 90u8, 111u8, 172u8,
    ],
    [
        36u8, 206u8, 77u8, 81u8, 153u8, 8u8, 121u8, 145u8, 118u8, 127u8, 81u8, 208u8, 226u8, 196u8,
        104u8, 190u8, 248u8, 143u8, 232u8, 142u8, 205u8, 231u8, 123u8, 1u8, 196u8, 142u8, 189u8,
        3u8, 140u8, 247u8, 33u8, 7u8, 7u8, 245u8, 200u8, 41u8, 208u8, 66u8, 243u8, 163u8, 133u8,
        153u8, 144u8, 35u8, 107u8, 45u8, 192u8, 40u8, 230u8, 167u8, 58u8, 204u8, 13u8, 198u8,
        106u8, 197u8, 169u8, 86u8, 153u8, 254u8, 102u8, 54u8, 169u8, 156u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        11u8, 6u8, 241u8, 25u8, 182u8, 198u8, 79u8, 252u8, 168u8, 54u8, 50u8, 54u8, 191u8, 41u8,
        228u8, 148u8, 10u8, 205u8, 44u8, 223u8, 154u8, 121u8, 71u8, 198u8, 223u8, 236u8, 203u8,
        73u8, 68u8, 91u8, 98u8, 145u8, 20u8, 72u8, 170u8, 238u8, 155u8, 51u8, 3u8, 90u8, 171u8,
        235u8, 12u8, 155u8, 152u8, 197u8, 197u8, 155u8, 176u8, 245u8, 140u8, 51u8, 112u8, 80u8,
        156u8, 142u8, 22u8, 65u8, 55u8, 205u8, 206u8, 87u8, 236u8, 112u8,
    ],
    vk_beta_g2: [
        25u8, 145u8, 69u8, 133u8, 163u8, 33u8, 99u8, 209u8, 114u8, 213u8, 145u8, 88u8, 70u8, 18u8,
        1u8, 34u8, 145u8, 245u8, 10u8, 43u8, 70u8, 38u8, 159u8, 93u8, 123u8, 139u8, 180u8, 213u8,
        114u8, 78u8, 223u8, 61u8, 33u8, 232u8, 100u8, 82u8, 6u8, 46u8, 163u8, 111u8, 70u8, 247u8,
        246u8, 199u8, 219u8, 170u8, 204u8, 234u8, 31u8, 255u8, 121u8, 122u8, 191u8, 31u8, 174u8,
        4u8, 77u8, 36u8, 19u8, 146u8, 149u8, 42u8, 67u8, 245u8, 41u8, 244u8, 40u8, 55u8, 58u8,
        225u8, 136u8, 65u8, 192u8, 13u8, 3u8, 35u8, 217u8, 147u8, 254u8, 138u8, 120u8, 108u8, 79u8,
        219u8, 157u8, 214u8, 184u8, 182u8, 105u8, 241u8, 10u8, 20u8, 220u8, 10u8, 212u8, 140u8,
        15u8, 166u8, 54u8, 93u8, 147u8, 252u8, 223u8, 28u8, 121u8, 66u8, 242u8, 202u8, 214u8,
        231u8, 145u8, 189u8, 230u8, 235u8, 39u8, 98u8, 252u8, 70u8, 57u8, 157u8, 150u8, 167u8,
        225u8, 81u8, 42u8, 34u8, 128u8, 101u8,
    ],
    vk_gamma_g2: [
        13u8, 128u8, 35u8, 139u8, 2u8, 241u8, 199u8, 106u8, 62u8, 26u8, 234u8, 157u8, 9u8, 242u8,
        14u8, 219u8, 42u8, 170u8, 211u8, 158u8, 238u8, 222u8, 156u8, 209u8, 18u8, 211u8, 189u8,
        152u8, 191u8, 3u8, 211u8, 97u8, 45u8, 17u8, 230u8, 218u8, 20u8, 114u8, 190u8, 174u8, 252u8,
        212u8, 139u8, 55u8, 93u8, 111u8, 49u8, 239u8, 209u8, 201u8, 73u8, 126u8, 163u8, 237u8,
        16u8, 192u8, 227u8, 56u8, 41u8, 184u8, 172u8, 245u8, 109u8, 236u8, 9u8, 108u8, 130u8,
        240u8, 89u8, 131u8, 154u8, 195u8, 10u8, 253u8, 161u8, 182u8, 38u8, 32u8, 73u8, 40u8, 4u8,
        169u8, 70u8, 77u8, 149u8, 6u8, 29u8, 235u8, 50u8, 156u8, 15u8, 230u8, 211u8, 169u8, 58u8,
        181u8, 43u8, 133u8, 46u8, 232u8, 144u8, 75u8, 71u8, 187u8, 102u8, 153u8, 7u8, 147u8, 88u8,
        225u8, 250u8, 119u8, 124u8, 111u8, 112u8, 67u8, 227u8, 200u8, 14u8, 179u8, 115u8, 68u8,
        14u8, 137u8, 127u8, 243u8, 8u8, 15u8,
    ],
    vk_delta_g2: [
        42u8, 247u8, 18u8, 85u8, 99u8, 152u8, 156u8, 152u8, 170u8, 166u8, 110u8, 173u8, 58u8,
        111u8, 87u8, 118u8, 9u8, 74u8, 162u8, 4u8, 197u8, 32u8, 17u8, 54u8, 167u8, 23u8, 62u8,
        186u8, 244u8, 236u8, 204u8, 67u8, 6u8, 79u8, 248u8, 204u8, 248u8, 104u8, 43u8, 3u8, 187u8,
        101u8, 24u8, 124u8, 1u8, 155u8, 175u8, 4u8, 81u8, 244u8, 198u8, 87u8, 210u8, 92u8, 41u8,
        138u8, 140u8, 81u8, 237u8, 26u8, 185u8, 30u8, 57u8, 114u8, 44u8, 98u8, 50u8, 158u8, 91u8,
        106u8, 254u8, 56u8, 8u8, 215u8, 12u8, 165u8, 69u8, 31u8, 132u8, 107u8, 209u8, 56u8, 112u8,
        61u8, 25u8, 195u8, 179u8, 186u8, 205u8, 190u8, 252u8, 3u8, 8u8, 38u8, 238u8, 193u8, 7u8,
        133u8, 59u8, 148u8, 91u8, 221u8, 78u8, 206u8, 17u8, 45u8, 64u8, 244u8, 217u8, 241u8, 99u8,
        81u8, 188u8, 161u8, 91u8, 54u8, 0u8, 224u8, 209u8, 13u8, 119u8, 17u8, 1u8, 126u8, 200u8,
        189u8, 117u8, 133u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [238u8, 58u8, 139u8, 48u8, 169u8, 4u8, 84u8, 241u8, 219u8, 64u8, 235u8, 93u8, 112u8, 69u8, 143u8, 157u8, 176u8, 86u8, 40u8, 235u8, 11u8, 240u8, 66u8, 89u8, 144u8, 154u8, 157u8, 237u8, 240u8, 207u8, 27u8, 157u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_023244d8a416529a")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00ee3a8b30a90454f1db40eb5d70458f9db05628eb0bf04259909a9dedf0cf1b9d\x00=======END GROTH16 VK SETUP V1=======\x00";
