// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        30u8, 166u8, 38u8, 118u8, 237u8, 147u8, 40u8, 28u8, 156u8, 166u8, 118u8, 42u8, 231u8, 71u8,
        60u8, 252u8, 147u8, 13u8, 249u8, 69u8, 48u8, 180u8, 79u8, 23u8, 115u8, 41u8, 2u8, 211u8,
        128u8, 168u8, 140u8, 177u8, 23u8, 204u8, 242u8, 162u8, 196u8, 116u8, 236u8, 86u8, 109u8,
        95u8, 209u8, 4u8, 58u8, 109u8, 121u8, 244u8, 130u8, 89u8, 120u8, 219u8, 178u8, 93u8, 70u8,
        183u8, 80u8, 122u8, 26u8, 27u8, 161u8, 12u8, 92u8, 168u8,
    ],
    [
        16u8, 4u8, 153u8, 62u8, 71u8, 234u8, 201u8, 105u8, 121u8, 99u8, 203u8, 232u8, 161u8, 0u8,
        2u8, 104u8, 16u8, 26u8, 39u8, 119u8, 118u8, 214u8, 86u8, 231u8, 19u8, 170u8, 229u8, 18u8,
        69u8, 159u8, 33u8, 125u8, 39u8, 115u8, 10u8, 195u8, 202u8, 52u8, 59u8, 70u8, 167u8, 54u8,
        113u8, 119u8, 249u8, 41u8, 121u8, 0u8, 61u8, 50u8, 202u8, 27u8, 229u8, 211u8, 50u8, 22u8,
        145u8, 152u8, 21u8, 207u8, 112u8, 114u8, 192u8, 196u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        6u8, 202u8, 91u8, 107u8, 94u8, 218u8, 154u8, 113u8, 69u8, 157u8, 152u8, 225u8, 229u8, 11u8,
        168u8, 109u8, 1u8, 6u8, 154u8, 174u8, 42u8, 7u8, 36u8, 239u8, 74u8, 178u8, 69u8, 164u8,
        43u8, 57u8, 4u8, 50u8, 27u8, 220u8, 231u8, 87u8, 214u8, 163u8, 64u8, 63u8, 140u8, 112u8,
        236u8, 185u8, 233u8, 166u8, 55u8, 184u8, 95u8, 17u8, 91u8, 137u8, 115u8, 172u8, 2u8, 211u8,
        162u8, 116u8, 174u8, 222u8, 59u8, 110u8, 29u8, 32u8,
    ],
    vk_beta_g2: [
        27u8, 231u8, 35u8, 45u8, 225u8, 205u8, 173u8, 147u8, 106u8, 173u8, 144u8, 139u8, 103u8,
        9u8, 246u8, 175u8, 199u8, 220u8, 189u8, 104u8, 41u8, 204u8, 248u8, 222u8, 150u8, 111u8,
        124u8, 152u8, 107u8, 101u8, 198u8, 124u8, 36u8, 58u8, 22u8, 77u8, 39u8, 210u8, 41u8, 159u8,
        180u8, 89u8, 131u8, 105u8, 5u8, 97u8, 201u8, 252u8, 82u8, 103u8, 139u8, 236u8, 40u8, 196u8,
        125u8, 22u8, 104u8, 166u8, 180u8, 46u8, 33u8, 74u8, 23u8, 91u8, 41u8, 150u8, 3u8, 101u8,
        212u8, 39u8, 245u8, 132u8, 79u8, 211u8, 39u8, 113u8, 175u8, 89u8, 250u8, 188u8, 253u8,
        53u8, 51u8, 29u8, 166u8, 123u8, 30u8, 84u8, 74u8, 238u8, 174u8, 134u8, 139u8, 151u8, 93u8,
        185u8, 17u8, 95u8, 178u8, 157u8, 108u8, 241u8, 142u8, 45u8, 254u8, 115u8, 122u8, 84u8,
        121u8, 154u8, 179u8, 34u8, 180u8, 75u8, 127u8, 193u8, 123u8, 122u8, 176u8, 252u8, 183u8,
        14u8, 105u8, 78u8, 188u8, 55u8, 145u8, 32u8,
    ],
    vk_gamma_g2: [
        30u8, 23u8, 46u8, 74u8, 122u8, 76u8, 36u8, 57u8, 242u8, 109u8, 68u8, 115u8, 227u8, 82u8,
        179u8, 42u8, 202u8, 57u8, 227u8, 47u8, 240u8, 224u8, 232u8, 229u8, 55u8, 143u8, 167u8,
        202u8, 36u8, 198u8, 125u8, 92u8, 26u8, 139u8, 52u8, 254u8, 54u8, 161u8, 62u8, 115u8, 144u8,
        3u8, 120u8, 23u8, 111u8, 132u8, 165u8, 203u8, 224u8, 236u8, 237u8, 136u8, 176u8, 245u8,
        210u8, 243u8, 210u8, 243u8, 185u8, 216u8, 141u8, 34u8, 37u8, 159u8, 42u8, 94u8, 225u8,
        191u8, 200u8, 51u8, 102u8, 166u8, 89u8, 145u8, 63u8, 178u8, 207u8, 197u8, 184u8, 118u8,
        237u8, 249u8, 71u8, 28u8, 92u8, 243u8, 34u8, 179u8, 106u8, 80u8, 187u8, 138u8, 126u8,
        181u8, 41u8, 173u8, 4u8, 7u8, 89u8, 49u8, 197u8, 248u8, 90u8, 48u8, 221u8, 184u8, 249u8,
        61u8, 17u8, 134u8, 10u8, 246u8, 15u8, 217u8, 55u8, 166u8, 106u8, 132u8, 217u8, 253u8, 53u8,
        248u8, 100u8, 12u8, 35u8, 14u8, 241u8, 47u8,
    ],
    vk_delta_g2: [
        28u8, 169u8, 230u8, 202u8, 73u8, 233u8, 125u8, 238u8, 226u8, 121u8, 198u8, 62u8, 187u8,
        147u8, 251u8, 54u8, 163u8, 186u8, 87u8, 244u8, 138u8, 191u8, 220u8, 209u8, 142u8, 123u8,
        78u8, 63u8, 235u8, 221u8, 253u8, 28u8, 4u8, 114u8, 77u8, 28u8, 151u8, 104u8, 134u8, 137u8,
        61u8, 148u8, 124u8, 147u8, 64u8, 154u8, 44u8, 38u8, 253u8, 210u8, 228u8, 208u8, 178u8,
        14u8, 62u8, 112u8, 40u8, 191u8, 142u8, 123u8, 84u8, 124u8, 230u8, 180u8, 44u8, 42u8, 113u8,
        93u8, 191u8, 114u8, 46u8, 6u8, 99u8, 159u8, 235u8, 255u8, 103u8, 215u8, 211u8, 223u8,
        249u8, 238u8, 64u8, 13u8, 9u8, 133u8, 195u8, 245u8, 35u8, 47u8, 14u8, 52u8, 110u8, 135u8,
        17u8, 181u8, 36u8, 56u8, 30u8, 107u8, 158u8, 172u8, 27u8, 94u8, 175u8, 99u8, 193u8, 71u8,
        177u8, 159u8, 237u8, 67u8, 65u8, 246u8, 254u8, 132u8, 41u8, 236u8, 167u8, 200u8, 150u8,
        254u8, 140u8, 169u8, 135u8, 255u8, 233u8, 88u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [233u8, 94u8, 165u8, 102u8, 218u8, 73u8, 219u8, 95u8, 250u8, 73u8, 150u8, 167u8, 173u8, 4u8, 79u8, 162u8, 126u8, 178u8, 73u8, 15u8, 75u8, 122u8, 98u8, 144u8, 201u8, 81u8, 31u8, 249u8, 145u8, 253u8, 155u8, 144u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_65dea07b2bb8883a")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00e95ea566da49db5ffa4996a7ad044fa27eb2490f4b7a6290c9511ff991fd9b90\x00=======END GROTH16 VK SETUP V1=======\x00";
