// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        31u8, 15u8, 121u8, 188u8, 210u8, 65u8, 232u8, 254u8, 101u8, 230u8, 54u8, 191u8, 211u8,
        18u8, 75u8, 203u8, 135u8, 164u8, 112u8, 65u8, 91u8, 62u8, 227u8, 148u8, 22u8, 0u8, 16u8,
        166u8, 223u8, 194u8, 176u8, 207u8, 42u8, 15u8, 36u8, 248u8, 247u8, 160u8, 239u8, 78u8,
        64u8, 98u8, 239u8, 85u8, 197u8, 84u8, 28u8, 211u8, 193u8, 141u8, 40u8, 66u8, 90u8, 101u8,
        161u8, 27u8, 255u8, 102u8, 220u8, 42u8, 20u8, 97u8, 223u8, 16u8,
    ],
    [
        41u8, 130u8, 187u8, 71u8, 25u8, 87u8, 123u8, 48u8, 128u8, 175u8, 233u8, 149u8, 56u8, 29u8,
        37u8, 71u8, 129u8, 183u8, 66u8, 58u8, 136u8, 8u8, 162u8, 161u8, 221u8, 186u8, 100u8, 44u8,
        251u8, 146u8, 144u8, 213u8, 47u8, 218u8, 233u8, 91u8, 210u8, 198u8, 58u8, 235u8, 81u8,
        177u8, 49u8, 109u8, 41u8, 60u8, 19u8, 49u8, 145u8, 2u8, 196u8, 98u8, 96u8, 96u8, 38u8,
        43u8, 44u8, 188u8, 244u8, 101u8, 113u8, 202u8, 11u8, 156u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        19u8, 115u8, 63u8, 147u8, 82u8, 153u8, 217u8, 246u8, 99u8, 205u8, 211u8, 240u8, 2u8, 204u8,
        12u8, 115u8, 228u8, 81u8, 162u8, 25u8, 140u8, 252u8, 70u8, 169u8, 187u8, 240u8, 107u8,
        210u8, 131u8, 201u8, 75u8, 151u8, 19u8, 166u8, 157u8, 54u8, 41u8, 32u8, 230u8, 208u8, 23u8,
        52u8, 111u8, 203u8, 134u8, 208u8, 107u8, 236u8, 81u8, 47u8, 56u8, 73u8, 219u8, 52u8, 200u8,
        164u8, 226u8, 44u8, 240u8, 33u8, 197u8, 95u8, 67u8, 16u8,
    ],
    vk_beta_g2: [
        31u8, 20u8, 240u8, 160u8, 6u8, 153u8, 195u8, 29u8, 51u8, 42u8, 43u8, 242u8, 51u8, 188u8,
        146u8, 251u8, 224u8, 222u8, 180u8, 251u8, 218u8, 71u8, 36u8, 171u8, 143u8, 223u8, 108u8,
        117u8, 203u8, 25u8, 197u8, 180u8, 34u8, 89u8, 85u8, 154u8, 46u8, 232u8, 79u8, 224u8, 224u8,
        133u8, 4u8, 51u8, 12u8, 58u8, 148u8, 212u8, 171u8, 217u8, 249u8, 227u8, 213u8, 57u8, 186u8,
        34u8, 48u8, 202u8, 95u8, 0u8, 98u8, 96u8, 43u8, 216u8, 12u8, 90u8, 31u8, 197u8, 95u8,
        110u8, 89u8, 145u8, 253u8, 154u8, 254u8, 177u8, 193u8, 12u8, 81u8, 23u8, 105u8, 43u8,
        198u8, 156u8, 0u8, 33u8, 253u8, 226u8, 28u8, 121u8, 150u8, 129u8, 9u8, 154u8, 57u8, 228u8,
        45u8, 14u8, 121u8, 15u8, 71u8, 20u8, 204u8, 29u8, 2u8, 244u8, 253u8, 21u8, 116u8, 247u8,
        189u8, 30u8, 230u8, 26u8, 12u8, 152u8, 207u8, 81u8, 147u8, 120u8, 81u8, 101u8, 182u8,
        103u8, 174u8, 22u8, 167u8, 33u8,
    ],
    vk_gamma_g2: [
        11u8, 16u8, 116u8, 194u8, 108u8, 22u8, 62u8, 218u8, 13u8, 119u8, 189u8, 157u8, 182u8,
        215u8, 140u8, 102u8, 178u8, 39u8, 109u8, 54u8, 42u8, 179u8, 113u8, 44u8, 247u8, 167u8,
        38u8, 221u8, 208u8, 25u8, 70u8, 210u8, 29u8, 102u8, 235u8, 198u8, 96u8, 175u8, 33u8, 56u8,
        105u8, 200u8, 219u8, 101u8, 57u8, 214u8, 41u8, 161u8, 62u8, 221u8, 141u8, 73u8, 90u8,
        129u8, 61u8, 116u8, 67u8, 224u8, 86u8, 25u8, 159u8, 134u8, 203u8, 190u8, 44u8, 227u8,
        249u8, 34u8, 8u8, 216u8, 198u8, 75u8, 135u8, 132u8, 25u8, 127u8, 140u8, 255u8, 65u8, 252u8,
        32u8, 49u8, 187u8, 133u8, 36u8, 241u8, 50u8, 113u8, 213u8, 84u8, 27u8, 0u8, 168u8, 178u8,
        78u8, 26u8, 15u8, 58u8, 172u8, 171u8, 160u8, 55u8, 87u8, 139u8, 86u8, 126u8, 147u8, 8u8,
        219u8, 175u8, 225u8, 153u8, 215u8, 133u8, 226u8, 21u8, 122u8, 224u8, 87u8, 201u8, 198u8,
        246u8, 174u8, 177u8, 212u8, 90u8, 85u8, 171u8,
    ],
    vk_delta_g2: [
        5u8, 245u8, 228u8, 66u8, 93u8, 84u8, 202u8, 40u8, 247u8, 189u8, 118u8, 120u8, 255u8, 168u8,
        4u8, 221u8, 15u8, 64u8, 254u8, 42u8, 147u8, 175u8, 170u8, 140u8, 71u8, 248u8, 61u8, 22u8,
        198u8, 22u8, 150u8, 207u8, 46u8, 72u8, 118u8, 9u8, 82u8, 163u8, 241u8, 106u8, 18u8, 88u8,
        81u8, 124u8, 201u8, 92u8, 246u8, 168u8, 169u8, 97u8, 51u8, 23u8, 122u8, 225u8, 168u8, 5u8,
        144u8, 215u8, 189u8, 234u8, 85u8, 188u8, 163u8, 75u8, 28u8, 182u8, 7u8, 77u8, 133u8, 142u8,
        15u8, 67u8, 211u8, 97u8, 163u8, 216u8, 97u8, 6u8, 81u8, 108u8, 204u8, 104u8, 124u8, 238u8,
        32u8, 54u8, 0u8, 195u8, 143u8, 36u8, 196u8, 175u8, 109u8, 93u8, 183u8, 110u8, 23u8, 86u8,
        39u8, 161u8, 198u8, 28u8, 58u8, 108u8, 76u8, 175u8, 203u8, 75u8, 248u8, 148u8, 13u8, 23u8,
        126u8, 9u8, 46u8, 90u8, 154u8, 31u8, 180u8, 35u8, 208u8, 181u8, 7u8, 167u8, 98u8, 100u8,
        71u8, 208u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [50u8, 96u8, 200u8, 71u8, 241u8, 26u8, 47u8, 221u8, 217u8, 129u8, 250u8, 25u8, 116u8, 234u8, 32u8, 174u8, 54u8, 96u8, 17u8, 86u8, 227u8, 74u8, 66u8, 114u8, 47u8, 63u8, 160u8, 142u8, 190u8, 116u8, 90u8, 158u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_1a069224b8d43f7a")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x003260c847f11a2fddd981fa1974ea20ae36601156e34a42722f3fa08ebe745a9e\x00=======END GROTH16 VK SETUP V1=======\x00";
