// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        33u8, 27u8, 35u8, 116u8, 46u8, 187u8, 192u8, 52u8, 248u8, 122u8, 141u8, 234u8, 243u8, 50u8,
        184u8, 29u8, 77u8, 248u8, 137u8, 85u8, 213u8, 197u8, 98u8, 107u8, 176u8, 161u8, 190u8,
        191u8, 241u8, 173u8, 28u8, 67u8, 10u8, 241u8, 252u8, 247u8, 194u8, 221u8, 218u8, 142u8,
        230u8, 100u8, 116u8, 170u8, 134u8, 169u8, 52u8, 148u8, 131u8, 242u8, 146u8, 250u8, 173u8,
        46u8, 194u8, 244u8, 97u8, 120u8, 125u8, 208u8, 187u8, 183u8, 245u8, 208u8,
    ],
    [
        25u8, 196u8, 10u8, 115u8, 28u8, 14u8, 165u8, 171u8, 55u8, 174u8, 1u8, 228u8, 108u8, 13u8,
        132u8, 63u8, 135u8, 123u8, 218u8, 107u8, 89u8, 165u8, 200u8, 209u8, 144u8, 14u8, 221u8,
        91u8, 160u8, 80u8, 228u8, 113u8, 5u8, 26u8, 43u8, 107u8, 121u8, 150u8, 202u8, 175u8, 146u8,
        234u8, 229u8, 43u8, 233u8, 11u8, 173u8, 211u8, 86u8, 66u8, 118u8, 152u8, 37u8, 216u8,
        246u8, 64u8, 197u8, 0u8, 39u8, 69u8, 44u8, 244u8, 23u8, 50u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        28u8, 154u8, 229u8, 173u8, 252u8, 204u8, 168u8, 40u8, 107u8, 115u8, 185u8, 136u8, 38u8,
        5u8, 156u8, 57u8, 111u8, 176u8, 207u8, 216u8, 8u8, 216u8, 252u8, 22u8, 122u8, 151u8, 107u8,
        135u8, 213u8, 179u8, 117u8, 49u8, 44u8, 159u8, 194u8, 76u8, 169u8, 108u8, 186u8, 119u8,
        252u8, 219u8, 225u8, 93u8, 105u8, 153u8, 99u8, 100u8, 194u8, 19u8, 163u8, 45u8, 25u8,
        225u8, 98u8, 124u8, 18u8, 3u8, 210u8, 129u8, 132u8, 50u8, 160u8, 247u8,
    ],
    vk_beta_g2: [
        20u8, 60u8, 69u8, 136u8, 237u8, 69u8, 191u8, 237u8, 79u8, 146u8, 48u8, 156u8, 81u8, 103u8,
        169u8, 17u8, 37u8, 158u8, 47u8, 199u8, 17u8, 30u8, 110u8, 10u8, 66u8, 181u8, 109u8, 129u8,
        69u8, 76u8, 38u8, 151u8, 32u8, 152u8, 189u8, 201u8, 55u8, 49u8, 213u8, 13u8, 134u8, 121u8,
        117u8, 234u8, 60u8, 130u8, 41u8, 151u8, 216u8, 150u8, 92u8, 52u8, 215u8, 26u8, 162u8,
        153u8, 23u8, 0u8, 218u8, 213u8, 22u8, 57u8, 199u8, 235u8, 0u8, 80u8, 96u8, 174u8, 7u8,
        227u8, 173u8, 58u8, 62u8, 21u8, 189u8, 62u8, 127u8, 105u8, 236u8, 176u8, 92u8, 92u8, 191u8,
        186u8, 65u8, 34u8, 112u8, 31u8, 165u8, 190u8, 241u8, 11u8, 69u8, 60u8, 106u8, 229u8, 1u8,
        117u8, 163u8, 90u8, 147u8, 69u8, 225u8, 223u8, 182u8, 112u8, 240u8, 64u8, 114u8, 14u8,
        157u8, 107u8, 38u8, 235u8, 240u8, 116u8, 58u8, 198u8, 77u8, 222u8, 62u8, 154u8, 109u8,
        146u8, 158u8, 137u8, 100u8, 45u8,
    ],
    vk_gamma_g2: [
        39u8, 14u8, 202u8, 92u8, 46u8, 194u8, 72u8, 247u8, 23u8, 80u8, 99u8, 55u8, 227u8, 217u8,
        171u8, 186u8, 5u8, 70u8, 159u8, 165u8, 142u8, 9u8, 9u8, 245u8, 107u8, 2u8, 76u8, 22u8,
        125u8, 205u8, 48u8, 105u8, 13u8, 165u8, 115u8, 172u8, 181u8, 180u8, 13u8, 80u8, 248u8,
        160u8, 33u8, 83u8, 9u8, 34u8, 117u8, 121u8, 141u8, 66u8, 244u8, 33u8, 218u8, 165u8, 237u8,
        201u8, 109u8, 102u8, 44u8, 148u8, 176u8, 190u8, 115u8, 245u8, 39u8, 59u8, 202u8, 176u8,
        64u8, 42u8, 229u8, 29u8, 242u8, 88u8, 128u8, 166u8, 133u8, 251u8, 245u8, 130u8, 179u8,
        20u8, 52u8, 34u8, 157u8, 104u8, 48u8, 66u8, 54u8, 136u8, 122u8, 208u8, 147u8, 251u8, 170u8,
        69u8, 20u8, 254u8, 244u8, 99u8, 215u8, 196u8, 222u8, 69u8, 118u8, 148u8, 160u8, 17u8,
        205u8, 178u8, 253u8, 188u8, 22u8, 145u8, 102u8, 53u8, 51u8, 196u8, 16u8, 127u8, 239u8,
        175u8, 138u8, 66u8, 174u8, 168u8, 34u8, 173u8,
    ],
    vk_delta_g2: [
        0u8, 47u8, 19u8, 169u8, 64u8, 188u8, 133u8, 171u8, 149u8, 122u8, 68u8, 24u8, 116u8, 51u8,
        163u8, 229u8, 6u8, 244u8, 236u8, 137u8, 191u8, 91u8, 82u8, 132u8, 127u8, 14u8, 115u8, 25u8,
        217u8, 229u8, 130u8, 191u8, 38u8, 153u8, 253u8, 94u8, 115u8, 150u8, 17u8, 120u8, 21u8,
        106u8, 109u8, 143u8, 154u8, 203u8, 179u8, 224u8, 170u8, 4u8, 13u8, 43u8, 78u8, 172u8, 0u8,
        109u8, 74u8, 225u8, 113u8, 236u8, 240u8, 236u8, 121u8, 117u8, 34u8, 144u8, 210u8, 102u8,
        138u8, 175u8, 81u8, 221u8, 128u8, 76u8, 176u8, 227u8, 161u8, 193u8, 150u8, 146u8, 117u8,
        158u8, 62u8, 188u8, 107u8, 121u8, 62u8, 157u8, 233u8, 184u8, 116u8, 207u8, 59u8, 29u8,
        49u8, 51u8, 17u8, 230u8, 106u8, 96u8, 41u8, 19u8, 73u8, 169u8, 252u8, 195u8, 156u8, 64u8,
        150u8, 189u8, 39u8, 149u8, 235u8, 66u8, 221u8, 25u8, 106u8, 245u8, 67u8, 150u8, 147u8,
        12u8, 198u8, 252u8, 28u8, 213u8, 47u8, 234u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [172u8, 239u8, 186u8, 183u8, 185u8, 214u8, 211u8, 233u8, 215u8, 98u8, 99u8, 251u8, 76u8, 220u8, 73u8, 102u8, 108u8, 108u8, 177u8, 208u8, 230u8, 81u8, 196u8, 210u8, 115u8, 213u8, 165u8, 219u8, 139u8, 167u8, 57u8, 246u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_c96b45ecb64cdcef")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00acefbab7b9d6d3e9d76263fb4cdc49666c6cb1d0e651c4d273d5a5db8ba739f6\x00=======END GROTH16 VK SETUP V1=======\x00";
