// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        19u8, 144u8, 225u8, 158u8, 189u8, 254u8, 75u8, 239u8, 135u8, 15u8, 90u8, 45u8, 165u8,
        122u8, 67u8, 194u8, 126u8, 227u8, 132u8, 149u8, 221u8, 89u8, 116u8, 176u8, 122u8, 102u8,
        220u8, 91u8, 94u8, 96u8, 28u8, 196u8, 14u8, 208u8, 74u8, 235u8, 35u8, 192u8, 177u8, 175u8,
        205u8, 172u8, 62u8, 136u8, 163u8, 219u8, 13u8, 33u8, 98u8, 124u8, 90u8, 84u8, 231u8, 50u8,
        1u8, 207u8, 136u8, 152u8, 153u8, 111u8, 118u8, 104u8, 47u8, 104u8,
    ],
    [
        20u8, 214u8, 135u8, 231u8, 243u8, 21u8, 166u8, 245u8, 99u8, 28u8, 113u8, 214u8, 124u8,
        23u8, 148u8, 227u8, 202u8, 107u8, 104u8, 111u8, 239u8, 195u8, 104u8, 165u8, 58u8, 240u8,
        202u8, 247u8, 62u8, 178u8, 12u8, 33u8, 14u8, 123u8, 207u8, 216u8, 18u8, 60u8, 253u8, 28u8,
        141u8, 143u8, 70u8, 143u8, 27u8, 89u8, 214u8, 181u8, 249u8, 28u8, 126u8, 171u8, 216u8,
        95u8, 254u8, 172u8, 134u8, 193u8, 100u8, 69u8, 147u8, 234u8, 230u8, 12u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        35u8, 179u8, 162u8, 43u8, 58u8, 196u8, 11u8, 156u8, 64u8, 109u8, 174u8, 181u8, 151u8,
        241u8, 219u8, 29u8, 156u8, 11u8, 37u8, 65u8, 76u8, 186u8, 191u8, 91u8, 183u8, 167u8, 117u8,
        210u8, 2u8, 60u8, 202u8, 1u8, 7u8, 87u8, 46u8, 119u8, 130u8, 91u8, 70u8, 243u8, 224u8,
        247u8, 128u8, 120u8, 0u8, 238u8, 158u8, 241u8, 198u8, 187u8, 82u8, 135u8, 167u8, 48u8,
        14u8, 186u8, 207u8, 116u8, 235u8, 33u8, 203u8, 107u8, 240u8, 253u8,
    ],
    vk_beta_g2: [
        13u8, 26u8, 134u8, 109u8, 197u8, 235u8, 228u8, 228u8, 68u8, 4u8, 126u8, 117u8, 218u8,
        134u8, 208u8, 252u8, 244u8, 67u8, 196u8, 56u8, 48u8, 48u8, 173u8, 245u8, 134u8, 231u8,
        160u8, 149u8, 73u8, 66u8, 108u8, 27u8, 46u8, 21u8, 61u8, 174u8, 184u8, 115u8, 114u8, 22u8,
        141u8, 189u8, 181u8, 33u8, 137u8, 2u8, 192u8, 71u8, 159u8, 43u8, 76u8, 108u8, 249u8, 65u8,
        220u8, 12u8, 223u8, 48u8, 119u8, 187u8, 9u8, 47u8, 222u8, 8u8, 22u8, 75u8, 180u8, 118u8,
        79u8, 99u8, 189u8, 169u8, 168u8, 37u8, 71u8, 159u8, 84u8, 166u8, 129u8, 32u8, 49u8, 70u8,
        198u8, 187u8, 224u8, 6u8, 44u8, 247u8, 241u8, 95u8, 230u8, 190u8, 135u8, 255u8, 188u8,
        84u8, 46u8, 54u8, 237u8, 174u8, 32u8, 130u8, 228u8, 157u8, 252u8, 196u8, 209u8, 233u8,
        57u8, 37u8, 146u8, 153u8, 235u8, 137u8, 63u8, 95u8, 19u8, 219u8, 99u8, 36u8, 171u8, 224u8,
        188u8, 51u8, 212u8, 231u8, 7u8, 185u8,
    ],
    vk_gamma_g2: [
        16u8, 75u8, 167u8, 14u8, 179u8, 110u8, 190u8, 27u8, 105u8, 32u8, 212u8, 180u8, 40u8, 119u8,
        105u8, 109u8, 155u8, 183u8, 193u8, 89u8, 240u8, 162u8, 85u8, 242u8, 170u8, 74u8, 242u8,
        130u8, 216u8, 142u8, 94u8, 234u8, 5u8, 155u8, 148u8, 129u8, 13u8, 16u8, 67u8, 11u8, 51u8,
        115u8, 223u8, 57u8, 255u8, 75u8, 139u8, 124u8, 145u8, 193u8, 231u8, 161u8, 26u8, 225u8,
        75u8, 208u8, 120u8, 77u8, 204u8, 88u8, 96u8, 12u8, 185u8, 60u8, 31u8, 137u8, 61u8, 211u8,
        79u8, 172u8, 0u8, 16u8, 93u8, 171u8, 163u8, 226u8, 34u8, 47u8, 180u8, 197u8, 99u8, 175u8,
        38u8, 103u8, 95u8, 132u8, 152u8, 243u8, 179u8, 146u8, 240u8, 36u8, 242u8, 146u8, 21u8,
        138u8, 48u8, 8u8, 145u8, 12u8, 215u8, 117u8, 244u8, 30u8, 71u8, 73u8, 102u8, 26u8, 199u8,
        213u8, 176u8, 20u8, 93u8, 117u8, 42u8, 121u8, 5u8, 52u8, 250u8, 91u8, 4u8, 150u8, 4u8,
        167u8, 238u8, 160u8, 49u8, 55u8,
    ],
    vk_delta_g2: [
        15u8, 194u8, 21u8, 81u8, 91u8, 54u8, 2u8, 200u8, 46u8, 17u8, 253u8, 100u8, 46u8, 44u8,
        48u8, 52u8, 212u8, 69u8, 99u8, 156u8, 175u8, 125u8, 118u8, 174u8, 178u8, 72u8, 1u8, 64u8,
        211u8, 11u8, 166u8, 170u8, 45u8, 115u8, 248u8, 123u8, 183u8, 30u8, 71u8, 13u8, 198u8,
        227u8, 241u8, 118u8, 89u8, 194u8, 249u8, 207u8, 238u8, 11u8, 203u8, 220u8, 106u8, 144u8,
        118u8, 40u8, 28u8, 81u8, 147u8, 253u8, 62u8, 177u8, 223u8, 71u8, 17u8, 197u8, 238u8, 152u8,
        100u8, 7u8, 61u8, 50u8, 8u8, 108u8, 161u8, 187u8, 122u8, 186u8, 234u8, 71u8, 135u8, 21u8,
        97u8, 196u8, 239u8, 127u8, 134u8, 57u8, 63u8, 243u8, 210u8, 153u8, 110u8, 118u8, 74u8,
        170u8, 35u8, 145u8, 100u8, 43u8, 111u8, 60u8, 150u8, 88u8, 151u8, 68u8, 115u8, 109u8,
        136u8, 60u8, 190u8, 29u8, 41u8, 67u8, 25u8, 82u8, 68u8, 172u8, 204u8, 219u8, 243u8, 120u8,
        62u8, 111u8, 179u8, 92u8, 100u8, 202u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [222u8, 239u8, 234u8, 71u8, 96u8, 180u8, 51u8, 5u8, 32u8, 224u8, 15u8, 139u8, 171u8, 235u8, 185u8, 83u8, 152u8, 131u8, 172u8, 133u8, 248u8, 204u8, 62u8, 186u8, 83u8, 55u8, 61u8, 0u8, 152u8, 247u8, 170u8, 244u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_31e17386d00b5cea")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00deefea4760b4330520e00f8babebb9539883ac85f8cc3eba53373d0098f7aaf4\x00=======END GROTH16 VK SETUP V1=======\x00";
