// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        13u8, 146u8, 149u8, 109u8, 194u8, 232u8, 102u8, 77u8, 7u8, 185u8, 206u8, 174u8, 183u8,
        44u8, 204u8, 96u8, 216u8, 59u8, 55u8, 39u8, 29u8, 47u8, 225u8, 227u8, 186u8, 20u8, 139u8,
        26u8, 94u8, 255u8, 192u8, 135u8, 15u8, 222u8, 67u8, 9u8, 37u8, 86u8, 130u8, 115u8, 66u8,
        34u8, 116u8, 129u8, 154u8, 16u8, 149u8, 104u8, 230u8, 249u8, 120u8, 88u8, 143u8, 211u8,
        68u8, 13u8, 31u8, 58u8, 53u8, 97u8, 93u8, 116u8, 33u8, 18u8,
    ],
    [
        15u8, 58u8, 144u8, 174u8, 83u8, 42u8, 223u8, 181u8, 95u8, 23u8, 200u8, 138u8, 130u8, 193u8,
        98u8, 165u8, 8u8, 203u8, 82u8, 118u8, 57u8, 251u8, 199u8, 255u8, 168u8, 185u8, 200u8, 66u8,
        188u8, 99u8, 101u8, 225u8, 6u8, 201u8, 50u8, 200u8, 151u8, 144u8, 133u8, 25u8, 30u8, 146u8,
        76u8, 120u8, 7u8, 190u8, 152u8, 16u8, 0u8, 30u8, 59u8, 154u8, 95u8, 195u8, 32u8, 125u8,
        149u8, 229u8, 46u8, 214u8, 104u8, 194u8, 244u8, 232u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        16u8, 86u8, 85u8, 150u8, 230u8, 181u8, 230u8, 203u8, 49u8, 181u8, 19u8, 51u8, 73u8, 78u8,
        161u8, 29u8, 79u8, 39u8, 156u8, 38u8, 47u8, 137u8, 218u8, 27u8, 161u8, 53u8, 227u8, 178u8,
        154u8, 189u8, 136u8, 18u8, 15u8, 157u8, 167u8, 208u8, 92u8, 76u8, 125u8, 206u8, 147u8,
        137u8, 182u8, 146u8, 211u8, 63u8, 124u8, 92u8, 161u8, 30u8, 70u8, 72u8, 252u8, 8u8, 127u8,
        213u8, 4u8, 199u8, 28u8, 140u8, 39u8, 177u8, 53u8, 47u8,
    ],
    vk_beta_g2: [
        24u8, 64u8, 234u8, 114u8, 141u8, 54u8, 44u8, 187u8, 169u8, 144u8, 6u8, 16u8, 84u8, 117u8,
        82u8, 9u8, 185u8, 74u8, 166u8, 1u8, 251u8, 31u8, 33u8, 62u8, 235u8, 126u8, 129u8, 236u8,
        254u8, 23u8, 149u8, 98u8, 16u8, 10u8, 125u8, 202u8, 76u8, 240u8, 109u8, 197u8, 205u8,
        202u8, 195u8, 32u8, 255u8, 130u8, 25u8, 228u8, 248u8, 212u8, 70u8, 201u8, 70u8, 72u8,
        201u8, 86u8, 4u8, 146u8, 239u8, 168u8, 105u8, 222u8, 1u8, 204u8, 4u8, 22u8, 27u8, 149u8,
        129u8, 56u8, 167u8, 178u8, 57u8, 128u8, 123u8, 235u8, 187u8, 182u8, 106u8, 239u8, 12u8,
        204u8, 179u8, 2u8, 239u8, 99u8, 236u8, 1u8, 91u8, 154u8, 113u8, 18u8, 199u8, 224u8, 123u8,
        11u8, 14u8, 74u8, 254u8, 166u8, 66u8, 191u8, 174u8, 139u8, 93u8, 233u8, 116u8, 160u8,
        132u8, 151u8, 251u8, 63u8, 197u8, 59u8, 56u8, 251u8, 20u8, 113u8, 201u8, 229u8, 152u8,
        130u8, 139u8, 32u8, 25u8, 14u8, 69u8, 55u8,
    ],
    vk_gamma_g2: [
        13u8, 11u8, 24u8, 92u8, 224u8, 68u8, 214u8, 74u8, 248u8, 224u8, 49u8, 97u8, 17u8, 66u8,
        128u8, 179u8, 106u8, 18u8, 109u8, 98u8, 41u8, 124u8, 90u8, 242u8, 138u8, 139u8, 212u8,
        150u8, 124u8, 167u8, 121u8, 98u8, 10u8, 22u8, 125u8, 98u8, 66u8, 243u8, 167u8, 216u8, 3u8,
        49u8, 226u8, 69u8, 191u8, 210u8, 231u8, 41u8, 213u8, 61u8, 16u8, 137u8, 8u8, 118u8, 100u8,
        189u8, 126u8, 126u8, 99u8, 17u8, 231u8, 19u8, 71u8, 176u8, 34u8, 54u8, 142u8, 204u8, 150u8,
        66u8, 28u8, 241u8, 168u8, 82u8, 87u8, 211u8, 224u8, 53u8, 67u8, 148u8, 96u8, 228u8, 1u8,
        138u8, 12u8, 85u8, 196u8, 161u8, 25u8, 100u8, 55u8, 167u8, 89u8, 127u8, 8u8, 49u8, 30u8,
        117u8, 96u8, 61u8, 213u8, 16u8, 157u8, 190u8, 86u8, 248u8, 128u8, 26u8, 59u8, 213u8, 173u8,
        246u8, 33u8, 84u8, 44u8, 52u8, 146u8, 78u8, 101u8, 36u8, 56u8, 153u8, 57u8, 171u8, 100u8,
        205u8, 196u8, 145u8,
    ],
    vk_delta_g2: [
        46u8, 7u8, 182u8, 59u8, 42u8, 82u8, 21u8, 168u8, 85u8, 82u8, 127u8, 254u8, 168u8, 245u8,
        25u8, 121u8, 123u8, 14u8, 93u8, 144u8, 46u8, 246u8, 225u8, 220u8, 14u8, 96u8, 170u8, 29u8,
        8u8, 133u8, 209u8, 44u8, 20u8, 218u8, 21u8, 180u8, 29u8, 230u8, 6u8, 129u8, 137u8, 244u8,
        239u8, 37u8, 0u8, 44u8, 247u8, 106u8, 227u8, 218u8, 227u8, 136u8, 40u8, 45u8, 195u8, 195u8,
        181u8, 230u8, 183u8, 253u8, 11u8, 1u8, 176u8, 147u8, 45u8, 52u8, 74u8, 76u8, 20u8, 196u8,
        220u8, 6u8, 161u8, 145u8, 0u8, 188u8, 29u8, 3u8, 21u8, 100u8, 62u8, 152u8, 3u8, 145u8,
        197u8, 11u8, 151u8, 107u8, 71u8, 87u8, 245u8, 16u8, 238u8, 89u8, 250u8, 17u8, 20u8, 12u8,
        1u8, 155u8, 43u8, 136u8, 179u8, 80u8, 77u8, 38u8, 230u8, 66u8, 164u8, 155u8, 54u8, 82u8,
        234u8, 131u8, 225u8, 100u8, 199u8, 255u8, 100u8, 164u8, 129u8, 86u8, 126u8, 22u8, 110u8,
        125u8, 87u8, 14u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [63u8, 116u8, 175u8, 41u8, 199u8, 91u8, 116u8, 247u8, 108u8, 232u8, 12u8, 122u8, 185u8, 62u8, 231u8, 173u8, 93u8, 166u8, 195u8, 90u8, 6u8, 125u8, 247u8, 46u8, 97u8, 62u8, 97u8, 239u8, 161u8, 80u8, 49u8, 50u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_aa43e7094e777be8")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x003f74af29c75b74f76ce80c7ab93ee7ad5da6c35a067df72e613e61efa1503132\x00=======END GROTH16 VK SETUP V1=======\x00";
