// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        45u8, 87u8, 239u8, 176u8, 53u8, 9u8, 58u8, 9u8, 150u8, 101u8, 234u8, 38u8, 149u8, 154u8,
        158u8, 45u8, 213u8, 248u8, 233u8, 229u8, 44u8, 187u8, 183u8, 17u8, 13u8, 2u8, 8u8, 55u8,
        156u8, 178u8, 157u8, 55u8, 21u8, 233u8, 85u8, 109u8, 170u8, 203u8, 29u8, 6u8, 139u8, 49u8,
        115u8, 110u8, 34u8, 161u8, 213u8, 105u8, 201u8, 103u8, 95u8, 17u8, 108u8, 14u8, 46u8,
        117u8, 28u8, 146u8, 10u8, 161u8, 66u8, 59u8, 173u8, 19u8,
    ],
    [
        11u8, 202u8, 237u8, 33u8, 125u8, 183u8, 26u8, 240u8, 21u8, 109u8, 123u8, 54u8, 113u8,
        211u8, 110u8, 243u8, 92u8, 172u8, 62u8, 130u8, 19u8, 137u8, 184u8, 75u8, 197u8, 189u8,
        226u8, 146u8, 42u8, 150u8, 5u8, 169u8, 39u8, 18u8, 89u8, 119u8, 255u8, 177u8, 154u8, 14u8,
        84u8, 47u8, 145u8, 35u8, 16u8, 185u8, 25u8, 147u8, 101u8, 56u8, 225u8, 155u8, 145u8, 196u8,
        169u8, 193u8, 254u8, 141u8, 82u8, 17u8, 205u8, 111u8, 219u8, 209u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        43u8, 117u8, 144u8, 216u8, 250u8, 139u8, 47u8, 6u8, 239u8, 220u8, 246u8, 179u8, 230u8,
        151u8, 98u8, 193u8, 41u8, 2u8, 176u8, 189u8, 235u8, 220u8, 210u8, 76u8, 39u8, 34u8, 214u8,
        202u8, 18u8, 126u8, 223u8, 153u8, 8u8, 40u8, 239u8, 69u8, 171u8, 255u8, 50u8, 125u8, 31u8,
        253u8, 75u8, 165u8, 19u8, 144u8, 178u8, 227u8, 148u8, 10u8, 253u8, 145u8, 132u8, 43u8,
        95u8, 96u8, 242u8, 223u8, 13u8, 42u8, 26u8, 88u8, 210u8, 172u8,
    ],
    vk_beta_g2: [
        12u8, 3u8, 170u8, 147u8, 142u8, 203u8, 176u8, 184u8, 48u8, 31u8, 244u8, 75u8, 195u8, 175u8,
        217u8, 147u8, 143u8, 59u8, 194u8, 49u8, 82u8, 156u8, 227u8, 204u8, 159u8, 86u8, 56u8,
        132u8, 235u8, 212u8, 209u8, 83u8, 21u8, 88u8, 83u8, 214u8, 16u8, 148u8, 101u8, 7u8, 72u8,
        17u8, 242u8, 232u8, 187u8, 188u8, 97u8, 136u8, 86u8, 222u8, 84u8, 196u8, 139u8, 202u8,
        244u8, 127u8, 143u8, 172u8, 73u8, 68u8, 102u8, 175u8, 186u8, 192u8, 32u8, 182u8, 190u8,
        212u8, 169u8, 59u8, 89u8, 233u8, 56u8, 1u8, 77u8, 202u8, 156u8, 245u8, 129u8, 62u8, 166u8,
        217u8, 148u8, 90u8, 111u8, 13u8, 170u8, 192u8, 206u8, 64u8, 245u8, 58u8, 147u8, 251u8,
        49u8, 10u8, 27u8, 115u8, 84u8, 160u8, 141u8, 99u8, 107u8, 198u8, 94u8, 120u8, 181u8, 19u8,
        29u8, 227u8, 2u8, 167u8, 180u8, 160u8, 115u8, 112u8, 47u8, 59u8, 75u8, 119u8, 206u8, 129u8,
        42u8, 243u8, 87u8, 235u8, 27u8, 101u8,
    ],
    vk_gamma_g2: [
        5u8, 196u8, 178u8, 184u8, 0u8, 52u8, 184u8, 18u8, 73u8, 205u8, 184u8, 39u8, 10u8, 243u8,
        58u8, 224u8, 19u8, 193u8, 72u8, 124u8, 40u8, 252u8, 242u8, 53u8, 50u8, 205u8, 54u8, 1u8,
        226u8, 177u8, 83u8, 134u8, 34u8, 15u8, 181u8, 80u8, 120u8, 91u8, 138u8, 171u8, 82u8, 222u8,
        70u8, 201u8, 57u8, 26u8, 30u8, 169u8, 194u8, 57u8, 82u8, 207u8, 119u8, 1u8, 180u8, 174u8,
        133u8, 66u8, 38u8, 210u8, 143u8, 238u8, 89u8, 132u8, 14u8, 168u8, 67u8, 119u8, 127u8,
        119u8, 219u8, 75u8, 242u8, 248u8, 214u8, 31u8, 139u8, 247u8, 61u8, 87u8, 84u8, 203u8, 67u8,
        240u8, 246u8, 143u8, 214u8, 151u8, 157u8, 128u8, 15u8, 108u8, 242u8, 106u8, 218u8, 68u8,
        6u8, 57u8, 142u8, 198u8, 143u8, 214u8, 187u8, 78u8, 47u8, 243u8, 103u8, 117u8, 83u8, 166u8,
        243u8, 150u8, 106u8, 71u8, 152u8, 221u8, 41u8, 96u8, 160u8, 5u8, 97u8, 98u8, 177u8, 179u8,
        117u8, 95u8, 95u8, 32u8,
    ],
    vk_delta_g2: [
        42u8, 111u8, 171u8, 210u8, 236u8, 147u8, 181u8, 104u8, 112u8, 86u8, 37u8, 21u8, 53u8, 76u8,
        154u8, 197u8, 220u8, 116u8, 240u8, 24u8, 8u8, 58u8, 124u8, 164u8, 184u8, 208u8, 40u8,
        211u8, 176u8, 83u8, 169u8, 124u8, 31u8, 80u8, 136u8, 204u8, 64u8, 93u8, 235u8, 70u8, 4u8,
        228u8, 217u8, 225u8, 49u8, 198u8, 253u8, 218u8, 13u8, 101u8, 242u8, 127u8, 95u8, 103u8,
        250u8, 158u8, 229u8, 19u8, 102u8, 225u8, 242u8, 7u8, 200u8, 235u8, 16u8, 120u8, 54u8,
        180u8, 252u8, 210u8, 83u8, 251u8, 8u8, 170u8, 244u8, 191u8, 94u8, 123u8, 202u8, 207u8,
        89u8, 231u8, 183u8, 8u8, 150u8, 125u8, 210u8, 174u8, 91u8, 52u8, 24u8, 212u8, 51u8, 95u8,
        71u8, 251u8, 20u8, 251u8, 97u8, 75u8, 242u8, 143u8, 84u8, 106u8, 141u8, 139u8, 181u8, 21u8,
        180u8, 20u8, 81u8, 62u8, 97u8, 5u8, 172u8, 25u8, 47u8, 152u8, 18u8, 64u8, 245u8, 179u8,
        92u8, 78u8, 217u8, 234u8, 23u8, 217u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [72u8, 219u8, 80u8, 152u8, 137u8, 75u8, 57u8, 135u8, 93u8, 101u8, 154u8, 33u8, 76u8, 195u8, 223u8, 166u8, 87u8, 204u8, 128u8, 240u8, 240u8, 174u8, 159u8, 181u8, 79u8, 40u8, 91u8, 151u8, 115u8, 234u8, 111u8, 11u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_6dfc170e3b4e6d86")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x0048db5098894b39875d659a214cc3dfa657cc80f0f0ae9fb54f285b9773ea6f0b\x00=======END GROTH16 VK SETUP V1=======\x00";
