// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        45u8, 60u8, 66u8, 147u8, 84u8, 227u8, 177u8, 66u8, 107u8, 80u8, 99u8, 68u8, 230u8, 160u8,
        158u8, 43u8, 200u8, 54u8, 222u8, 201u8, 85u8, 37u8, 129u8, 246u8, 84u8, 52u8, 9u8, 19u8,
        126u8, 102u8, 15u8, 195u8, 35u8, 58u8, 7u8, 186u8, 30u8, 54u8, 178u8, 64u8, 145u8, 22u8,
        172u8, 54u8, 39u8, 36u8, 159u8, 52u8, 253u8, 61u8, 119u8, 36u8, 224u8, 23u8, 125u8, 99u8,
        113u8, 212u8, 235u8, 72u8, 207u8, 118u8, 8u8, 2u8,
    ],
    [
        17u8, 48u8, 179u8, 142u8, 96u8, 177u8, 96u8, 188u8, 176u8, 252u8, 119u8, 46u8, 206u8, 89u8,
        121u8, 18u8, 21u8, 247u8, 205u8, 76u8, 120u8, 159u8, 199u8, 91u8, 116u8, 247u8, 7u8, 40u8,
        190u8, 196u8, 116u8, 92u8, 9u8, 229u8, 101u8, 201u8, 229u8, 119u8, 17u8, 182u8, 56u8,
        110u8, 129u8, 177u8, 2u8, 219u8, 183u8, 215u8, 96u8, 70u8, 131u8, 140u8, 181u8, 227u8,
        183u8, 86u8, 70u8, 19u8, 200u8, 87u8, 91u8, 247u8, 170u8, 234u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        42u8, 22u8, 85u8, 170u8, 177u8, 112u8, 143u8, 241u8, 64u8, 144u8, 57u8, 22u8, 115u8, 201u8,
        234u8, 50u8, 162u8, 172u8, 96u8, 64u8, 128u8, 164u8, 78u8, 228u8, 17u8, 35u8, 47u8, 75u8,
        218u8, 22u8, 130u8, 122u8, 14u8, 216u8, 85u8, 217u8, 64u8, 226u8, 158u8, 37u8, 42u8, 28u8,
        21u8, 117u8, 174u8, 188u8, 251u8, 36u8, 204u8, 201u8, 66u8, 146u8, 175u8, 17u8, 115u8,
        24u8, 179u8, 8u8, 148u8, 112u8, 68u8, 3u8, 54u8, 136u8,
    ],
    vk_beta_g2: [
        23u8, 226u8, 138u8, 177u8, 135u8, 180u8, 193u8, 84u8, 76u8, 112u8, 36u8, 207u8, 108u8,
        169u8, 201u8, 149u8, 192u8, 165u8, 75u8, 214u8, 212u8, 211u8, 93u8, 163u8, 102u8, 166u8,
        183u8, 50u8, 11u8, 173u8, 204u8, 250u8, 0u8, 225u8, 20u8, 211u8, 122u8, 175u8, 249u8,
        126u8, 181u8, 118u8, 107u8, 213u8, 52u8, 192u8, 39u8, 243u8, 199u8, 179u8, 141u8, 65u8,
        250u8, 94u8, 230u8, 211u8, 165u8, 48u8, 78u8, 89u8, 99u8, 135u8, 166u8, 237u8, 46u8, 108u8,
        108u8, 125u8, 103u8, 22u8, 138u8, 33u8, 126u8, 110u8, 193u8, 228u8, 233u8, 230u8, 50u8,
        159u8, 73u8, 249u8, 177u8, 47u8, 19u8, 97u8, 149u8, 36u8, 182u8, 233u8, 242u8, 115u8, 19u8,
        138u8, 15u8, 56u8, 46u8, 65u8, 214u8, 71u8, 236u8, 223u8, 142u8, 171u8, 7u8, 114u8, 74u8,
        138u8, 30u8, 219u8, 4u8, 59u8, 0u8, 115u8, 63u8, 103u8, 231u8, 97u8, 245u8, 64u8, 135u8,
        161u8, 136u8, 114u8, 34u8, 63u8, 193u8, 41u8,
    ],
    vk_gamma_g2: [
        32u8, 60u8, 44u8, 228u8, 73u8, 255u8, 134u8, 112u8, 8u8, 241u8, 5u8, 150u8, 0u8, 252u8,
        35u8, 21u8, 79u8, 208u8, 41u8, 253u8, 13u8, 92u8, 254u8, 39u8, 181u8, 254u8, 24u8, 77u8,
        127u8, 231u8, 238u8, 237u8, 19u8, 7u8, 133u8, 134u8, 143u8, 210u8, 237u8, 152u8, 184u8,
        118u8, 175u8, 146u8, 208u8, 254u8, 156u8, 235u8, 40u8, 57u8, 136u8, 69u8, 225u8, 195u8,
        238u8, 171u8, 151u8, 197u8, 62u8, 240u8, 16u8, 11u8, 99u8, 195u8, 8u8, 245u8, 224u8, 17u8,
        230u8, 121u8, 126u8, 51u8, 47u8, 8u8, 204u8, 255u8, 26u8, 239u8, 26u8, 85u8, 184u8, 84u8,
        81u8, 36u8, 115u8, 236u8, 24u8, 193u8, 48u8, 209u8, 219u8, 171u8, 91u8, 92u8, 155u8, 131u8,
        23u8, 167u8, 12u8, 228u8, 115u8, 134u8, 39u8, 249u8, 212u8, 109u8, 239u8, 211u8, 207u8,
        81u8, 57u8, 136u8, 166u8, 111u8, 57u8, 139u8, 160u8, 207u8, 151u8, 218u8, 116u8, 223u8,
        240u8, 182u8, 196u8, 143u8, 220u8, 47u8,
    ],
    vk_delta_g2: [
        32u8, 103u8, 25u8, 90u8, 172u8, 95u8, 20u8, 174u8, 187u8, 212u8, 231u8, 48u8, 200u8, 72u8,
        228u8, 242u8, 105u8, 61u8, 155u8, 21u8, 90u8, 52u8, 145u8, 139u8, 0u8, 204u8, 192u8, 100u8,
        82u8, 198u8, 54u8, 248u8, 27u8, 197u8, 123u8, 225u8, 218u8, 84u8, 4u8, 208u8, 253u8, 52u8,
        79u8, 115u8, 205u8, 231u8, 34u8, 207u8, 105u8, 87u8, 125u8, 80u8, 65u8, 140u8, 123u8,
        148u8, 123u8, 12u8, 83u8, 99u8, 133u8, 54u8, 20u8, 49u8, 19u8, 114u8, 245u8, 252u8, 68u8,
        132u8, 205u8, 69u8, 24u8, 1u8, 18u8, 6u8, 13u8, 93u8, 152u8, 109u8, 79u8, 235u8, 158u8,
        96u8, 156u8, 30u8, 154u8, 201u8, 112u8, 244u8, 221u8, 177u8, 134u8, 91u8, 7u8, 3u8, 14u8,
        242u8, 210u8, 127u8, 213u8, 108u8, 12u8, 240u8, 11u8, 246u8, 255u8, 51u8, 61u8, 203u8,
        148u8, 92u8, 122u8, 90u8, 66u8, 254u8, 163u8, 159u8, 66u8, 10u8, 6u8, 150u8, 21u8, 10u8,
        124u8, 144u8, 234u8, 221u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [84u8, 253u8, 117u8, 254u8, 144u8, 88u8, 38u8, 113u8, 115u8, 226u8, 149u8, 44u8, 100u8, 53u8, 173u8, 195u8, 178u8, 67u8, 71u8, 247u8, 148u8, 9u8, 236u8, 121u8, 205u8, 124u8, 244u8, 191u8, 243u8, 241u8, 157u8, 170u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_038b642ae50d8ba0")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x0054fd75fe9058267173e2952c6435adc3b24347f79409ec79cd7cf4bff3f19daa\x00=======END GROTH16 VK SETUP V1=======\x00";
