// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        0u8, 94u8, 30u8, 127u8, 101u8, 81u8, 57u8, 214u8, 163u8, 108u8, 55u8, 94u8, 228u8, 159u8,
        12u8, 54u8, 80u8, 74u8, 193u8, 188u8, 115u8, 77u8, 4u8, 178u8, 26u8, 141u8, 59u8, 29u8,
        138u8, 222u8, 142u8, 129u8, 41u8, 82u8, 190u8, 129u8, 15u8, 210u8, 142u8, 21u8, 250u8,
        20u8, 62u8, 174u8, 7u8, 186u8, 95u8, 220u8, 107u8, 39u8, 122u8, 9u8, 226u8, 85u8, 187u8,
        215u8, 173u8, 34u8, 12u8, 229u8, 165u8, 171u8, 16u8, 233u8,
    ],
    [
        18u8, 115u8, 82u8, 115u8, 2u8, 109u8, 28u8, 122u8, 6u8, 203u8, 166u8, 81u8, 193u8, 91u8,
        27u8, 217u8, 108u8, 65u8, 204u8, 254u8, 90u8, 75u8, 132u8, 198u8, 67u8, 44u8, 140u8, 31u8,
        84u8, 114u8, 63u8, 156u8, 38u8, 117u8, 2u8, 151u8, 27u8, 178u8, 95u8, 115u8, 27u8, 6u8,
        10u8, 225u8, 235u8, 108u8, 82u8, 156u8, 5u8, 131u8, 211u8, 86u8, 146u8, 128u8, 63u8, 195u8,
        242u8, 12u8, 218u8, 129u8, 136u8, 252u8, 19u8, 212u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        22u8, 47u8, 229u8, 164u8, 14u8, 240u8, 241u8, 95u8, 3u8, 131u8, 39u8, 128u8, 163u8, 100u8,
        55u8, 250u8, 157u8, 96u8, 52u8, 132u8, 24u8, 84u8, 184u8, 78u8, 178u8, 94u8, 127u8, 116u8,
        13u8, 131u8, 80u8, 61u8, 20u8, 144u8, 88u8, 122u8, 38u8, 13u8, 226u8, 167u8, 196u8, 241u8,
        232u8, 95u8, 130u8, 58u8, 81u8, 215u8, 105u8, 205u8, 214u8, 204u8, 217u8, 6u8, 36u8, 30u8,
        114u8, 137u8, 54u8, 132u8, 136u8, 189u8, 105u8, 167u8,
    ],
    vk_beta_g2: [
        41u8, 36u8, 1u8, 30u8, 247u8, 98u8, 128u8, 50u8, 51u8, 83u8, 195u8, 220u8, 95u8, 232u8,
        86u8, 163u8, 163u8, 2u8, 174u8, 128u8, 72u8, 152u8, 121u8, 140u8, 63u8, 11u8, 56u8, 132u8,
        243u8, 69u8, 239u8, 68u8, 38u8, 75u8, 122u8, 56u8, 235u8, 74u8, 2u8, 170u8, 236u8, 7u8,
        189u8, 84u8, 13u8, 214u8, 25u8, 207u8, 111u8, 155u8, 98u8, 134u8, 45u8, 29u8, 72u8, 154u8,
        46u8, 9u8, 139u8, 168u8, 55u8, 179u8, 199u8, 70u8, 26u8, 18u8, 204u8, 158u8, 209u8, 96u8,
        132u8, 40u8, 172u8, 165u8, 135u8, 173u8, 125u8, 172u8, 168u8, 175u8, 128u8, 18u8, 207u8,
        176u8, 182u8, 211u8, 110u8, 72u8, 95u8, 239u8, 199u8, 60u8, 49u8, 62u8, 149u8, 185u8, 34u8,
        180u8, 218u8, 70u8, 118u8, 201u8, 208u8, 161u8, 172u8, 49u8, 92u8, 18u8, 96u8, 139u8, 85u8,
        19u8, 143u8, 140u8, 56u8, 51u8, 33u8, 152u8, 234u8, 0u8, 118u8, 42u8, 255u8, 13u8, 166u8,
        229u8, 160u8, 1u8,
    ],
    vk_gamma_g2: [
        38u8, 229u8, 144u8, 120u8, 103u8, 212u8, 99u8, 36u8, 249u8, 71u8, 94u8, 13u8, 217u8, 182u8,
        147u8, 110u8, 21u8, 76u8, 223u8, 93u8, 86u8, 85u8, 104u8, 48u8, 31u8, 9u8, 218u8, 97u8,
        146u8, 170u8, 104u8, 219u8, 24u8, 123u8, 161u8, 146u8, 52u8, 204u8, 15u8, 123u8, 246u8,
        53u8, 126u8, 214u8, 166u8, 218u8, 75u8, 145u8, 11u8, 230u8, 96u8, 18u8, 101u8, 55u8, 69u8,
        29u8, 183u8, 210u8, 205u8, 119u8, 46u8, 183u8, 230u8, 236u8, 34u8, 59u8, 186u8, 179u8,
        172u8, 203u8, 13u8, 172u8, 143u8, 217u8, 72u8, 105u8, 134u8, 223u8, 27u8, 240u8, 168u8,
        166u8, 95u8, 132u8, 117u8, 186u8, 175u8, 6u8, 129u8, 60u8, 77u8, 151u8, 204u8, 90u8, 137u8,
        148u8, 41u8, 102u8, 46u8, 174u8, 179u8, 175u8, 168u8, 64u8, 193u8, 182u8, 12u8, 111u8,
        51u8, 161u8, 132u8, 84u8, 112u8, 101u8, 228u8, 116u8, 135u8, 92u8, 74u8, 112u8, 74u8,
        136u8, 37u8, 169u8, 86u8, 75u8, 162u8, 30u8,
    ],
    vk_delta_g2: [
        36u8, 44u8, 67u8, 160u8, 22u8, 229u8, 44u8, 21u8, 37u8, 241u8, 151u8, 95u8, 174u8, 39u8,
        239u8, 239u8, 218u8, 158u8, 185u8, 163u8, 31u8, 190u8, 149u8, 56u8, 51u8, 196u8, 152u8,
        31u8, 249u8, 252u8, 197u8, 115u8, 39u8, 116u8, 216u8, 106u8, 220u8, 188u8, 14u8, 1u8,
        195u8, 89u8, 63u8, 109u8, 41u8, 170u8, 143u8, 8u8, 82u8, 46u8, 43u8, 14u8, 144u8, 211u8,
        101u8, 192u8, 6u8, 27u8, 119u8, 40u8, 244u8, 0u8, 143u8, 80u8, 44u8, 72u8, 153u8, 5u8,
        151u8, 10u8, 180u8, 163u8, 235u8, 15u8, 15u8, 244u8, 63u8, 14u8, 82u8, 53u8, 47u8, 57u8,
        41u8, 72u8, 87u8, 2u8, 174u8, 67u8, 30u8, 182u8, 155u8, 24u8, 219u8, 165u8, 117u8, 87u8,
        28u8, 248u8, 144u8, 185u8, 237u8, 162u8, 161u8, 241u8, 66u8, 53u8, 230u8, 181u8, 34u8,
        157u8, 146u8, 64u8, 63u8, 150u8, 197u8, 57u8, 251u8, 2u8, 116u8, 194u8, 25u8, 238u8, 157u8,
        48u8, 128u8, 163u8, 116u8, 26u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [42u8, 222u8, 242u8, 16u8, 55u8, 6u8, 188u8, 28u8, 96u8, 119u8, 223u8, 158u8, 35u8, 19u8, 39u8, 30u8, 255u8, 48u8, 117u8, 197u8, 43u8, 28u8, 181u8, 68u8, 183u8, 112u8, 114u8, 237u8, 188u8, 98u8, 173u8, 124u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_492ded9501d5f2b2")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x002adef2103706bc1c6077df9e2313271eff3075c52b1cb544b77072edbc62ad7c\x00=======END GROTH16 VK SETUP V1=======\x00";
