// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        11u8, 142u8, 120u8, 15u8, 60u8, 23u8, 221u8, 165u8, 159u8, 162u8, 226u8, 243u8, 164u8,
        57u8, 181u8, 128u8, 44u8, 76u8, 197u8, 165u8, 184u8, 77u8, 102u8, 181u8, 174u8, 16u8,
        171u8, 100u8, 130u8, 151u8, 136u8, 0u8, 27u8, 47u8, 160u8, 13u8, 181u8, 227u8, 46u8, 33u8,
        248u8, 87u8, 234u8, 148u8, 106u8, 224u8, 242u8, 214u8, 63u8, 21u8, 236u8, 126u8, 254u8,
        201u8, 154u8, 13u8, 54u8, 162u8, 79u8, 7u8, 154u8, 122u8, 35u8, 120u8,
    ],
    [
        30u8, 219u8, 75u8, 41u8, 135u8, 184u8, 247u8, 224u8, 32u8, 67u8, 149u8, 6u8, 163u8, 233u8,
        86u8, 193u8, 11u8, 6u8, 191u8, 242u8, 128u8, 60u8, 230u8, 181u8, 166u8, 66u8, 191u8, 132u8,
        70u8, 35u8, 168u8, 125u8, 14u8, 166u8, 18u8, 98u8, 202u8, 171u8, 91u8, 170u8, 216u8, 52u8,
        176u8, 113u8, 193u8, 181u8, 133u8, 40u8, 7u8, 130u8, 228u8, 57u8, 218u8, 25u8, 246u8,
        132u8, 29u8, 117u8, 30u8, 71u8, 51u8, 229u8, 238u8, 103u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        30u8, 193u8, 135u8, 253u8, 170u8, 168u8, 86u8, 225u8, 150u8, 60u8, 187u8, 199u8, 4u8,
        131u8, 51u8, 146u8, 222u8, 8u8, 196u8, 239u8, 122u8, 114u8, 172u8, 58u8, 37u8, 226u8, 17u8,
        44u8, 68u8, 252u8, 167u8, 0u8, 18u8, 39u8, 10u8, 61u8, 49u8, 25u8, 151u8, 22u8, 4u8, 86u8,
        213u8, 158u8, 60u8, 175u8, 49u8, 33u8, 189u8, 163u8, 12u8, 0u8, 22u8, 189u8, 130u8, 46u8,
        88u8, 188u8, 106u8, 12u8, 181u8, 141u8, 66u8, 124u8,
    ],
    vk_beta_g2: [
        33u8, 104u8, 220u8, 111u8, 122u8, 135u8, 171u8, 92u8, 177u8, 129u8, 155u8, 55u8, 115u8,
        120u8, 140u8, 243u8, 18u8, 146u8, 83u8, 249u8, 117u8, 89u8, 153u8, 188u8, 56u8, 82u8, 72u8,
        49u8, 42u8, 103u8, 5u8, 231u8, 27u8, 254u8, 32u8, 209u8, 41u8, 93u8, 237u8, 127u8, 133u8,
        254u8, 84u8, 121u8, 53u8, 5u8, 212u8, 242u8, 172u8, 209u8, 124u8, 52u8, 191u8, 200u8, 27u8,
        71u8, 6u8, 172u8, 95u8, 8u8, 113u8, 9u8, 164u8, 197u8, 34u8, 46u8, 251u8, 173u8, 14u8,
        230u8, 132u8, 208u8, 87u8, 82u8, 80u8, 94u8, 99u8, 15u8, 250u8, 231u8, 108u8, 156u8, 59u8,
        112u8, 212u8, 91u8, 49u8, 202u8, 79u8, 17u8, 4u8, 109u8, 232u8, 218u8, 68u8, 199u8, 42u8,
        125u8, 10u8, 114u8, 73u8, 48u8, 95u8, 107u8, 235u8, 76u8, 145u8, 111u8, 68u8, 135u8, 36u8,
        196u8, 217u8, 37u8, 181u8, 124u8, 225u8, 142u8, 183u8, 235u8, 26u8, 114u8, 80u8, 250u8,
        249u8, 141u8, 170u8, 145u8,
    ],
    vk_gamma_g2: [
        34u8, 193u8, 143u8, 224u8, 168u8, 133u8, 36u8, 189u8, 198u8, 101u8, 3u8, 145u8, 31u8,
        143u8, 75u8, 29u8, 159u8, 27u8, 197u8, 23u8, 209u8, 180u8, 21u8, 84u8, 99u8, 153u8, 57u8,
        249u8, 225u8, 254u8, 13u8, 125u8, 8u8, 240u8, 1u8, 188u8, 197u8, 87u8, 194u8, 57u8, 24u8,
        42u8, 15u8, 17u8, 16u8, 200u8, 93u8, 5u8, 27u8, 119u8, 37u8, 249u8, 171u8, 227u8, 128u8,
        32u8, 30u8, 59u8, 198u8, 182u8, 44u8, 204u8, 120u8, 244u8, 19u8, 155u8, 37u8, 38u8, 197u8,
        5u8, 131u8, 145u8, 246u8, 135u8, 95u8, 66u8, 237u8, 147u8, 172u8, 255u8, 29u8, 166u8, 51u8,
        162u8, 48u8, 169u8, 68u8, 156u8, 132u8, 11u8, 209u8, 87u8, 22u8, 219u8, 133u8, 168u8, 25u8,
        44u8, 219u8, 114u8, 202u8, 129u8, 5u8, 244u8, 104u8, 97u8, 36u8, 25u8, 67u8, 189u8, 94u8,
        202u8, 34u8, 238u8, 251u8, 30u8, 19u8, 11u8, 217u8, 138u8, 202u8, 222u8, 251u8, 153u8,
        138u8, 11u8, 194u8, 254u8,
    ],
    vk_delta_g2: [
        42u8, 83u8, 250u8, 155u8, 161u8, 128u8, 226u8, 48u8, 163u8, 137u8, 110u8, 40u8, 223u8,
        54u8, 211u8, 140u8, 146u8, 63u8, 228u8, 98u8, 186u8, 29u8, 206u8, 142u8, 80u8, 169u8,
        145u8, 206u8, 248u8, 104u8, 241u8, 86u8, 21u8, 142u8, 252u8, 177u8, 179u8, 24u8, 186u8,
        47u8, 100u8, 36u8, 235u8, 9u8, 244u8, 211u8, 92u8, 227u8, 217u8, 108u8, 152u8, 211u8, 34u8,
        181u8, 86u8, 199u8, 199u8, 228u8, 140u8, 181u8, 56u8, 198u8, 255u8, 171u8, 16u8, 27u8,
        223u8, 83u8, 148u8, 80u8, 0u8, 37u8, 155u8, 82u8, 179u8, 24u8, 58u8, 87u8, 79u8, 125u8,
        33u8, 218u8, 136u8, 96u8, 113u8, 22u8, 197u8, 157u8, 141u8, 236u8, 97u8, 181u8, 151u8,
        141u8, 12u8, 107u8, 30u8, 12u8, 29u8, 253u8, 12u8, 105u8, 119u8, 64u8, 136u8, 81u8, 107u8,
        233u8, 125u8, 113u8, 187u8, 200u8, 38u8, 105u8, 145u8, 238u8, 13u8, 245u8, 182u8, 200u8,
        122u8, 109u8, 106u8, 228u8, 205u8, 132u8, 97u8, 30u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [233u8, 147u8, 61u8, 67u8, 206u8, 138u8, 63u8, 162u8, 160u8, 162u8, 211u8, 136u8, 81u8, 76u8, 116u8, 170u8, 90u8, 185u8, 105u8, 95u8, 28u8, 135u8, 65u8, 250u8, 104u8, 64u8, 72u8, 108u8, 218u8, 137u8, 143u8, 122u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_c6ad61ec80fe87fe")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00e9933d43ce8a3fa2a0a2d388514c74aa5ab9695f1c8741fa6840486cda898f7a\x00=======END GROTH16 VK SETUP V1=======\x00";
