// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        37u8, 11u8, 203u8, 191u8, 196u8, 227u8, 96u8, 76u8, 154u8, 3u8, 219u8, 22u8, 48u8, 6u8,
        146u8, 234u8, 59u8, 216u8, 167u8, 158u8, 110u8, 113u8, 11u8, 182u8, 69u8, 255u8, 202u8,
        210u8, 22u8, 250u8, 217u8, 176u8, 35u8, 133u8, 41u8, 180u8, 84u8, 115u8, 255u8, 25u8,
        134u8, 227u8, 255u8, 17u8, 74u8, 56u8, 35u8, 61u8, 245u8, 150u8, 197u8, 66u8, 250u8, 135u8,
        156u8, 106u8, 239u8, 171u8, 76u8, 215u8, 78u8, 130u8, 182u8, 155u8,
    ],
    [
        25u8, 8u8, 105u8, 242u8, 67u8, 42u8, 107u8, 90u8, 127u8, 141u8, 237u8, 205u8, 192u8, 245u8,
        49u8, 24u8, 142u8, 10u8, 69u8, 21u8, 57u8, 66u8, 187u8, 60u8, 250u8, 25u8, 143u8, 78u8,
        66u8, 92u8, 150u8, 186u8, 28u8, 94u8, 222u8, 32u8, 105u8, 39u8, 156u8, 38u8, 18u8, 12u8,
        212u8, 43u8, 192u8, 41u8, 247u8, 152u8, 4u8, 199u8, 38u8, 243u8, 248u8, 54u8, 235u8, 165u8,
        123u8, 158u8, 154u8, 235u8, 190u8, 185u8, 228u8, 205u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        46u8, 16u8, 233u8, 98u8, 90u8, 218u8, 221u8, 150u8, 64u8, 71u8, 215u8, 53u8, 185u8, 241u8,
        96u8, 46u8, 239u8, 91u8, 226u8, 62u8, 98u8, 183u8, 129u8, 17u8, 83u8, 131u8, 219u8, 254u8,
        212u8, 240u8, 224u8, 78u8, 2u8, 236u8, 218u8, 195u8, 253u8, 198u8, 117u8, 98u8, 5u8, 47u8,
        28u8, 225u8, 199u8, 246u8, 230u8, 144u8, 116u8, 187u8, 207u8, 29u8, 114u8, 45u8, 180u8,
        253u8, 222u8, 130u8, 221u8, 65u8, 214u8, 65u8, 122u8, 201u8,
    ],
    vk_beta_g2: [
        8u8, 68u8, 245u8, 6u8, 170u8, 3u8, 147u8, 173u8, 71u8, 219u8, 18u8, 189u8, 202u8, 202u8,
        197u8, 0u8, 226u8, 38u8, 52u8, 243u8, 11u8, 199u8, 106u8, 27u8, 217u8, 27u8, 19u8, 19u8,
        255u8, 190u8, 43u8, 41u8, 47u8, 133u8, 100u8, 83u8, 117u8, 58u8, 8u8, 71u8, 182u8, 208u8,
        31u8, 172u8, 46u8, 97u8, 239u8, 250u8, 138u8, 156u8, 198u8, 95u8, 156u8, 108u8, 121u8,
        146u8, 92u8, 167u8, 146u8, 71u8, 31u8, 160u8, 3u8, 114u8, 38u8, 246u8, 177u8, 159u8, 76u8,
        33u8, 190u8, 162u8, 244u8, 141u8, 77u8, 108u8, 3u8, 11u8, 246u8, 184u8, 95u8, 249u8, 171u8,
        67u8, 139u8, 142u8, 186u8, 40u8, 210u8, 109u8, 66u8, 24u8, 226u8, 76u8, 113u8, 54u8, 1u8,
        215u8, 186u8, 17u8, 215u8, 46u8, 81u8, 240u8, 72u8, 56u8, 46u8, 68u8, 95u8, 10u8, 242u8,
        20u8, 63u8, 252u8, 149u8, 170u8, 122u8, 137u8, 108u8, 215u8, 252u8, 250u8, 217u8, 13u8,
        137u8, 15u8, 206u8, 19u8,
    ],
    vk_gamma_g2: [
        25u8, 46u8, 194u8, 37u8, 32u8, 188u8, 152u8, 243u8, 1u8, 75u8, 99u8, 56u8, 75u8, 21u8,
        22u8, 176u8, 7u8, 118u8, 207u8, 1u8, 208u8, 107u8, 178u8, 87u8, 233u8, 198u8, 255u8, 179u8,
        240u8, 120u8, 55u8, 168u8, 9u8, 80u8, 24u8, 196u8, 183u8, 45u8, 0u8, 54u8, 206u8, 212u8,
        10u8, 140u8, 81u8, 236u8, 151u8, 154u8, 105u8, 50u8, 97u8, 27u8, 118u8, 47u8, 117u8, 122u8,
        188u8, 51u8, 132u8, 19u8, 81u8, 3u8, 158u8, 203u8, 20u8, 10u8, 100u8, 12u8, 212u8, 123u8,
        47u8, 218u8, 140u8, 223u8, 75u8, 58u8, 44u8, 154u8, 44u8, 56u8, 236u8, 192u8, 248u8, 196u8,
        226u8, 183u8, 243u8, 12u8, 201u8, 65u8, 183u8, 147u8, 81u8, 224u8, 121u8, 62u8, 42u8,
        169u8, 190u8, 160u8, 110u8, 102u8, 60u8, 108u8, 29u8, 180u8, 11u8, 180u8, 212u8, 158u8,
        146u8, 214u8, 93u8, 56u8, 0u8, 43u8, 245u8, 31u8, 179u8, 95u8, 156u8, 142u8, 182u8, 204u8,
        34u8, 99u8, 78u8, 180u8,
    ],
    vk_delta_g2: [
        22u8, 138u8, 212u8, 71u8, 94u8, 236u8, 174u8, 78u8, 178u8, 148u8, 108u8, 127u8, 193u8,
        245u8, 150u8, 101u8, 59u8, 224u8, 206u8, 59u8, 104u8, 77u8, 207u8, 81u8, 29u8, 76u8, 229u8,
        188u8, 168u8, 112u8, 11u8, 139u8, 28u8, 62u8, 164u8, 20u8, 86u8, 255u8, 178u8, 246u8, 8u8,
        247u8, 236u8, 120u8, 209u8, 133u8, 39u8, 188u8, 197u8, 226u8, 51u8, 4u8, 218u8, 98u8,
        242u8, 128u8, 183u8, 25u8, 127u8, 172u8, 83u8, 148u8, 157u8, 2u8, 45u8, 164u8, 32u8, 136u8,
        89u8, 176u8, 66u8, 41u8, 99u8, 157u8, 71u8, 144u8, 242u8, 66u8, 7u8, 177u8, 199u8, 226u8,
        152u8, 234u8, 47u8, 252u8, 8u8, 218u8, 4u8, 166u8, 104u8, 195u8, 172u8, 40u8, 31u8, 204u8,
        44u8, 193u8, 63u8, 84u8, 8u8, 197u8, 95u8, 170u8, 90u8, 255u8, 239u8, 206u8, 100u8, 118u8,
        223u8, 236u8, 80u8, 249u8, 210u8, 144u8, 83u8, 152u8, 243u8, 217u8, 247u8, 209u8, 14u8,
        221u8, 88u8, 223u8, 102u8, 44u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [63u8, 127u8, 26u8, 212u8, 175u8, 193u8, 216u8, 168u8, 23u8, 46u8, 176u8, 78u8, 229u8, 100u8, 147u8, 190u8, 138u8, 106u8, 5u8, 246u8, 216u8, 156u8, 33u8, 44u8, 203u8, 201u8, 212u8, 44u8, 121u8, 157u8, 233u8, 148u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_2fc81ad90cf68e83")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x003f7f1ad4afc1d8a8172eb04ee56493be8a6a05f6d89c212ccbc9d42c799de994\x00=======END GROTH16 VK SETUP V1=======\x00";
