// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        36u8, 168u8, 117u8, 12u8, 7u8, 154u8, 42u8, 240u8, 175u8, 254u8, 92u8, 19u8, 1u8, 88u8,
        28u8, 133u8, 229u8, 126u8, 23u8, 130u8, 17u8, 143u8, 84u8, 48u8, 190u8, 220u8, 235u8, 29u8,
        71u8, 49u8, 187u8, 147u8, 6u8, 121u8, 226u8, 73u8, 213u8, 190u8, 163u8, 206u8, 63u8, 53u8,
        241u8, 127u8, 159u8, 93u8, 219u8, 246u8, 241u8, 193u8, 123u8, 124u8, 147u8, 234u8, 154u8,
        182u8, 182u8, 237u8, 254u8, 79u8, 77u8, 113u8, 10u8, 30u8,
    ],
    [
        21u8, 114u8, 223u8, 217u8, 146u8, 170u8, 138u8, 88u8, 116u8, 99u8, 244u8, 225u8, 93u8,
        189u8, 55u8, 223u8, 204u8, 254u8, 228u8, 194u8, 30u8, 33u8, 133u8, 198u8, 52u8, 109u8,
        136u8, 192u8, 193u8, 216u8, 9u8, 182u8, 44u8, 53u8, 142u8, 76u8, 102u8, 58u8, 103u8, 122u8,
        187u8, 96u8, 152u8, 236u8, 136u8, 28u8, 91u8, 59u8, 191u8, 70u8, 146u8, 153u8, 251u8, 31u8,
        43u8, 184u8, 216u8, 213u8, 182u8, 211u8, 133u8, 0u8, 71u8, 120u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        34u8, 164u8, 87u8, 122u8, 208u8, 176u8, 153u8, 207u8, 212u8, 21u8, 35u8, 31u8, 225u8,
        157u8, 236u8, 93u8, 174u8, 88u8, 8u8, 158u8, 151u8, 165u8, 103u8, 210u8, 165u8, 52u8, 34u8,
        223u8, 57u8, 197u8, 62u8, 59u8, 5u8, 14u8, 85u8, 103u8, 41u8, 84u8, 116u8, 59u8, 182u8,
        162u8, 209u8, 3u8, 113u8, 153u8, 177u8, 202u8, 174u8, 229u8, 109u8, 47u8, 197u8, 104u8,
        22u8, 94u8, 11u8, 33u8, 106u8, 152u8, 134u8, 238u8, 126u8, 18u8,
    ],
    vk_beta_g2: [
        37u8, 30u8, 118u8, 117u8, 87u8, 176u8, 239u8, 244u8, 80u8, 158u8, 229u8, 161u8, 47u8,
        131u8, 52u8, 125u8, 163u8, 98u8, 10u8, 240u8, 25u8, 147u8, 255u8, 188u8, 46u8, 47u8, 71u8,
        224u8, 147u8, 178u8, 173u8, 93u8, 26u8, 120u8, 44u8, 5u8, 163u8, 216u8, 23u8, 38u8, 12u8,
        192u8, 69u8, 252u8, 54u8, 46u8, 200u8, 26u8, 116u8, 220u8, 220u8, 61u8, 61u8, 104u8, 165u8,
        110u8, 238u8, 2u8, 230u8, 70u8, 106u8, 23u8, 202u8, 201u8, 28u8, 57u8, 157u8, 86u8, 142u8,
        72u8, 48u8, 129u8, 220u8, 174u8, 203u8, 9u8, 65u8, 178u8, 59u8, 9u8, 26u8, 179u8, 186u8,
        79u8, 175u8, 191u8, 228u8, 138u8, 241u8, 100u8, 33u8, 76u8, 28u8, 51u8, 15u8, 166u8, 32u8,
        49u8, 7u8, 127u8, 225u8, 95u8, 70u8, 212u8, 38u8, 243u8, 191u8, 3u8, 227u8, 47u8, 102u8,
        221u8, 39u8, 98u8, 75u8, 102u8, 133u8, 6u8, 144u8, 6u8, 84u8, 145u8, 255u8, 139u8, 164u8,
        7u8, 192u8, 170u8,
    ],
    vk_gamma_g2: [
        13u8, 134u8, 199u8, 41u8, 163u8, 178u8, 136u8, 205u8, 197u8, 122u8, 33u8, 19u8, 249u8,
        230u8, 99u8, 3u8, 151u8, 118u8, 62u8, 2u8, 130u8, 219u8, 8u8, 172u8, 203u8, 24u8, 6u8,
        164u8, 140u8, 127u8, 239u8, 34u8, 14u8, 85u8, 168u8, 19u8, 68u8, 113u8, 3u8, 206u8, 3u8,
        137u8, 220u8, 238u8, 237u8, 229u8, 73u8, 94u8, 62u8, 125u8, 160u8, 114u8, 110u8, 167u8,
        241u8, 48u8, 117u8, 206u8, 5u8, 13u8, 156u8, 176u8, 3u8, 185u8, 25u8, 40u8, 178u8, 188u8,
        103u8, 66u8, 71u8, 108u8, 174u8, 97u8, 103u8, 107u8, 160u8, 169u8, 114u8, 186u8, 19u8,
        152u8, 223u8, 73u8, 153u8, 77u8, 43u8, 71u8, 220u8, 178u8, 108u8, 180u8, 231u8, 5u8, 68u8,
        249u8, 27u8, 24u8, 102u8, 149u8, 144u8, 117u8, 102u8, 255u8, 214u8, 251u8, 146u8, 164u8,
        2u8, 227u8, 166u8, 128u8, 167u8, 66u8, 163u8, 121u8, 67u8, 26u8, 199u8, 126u8, 193u8,
        206u8, 37u8, 230u8, 48u8, 178u8, 76u8, 62u8,
    ],
    vk_delta_g2: [
        37u8, 9u8, 33u8, 70u8, 106u8, 178u8, 72u8, 98u8, 184u8, 154u8, 174u8, 209u8, 68u8, 0u8,
        79u8, 115u8, 121u8, 134u8, 101u8, 58u8, 238u8, 107u8, 92u8, 195u8, 186u8, 130u8, 229u8,
        147u8, 127u8, 254u8, 53u8, 208u8, 14u8, 4u8, 221u8, 11u8, 180u8, 107u8, 110u8, 240u8, 93u8,
        194u8, 228u8, 187u8, 163u8, 186u8, 159u8, 1u8, 2u8, 68u8, 174u8, 31u8, 254u8, 97u8, 63u8,
        23u8, 140u8, 139u8, 60u8, 69u8, 57u8, 45u8, 133u8, 206u8, 23u8, 70u8, 223u8, 253u8, 109u8,
        55u8, 175u8, 89u8, 65u8, 182u8, 43u8, 6u8, 22u8, 167u8, 167u8, 209u8, 155u8, 164u8, 92u8,
        164u8, 138u8, 162u8, 75u8, 164u8, 121u8, 91u8, 153u8, 99u8, 171u8, 177u8, 233u8, 25u8,
        24u8, 71u8, 177u8, 172u8, 229u8, 235u8, 39u8, 34u8, 9u8, 18u8, 252u8, 217u8, 127u8, 30u8,
        226u8, 74u8, 111u8, 216u8, 129u8, 152u8, 170u8, 112u8, 250u8, 46u8, 30u8, 115u8, 247u8,
        59u8, 126u8, 14u8, 32u8, 203u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [216u8, 135u8, 30u8, 45u8, 168u8, 208u8, 122u8, 106u8, 100u8, 166u8, 37u8, 226u8, 36u8, 16u8, 81u8, 83u8, 185u8, 174u8, 112u8, 128u8, 120u8, 57u8, 41u8, 193u8, 120u8, 16u8, 101u8, 73u8, 54u8, 173u8, 152u8, 237u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_6f38ce2396ca10e8")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00d8871e2da8d07a6a64a625e224105153b9ae7080783929c17810654936ad98ed\x00=======END GROTH16 VK SETUP V1=======\x00";
