// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        18u8, 139u8, 82u8, 238u8, 62u8, 112u8, 20u8, 23u8, 113u8, 107u8, 72u8, 243u8, 47u8, 151u8,
        127u8, 225u8, 77u8, 81u8, 28u8, 27u8, 179u8, 146u8, 143u8, 200u8, 116u8, 33u8, 247u8, 39u8,
        126u8, 67u8, 114u8, 168u8, 30u8, 181u8, 230u8, 52u8, 43u8, 32u8, 74u8, 138u8, 139u8, 8u8,
        114u8, 199u8, 50u8, 242u8, 177u8, 65u8, 44u8, 105u8, 29u8, 49u8, 114u8, 114u8, 185u8, 58u8,
        125u8, 230u8, 212u8, 164u8, 63u8, 45u8, 79u8, 163u8,
    ],
    [
        29u8, 11u8, 146u8, 50u8, 153u8, 38u8, 212u8, 73u8, 29u8, 93u8, 111u8, 123u8, 51u8, 189u8,
        138u8, 9u8, 5u8, 225u8, 100u8, 150u8, 149u8, 122u8, 187u8, 87u8, 224u8, 88u8, 248u8, 138u8,
        161u8, 23u8, 113u8, 136u8, 13u8, 235u8, 111u8, 80u8, 145u8, 239u8, 219u8, 218u8, 254u8,
        168u8, 105u8, 116u8, 116u8, 83u8, 255u8, 194u8, 225u8, 183u8, 157u8, 221u8, 124u8, 114u8,
        83u8, 83u8, 95u8, 119u8, 142u8, 145u8, 90u8, 116u8, 194u8, 163u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        44u8, 44u8, 131u8, 208u8, 225u8, 247u8, 29u8, 95u8, 87u8, 73u8, 5u8, 161u8, 131u8, 51u8,
        55u8, 109u8, 51u8, 54u8, 15u8, 6u8, 56u8, 27u8, 115u8, 6u8, 245u8, 252u8, 81u8, 210u8,
        24u8, 156u8, 86u8, 93u8, 34u8, 172u8, 217u8, 6u8, 16u8, 9u8, 107u8, 132u8, 175u8, 164u8,
        218u8, 74u8, 83u8, 106u8, 252u8, 130u8, 144u8, 214u8, 227u8, 15u8, 22u8, 58u8, 128u8,
        173u8, 0u8, 117u8, 213u8, 36u8, 26u8, 167u8, 225u8, 91u8,
    ],
    vk_beta_g2: [
        24u8, 117u8, 48u8, 63u8, 69u8, 175u8, 87u8, 202u8, 203u8, 132u8, 133u8, 89u8, 119u8, 18u8,
        140u8, 254u8, 51u8, 43u8, 126u8, 74u8, 203u8, 42u8, 75u8, 163u8, 155u8, 111u8, 74u8, 154u8,
        24u8, 80u8, 154u8, 214u8, 1u8, 13u8, 86u8, 255u8, 212u8, 237u8, 11u8, 119u8, 23u8, 35u8,
        122u8, 195u8, 139u8, 234u8, 214u8, 143u8, 8u8, 86u8, 159u8, 107u8, 32u8, 58u8, 70u8, 203u8,
        69u8, 79u8, 211u8, 113u8, 55u8, 187u8, 201u8, 170u8, 47u8, 28u8, 228u8, 164u8, 73u8, 104u8,
        161u8, 2u8, 224u8, 128u8, 51u8, 251u8, 138u8, 52u8, 48u8, 23u8, 39u8, 215u8, 223u8, 199u8,
        145u8, 223u8, 55u8, 115u8, 240u8, 90u8, 77u8, 176u8, 160u8, 108u8, 246u8, 72u8, 40u8,
        141u8, 194u8, 56u8, 128u8, 111u8, 215u8, 84u8, 220u8, 104u8, 66u8, 182u8, 186u8, 72u8,
        237u8, 166u8, 151u8, 2u8, 126u8, 170u8, 179u8, 140u8, 72u8, 159u8, 250u8, 53u8, 218u8,
        41u8, 163u8, 254u8, 211u8, 141u8,
    ],
    vk_gamma_g2: [
        8u8, 200u8, 6u8, 66u8, 22u8, 83u8, 227u8, 72u8, 28u8, 141u8, 87u8, 142u8, 117u8, 248u8,
        118u8, 154u8, 147u8, 212u8, 231u8, 235u8, 182u8, 249u8, 207u8, 233u8, 132u8, 87u8, 8u8,
        227u8, 23u8, 153u8, 37u8, 7u8, 33u8, 125u8, 217u8, 100u8, 111u8, 112u8, 32u8, 254u8, 150u8,
        66u8, 208u8, 109u8, 14u8, 73u8, 94u8, 66u8, 37u8, 66u8, 98u8, 241u8, 192u8, 4u8, 196u8,
        156u8, 253u8, 129u8, 219u8, 108u8, 151u8, 95u8, 151u8, 201u8, 36u8, 53u8, 201u8, 69u8,
        166u8, 98u8, 40u8, 152u8, 53u8, 218u8, 235u8, 19u8, 167u8, 80u8, 163u8, 199u8, 133u8,
        102u8, 106u8, 255u8, 230u8, 144u8, 209u8, 141u8, 56u8, 185u8, 139u8, 202u8, 211u8, 200u8,
        153u8, 32u8, 28u8, 63u8, 50u8, 166u8, 123u8, 238u8, 118u8, 23u8, 215u8, 221u8, 10u8, 231u8,
        86u8, 15u8, 198u8, 105u8, 130u8, 162u8, 53u8, 71u8, 204u8, 151u8, 96u8, 74u8, 231u8, 165u8,
        140u8, 112u8, 3u8, 151u8, 253u8, 66u8,
    ],
    vk_delta_g2: [
        39u8, 35u8, 141u8, 106u8, 193u8, 116u8, 141u8, 246u8, 168u8, 115u8, 66u8, 244u8, 215u8,
        8u8, 150u8, 61u8, 1u8, 194u8, 164u8, 76u8, 48u8, 42u8, 212u8, 100u8, 244u8, 152u8, 28u8,
        192u8, 79u8, 18u8, 13u8, 216u8, 39u8, 53u8, 95u8, 242u8, 220u8, 149u8, 85u8, 238u8, 120u8,
        64u8, 188u8, 55u8, 251u8, 152u8, 255u8, 215u8, 158u8, 102u8, 54u8, 77u8, 39u8, 177u8, 21u8,
        11u8, 131u8, 225u8, 100u8, 56u8, 199u8, 193u8, 37u8, 161u8, 3u8, 7u8, 255u8, 153u8, 26u8,
        95u8, 116u8, 192u8, 24u8, 200u8, 143u8, 149u8, 235u8, 86u8, 194u8, 5u8, 94u8, 81u8, 105u8,
        156u8, 187u8, 240u8, 129u8, 97u8, 192u8, 104u8, 19u8, 34u8, 223u8, 168u8, 251u8, 21u8,
        27u8, 12u8, 110u8, 104u8, 46u8, 244u8, 138u8, 220u8, 129u8, 202u8, 175u8, 51u8, 46u8,
        202u8, 115u8, 215u8, 203u8, 200u8, 76u8, 36u8, 54u8, 101u8, 78u8, 152u8, 54u8, 156u8,
        116u8, 123u8, 10u8, 125u8, 179u8, 10u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [169u8, 191u8, 178u8, 65u8, 73u8, 81u8, 167u8, 254u8, 32u8, 168u8, 110u8, 12u8, 192u8, 64u8, 225u8, 49u8, 166u8, 208u8, 136u8, 209u8, 241u8, 129u8, 243u8, 24u8, 108u8, 211u8, 124u8, 27u8, 237u8, 189u8, 220u8, 215u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_2701cde2c9d3c9ba")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00a9bfb2414951a7fe20a86e0cc040e131a6d088d1f181f3186cd37c1bedbddcd7\x00=======END GROTH16 VK SETUP V1=======\x00";
