// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        30u8, 207u8, 172u8, 146u8, 113u8, 63u8, 29u8, 85u8, 241u8, 37u8, 196u8, 34u8, 216u8, 214u8,
        201u8, 184u8, 167u8, 76u8, 90u8, 27u8, 23u8, 50u8, 45u8, 189u8, 147u8, 225u8, 144u8, 204u8,
        207u8, 15u8, 178u8, 178u8, 32u8, 195u8, 219u8, 51u8, 154u8, 23u8, 72u8, 38u8, 114u8, 33u8,
        179u8, 62u8, 184u8, 169u8, 19u8, 183u8, 251u8, 120u8, 167u8, 85u8, 3u8, 172u8, 202u8, 90u8,
        16u8, 78u8, 191u8, 132u8, 30u8, 44u8, 100u8, 20u8,
    ],
    [
        0u8, 137u8, 62u8, 223u8, 146u8, 153u8, 199u8, 224u8, 254u8, 40u8, 206u8, 216u8, 10u8, 95u8,
        58u8, 38u8, 1u8, 163u8, 96u8, 85u8, 128u8, 157u8, 219u8, 125u8, 27u8, 23u8, 139u8, 114u8,
        244u8, 18u8, 70u8, 226u8, 46u8, 62u8, 110u8, 216u8, 219u8, 250u8, 218u8, 34u8, 64u8, 73u8,
        210u8, 244u8, 94u8, 122u8, 129u8, 124u8, 66u8, 153u8, 199u8, 19u8, 187u8, 46u8, 228u8,
        131u8, 148u8, 55u8, 12u8, 160u8, 192u8, 96u8, 216u8, 37u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        28u8, 224u8, 243u8, 78u8, 32u8, 55u8, 213u8, 61u8, 251u8, 88u8, 139u8, 244u8, 3u8, 18u8,
        241u8, 200u8, 129u8, 115u8, 168u8, 78u8, 247u8, 15u8, 61u8, 159u8, 238u8, 58u8, 5u8, 15u8,
        82u8, 168u8, 138u8, 132u8, 26u8, 87u8, 227u8, 193u8, 23u8, 138u8, 182u8, 173u8, 198u8,
        65u8, 43u8, 204u8, 93u8, 111u8, 248u8, 40u8, 240u8, 206u8, 245u8, 171u8, 45u8, 162u8, 39u8,
        129u8, 144u8, 251u8, 160u8, 214u8, 18u8, 12u8, 85u8, 176u8,
    ],
    vk_beta_g2: [
        36u8, 198u8, 3u8, 108u8, 83u8, 3u8, 169u8, 234u8, 35u8, 58u8, 108u8, 141u8, 192u8, 15u8,
        189u8, 2u8, 103u8, 221u8, 33u8, 239u8, 43u8, 254u8, 250u8, 247u8, 70u8, 102u8, 99u8, 13u8,
        180u8, 150u8, 101u8, 25u8, 6u8, 174u8, 39u8, 83u8, 173u8, 246u8, 1u8, 77u8, 186u8, 229u8,
        213u8, 74u8, 127u8, 37u8, 24u8, 248u8, 200u8, 145u8, 200u8, 69u8, 179u8, 34u8, 63u8, 100u8,
        12u8, 244u8, 145u8, 157u8, 74u8, 104u8, 107u8, 78u8, 41u8, 47u8, 105u8, 27u8, 212u8, 181u8,
        127u8, 144u8, 90u8, 201u8, 107u8, 97u8, 161u8, 74u8, 80u8, 172u8, 91u8, 87u8, 37u8, 222u8,
        187u8, 13u8, 106u8, 180u8, 149u8, 142u8, 123u8, 5u8, 109u8, 188u8, 12u8, 194u8, 34u8,
        146u8, 231u8, 192u8, 246u8, 72u8, 155u8, 218u8, 175u8, 166u8, 224u8, 221u8, 100u8, 129u8,
        89u8, 219u8, 201u8, 28u8, 26u8, 110u8, 42u8, 172u8, 212u8, 195u8, 7u8, 124u8, 125u8, 128u8,
        119u8, 95u8, 231u8, 86u8,
    ],
    vk_gamma_g2: [
        44u8, 221u8, 13u8, 128u8, 103u8, 158u8, 4u8, 111u8, 44u8, 199u8, 74u8, 141u8, 53u8, 201u8,
        148u8, 228u8, 23u8, 209u8, 164u8, 160u8, 15u8, 116u8, 83u8, 96u8, 98u8, 105u8, 117u8,
        131u8, 134u8, 125u8, 80u8, 112u8, 21u8, 196u8, 246u8, 35u8, 158u8, 170u8, 100u8, 129u8,
        90u8, 2u8, 95u8, 138u8, 15u8, 135u8, 123u8, 204u8, 249u8, 216u8, 85u8, 28u8, 243u8, 18u8,
        200u8, 104u8, 99u8, 60u8, 194u8, 188u8, 249u8, 156u8, 99u8, 42u8, 48u8, 61u8, 209u8, 99u8,
        120u8, 34u8, 101u8, 226u8, 142u8, 209u8, 191u8, 122u8, 173u8, 42u8, 192u8, 2u8, 109u8, 6u8,
        170u8, 144u8, 47u8, 73u8, 177u8, 153u8, 124u8, 163u8, 190u8, 129u8, 149u8, 210u8, 32u8,
        20u8, 28u8, 97u8, 189u8, 32u8, 208u8, 22u8, 185u8, 92u8, 255u8, 126u8, 242u8, 34u8, 134u8,
        202u8, 119u8, 73u8, 1u8, 173u8, 42u8, 228u8, 176u8, 127u8, 154u8, 114u8, 203u8, 5u8, 172u8,
        203u8, 27u8, 201u8, 111u8, 16u8,
    ],
    vk_delta_g2: [
        38u8, 119u8, 97u8, 10u8, 189u8, 250u8, 201u8, 50u8, 45u8, 60u8, 157u8, 33u8, 80u8, 237u8,
        110u8, 166u8, 5u8, 77u8, 87u8, 168u8, 169u8, 194u8, 251u8, 54u8, 145u8, 73u8, 227u8, 172u8,
        175u8, 32u8, 150u8, 153u8, 8u8, 195u8, 19u8, 75u8, 166u8, 115u8, 244u8, 132u8, 68u8, 188u8,
        140u8, 201u8, 114u8, 5u8, 71u8, 104u8, 125u8, 80u8, 128u8, 164u8, 153u8, 78u8, 154u8,
        107u8, 88u8, 76u8, 203u8, 33u8, 254u8, 206u8, 168u8, 59u8, 4u8, 70u8, 64u8, 255u8, 207u8,
        38u8, 102u8, 81u8, 0u8, 107u8, 231u8, 234u8, 254u8, 232u8, 215u8, 192u8, 157u8, 163u8,
        144u8, 2u8, 28u8, 55u8, 244u8, 81u8, 130u8, 126u8, 228u8, 57u8, 24u8, 102u8, 62u8, 57u8,
        45u8, 206u8, 245u8, 157u8, 231u8, 213u8, 210u8, 31u8, 108u8, 16u8, 53u8, 119u8, 3u8, 60u8,
        153u8, 55u8, 17u8, 140u8, 65u8, 42u8, 129u8, 203u8, 241u8, 254u8, 142u8, 220u8, 139u8,
        160u8, 127u8, 48u8, 155u8, 185u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [119u8, 199u8, 174u8, 225u8, 27u8, 193u8, 1u8, 185u8, 8u8, 194u8, 196u8, 58u8, 109u8, 175u8, 153u8, 215u8, 100u8, 11u8, 48u8, 199u8, 222u8, 255u8, 42u8, 175u8, 26u8, 119u8, 236u8, 92u8, 99u8, 140u8, 208u8, 100u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_1bacedd6c70181b1")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x0077c7aee11bc101b908c2c43a6daf99d7640b30c7deff2aaf1a77ec5c638cd064\x00=======END GROTH16 VK SETUP V1=======\x00";
