// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        35u8, 72u8, 148u8, 168u8, 230u8, 97u8, 81u8, 48u8, 195u8, 149u8, 64u8, 24u8, 6u8, 22u8,
        111u8, 188u8, 208u8, 90u8, 171u8, 135u8, 163u8, 44u8, 72u8, 146u8, 10u8, 144u8, 128u8,
        210u8, 154u8, 126u8, 21u8, 119u8, 23u8, 12u8, 88u8, 36u8, 213u8, 112u8, 195u8, 154u8,
        199u8, 231u8, 95u8, 54u8, 124u8, 247u8, 76u8, 93u8, 186u8, 193u8, 120u8, 229u8, 175u8,
        184u8, 6u8, 36u8, 170u8, 136u8, 70u8, 201u8, 155u8, 13u8, 244u8, 28u8,
    ],
    [
        23u8, 110u8, 176u8, 201u8, 44u8, 105u8, 183u8, 119u8, 81u8, 22u8, 150u8, 53u8, 145u8, 97u8,
        82u8, 44u8, 86u8, 51u8, 92u8, 244u8, 108u8, 241u8, 162u8, 243u8, 251u8, 152u8, 93u8, 169u8,
        232u8, 102u8, 77u8, 211u8, 21u8, 200u8, 210u8, 108u8, 76u8, 19u8, 164u8, 218u8, 53u8, 17u8,
        10u8, 29u8, 25u8, 191u8, 198u8, 55u8, 179u8, 233u8, 160u8, 204u8, 68u8, 169u8, 32u8, 245u8,
        219u8, 94u8, 105u8, 166u8, 237u8, 178u8, 30u8, 215u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        37u8, 55u8, 141u8, 172u8, 50u8, 134u8, 32u8, 181u8, 27u8, 185u8, 10u8, 97u8, 42u8, 75u8,
        179u8, 150u8, 232u8, 158u8, 124u8, 175u8, 27u8, 251u8, 16u8, 54u8, 63u8, 50u8, 187u8,
        169u8, 235u8, 116u8, 57u8, 97u8, 37u8, 134u8, 210u8, 112u8, 4u8, 8u8, 222u8, 48u8, 142u8,
        113u8, 60u8, 186u8, 46u8, 105u8, 225u8, 55u8, 76u8, 44u8, 123u8, 194u8, 254u8, 105u8,
        225u8, 192u8, 178u8, 225u8, 200u8, 7u8, 35u8, 201u8, 104u8, 135u8,
    ],
    vk_beta_g2: [
        38u8, 105u8, 135u8, 174u8, 134u8, 141u8, 15u8, 224u8, 98u8, 152u8, 128u8, 117u8, 165u8,
        242u8, 98u8, 8u8, 187u8, 44u8, 208u8, 159u8, 132u8, 235u8, 241u8, 82u8, 171u8, 179u8,
        218u8, 247u8, 252u8, 186u8, 57u8, 197u8, 38u8, 79u8, 246u8, 53u8, 192u8, 57u8, 202u8, 50u8,
        128u8, 91u8, 24u8, 178u8, 175u8, 205u8, 173u8, 13u8, 135u8, 253u8, 42u8, 253u8, 157u8,
        72u8, 58u8, 73u8, 41u8, 187u8, 6u8, 153u8, 50u8, 67u8, 0u8, 5u8, 32u8, 240u8, 79u8, 34u8,
        153u8, 64u8, 89u8, 184u8, 20u8, 238u8, 115u8, 43u8, 98u8, 236u8, 160u8, 58u8, 9u8, 151u8,
        110u8, 183u8, 191u8, 166u8, 36u8, 131u8, 120u8, 108u8, 113u8, 78u8, 5u8, 40u8, 22u8, 205u8,
        13u8, 217u8, 214u8, 120u8, 112u8, 57u8, 156u8, 80u8, 128u8, 249u8, 222u8, 163u8, 72u8,
        176u8, 237u8, 187u8, 249u8, 39u8, 195u8, 221u8, 96u8, 211u8, 84u8, 9u8, 27u8, 141u8, 98u8,
        30u8, 61u8, 39u8, 202u8, 13u8,
    ],
    vk_gamma_g2: [
        28u8, 126u8, 193u8, 21u8, 125u8, 96u8, 36u8, 18u8, 129u8, 105u8, 210u8, 202u8, 191u8,
        223u8, 6u8, 14u8, 226u8, 181u8, 202u8, 179u8, 132u8, 234u8, 199u8, 19u8, 140u8, 181u8, 9u8,
        117u8, 183u8, 133u8, 89u8, 19u8, 38u8, 26u8, 83u8, 210u8, 60u8, 164u8, 254u8, 209u8, 199u8,
        121u8, 200u8, 197u8, 149u8, 221u8, 137u8, 30u8, 206u8, 152u8, 150u8, 24u8, 40u8, 219u8,
        92u8, 254u8, 145u8, 65u8, 152u8, 113u8, 142u8, 209u8, 242u8, 130u8, 3u8, 32u8, 63u8, 182u8,
        100u8, 238u8, 97u8, 28u8, 154u8, 175u8, 106u8, 211u8, 215u8, 148u8, 67u8, 115u8, 176u8,
        69u8, 15u8, 81u8, 199u8, 75u8, 42u8, 203u8, 143u8, 86u8, 73u8, 102u8, 94u8, 50u8, 3u8,
        87u8, 48u8, 20u8, 43u8, 147u8, 242u8, 90u8, 210u8, 7u8, 66u8, 77u8, 154u8, 128u8, 69u8,
        236u8, 167u8, 54u8, 107u8, 229u8, 61u8, 86u8, 169u8, 248u8, 51u8, 217u8, 133u8, 62u8,
        229u8, 221u8, 0u8, 206u8, 168u8, 21u8,
    ],
    vk_delta_g2: [
        14u8, 56u8, 118u8, 199u8, 233u8, 228u8, 121u8, 131u8, 47u8, 10u8, 208u8, 227u8, 149u8,
        38u8, 86u8, 203u8, 71u8, 169u8, 18u8, 107u8, 201u8, 33u8, 19u8, 53u8, 214u8, 37u8, 127u8,
        138u8, 24u8, 73u8, 169u8, 138u8, 15u8, 79u8, 180u8, 196u8, 124u8, 160u8, 62u8, 42u8, 27u8,
        106u8, 216u8, 72u8, 103u8, 10u8, 213u8, 110u8, 103u8, 188u8, 160u8, 190u8, 191u8, 110u8,
        11u8, 175u8, 129u8, 223u8, 78u8, 170u8, 75u8, 0u8, 163u8, 156u8, 35u8, 53u8, 253u8, 181u8,
        5u8, 76u8, 42u8, 194u8, 143u8, 143u8, 73u8, 199u8, 43u8, 128u8, 178u8, 115u8, 182u8, 74u8,
        22u8, 87u8, 222u8, 252u8, 20u8, 99u8, 105u8, 113u8, 66u8, 159u8, 225u8, 0u8, 207u8, 63u8,
        41u8, 186u8, 138u8, 5u8, 58u8, 130u8, 99u8, 214u8, 50u8, 233u8, 6u8, 207u8, 237u8, 91u8,
        17u8, 179u8, 232u8, 189u8, 151u8, 123u8, 43u8, 137u8, 134u8, 32u8, 88u8, 188u8, 126u8,
        94u8, 1u8, 181u8, 155u8, 162u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [121u8, 132u8, 101u8, 58u8, 253u8, 103u8, 131u8, 106u8, 112u8, 31u8, 206u8, 56u8, 16u8, 92u8, 198u8, 65u8, 87u8, 100u8, 163u8, 239u8, 139u8, 113u8, 84u8, 142u8, 80u8, 244u8, 20u8, 247u8, 36u8, 144u8, 88u8, 239u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_932f417e7beeb586")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x007984653afd67836a701fce38105cc6415764a3ef8b71548e50f414f7249058ef\x00=======END GROTH16 VK SETUP V1=======\x00";
