// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        10u8, 252u8, 104u8, 22u8, 54u8, 219u8, 206u8, 148u8, 35u8, 28u8, 224u8, 251u8, 232u8, 20u8,
        210u8, 189u8, 83u8, 15u8, 62u8, 180u8, 189u8, 194u8, 74u8, 198u8, 188u8, 52u8, 91u8, 22u8,
        111u8, 33u8, 181u8, 193u8, 31u8, 61u8, 238u8, 122u8, 151u8, 43u8, 47u8, 97u8, 86u8, 36u8,
        182u8, 46u8, 68u8, 101u8, 194u8, 106u8, 104u8, 237u8, 105u8, 66u8, 41u8, 153u8, 203u8,
        186u8, 37u8, 95u8, 138u8, 100u8, 13u8, 236u8, 48u8, 179u8,
    ],
    [
        25u8, 47u8, 41u8, 214u8, 30u8, 72u8, 122u8, 255u8, 249u8, 157u8, 188u8, 229u8, 55u8, 46u8,
        160u8, 202u8, 134u8, 45u8, 216u8, 156u8, 98u8, 19u8, 237u8, 245u8, 213u8, 216u8, 90u8,
        239u8, 176u8, 73u8, 49u8, 54u8, 2u8, 62u8, 168u8, 175u8, 118u8, 146u8, 55u8, 109u8, 176u8,
        90u8, 130u8, 158u8, 106u8, 197u8, 179u8, 140u8, 123u8, 60u8, 233u8, 155u8, 98u8, 52u8,
        236u8, 98u8, 227u8, 128u8, 92u8, 155u8, 192u8, 235u8, 196u8, 28u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        39u8, 85u8, 31u8, 49u8, 181u8, 14u8, 99u8, 234u8, 234u8, 39u8, 64u8, 17u8, 167u8, 198u8,
        53u8, 198u8, 79u8, 167u8, 124u8, 214u8, 122u8, 178u8, 178u8, 173u8, 119u8, 159u8, 191u8,
        249u8, 148u8, 168u8, 32u8, 43u8, 9u8, 153u8, 23u8, 49u8, 126u8, 99u8, 206u8, 48u8, 152u8,
        70u8, 248u8, 124u8, 192u8, 159u8, 213u8, 21u8, 119u8, 79u8, 74u8, 109u8, 98u8, 184u8,
        214u8, 147u8, 96u8, 35u8, 160u8, 55u8, 229u8, 162u8, 4u8, 204u8,
    ],
    vk_beta_g2: [
        25u8, 247u8, 24u8, 114u8, 155u8, 187u8, 90u8, 97u8, 33u8, 101u8, 84u8, 38u8, 57u8, 174u8,
        149u8, 121u8, 40u8, 20u8, 165u8, 139u8, 5u8, 49u8, 200u8, 92u8, 223u8, 169u8, 250u8, 158u8,
        176u8, 216u8, 41u8, 196u8, 19u8, 219u8, 224u8, 207u8, 169u8, 174u8, 47u8, 235u8, 74u8,
        184u8, 169u8, 168u8, 125u8, 114u8, 114u8, 7u8, 120u8, 60u8, 236u8, 50u8, 40u8, 142u8,
        120u8, 221u8, 112u8, 41u8, 95u8, 163u8, 182u8, 1u8, 143u8, 249u8, 14u8, 122u8, 236u8,
        160u8, 104u8, 125u8, 225u8, 162u8, 24u8, 167u8, 144u8, 86u8, 140u8, 243u8, 171u8, 213u8,
        187u8, 65u8, 181u8, 113u8, 198u8, 227u8, 156u8, 135u8, 223u8, 204u8, 70u8, 4u8, 65u8,
        183u8, 17u8, 43u8, 41u8, 239u8, 233u8, 100u8, 229u8, 182u8, 147u8, 24u8, 184u8, 213u8,
        227u8, 146u8, 48u8, 169u8, 85u8, 181u8, 55u8, 113u8, 132u8, 158u8, 4u8, 162u8, 82u8, 183u8,
        6u8, 67u8, 122u8, 75u8, 99u8, 25u8, 226u8, 125u8,
    ],
    vk_gamma_g2: [
        35u8, 124u8, 30u8, 189u8, 204u8, 212u8, 221u8, 163u8, 60u8, 187u8, 137u8, 57u8, 114u8,
        233u8, 132u8, 80u8, 143u8, 131u8, 126u8, 198u8, 78u8, 130u8, 217u8, 55u8, 19u8, 103u8,
        112u8, 225u8, 217u8, 153u8, 26u8, 216u8, 45u8, 102u8, 108u8, 255u8, 237u8, 128u8, 197u8,
        228u8, 49u8, 168u8, 17u8, 170u8, 240u8, 213u8, 95u8, 99u8, 226u8, 87u8, 148u8, 82u8, 222u8,
        174u8, 133u8, 251u8, 63u8, 108u8, 146u8, 174u8, 123u8, 26u8, 127u8, 165u8, 17u8, 204u8,
        11u8, 183u8, 175u8, 20u8, 2u8, 64u8, 165u8, 251u8, 83u8, 205u8, 90u8, 49u8, 250u8, 173u8,
        78u8, 183u8, 151u8, 93u8, 148u8, 21u8, 253u8, 91u8, 39u8, 44u8, 149u8, 28u8, 181u8, 191u8,
        185u8, 193u8, 25u8, 253u8, 204u8, 127u8, 163u8, 191u8, 49u8, 253u8, 15u8, 237u8, 216u8,
        31u8, 174u8, 242u8, 84u8, 247u8, 225u8, 113u8, 179u8, 92u8, 106u8, 143u8, 29u8, 254u8,
        108u8, 24u8, 77u8, 32u8, 7u8, 44u8, 18u8, 42u8,
    ],
    vk_delta_g2: [
        3u8, 60u8, 147u8, 56u8, 106u8, 246u8, 67u8, 14u8, 112u8, 98u8, 155u8, 1u8, 82u8, 7u8, 67u8,
        141u8, 16u8, 200u8, 76u8, 244u8, 17u8, 184u8, 246u8, 235u8, 119u8, 134u8, 215u8, 37u8,
        11u8, 100u8, 81u8, 179u8, 46u8, 174u8, 126u8, 85u8, 159u8, 14u8, 228u8, 46u8, 96u8, 38u8,
        216u8, 25u8, 226u8, 26u8, 136u8, 63u8, 208u8, 200u8, 11u8, 156u8, 212u8, 203u8, 207u8,
        126u8, 92u8, 116u8, 200u8, 39u8, 253u8, 110u8, 58u8, 96u8, 16u8, 6u8, 143u8, 141u8, 23u8,
        208u8, 105u8, 199u8, 174u8, 75u8, 45u8, 3u8, 104u8, 220u8, 234u8, 196u8, 200u8, 224u8,
        227u8, 155u8, 65u8, 96u8, 100u8, 177u8, 169u8, 0u8, 250u8, 97u8, 5u8, 180u8, 84u8, 161u8,
        34u8, 203u8, 195u8, 85u8, 16u8, 122u8, 118u8, 26u8, 138u8, 236u8, 8u8, 181u8, 9u8, 19u8,
        207u8, 241u8, 125u8, 66u8, 105u8, 196u8, 60u8, 162u8, 207u8, 107u8, 28u8, 37u8, 0u8, 163u8,
        144u8, 37u8, 209u8, 56u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [26u8, 218u8, 43u8, 19u8, 137u8, 219u8, 23u8, 248u8, 125u8, 143u8, 171u8, 131u8, 169u8, 221u8, 215u8, 46u8, 171u8, 71u8, 77u8, 158u8, 5u8, 6u8, 180u8, 221u8, 187u8, 167u8, 235u8, 39u8, 237u8, 15u8, 20u8, 245u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_70be1976d2a1d1e5")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x001ada2b1389db17f87d8fab83a9ddd72eab474d9e0506b4ddbba7eb27ed0f14f5\x00=======END GROTH16 VK SETUP V1=======\x00";
