// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        31u8, 232u8, 193u8, 225u8, 231u8, 184u8, 124u8, 144u8, 205u8, 212u8, 160u8, 30u8, 34u8,
        83u8, 103u8, 249u8, 65u8, 176u8, 121u8, 164u8, 178u8, 94u8, 114u8, 207u8, 12u8, 105u8,
        139u8, 139u8, 122u8, 38u8, 1u8, 190u8, 6u8, 104u8, 163u8, 230u8, 15u8, 182u8, 109u8, 171u8,
        191u8, 35u8, 50u8, 131u8, 11u8, 219u8, 76u8, 31u8, 34u8, 87u8, 202u8, 16u8, 247u8, 117u8,
        176u8, 100u8, 153u8, 223u8, 254u8, 1u8, 155u8, 15u8, 6u8, 106u8,
    ],
    [
        40u8, 48u8, 70u8, 33u8, 30u8, 92u8, 7u8, 25u8, 80u8, 45u8, 155u8, 84u8, 132u8, 164u8, 49u8,
        139u8, 205u8, 173u8, 167u8, 120u8, 41u8, 226u8, 82u8, 145u8, 72u8, 204u8, 246u8, 148u8,
        92u8, 157u8, 17u8, 140u8, 0u8, 59u8, 213u8, 80u8, 231u8, 24u8, 126u8, 202u8, 221u8, 30u8,
        175u8, 181u8, 254u8, 154u8, 53u8, 39u8, 104u8, 255u8, 187u8, 230u8, 230u8, 217u8, 20u8,
        84u8, 154u8, 16u8, 161u8, 103u8, 11u8, 48u8, 182u8, 250u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        42u8, 49u8, 67u8, 209u8, 27u8, 165u8, 192u8, 184u8, 98u8, 247u8, 33u8, 202u8, 219u8, 187u8,
        71u8, 252u8, 229u8, 248u8, 36u8, 134u8, 244u8, 74u8, 38u8, 220u8, 167u8, 166u8, 30u8,
        125u8, 196u8, 16u8, 255u8, 154u8, 5u8, 111u8, 1u8, 51u8, 58u8, 125u8, 145u8, 199u8, 7u8,
        183u8, 145u8, 130u8, 90u8, 124u8, 28u8, 240u8, 4u8, 68u8, 87u8, 241u8, 34u8, 177u8, 239u8,
        112u8, 163u8, 177u8, 153u8, 28u8, 8u8, 59u8, 105u8, 179u8,
    ],
    vk_beta_g2: [
        40u8, 183u8, 72u8, 114u8, 129u8, 98u8, 103u8, 146u8, 39u8, 147u8, 90u8, 15u8, 169u8, 196u8,
        170u8, 54u8, 97u8, 12u8, 26u8, 44u8, 199u8, 36u8, 113u8, 151u8, 58u8, 183u8, 192u8, 55u8,
        72u8, 135u8, 236u8, 84u8, 25u8, 69u8, 59u8, 83u8, 116u8, 248u8, 255u8, 137u8, 64u8, 69u8,
        29u8, 229u8, 105u8, 48u8, 40u8, 3u8, 207u8, 246u8, 90u8, 220u8, 212u8, 79u8, 185u8, 181u8,
        172u8, 90u8, 101u8, 231u8, 218u8, 216u8, 254u8, 241u8, 2u8, 39u8, 153u8, 189u8, 17u8, 30u8,
        120u8, 38u8, 174u8, 244u8, 138u8, 90u8, 182u8, 86u8, 244u8, 149u8, 197u8, 114u8, 243u8,
        155u8, 87u8, 26u8, 134u8, 71u8, 1u8, 68u8, 61u8, 157u8, 121u8, 172u8, 124u8, 225u8, 12u8,
        34u8, 219u8, 114u8, 162u8, 214u8, 21u8, 166u8, 119u8, 89u8, 65u8, 212u8, 67u8, 245u8,
        216u8, 218u8, 137u8, 45u8, 12u8, 227u8, 169u8, 42u8, 68u8, 60u8, 118u8, 68u8, 41u8, 39u8,
        251u8, 91u8, 49u8, 18u8,
    ],
    vk_gamma_g2: [
        48u8, 55u8, 234u8, 27u8, 126u8, 182u8, 147u8, 40u8, 180u8, 177u8, 209u8, 196u8, 97u8, 91u8,
        40u8, 157u8, 8u8, 51u8, 0u8, 248u8, 173u8, 218u8, 172u8, 195u8, 91u8, 0u8, 17u8, 65u8,
        31u8, 36u8, 24u8, 110u8, 45u8, 28u8, 10u8, 141u8, 127u8, 146u8, 247u8, 247u8, 102u8, 255u8,
        157u8, 202u8, 199u8, 98u8, 22u8, 77u8, 163u8, 26u8, 173u8, 197u8, 192u8, 119u8, 248u8,
        218u8, 145u8, 227u8, 143u8, 188u8, 173u8, 81u8, 213u8, 188u8, 29u8, 121u8, 139u8, 44u8,
        152u8, 33u8, 46u8, 71u8, 196u8, 185u8, 57u8, 193u8, 162u8, 58u8, 210u8, 132u8, 9u8, 106u8,
        202u8, 210u8, 205u8, 223u8, 16u8, 93u8, 216u8, 95u8, 73u8, 25u8, 16u8, 209u8, 38u8, 96u8,
        29u8, 193u8, 246u8, 53u8, 160u8, 108u8, 144u8, 209u8, 105u8, 67u8, 28u8, 186u8, 189u8,
        172u8, 20u8, 190u8, 28u8, 55u8, 213u8, 35u8, 144u8, 187u8, 27u8, 125u8, 33u8, 221u8, 138u8,
        147u8, 156u8, 68u8, 146u8, 17u8,
    ],
    vk_delta_g2: [
        2u8, 52u8, 245u8, 47u8, 220u8, 212u8, 184u8, 168u8, 79u8, 160u8, 200u8, 139u8, 29u8, 166u8,
        41u8, 26u8, 93u8, 48u8, 50u8, 115u8, 172u8, 42u8, 193u8, 241u8, 7u8, 221u8, 197u8, 20u8,
        255u8, 129u8, 24u8, 78u8, 46u8, 114u8, 123u8, 60u8, 36u8, 169u8, 191u8, 229u8, 92u8, 63u8,
        231u8, 0u8, 153u8, 116u8, 213u8, 233u8, 112u8, 51u8, 225u8, 29u8, 100u8, 226u8, 64u8,
        191u8, 158u8, 210u8, 111u8, 254u8, 146u8, 113u8, 146u8, 131u8, 22u8, 203u8, 66u8, 218u8,
        255u8, 136u8, 165u8, 172u8, 192u8, 126u8, 56u8, 91u8, 103u8, 122u8, 226u8, 9u8, 194u8,
        253u8, 188u8, 21u8, 101u8, 175u8, 152u8, 53u8, 253u8, 154u8, 73u8, 241u8, 21u8, 229u8,
        215u8, 88u8, 27u8, 160u8, 42u8, 80u8, 114u8, 16u8, 61u8, 231u8, 97u8, 54u8, 117u8, 79u8,
        90u8, 73u8, 177u8, 3u8, 85u8, 154u8, 146u8, 26u8, 139u8, 43u8, 99u8, 196u8, 186u8, 123u8,
        203u8, 132u8, 13u8, 110u8, 217u8, 25u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [9u8, 0u8, 147u8, 34u8, 83u8, 28u8, 169u8, 56u8, 11u8, 23u8, 74u8, 232u8, 44u8, 50u8, 79u8, 252u8, 241u8, 243u8, 105u8, 47u8, 142u8, 253u8, 168u8, 34u8, 238u8, 133u8, 218u8, 48u8, 43u8, 193u8, 223u8, 60u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_c25c681918b12c22")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x0009009322531ca9380b174ae82c324ffcf1f3692f8efda822ee85da302bc1df3c\x00=======END GROTH16 VK SETUP V1=======\x00";
