// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        13u8, 218u8, 135u8, 75u8, 247u8, 26u8, 131u8, 101u8, 140u8, 87u8, 74u8, 230u8, 90u8, 179u8,
        184u8, 27u8, 17u8, 235u8, 137u8, 191u8, 31u8, 133u8, 170u8, 147u8, 78u8, 57u8, 113u8, 86u8,
        226u8, 46u8, 127u8, 84u8, 15u8, 82u8, 180u8, 5u8, 4u8, 58u8, 171u8, 153u8, 175u8, 253u8,
        17u8, 85u8, 143u8, 39u8, 223u8, 102u8, 254u8, 89u8, 40u8, 216u8, 80u8, 123u8, 8u8, 202u8,
        21u8, 50u8, 200u8, 186u8, 34u8, 89u8, 91u8, 149u8,
    ],
    [
        33u8, 30u8, 3u8, 165u8, 122u8, 253u8, 105u8, 73u8, 209u8, 243u8, 43u8, 201u8, 36u8, 221u8,
        150u8, 191u8, 76u8, 125u8, 36u8, 150u8, 45u8, 212u8, 198u8, 65u8, 75u8, 179u8, 24u8, 179u8,
        86u8, 245u8, 74u8, 102u8, 41u8, 12u8, 54u8, 49u8, 137u8, 237u8, 236u8, 94u8, 178u8, 207u8,
        181u8, 110u8, 230u8, 79u8, 190u8, 71u8, 182u8, 24u8, 136u8, 86u8, 60u8, 83u8, 31u8, 37u8,
        6u8, 149u8, 53u8, 27u8, 186u8, 180u8, 235u8, 24u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        5u8, 52u8, 130u8, 142u8, 158u8, 94u8, 156u8, 249u8, 24u8, 50u8, 186u8, 195u8, 234u8, 135u8,
        181u8, 47u8, 96u8, 164u8, 48u8, 40u8, 190u8, 255u8, 127u8, 141u8, 187u8, 94u8, 241u8, 18u8,
        148u8, 119u8, 48u8, 255u8, 3u8, 33u8, 191u8, 143u8, 92u8, 165u8, 191u8, 134u8, 211u8,
        179u8, 20u8, 60u8, 37u8, 93u8, 89u8, 52u8, 166u8, 217u8, 4u8, 155u8, 190u8, 115u8, 181u8,
        184u8, 59u8, 71u8, 239u8, 14u8, 210u8, 145u8, 251u8, 239u8,
    ],
    vk_beta_g2: [
        34u8, 161u8, 219u8, 168u8, 112u8, 213u8, 245u8, 157u8, 5u8, 60u8, 242u8, 163u8, 8u8, 98u8,
        93u8, 32u8, 231u8, 4u8, 48u8, 143u8, 86u8, 164u8, 193u8, 207u8, 128u8, 69u8, 158u8, 120u8,
        249u8, 102u8, 173u8, 187u8, 33u8, 30u8, 231u8, 27u8, 8u8, 149u8, 146u8, 255u8, 51u8, 99u8,
        176u8, 249u8, 189u8, 229u8, 190u8, 106u8, 84u8, 23u8, 58u8, 123u8, 31u8, 157u8, 5u8, 172u8,
        214u8, 32u8, 242u8, 245u8, 136u8, 31u8, 25u8, 66u8, 17u8, 45u8, 194u8, 23u8, 182u8, 178u8,
        0u8, 134u8, 246u8, 203u8, 128u8, 89u8, 46u8, 177u8, 29u8, 52u8, 21u8, 234u8, 180u8, 120u8,
        145u8, 116u8, 0u8, 6u8, 130u8, 43u8, 232u8, 51u8, 92u8, 249u8, 146u8, 251u8, 21u8, 190u8,
        46u8, 73u8, 84u8, 180u8, 204u8, 95u8, 120u8, 78u8, 237u8, 182u8, 10u8, 230u8, 46u8, 31u8,
        228u8, 108u8, 23u8, 142u8, 224u8, 88u8, 225u8, 254u8, 137u8, 75u8, 138u8, 109u8, 50u8,
        57u8, 157u8, 24u8,
    ],
    vk_gamma_g2: [
        34u8, 58u8, 29u8, 100u8, 251u8, 236u8, 43u8, 156u8, 172u8, 8u8, 217u8, 36u8, 17u8, 86u8,
        46u8, 145u8, 66u8, 12u8, 185u8, 164u8, 174u8, 84u8, 108u8, 214u8, 88u8, 200u8, 148u8, 89u8,
        26u8, 237u8, 33u8, 219u8, 23u8, 111u8, 181u8, 128u8, 106u8, 130u8, 189u8, 195u8, 55u8,
        117u8, 41u8, 117u8, 245u8, 145u8, 62u8, 43u8, 137u8, 225u8, 76u8, 115u8, 228u8, 95u8,
        246u8, 93u8, 219u8, 71u8, 50u8, 80u8, 21u8, 241u8, 154u8, 141u8, 31u8, 104u8, 225u8, 131u8,
        33u8, 219u8, 50u8, 156u8, 167u8, 44u8, 213u8, 214u8, 93u8, 203u8, 82u8, 225u8, 188u8, 56u8,
        33u8, 126u8, 102u8, 24u8, 230u8, 220u8, 21u8, 95u8, 202u8, 140u8, 129u8, 233u8, 101u8,
        148u8, 15u8, 73u8, 192u8, 140u8, 208u8, 122u8, 126u8, 68u8, 199u8, 97u8, 252u8, 42u8, 83u8,
        199u8, 146u8, 129u8, 215u8, 206u8, 120u8, 78u8, 247u8, 106u8, 207u8, 240u8, 83u8, 42u8,
        45u8, 170u8, 249u8, 223u8, 63u8, 235u8,
    ],
    vk_delta_g2: [
        3u8, 45u8, 12u8, 97u8, 239u8, 18u8, 229u8, 19u8, 248u8, 122u8, 110u8, 125u8, 34u8, 51u8,
        196u8, 144u8, 69u8, 179u8, 206u8, 244u8, 249u8, 90u8, 171u8, 58u8, 173u8, 163u8, 86u8,
        109u8, 17u8, 243u8, 255u8, 98u8, 15u8, 31u8, 66u8, 115u8, 215u8, 166u8, 91u8, 219u8, 132u8,
        149u8, 67u8, 108u8, 106u8, 50u8, 188u8, 34u8, 197u8, 129u8, 92u8, 112u8, 163u8, 107u8,
        118u8, 139u8, 141u8, 151u8, 146u8, 234u8, 154u8, 48u8, 228u8, 139u8, 35u8, 146u8, 224u8,
        145u8, 252u8, 137u8, 208u8, 125u8, 52u8, 11u8, 103u8, 34u8, 48u8, 34u8, 126u8, 204u8,
        135u8, 236u8, 6u8, 174u8, 171u8, 90u8, 174u8, 63u8, 216u8, 76u8, 115u8, 101u8, 204u8, 3u8,
        178u8, 174u8, 0u8, 72u8, 205u8, 94u8, 42u8, 95u8, 138u8, 2u8, 186u8, 95u8, 200u8, 169u8,
        43u8, 26u8, 103u8, 33u8, 33u8, 189u8, 12u8, 229u8, 90u8, 177u8, 109u8, 93u8, 57u8, 127u8,
        176u8, 168u8, 250u8, 132u8, 206u8, 66u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [127u8, 202u8, 98u8, 231u8, 213u8, 18u8, 179u8, 209u8, 40u8, 240u8, 211u8, 159u8, 54u8, 97u8, 22u8, 5u8, 107u8, 104u8, 155u8, 66u8, 120u8, 26u8, 176u8, 3u8, 101u8, 228u8, 193u8, 172u8, 132u8, 212u8, 200u8, 10u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_1607430158d94d5a")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x007fca62e7d512b3d128f0d39f366116056b689b42781ab00365e4c1ac84d4c80a\x00=======END GROTH16 VK SETUP V1=======\x00";
