// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        36u8, 174u8, 213u8, 105u8, 231u8, 109u8, 164u8, 138u8, 107u8, 212u8, 14u8, 68u8, 213u8,
        117u8, 179u8, 74u8, 4u8, 119u8, 16u8, 209u8, 19u8, 90u8, 175u8, 97u8, 99u8, 152u8, 169u8,
        212u8, 120u8, 56u8, 40u8, 225u8, 22u8, 33u8, 66u8, 15u8, 151u8, 17u8, 113u8, 153u8, 197u8,
        44u8, 129u8, 236u8, 205u8, 211u8, 18u8, 142u8, 173u8, 106u8, 237u8, 63u8, 42u8, 135u8,
        216u8, 200u8, 246u8, 197u8, 163u8, 3u8, 2u8, 66u8, 29u8, 32u8,
    ],
    [
        37u8, 120u8, 166u8, 5u8, 156u8, 40u8, 61u8, 159u8, 40u8, 2u8, 182u8, 99u8, 106u8, 205u8,
        60u8, 161u8, 118u8, 12u8, 208u8, 73u8, 139u8, 121u8, 147u8, 7u8, 158u8, 191u8, 47u8, 160u8,
        91u8, 140u8, 26u8, 32u8, 38u8, 23u8, 93u8, 80u8, 97u8, 25u8, 0u8, 15u8, 85u8, 126u8, 215u8,
        28u8, 16u8, 72u8, 138u8, 133u8, 64u8, 73u8, 149u8, 128u8, 188u8, 136u8, 73u8, 217u8, 63u8,
        234u8, 59u8, 140u8, 202u8, 184u8, 205u8, 109u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        9u8, 10u8, 84u8, 185u8, 6u8, 88u8, 248u8, 201u8, 184u8, 82u8, 24u8, 149u8, 102u8, 56u8,
        170u8, 202u8, 56u8, 15u8, 48u8, 207u8, 231u8, 24u8, 17u8, 215u8, 113u8, 187u8, 105u8,
        133u8, 178u8, 183u8, 41u8, 181u8, 22u8, 128u8, 185u8, 75u8, 26u8, 133u8, 81u8, 116u8,
        170u8, 245u8, 37u8, 75u8, 67u8, 166u8, 125u8, 177u8, 78u8, 205u8, 99u8, 182u8, 128u8,
        107u8, 183u8, 69u8, 189u8, 177u8, 202u8, 170u8, 242u8, 170u8, 66u8, 139u8,
    ],
    vk_beta_g2: [
        12u8, 61u8, 49u8, 54u8, 205u8, 167u8, 182u8, 11u8, 225u8, 13u8, 175u8, 123u8, 4u8, 85u8,
        18u8, 35u8, 249u8, 156u8, 221u8, 1u8, 170u8, 153u8, 25u8, 55u8, 218u8, 178u8, 196u8, 179u8,
        77u8, 189u8, 33u8, 90u8, 36u8, 142u8, 59u8, 159u8, 12u8, 236u8, 173u8, 78u8, 142u8, 53u8,
        138u8, 4u8, 230u8, 64u8, 86u8, 16u8, 108u8, 228u8, 111u8, 237u8, 52u8, 53u8, 136u8, 18u8,
        247u8, 79u8, 101u8, 35u8, 214u8, 116u8, 246u8, 192u8, 25u8, 125u8, 132u8, 202u8, 196u8,
        171u8, 168u8, 69u8, 244u8, 152u8, 191u8, 163u8, 105u8, 69u8, 97u8, 177u8, 92u8, 38u8,
        202u8, 180u8, 208u8, 233u8, 101u8, 21u8, 253u8, 2u8, 128u8, 88u8, 49u8, 216u8, 30u8, 4u8,
        3u8, 171u8, 4u8, 194u8, 87u8, 204u8, 164u8, 117u8, 138u8, 49u8, 134u8, 173u8, 216u8, 229u8,
        72u8, 124u8, 149u8, 87u8, 69u8, 184u8, 237u8, 117u8, 86u8, 245u8, 254u8, 223u8, 45u8,
        236u8, 23u8, 241u8, 187u8, 70u8,
    ],
    vk_gamma_g2: [
        6u8, 218u8, 45u8, 0u8, 171u8, 233u8, 125u8, 212u8, 234u8, 171u8, 4u8, 178u8, 184u8, 180u8,
        63u8, 236u8, 243u8, 206u8, 222u8, 68u8, 70u8, 19u8, 83u8, 162u8, 215u8, 64u8, 62u8, 242u8,
        224u8, 151u8, 224u8, 154u8, 30u8, 14u8, 149u8, 135u8, 167u8, 42u8, 191u8, 187u8, 136u8,
        13u8, 202u8, 183u8, 71u8, 139u8, 224u8, 148u8, 102u8, 5u8, 8u8, 64u8, 129u8, 36u8, 190u8,
        124u8, 64u8, 18u8, 191u8, 37u8, 141u8, 221u8, 237u8, 84u8, 23u8, 219u8, 107u8, 228u8,
        122u8, 101u8, 66u8, 93u8, 114u8, 113u8, 229u8, 37u8, 23u8, 45u8, 250u8, 5u8, 40u8, 241u8,
        157u8, 82u8, 116u8, 34u8, 76u8, 245u8, 230u8, 133u8, 155u8, 37u8, 44u8, 23u8, 208u8, 197u8,
        14u8, 243u8, 180u8, 193u8, 211u8, 226u8, 162u8, 13u8, 38u8, 17u8, 168u8, 247u8, 118u8,
        33u8, 109u8, 74u8, 134u8, 56u8, 231u8, 215u8, 94u8, 63u8, 225u8, 177u8, 26u8, 53u8, 152u8,
        185u8, 166u8, 141u8, 56u8, 175u8,
    ],
    vk_delta_g2: [
        1u8, 70u8, 204u8, 245u8, 30u8, 38u8, 175u8, 217u8, 9u8, 211u8, 221u8, 234u8, 62u8, 142u8,
        190u8, 181u8, 162u8, 244u8, 188u8, 108u8, 124u8, 87u8, 150u8, 218u8, 165u8, 174u8, 10u8,
        184u8, 236u8, 231u8, 48u8, 17u8, 46u8, 135u8, 161u8, 215u8, 156u8, 57u8, 118u8, 170u8,
        183u8, 238u8, 212u8, 146u8, 41u8, 152u8, 166u8, 177u8, 149u8, 125u8, 101u8, 184u8, 30u8,
        230u8, 135u8, 41u8, 235u8, 23u8, 179u8, 215u8, 174u8, 123u8, 103u8, 129u8, 23u8, 35u8,
        40u8, 122u8, 248u8, 62u8, 181u8, 64u8, 146u8, 227u8, 118u8, 129u8, 161u8, 50u8, 178u8,
        229u8, 195u8, 224u8, 54u8, 50u8, 236u8, 142u8, 192u8, 178u8, 210u8, 197u8, 119u8, 55u8,
        4u8, 34u8, 65u8, 92u8, 17u8, 245u8, 208u8, 118u8, 57u8, 21u8, 168u8, 37u8, 15u8, 22u8,
        23u8, 122u8, 244u8, 49u8, 31u8, 56u8, 98u8, 73u8, 187u8, 95u8, 174u8, 138u8, 201u8, 248u8,
        142u8, 226u8, 172u8, 244u8, 227u8, 82u8, 106u8, 77u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [192u8, 54u8, 67u8, 90u8, 17u8, 213u8, 107u8, 133u8, 108u8, 24u8, 194u8, 55u8, 124u8, 174u8, 249u8, 122u8, 65u8, 214u8, 161u8, 131u8, 33u8, 223u8, 59u8, 19u8, 44u8, 239u8, 11u8, 88u8, 18u8, 125u8, 172u8, 81u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_95c152bfab4ae988")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00c036435a11d56b856c18c2377caef97a41d6a18321df3b132cef0b58127dac51\x00=======END GROTH16 VK SETUP V1=======\x00";
