// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        8u8, 120u8, 221u8, 211u8, 148u8, 69u8, 51u8, 213u8, 7u8, 228u8, 33u8, 184u8, 198u8, 96u8,
        177u8, 123u8, 31u8, 68u8, 170u8, 129u8, 85u8, 251u8, 117u8, 33u8, 183u8, 151u8, 148u8,
        160u8, 67u8, 10u8, 93u8, 91u8, 38u8, 93u8, 84u8, 34u8, 220u8, 29u8, 124u8, 10u8, 189u8,
        251u8, 59u8, 40u8, 98u8, 245u8, 122u8, 247u8, 59u8, 83u8, 111u8, 10u8, 174u8, 197u8, 55u8,
        85u8, 97u8, 189u8, 93u8, 235u8, 71u8, 45u8, 73u8, 178u8,
    ],
    [
        37u8, 244u8, 224u8, 97u8, 249u8, 245u8, 56u8, 130u8, 13u8, 176u8, 16u8, 221u8, 41u8, 190u8,
        175u8, 47u8, 185u8, 153u8, 25u8, 126u8, 247u8, 208u8, 235u8, 128u8, 10u8, 84u8, 137u8,
        161u8, 219u8, 29u8, 52u8, 180u8, 33u8, 146u8, 78u8, 63u8, 28u8, 209u8, 212u8, 131u8, 147u8,
        249u8, 102u8, 201u8, 50u8, 34u8, 218u8, 200u8, 121u8, 229u8, 67u8, 211u8, 102u8, 130u8,
        51u8, 34u8, 143u8, 113u8, 253u8, 58u8, 57u8, 38u8, 113u8, 21u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        6u8, 33u8, 123u8, 241u8, 243u8, 153u8, 242u8, 153u8, 121u8, 39u8, 2u8, 40u8, 133u8, 190u8,
        240u8, 84u8, 185u8, 215u8, 240u8, 131u8, 233u8, 181u8, 205u8, 27u8, 244u8, 27u8, 91u8,
        113u8, 12u8, 65u8, 240u8, 211u8, 7u8, 37u8, 31u8, 7u8, 73u8, 174u8, 58u8, 80u8, 184u8,
        20u8, 249u8, 4u8, 150u8, 6u8, 100u8, 160u8, 232u8, 66u8, 16u8, 197u8, 255u8, 162u8, 131u8,
        69u8, 4u8, 188u8, 1u8, 120u8, 76u8, 148u8, 137u8, 202u8,
    ],
    vk_beta_g2: [
        28u8, 226u8, 233u8, 72u8, 112u8, 127u8, 127u8, 95u8, 92u8, 0u8, 128u8, 132u8, 2u8, 109u8,
        145u8, 254u8, 126u8, 141u8, 181u8, 165u8, 175u8, 135u8, 228u8, 98u8, 174u8, 223u8, 253u8,
        228u8, 64u8, 40u8, 90u8, 30u8, 43u8, 98u8, 139u8, 0u8, 248u8, 181u8, 105u8, 24u8, 243u8,
        42u8, 193u8, 20u8, 235u8, 200u8, 251u8, 209u8, 61u8, 56u8, 100u8, 145u8, 125u8, 100u8,
        175u8, 205u8, 248u8, 220u8, 215u8, 110u8, 53u8, 145u8, 255u8, 65u8, 37u8, 214u8, 233u8,
        104u8, 42u8, 238u8, 67u8, 176u8, 201u8, 81u8, 252u8, 62u8, 6u8, 172u8, 116u8, 33u8, 27u8,
        242u8, 108u8, 130u8, 180u8, 203u8, 201u8, 66u8, 89u8, 209u8, 254u8, 184u8, 164u8, 65u8,
        130u8, 29u8, 9u8, 88u8, 82u8, 6u8, 183u8, 36u8, 139u8, 166u8, 126u8, 136u8, 69u8, 7u8,
        254u8, 6u8, 224u8, 28u8, 240u8, 45u8, 42u8, 14u8, 92u8, 194u8, 206u8, 253u8, 115u8, 148u8,
        167u8, 158u8, 187u8, 116u8, 108u8, 145u8,
    ],
    vk_gamma_g2: [
        29u8, 215u8, 235u8, 144u8, 161u8, 36u8, 178u8, 191u8, 76u8, 145u8, 55u8, 139u8, 111u8,
        132u8, 131u8, 211u8, 89u8, 104u8, 185u8, 120u8, 43u8, 223u8, 43u8, 1u8, 63u8, 41u8, 65u8,
        40u8, 76u8, 182u8, 100u8, 225u8, 36u8, 54u8, 93u8, 254u8, 160u8, 216u8, 228u8, 46u8, 75u8,
        69u8, 128u8, 62u8, 10u8, 91u8, 131u8, 59u8, 178u8, 153u8, 199u8, 208u8, 71u8, 251u8, 207u8,
        138u8, 154u8, 232u8, 103u8, 77u8, 225u8, 163u8, 201u8, 251u8, 39u8, 50u8, 49u8, 180u8,
        77u8, 226u8, 64u8, 41u8, 180u8, 124u8, 208u8, 9u8, 250u8, 136u8, 223u8, 76u8, 125u8, 129u8,
        28u8, 173u8, 143u8, 103u8, 112u8, 122u8, 179u8, 180u8, 35u8, 145u8, 100u8, 186u8, 246u8,
        5u8, 45u8, 3u8, 158u8, 208u8, 183u8, 212u8, 145u8, 158u8, 205u8, 12u8, 196u8, 86u8, 190u8,
        130u8, 212u8, 57u8, 240u8, 28u8, 216u8, 142u8, 86u8, 119u8, 247u8, 211u8, 75u8, 91u8,
        232u8, 96u8, 99u8, 88u8, 217u8, 159u8,
    ],
    vk_delta_g2: [
        27u8, 217u8, 62u8, 74u8, 64u8, 80u8, 94u8, 208u8, 75u8, 179u8, 13u8, 135u8, 151u8, 158u8,
        77u8, 48u8, 132u8, 135u8, 34u8, 248u8, 106u8, 170u8, 179u8, 168u8, 102u8, 176u8, 33u8, 0u8,
        97u8, 159u8, 152u8, 171u8, 36u8, 77u8, 90u8, 20u8, 254u8, 36u8, 180u8, 153u8, 79u8, 255u8,
        205u8, 0u8, 10u8, 95u8, 24u8, 19u8, 47u8, 185u8, 53u8, 145u8, 253u8, 191u8, 229u8, 239u8,
        236u8, 1u8, 98u8, 151u8, 184u8, 31u8, 174u8, 229u8, 33u8, 158u8, 198u8, 236u8, 194u8, 45u8,
        49u8, 205u8, 186u8, 173u8, 115u8, 207u8, 43u8, 236u8, 129u8, 76u8, 181u8, 126u8, 8u8, 44u8,
        47u8, 59u8, 6u8, 194u8, 202u8, 224u8, 198u8, 92u8, 36u8, 90u8, 60u8, 79u8, 33u8, 145u8,
        75u8, 170u8, 201u8, 177u8, 161u8, 44u8, 86u8, 209u8, 61u8, 243u8, 47u8, 127u8, 86u8, 104u8,
        226u8, 185u8, 156u8, 254u8, 204u8, 242u8, 80u8, 98u8, 228u8, 112u8, 232u8, 202u8, 233u8,
        144u8, 245u8, 165u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [93u8, 235u8, 70u8, 124u8, 81u8, 1u8, 198u8, 3u8, 65u8, 242u8, 4u8, 23u8, 98u8, 119u8, 76u8, 25u8, 217u8, 109u8, 162u8, 152u8, 68u8, 114u8, 172u8, 156u8, 84u8, 97u8, 239u8, 86u8, 134u8, 136u8, 24u8, 56u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_57672e60077042bc")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x005deb467c5101c60341f2041762774c19d96da2984472ac9c5461ef5686881838\x00=======END GROTH16 VK SETUP V1=======\x00";
