// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        7u8, 169u8, 22u8, 111u8, 33u8, 41u8, 230u8, 32u8, 250u8, 127u8, 204u8, 211u8, 8u8, 29u8,
        35u8, 79u8, 5u8, 64u8, 171u8, 76u8, 81u8, 163u8, 74u8, 147u8, 111u8, 92u8, 206u8, 205u8,
        228u8, 98u8, 36u8, 230u8, 15u8, 162u8, 173u8, 226u8, 93u8, 83u8, 251u8, 221u8, 206u8, 58u8,
        104u8, 150u8, 253u8, 164u8, 190u8, 84u8, 165u8, 204u8, 133u8, 128u8, 66u8, 59u8, 11u8,
        248u8, 205u8, 224u8, 29u8, 245u8, 163u8, 186u8, 124u8, 163u8,
    ],
    [
        15u8, 157u8, 12u8, 97u8, 166u8, 47u8, 126u8, 197u8, 86u8, 173u8, 113u8, 17u8, 79u8, 129u8,
        240u8, 92u8, 130u8, 69u8, 74u8, 185u8, 141u8, 162u8, 26u8, 108u8, 22u8, 111u8, 131u8,
        228u8, 78u8, 81u8, 36u8, 141u8, 21u8, 147u8, 28u8, 26u8, 142u8, 126u8, 59u8, 117u8, 212u8,
        61u8, 61u8, 39u8, 10u8, 82u8, 73u8, 171u8, 248u8, 243u8, 206u8, 172u8, 101u8, 182u8, 230u8,
        222u8, 78u8, 237u8, 87u8, 128u8, 158u8, 180u8, 49u8, 121u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        1u8, 117u8, 73u8, 254u8, 46u8, 237u8, 72u8, 37u8, 107u8, 222u8, 18u8, 205u8, 6u8, 126u8,
        235u8, 114u8, 100u8, 178u8, 241u8, 10u8, 178u8, 228u8, 176u8, 175u8, 54u8, 45u8, 113u8,
        223u8, 67u8, 175u8, 249u8, 15u8, 35u8, 25u8, 0u8, 68u8, 70u8, 118u8, 50u8, 182u8, 199u8,
        215u8, 196u8, 193u8, 61u8, 197u8, 191u8, 232u8, 91u8, 44u8, 213u8, 162u8, 177u8, 4u8,
        234u8, 67u8, 50u8, 214u8, 230u8, 92u8, 174u8, 118u8, 89u8, 236u8,
    ],
    vk_beta_g2: [
        40u8, 70u8, 194u8, 118u8, 57u8, 126u8, 172u8, 117u8, 24u8, 177u8, 184u8, 22u8, 107u8,
        159u8, 69u8, 205u8, 103u8, 240u8, 204u8, 136u8, 81u8, 242u8, 113u8, 27u8, 123u8, 167u8,
        57u8, 104u8, 89u8, 91u8, 84u8, 4u8, 1u8, 195u8, 58u8, 107u8, 81u8, 64u8, 231u8, 68u8,
        128u8, 125u8, 114u8, 33u8, 47u8, 196u8, 93u8, 42u8, 123u8, 70u8, 129u8, 86u8, 117u8, 205u8,
        192u8, 73u8, 165u8, 137u8, 149u8, 16u8, 147u8, 195u8, 127u8, 191u8, 11u8, 178u8, 212u8,
        171u8, 254u8, 178u8, 148u8, 7u8, 134u8, 173u8, 227u8, 161u8, 51u8, 18u8, 14u8, 78u8, 213u8,
        166u8, 8u8, 158u8, 223u8, 72u8, 81u8, 253u8, 130u8, 255u8, 12u8, 157u8, 230u8, 255u8, 26u8,
        159u8, 12u8, 108u8, 191u8, 25u8, 56u8, 27u8, 18u8, 206u8, 159u8, 21u8, 139u8, 114u8, 80u8,
        61u8, 74u8, 51u8, 201u8, 61u8, 97u8, 164u8, 201u8, 18u8, 178u8, 54u8, 42u8, 179u8, 46u8,
        80u8, 7u8, 120u8, 248u8, 6u8,
    ],
    vk_gamma_g2: [
        3u8, 107u8, 53u8, 226u8, 199u8, 142u8, 83u8, 144u8, 152u8, 172u8, 3u8, 224u8, 50u8, 178u8,
        217u8, 55u8, 238u8, 128u8, 70u8, 198u8, 177u8, 121u8, 25u8, 186u8, 58u8, 134u8, 70u8,
        196u8, 167u8, 53u8, 154u8, 89u8, 37u8, 126u8, 206u8, 210u8, 15u8, 88u8, 185u8, 167u8,
        134u8, 113u8, 182u8, 94u8, 187u8, 48u8, 40u8, 26u8, 90u8, 120u8, 24u8, 54u8, 180u8, 184u8,
        5u8, 182u8, 168u8, 192u8, 13u8, 11u8, 21u8, 37u8, 103u8, 82u8, 33u8, 2u8, 166u8, 49u8,
        62u8, 126u8, 152u8, 83u8, 99u8, 221u8, 17u8, 163u8, 75u8, 152u8, 169u8, 183u8, 38u8, 11u8,
        221u8, 65u8, 146u8, 92u8, 123u8, 108u8, 44u8, 143u8, 210u8, 61u8, 164u8, 1u8, 133u8, 96u8,
        18u8, 90u8, 12u8, 67u8, 178u8, 249u8, 222u8, 96u8, 26u8, 239u8, 96u8, 201u8, 160u8, 230u8,
        181u8, 8u8, 131u8, 112u8, 175u8, 24u8, 119u8, 41u8, 88u8, 105u8, 47u8, 235u8, 131u8, 72u8,
        139u8, 19u8, 138u8, 23u8,
    ],
    vk_delta_g2: [
        3u8, 100u8, 152u8, 33u8, 192u8, 7u8, 122u8, 246u8, 4u8, 145u8, 186u8, 180u8, 33u8, 167u8,
        77u8, 199u8, 162u8, 215u8, 111u8, 171u8, 198u8, 184u8, 126u8, 56u8, 168u8, 67u8, 147u8,
        168u8, 189u8, 62u8, 45u8, 208u8, 2u8, 247u8, 216u8, 225u8, 183u8, 91u8, 3u8, 77u8, 170u8,
        164u8, 7u8, 73u8, 146u8, 246u8, 36u8, 75u8, 171u8, 127u8, 78u8, 162u8, 130u8, 195u8, 39u8,
        248u8, 22u8, 193u8, 128u8, 138u8, 46u8, 180u8, 90u8, 57u8, 45u8, 195u8, 2u8, 34u8, 161u8,
        90u8, 115u8, 124u8, 129u8, 247u8, 239u8, 40u8, 110u8, 62u8, 162u8, 204u8, 60u8, 61u8,
        109u8, 249u8, 22u8, 30u8, 163u8, 23u8, 146u8, 88u8, 127u8, 90u8, 119u8, 148u8, 193u8,
        253u8, 37u8, 168u8, 224u8, 129u8, 203u8, 47u8, 207u8, 5u8, 6u8, 183u8, 203u8, 120u8, 229u8,
        15u8, 75u8, 37u8, 119u8, 111u8, 154u8, 164u8, 180u8, 35u8, 231u8, 202u8, 184u8, 243u8,
        160u8, 161u8, 120u8, 124u8, 212u8, 222u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [53u8, 86u8, 74u8, 50u8, 63u8, 21u8, 71u8, 67u8, 245u8, 141u8, 113u8, 255u8, 64u8, 49u8, 93u8, 117u8, 4u8, 219u8, 245u8, 91u8, 228u8, 204u8, 96u8, 208u8, 96u8, 208u8, 190u8, 194u8, 191u8, 78u8, 184u8, 204u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_10ae8fb27308f111")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x0035564a323f154743f58d71ff40315d7504dbf55be4cc60d060d0bec2bf4eb8cc\x00=======END GROTH16 VK SETUP V1=======\x00";
