// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        20u8, 193u8, 133u8, 39u8, 122u8, 76u8, 42u8, 95u8, 233u8, 111u8, 37u8, 89u8, 60u8, 6u8,
        210u8, 57u8, 113u8, 34u8, 23u8, 126u8, 163u8, 73u8, 87u8, 78u8, 34u8, 236u8, 241u8, 224u8,
        213u8, 1u8, 114u8, 249u8, 42u8, 205u8, 230u8, 170u8, 10u8, 249u8, 131u8, 152u8, 18u8,
        238u8, 7u8, 249u8, 62u8, 59u8, 172u8, 79u8, 27u8, 36u8, 73u8, 53u8, 164u8, 33u8, 231u8,
        44u8, 82u8, 50u8, 255u8, 155u8, 246u8, 202u8, 138u8, 253u8,
    ],
    [
        30u8, 194u8, 185u8, 132u8, 129u8, 96u8, 15u8, 170u8, 63u8, 64u8, 204u8, 137u8, 34u8, 16u8,
        18u8, 41u8, 112u8, 182u8, 30u8, 0u8, 142u8, 64u8, 193u8, 88u8, 19u8, 154u8, 117u8, 79u8,
        48u8, 220u8, 152u8, 57u8, 43u8, 204u8, 20u8, 0u8, 156u8, 120u8, 223u8, 133u8, 233u8, 173u8,
        72u8, 108u8, 188u8, 49u8, 46u8, 172u8, 191u8, 75u8, 124u8, 194u8, 47u8, 205u8, 203u8,
        160u8, 112u8, 209u8, 63u8, 43u8, 185u8, 155u8, 130u8, 16u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        37u8, 32u8, 38u8, 190u8, 167u8, 182u8, 133u8, 112u8, 149u8, 106u8, 70u8, 221u8, 11u8, 43u8,
        20u8, 167u8, 75u8, 161u8, 187u8, 57u8, 45u8, 163u8, 184u8, 226u8, 187u8, 11u8, 211u8,
        151u8, 162u8, 141u8, 77u8, 96u8, 30u8, 104u8, 244u8, 6u8, 122u8, 228u8, 29u8, 132u8, 211u8,
        126u8, 175u8, 211u8, 77u8, 221u8, 91u8, 202u8, 214u8, 58u8, 202u8, 201u8, 221u8, 79u8,
        72u8, 126u8, 255u8, 228u8, 154u8, 229u8, 149u8, 5u8, 179u8, 215u8,
    ],
    vk_beta_g2: [
        19u8, 30u8, 184u8, 172u8, 99u8, 183u8, 13u8, 175u8, 91u8, 161u8, 111u8, 137u8, 234u8, 30u8,
        117u8, 25u8, 154u8, 172u8, 220u8, 163u8, 153u8, 150u8, 87u8, 188u8, 15u8, 168u8, 210u8,
        101u8, 195u8, 15u8, 22u8, 67u8, 32u8, 66u8, 114u8, 186u8, 249u8, 96u8, 108u8, 155u8, 111u8,
        40u8, 138u8, 145u8, 190u8, 236u8, 27u8, 28u8, 80u8, 109u8, 36u8, 9u8, 111u8, 240u8, 209u8,
        70u8, 59u8, 229u8, 103u8, 238u8, 12u8, 149u8, 237u8, 152u8, 5u8, 130u8, 160u8, 59u8, 97u8,
        90u8, 184u8, 91u8, 176u8, 200u8, 18u8, 246u8, 18u8, 224u8, 114u8, 142u8, 61u8, 191u8,
        115u8, 169u8, 214u8, 83u8, 25u8, 16u8, 97u8, 214u8, 168u8, 181u8, 0u8, 226u8, 164u8, 175u8,
        10u8, 89u8, 160u8, 41u8, 234u8, 52u8, 9u8, 55u8, 246u8, 51u8, 224u8, 60u8, 127u8, 107u8,
        145u8, 181u8, 197u8, 40u8, 208u8, 242u8, 174u8, 25u8, 41u8, 211u8, 221u8, 188u8, 183u8,
        85u8, 192u8, 2u8, 39u8, 207u8,
    ],
    vk_gamma_g2: [
        42u8, 128u8, 20u8, 219u8, 51u8, 91u8, 96u8, 199u8, 159u8, 103u8, 165u8, 214u8, 175u8, 93u8,
        198u8, 241u8, 188u8, 216u8, 127u8, 132u8, 162u8, 145u8, 62u8, 24u8, 206u8, 76u8, 50u8,
        243u8, 173u8, 44u8, 181u8, 6u8, 33u8, 49u8, 109u8, 0u8, 253u8, 31u8, 210u8, 212u8, 153u8,
        234u8, 207u8, 222u8, 11u8, 199u8, 25u8, 83u8, 203u8, 153u8, 6u8, 60u8, 59u8, 85u8, 89u8,
        92u8, 145u8, 4u8, 228u8, 223u8, 144u8, 173u8, 33u8, 230u8, 18u8, 122u8, 91u8, 5u8, 237u8,
        210u8, 81u8, 25u8, 83u8, 81u8, 154u8, 9u8, 205u8, 173u8, 249u8, 106u8, 163u8, 106u8, 39u8,
        42u8, 215u8, 30u8, 219u8, 64u8, 188u8, 165u8, 110u8, 27u8, 69u8, 162u8, 117u8, 178u8, 46u8,
        229u8, 3u8, 78u8, 152u8, 78u8, 228u8, 21u8, 170u8, 212u8, 200u8, 107u8, 191u8, 31u8, 41u8,
        112u8, 40u8, 83u8, 93u8, 225u8, 193u8, 130u8, 147u8, 198u8, 113u8, 23u8, 82u8, 203u8, 56u8,
        100u8, 26u8, 229u8,
    ],
    vk_delta_g2: [
        38u8, 66u8, 55u8, 23u8, 238u8, 197u8, 217u8, 98u8, 86u8, 99u8, 207u8, 158u8, 206u8, 184u8,
        150u8, 124u8, 100u8, 231u8, 233u8, 105u8, 97u8, 143u8, 108u8, 31u8, 66u8, 23u8, 89u8,
        165u8, 134u8, 127u8, 26u8, 12u8, 26u8, 229u8, 7u8, 234u8, 122u8, 222u8, 162u8, 185u8,
        176u8, 68u8, 20u8, 210u8, 139u8, 155u8, 211u8, 70u8, 234u8, 93u8, 250u8, 3u8, 42u8, 210u8,
        255u8, 22u8, 169u8, 25u8, 116u8, 32u8, 49u8, 164u8, 106u8, 71u8, 18u8, 112u8, 138u8, 1u8,
        244u8, 166u8, 213u8, 175u8, 82u8, 58u8, 130u8, 177u8, 142u8, 135u8, 213u8, 235u8, 179u8,
        48u8, 104u8, 61u8, 47u8, 198u8, 249u8, 158u8, 88u8, 208u8, 106u8, 151u8, 244u8, 206u8,
        76u8, 154u8, 30u8, 248u8, 120u8, 1u8, 195u8, 179u8, 68u8, 145u8, 255u8, 199u8, 161u8,
        253u8, 16u8, 41u8, 110u8, 15u8, 224u8, 185u8, 206u8, 156u8, 25u8, 255u8, 50u8, 66u8, 31u8,
        187u8, 56u8, 216u8, 95u8, 248u8, 245u8, 223u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [80u8, 18u8, 239u8, 217u8, 43u8, 253u8, 100u8, 55u8, 183u8, 155u8, 136u8, 140u8, 128u8, 47u8, 27u8, 187u8, 37u8, 226u8, 128u8, 69u8, 115u8, 77u8, 152u8, 154u8, 115u8, 87u8, 119u8, 250u8, 185u8, 196u8, 22u8, 109u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_96963c45e5ecd49a")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x005012efd92bfd6437b79b888c802f1bbb25e28045734d989a735777fab9c4166d\x00=======END GROTH16 VK SETUP V1=======\x00";
