// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        29u8, 45u8, 114u8, 99u8, 101u8, 210u8, 93u8, 121u8, 87u8, 112u8, 201u8, 55u8, 6u8, 216u8,
        154u8, 231u8, 21u8, 8u8, 3u8, 209u8, 43u8, 154u8, 37u8, 232u8, 4u8, 71u8, 96u8, 153u8,
        192u8, 164u8, 233u8, 51u8, 21u8, 101u8, 209u8, 82u8, 184u8, 86u8, 104u8, 44u8, 84u8, 20u8,
        82u8, 2u8, 149u8, 141u8, 38u8, 248u8, 218u8, 162u8, 23u8, 74u8, 205u8, 24u8, 98u8, 183u8,
        162u8, 61u8, 219u8, 187u8, 76u8, 242u8, 111u8, 223u8,
    ],
    [
        6u8, 79u8, 203u8, 224u8, 18u8, 119u8, 18u8, 220u8, 250u8, 240u8, 78u8, 50u8, 12u8, 196u8,
        66u8, 50u8, 47u8, 60u8, 164u8, 78u8, 176u8, 30u8, 76u8, 216u8, 33u8, 243u8, 120u8, 250u8,
        170u8, 225u8, 69u8, 196u8, 44u8, 191u8, 29u8, 146u8, 7u8, 246u8, 11u8, 1u8, 51u8, 170u8,
        126u8, 184u8, 168u8, 250u8, 117u8, 136u8, 232u8, 144u8, 222u8, 137u8, 168u8, 117u8, 95u8,
        215u8, 102u8, 63u8, 117u8, 146u8, 40u8, 247u8, 157u8, 186u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        38u8, 113u8, 133u8, 173u8, 26u8, 127u8, 32u8, 68u8, 175u8, 111u8, 90u8, 66u8, 24u8, 56u8,
        139u8, 99u8, 225u8, 146u8, 23u8, 10u8, 136u8, 253u8, 30u8, 149u8, 154u8, 118u8, 9u8, 74u8,
        9u8, 29u8, 66u8, 13u8, 31u8, 17u8, 69u8, 76u8, 156u8, 100u8, 31u8, 131u8, 189u8, 84u8,
        19u8, 22u8, 193u8, 9u8, 158u8, 148u8, 224u8, 81u8, 230u8, 44u8, 152u8, 213u8, 150u8, 206u8,
        80u8, 250u8, 114u8, 18u8, 170u8, 149u8, 144u8, 182u8,
    ],
    vk_beta_g2: [
        29u8, 15u8, 45u8, 160u8, 180u8, 87u8, 145u8, 253u8, 114u8, 172u8, 43u8, 157u8, 101u8, 92u8,
        228u8, 149u8, 199u8, 129u8, 53u8, 30u8, 189u8, 12u8, 101u8, 46u8, 173u8, 119u8, 238u8,
        163u8, 218u8, 69u8, 27u8, 7u8, 8u8, 184u8, 52u8, 4u8, 12u8, 57u8, 184u8, 128u8, 84u8, 15u8,
        18u8, 26u8, 117u8, 196u8, 100u8, 18u8, 33u8, 168u8, 42u8, 121u8, 186u8, 120u8, 101u8,
        231u8, 61u8, 147u8, 10u8, 70u8, 58u8, 101u8, 68u8, 67u8, 37u8, 170u8, 105u8, 42u8, 70u8,
        100u8, 224u8, 3u8, 38u8, 98u8, 0u8, 242u8, 30u8, 188u8, 247u8, 226u8, 79u8, 167u8, 87u8,
        42u8, 141u8, 169u8, 200u8, 63u8, 82u8, 125u8, 197u8, 145u8, 206u8, 128u8, 183u8, 62u8,
        20u8, 56u8, 81u8, 108u8, 129u8, 75u8, 233u8, 230u8, 146u8, 28u8, 3u8, 5u8, 102u8, 159u8,
        134u8, 134u8, 161u8, 150u8, 202u8, 53u8, 207u8, 210u8, 17u8, 200u8, 149u8, 13u8, 73u8,
        89u8, 247u8, 79u8, 53u8, 230u8,
    ],
    vk_gamma_g2: [
        35u8, 44u8, 89u8, 195u8, 243u8, 123u8, 194u8, 187u8, 41u8, 209u8, 26u8, 70u8, 99u8, 59u8,
        168u8, 162u8, 49u8, 253u8, 52u8, 202u8, 24u8, 145u8, 98u8, 73u8, 254u8, 66u8, 153u8, 94u8,
        100u8, 125u8, 179u8, 213u8, 8u8, 28u8, 3u8, 55u8, 137u8, 245u8, 146u8, 162u8, 255u8, 131u8,
        167u8, 107u8, 114u8, 184u8, 86u8, 137u8, 182u8, 39u8, 185u8, 148u8, 52u8, 19u8, 232u8, 0u8,
        24u8, 122u8, 181u8, 92u8, 236u8, 40u8, 75u8, 93u8, 22u8, 51u8, 12u8, 166u8, 27u8, 114u8,
        66u8, 149u8, 230u8, 159u8, 204u8, 62u8, 70u8, 56u8, 87u8, 252u8, 144u8, 243u8, 171u8, 14u8,
        3u8, 25u8, 245u8, 137u8, 197u8, 224u8, 65u8, 166u8, 23u8, 33u8, 167u8, 80u8, 31u8, 46u8,
        23u8, 98u8, 157u8, 124u8, 227u8, 114u8, 78u8, 61u8, 238u8, 22u8, 147u8, 171u8, 252u8,
        164u8, 89u8, 248u8, 167u8, 209u8, 241u8, 43u8, 205u8, 22u8, 223u8, 156u8, 186u8, 113u8,
        127u8, 21u8, 107u8, 137u8,
    ],
    vk_delta_g2: [
        40u8, 158u8, 119u8, 133u8, 134u8, 157u8, 221u8, 9u8, 178u8, 118u8, 194u8, 91u8, 123u8,
        75u8, 39u8, 144u8, 248u8, 46u8, 137u8, 101u8, 252u8, 190u8, 88u8, 212u8, 228u8, 223u8,
        120u8, 110u8, 140u8, 16u8, 56u8, 191u8, 21u8, 238u8, 50u8, 21u8, 156u8, 189u8, 86u8, 137u8,
        206u8, 221u8, 38u8, 212u8, 125u8, 144u8, 254u8, 87u8, 162u8, 57u8, 95u8, 224u8, 62u8, 75u8,
        154u8, 74u8, 118u8, 68u8, 206u8, 131u8, 76u8, 148u8, 77u8, 106u8, 44u8, 244u8, 200u8, 56u8,
        47u8, 65u8, 230u8, 118u8, 88u8, 134u8, 195u8, 7u8, 10u8, 229u8, 7u8, 6u8, 114u8, 91u8,
        11u8, 8u8, 234u8, 101u8, 146u8, 144u8, 29u8, 109u8, 213u8, 214u8, 120u8, 24u8, 40u8, 242u8,
        0u8, 234u8, 192u8, 133u8, 236u8, 104u8, 250u8, 89u8, 178u8, 30u8, 24u8, 123u8, 167u8,
        203u8, 119u8, 85u8, 13u8, 59u8, 135u8, 116u8, 53u8, 212u8, 93u8, 187u8, 243u8, 86u8, 148u8,
        139u8, 34u8, 155u8, 231u8, 126u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [227u8, 100u8, 189u8, 197u8, 144u8, 59u8, 161u8, 35u8, 31u8, 71u8, 100u8, 208u8, 180u8, 212u8, 12u8, 126u8, 39u8, 100u8, 182u8, 15u8, 200u8, 133u8, 136u8, 246u8, 93u8, 72u8, 221u8, 130u8, 156u8, 60u8, 117u8, 13u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_b7945834b7abe3d9")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00e364bdc5903ba1231f4764d0b4d40c7e2764b60fc88588f65d48dd829c3c750d\x00=======END GROTH16 VK SETUP V1=======\x00";
