// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        7u8, 65u8, 179u8, 13u8, 34u8, 162u8, 245u8, 154u8, 47u8, 44u8, 143u8, 91u8, 183u8, 138u8,
        148u8, 193u8, 131u8, 253u8, 214u8, 241u8, 71u8, 71u8, 118u8, 86u8, 13u8, 82u8, 95u8, 131u8,
        193u8, 42u8, 179u8, 66u8, 15u8, 136u8, 47u8, 7u8, 92u8, 99u8, 45u8, 247u8, 188u8, 60u8,
        147u8, 44u8, 219u8, 242u8, 171u8, 140u8, 99u8, 191u8, 195u8, 221u8, 201u8, 251u8, 181u8,
        57u8, 214u8, 8u8, 207u8, 247u8, 49u8, 29u8, 135u8, 212u8,
    ],
    [
        43u8, 225u8, 196u8, 133u8, 56u8, 111u8, 82u8, 81u8, 14u8, 141u8, 3u8, 180u8, 63u8, 242u8,
        41u8, 139u8, 235u8, 5u8, 168u8, 228u8, 51u8, 109u8, 28u8, 59u8, 121u8, 27u8, 111u8, 210u8,
        70u8, 26u8, 127u8, 58u8, 15u8, 205u8, 195u8, 146u8, 239u8, 14u8, 207u8, 24u8, 243u8, 170u8,
        37u8, 43u8, 48u8, 212u8, 226u8, 196u8, 252u8, 17u8, 83u8, 31u8, 182u8, 196u8, 150u8, 123u8,
        161u8, 5u8, 96u8, 54u8, 239u8, 144u8, 15u8, 138u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        18u8, 213u8, 69u8, 54u8, 254u8, 121u8, 86u8, 122u8, 250u8, 66u8, 216u8, 53u8, 126u8, 3u8,
        171u8, 153u8, 37u8, 137u8, 115u8, 36u8, 15u8, 104u8, 232u8, 197u8, 141u8, 151u8, 10u8,
        91u8, 116u8, 72u8, 204u8, 186u8, 18u8, 182u8, 146u8, 42u8, 172u8, 184u8, 84u8, 77u8, 54u8,
        36u8, 60u8, 152u8, 241u8, 127u8, 237u8, 137u8, 139u8, 122u8, 57u8, 56u8, 75u8, 45u8, 45u8,
        176u8, 68u8, 28u8, 92u8, 8u8, 133u8, 0u8, 187u8, 162u8,
    ],
    vk_beta_g2: [
        0u8, 240u8, 207u8, 234u8, 167u8, 116u8, 26u8, 252u8, 241u8, 181u8, 108u8, 228u8, 183u8,
        171u8, 206u8, 117u8, 31u8, 76u8, 198u8, 45u8, 11u8, 83u8, 10u8, 28u8, 43u8, 253u8, 113u8,
        61u8, 148u8, 0u8, 225u8, 127u8, 18u8, 172u8, 23u8, 159u8, 84u8, 125u8, 164u8, 80u8, 150u8,
        73u8, 71u8, 187u8, 252u8, 124u8, 255u8, 105u8, 19u8, 193u8, 167u8, 226u8, 38u8, 34u8,
        167u8, 230u8, 225u8, 187u8, 223u8, 183u8, 161u8, 207u8, 93u8, 231u8, 44u8, 125u8, 226u8,
        56u8, 97u8, 27u8, 193u8, 227u8, 101u8, 161u8, 60u8, 3u8, 80u8, 195u8, 249u8, 127u8, 111u8,
        252u8, 239u8, 63u8, 40u8, 92u8, 103u8, 194u8, 201u8, 12u8, 115u8, 144u8, 80u8, 108u8,
        121u8, 73u8, 36u8, 86u8, 207u8, 66u8, 129u8, 110u8, 81u8, 39u8, 178u8, 176u8, 3u8, 229u8,
        245u8, 90u8, 195u8, 142u8, 144u8, 26u8, 220u8, 23u8, 51u8, 112u8, 193u8, 95u8, 208u8,
        224u8, 67u8, 148u8, 222u8, 39u8, 16u8, 73u8,
    ],
    vk_gamma_g2: [
        19u8, 2u8, 226u8, 34u8, 42u8, 198u8, 24u8, 150u8, 0u8, 1u8, 115u8, 76u8, 66u8, 90u8, 228u8,
        46u8, 197u8, 207u8, 47u8, 191u8, 7u8, 242u8, 18u8, 113u8, 74u8, 231u8, 47u8, 129u8, 34u8,
        63u8, 133u8, 192u8, 33u8, 0u8, 117u8, 213u8, 168u8, 79u8, 13u8, 222u8, 20u8, 143u8, 203u8,
        33u8, 80u8, 246u8, 2u8, 56u8, 180u8, 26u8, 240u8, 85u8, 162u8, 65u8, 160u8, 105u8, 152u8,
        4u8, 28u8, 224u8, 38u8, 2u8, 123u8, 252u8, 45u8, 156u8, 218u8, 78u8, 153u8, 23u8, 112u8,
        199u8, 209u8, 188u8, 233u8, 135u8, 200u8, 12u8, 13u8, 238u8, 41u8, 243u8, 41u8, 142u8,
        237u8, 199u8, 108u8, 173u8, 8u8, 65u8, 75u8, 128u8, 9u8, 46u8, 63u8, 206u8, 10u8, 215u8,
        9u8, 121u8, 212u8, 71u8, 77u8, 33u8, 177u8, 182u8, 9u8, 203u8, 119u8, 197u8, 141u8, 241u8,
        201u8, 126u8, 4u8, 132u8, 26u8, 97u8, 124u8, 43u8, 133u8, 239u8, 154u8, 214u8, 60u8, 96u8,
        243u8, 147u8,
    ],
    vk_delta_g2: [
        8u8, 112u8, 120u8, 184u8, 236u8, 32u8, 194u8, 1u8, 30u8, 135u8, 179u8, 193u8, 140u8, 237u8,
        245u8, 165u8, 81u8, 59u8, 20u8, 215u8, 134u8, 195u8, 171u8, 102u8, 11u8, 73u8, 246u8, 71u8,
        170u8, 203u8, 109u8, 189u8, 8u8, 67u8, 215u8, 160u8, 107u8, 34u8, 73u8, 254u8, 18u8, 35u8,
        253u8, 220u8, 130u8, 64u8, 11u8, 33u8, 233u8, 217u8, 254u8, 158u8, 128u8, 55u8, 125u8,
        216u8, 76u8, 78u8, 57u8, 101u8, 61u8, 17u8, 89u8, 91u8, 48u8, 66u8, 138u8, 42u8, 56u8,
        37u8, 66u8, 173u8, 221u8, 198u8, 39u8, 55u8, 14u8, 85u8, 56u8, 29u8, 84u8, 186u8, 192u8,
        20u8, 143u8, 160u8, 148u8, 96u8, 242u8, 201u8, 152u8, 99u8, 63u8, 234u8, 45u8, 123u8, 32u8,
        188u8, 99u8, 65u8, 239u8, 253u8, 70u8, 160u8, 52u8, 139u8, 235u8, 27u8, 112u8, 44u8, 255u8,
        30u8, 27u8, 249u8, 166u8, 98u8, 92u8, 167u8, 35u8, 204u8, 215u8, 165u8, 65u8, 209u8, 116u8,
        125u8, 109u8, 67u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [117u8, 246u8, 245u8, 232u8, 76u8, 251u8, 135u8, 99u8, 141u8, 20u8, 183u8, 164u8, 58u8, 39u8, 121u8, 246u8, 204u8, 240u8, 84u8, 187u8, 117u8, 150u8, 74u8, 147u8, 55u8, 94u8, 18u8, 86u8, 249u8, 255u8, 126u8, 41u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_4d9d8d3778f0bbcd")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x0075f6f5e84cfb87638d14b7a43a2779f6ccf054bb75964a93375e1256f9ff7e29\x00=======END GROTH16 VK SETUP V1=======\x00";
