// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        31u8, 157u8, 119u8, 232u8, 239u8, 146u8, 237u8, 209u8, 133u8, 154u8, 151u8, 254u8, 79u8,
        77u8, 80u8, 47u8, 131u8, 137u8, 96u8, 148u8, 192u8, 154u8, 9u8, 255u8, 52u8, 217u8, 102u8,
        10u8, 81u8, 137u8, 120u8, 120u8, 41u8, 8u8, 63u8, 10u8, 101u8, 240u8, 120u8, 120u8, 231u8,
        201u8, 144u8, 239u8, 223u8, 214u8, 148u8, 55u8, 199u8, 150u8, 253u8, 212u8, 116u8, 215u8,
        2u8, 129u8, 79u8, 123u8, 236u8, 51u8, 142u8, 176u8, 45u8, 112u8,
    ],
    [
        36u8, 12u8, 55u8, 3u8, 81u8, 250u8, 219u8, 20u8, 94u8, 107u8, 119u8, 35u8, 23u8, 175u8,
        179u8, 225u8, 39u8, 3u8, 58u8, 183u8, 127u8, 96u8, 223u8, 26u8, 248u8, 16u8, 123u8, 64u8,
        195u8, 73u8, 139u8, 117u8, 31u8, 128u8, 48u8, 238u8, 27u8, 25u8, 218u8, 8u8, 63u8, 41u8,
        110u8, 235u8, 163u8, 15u8, 199u8, 132u8, 156u8, 16u8, 41u8, 22u8, 129u8, 37u8, 121u8,
        163u8, 107u8, 232u8, 42u8, 228u8, 68u8, 173u8, 185u8, 110u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        42u8, 8u8, 63u8, 5u8, 126u8, 193u8, 252u8, 20u8, 75u8, 43u8, 29u8, 241u8, 207u8, 167u8,
        88u8, 250u8, 203u8, 40u8, 65u8, 100u8, 54u8, 162u8, 62u8, 165u8, 1u8, 148u8, 130u8, 172u8,
        67u8, 22u8, 59u8, 171u8, 16u8, 131u8, 105u8, 32u8, 12u8, 166u8, 132u8, 205u8, 23u8, 237u8,
        165u8, 229u8, 93u8, 76u8, 8u8, 45u8, 55u8, 129u8, 58u8, 47u8, 172u8, 89u8, 188u8, 98u8,
        54u8, 196u8, 54u8, 128u8, 77u8, 124u8, 126u8, 229u8,
    ],
    vk_beta_g2: [
        1u8, 199u8, 171u8, 29u8, 49u8, 154u8, 98u8, 148u8, 2u8, 85u8, 179u8, 216u8, 187u8, 193u8,
        246u8, 65u8, 42u8, 180u8, 28u8, 250u8, 57u8, 179u8, 185u8, 111u8, 221u8, 70u8, 28u8, 6u8,
        137u8, 18u8, 80u8, 71u8, 9u8, 235u8, 66u8, 163u8, 132u8, 21u8, 64u8, 39u8, 132u8, 93u8,
        237u8, 78u8, 115u8, 178u8, 219u8, 209u8, 99u8, 250u8, 68u8, 144u8, 48u8, 104u8, 36u8, 91u8,
        233u8, 120u8, 202u8, 170u8, 11u8, 197u8, 46u8, 37u8, 29u8, 185u8, 159u8, 93u8, 211u8, 41u8,
        97u8, 70u8, 178u8, 166u8, 14u8, 186u8, 72u8, 149u8, 200u8, 247u8, 152u8, 159u8, 38u8, 74u8,
        106u8, 71u8, 97u8, 211u8, 9u8, 133u8, 67u8, 209u8, 73u8, 90u8, 219u8, 207u8, 6u8, 234u8,
        254u8, 34u8, 45u8, 227u8, 52u8, 160u8, 165u8, 173u8, 225u8, 97u8, 199u8, 89u8, 110u8,
        212u8, 145u8, 174u8, 243u8, 136u8, 185u8, 38u8, 93u8, 71u8, 206u8, 211u8, 96u8, 229u8,
        239u8, 39u8, 63u8, 31u8,
    ],
    vk_gamma_g2: [
        11u8, 220u8, 97u8, 53u8, 249u8, 29u8, 143u8, 87u8, 213u8, 140u8, 100u8, 129u8, 48u8, 31u8,
        159u8, 214u8, 17u8, 196u8, 227u8, 44u8, 152u8, 125u8, 217u8, 48u8, 167u8, 21u8, 60u8,
        155u8, 176u8, 243u8, 115u8, 42u8, 31u8, 28u8, 16u8, 227u8, 106u8, 157u8, 66u8, 223u8,
        228u8, 37u8, 179u8, 105u8, 199u8, 90u8, 118u8, 62u8, 15u8, 52u8, 98u8, 45u8, 13u8, 21u8,
        246u8, 83u8, 222u8, 51u8, 141u8, 128u8, 51u8, 108u8, 181u8, 102u8, 5u8, 90u8, 139u8, 143u8,
        213u8, 80u8, 216u8, 229u8, 230u8, 227u8, 234u8, 5u8, 32u8, 5u8, 97u8, 17u8, 59u8, 227u8,
        151u8, 230u8, 91u8, 75u8, 4u8, 80u8, 225u8, 95u8, 164u8, 29u8, 203u8, 195u8, 20u8, 135u8,
        15u8, 206u8, 21u8, 181u8, 8u8, 30u8, 166u8, 108u8, 40u8, 79u8, 64u8, 0u8, 77u8, 211u8,
        19u8, 135u8, 226u8, 93u8, 66u8, 153u8, 79u8, 183u8, 135u8, 8u8, 144u8, 174u8, 159u8, 151u8,
        210u8, 203u8, 109u8, 185u8,
    ],
    vk_delta_g2: [
        28u8, 167u8, 18u8, 107u8, 209u8, 168u8, 46u8, 231u8, 109u8, 103u8, 117u8, 4u8, 57u8, 54u8,
        35u8, 120u8, 211u8, 213u8, 155u8, 86u8, 93u8, 105u8, 5u8, 179u8, 9u8, 162u8, 118u8, 127u8,
        114u8, 228u8, 50u8, 145u8, 42u8, 81u8, 186u8, 233u8, 103u8, 159u8, 64u8, 238u8, 73u8,
        241u8, 194u8, 238u8, 255u8, 30u8, 226u8, 230u8, 79u8, 89u8, 121u8, 230u8, 198u8, 176u8,
        72u8, 191u8, 125u8, 11u8, 15u8, 30u8, 248u8, 108u8, 104u8, 103u8, 35u8, 202u8, 219u8,
        224u8, 159u8, 72u8, 7u8, 175u8, 17u8, 156u8, 198u8, 187u8, 126u8, 154u8, 32u8, 26u8, 138u8,
        42u8, 245u8, 12u8, 28u8, 53u8, 216u8, 15u8, 208u8, 89u8, 136u8, 37u8, 155u8, 94u8, 213u8,
        121u8, 46u8, 253u8, 116u8, 96u8, 132u8, 105u8, 55u8, 162u8, 105u8, 194u8, 124u8, 155u8,
        111u8, 31u8, 125u8, 37u8, 129u8, 249u8, 253u8, 242u8, 203u8, 76u8, 231u8, 36u8, 16u8,
        154u8, 207u8, 33u8, 35u8, 180u8, 75u8, 182u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [220u8, 143u8, 245u8, 105u8, 189u8, 201u8, 103u8, 142u8, 243u8, 138u8, 237u8, 237u8, 91u8, 82u8, 193u8, 36u8, 88u8, 138u8, 28u8, 93u8, 52u8, 107u8, 6u8, 104u8, 29u8, 255u8, 190u8, 242u8, 81u8, 58u8, 65u8, 111u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_187ef0e863f52a87")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00dc8ff569bdc9678ef38aeded5b52c124588a1c5d346b06681dffbef2513a416f\x00=======END GROTH16 VK SETUP V1=======\x00";
