// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        17u8, 134u8, 247u8, 9u8, 125u8, 113u8, 25u8, 240u8, 200u8, 229u8, 146u8, 128u8, 159u8,
        69u8, 77u8, 81u8, 2u8, 96u8, 81u8, 228u8, 79u8, 181u8, 57u8, 72u8, 207u8, 223u8, 218u8,
        43u8, 119u8, 80u8, 67u8, 29u8, 28u8, 31u8, 78u8, 219u8, 226u8, 131u8, 43u8, 60u8, 167u8,
        98u8, 213u8, 224u8, 18u8, 117u8, 44u8, 167u8, 250u8, 150u8, 64u8, 128u8, 150u8, 78u8, 94u8,
        15u8, 117u8, 171u8, 47u8, 243u8, 94u8, 95u8, 137u8, 17u8,
    ],
    [
        27u8, 67u8, 244u8, 159u8, 72u8, 93u8, 199u8, 82u8, 211u8, 73u8, 196u8, 196u8, 155u8, 204u8,
        239u8, 201u8, 9u8, 92u8, 230u8, 25u8, 238u8, 18u8, 251u8, 162u8, 184u8, 199u8, 159u8,
        201u8, 79u8, 88u8, 124u8, 111u8, 17u8, 160u8, 150u8, 223u8, 253u8, 32u8, 64u8, 42u8, 83u8,
        251u8, 93u8, 182u8, 81u8, 179u8, 212u8, 252u8, 161u8, 115u8, 108u8, 160u8, 119u8, 64u8,
        178u8, 253u8, 29u8, 92u8, 104u8, 22u8, 129u8, 52u8, 13u8, 163u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        17u8, 53u8, 161u8, 32u8, 237u8, 119u8, 27u8, 47u8, 92u8, 116u8, 214u8, 199u8, 56u8, 46u8,
        71u8, 75u8, 102u8, 171u8, 107u8, 113u8, 84u8, 145u8, 148u8, 48u8, 186u8, 65u8, 42u8, 157u8,
        13u8, 104u8, 165u8, 198u8, 33u8, 61u8, 226u8, 170u8, 124u8, 144u8, 30u8, 138u8, 103u8,
        55u8, 186u8, 53u8, 75u8, 113u8, 140u8, 115u8, 199u8, 171u8, 60u8, 152u8, 104u8, 11u8,
        160u8, 46u8, 80u8, 85u8, 123u8, 57u8, 149u8, 134u8, 21u8, 212u8,
    ],
    vk_beta_g2: [
        33u8, 177u8, 185u8, 245u8, 88u8, 208u8, 153u8, 186u8, 59u8, 11u8, 138u8, 137u8, 216u8,
        143u8, 228u8, 134u8, 217u8, 134u8, 29u8, 185u8, 208u8, 212u8, 91u8, 242u8, 101u8, 99u8,
        131u8, 39u8, 163u8, 247u8, 125u8, 116u8, 18u8, 255u8, 107u8, 218u8, 198u8, 253u8, 63u8,
        3u8, 6u8, 148u8, 235u8, 106u8, 220u8, 246u8, 40u8, 129u8, 111u8, 177u8, 39u8, 76u8, 106u8,
        231u8, 169u8, 166u8, 31u8, 231u8, 198u8, 49u8, 173u8, 162u8, 147u8, 37u8, 11u8, 97u8,
        108u8, 168u8, 100u8, 105u8, 22u8, 253u8, 86u8, 144u8, 132u8, 188u8, 52u8, 32u8, 171u8,
        107u8, 40u8, 247u8, 46u8, 140u8, 60u8, 12u8, 174u8, 55u8, 127u8, 12u8, 159u8, 215u8, 49u8,
        60u8, 144u8, 195u8, 31u8, 206u8, 18u8, 53u8, 219u8, 246u8, 79u8, 99u8, 37u8, 125u8, 117u8,
        220u8, 228u8, 204u8, 65u8, 96u8, 160u8, 145u8, 86u8, 156u8, 103u8, 14u8, 83u8, 30u8, 33u8,
        122u8, 193u8, 189u8, 133u8, 103u8, 17u8, 216u8,
    ],
    vk_gamma_g2: [
        13u8, 254u8, 168u8, 190u8, 137u8, 51u8, 142u8, 97u8, 53u8, 125u8, 247u8, 70u8, 209u8, 60u8,
        54u8, 183u8, 204u8, 240u8, 18u8, 77u8, 201u8, 45u8, 13u8, 233u8, 191u8, 60u8, 86u8, 5u8,
        31u8, 62u8, 48u8, 237u8, 19u8, 184u8, 8u8, 229u8, 25u8, 152u8, 60u8, 239u8, 99u8, 80u8,
        160u8, 147u8, 127u8, 94u8, 146u8, 118u8, 4u8, 105u8, 204u8, 95u8, 102u8, 81u8, 104u8, 36u8,
        137u8, 131u8, 147u8, 117u8, 91u8, 222u8, 97u8, 93u8, 18u8, 229u8, 204u8, 42u8, 58u8, 215u8,
        207u8, 128u8, 255u8, 8u8, 241u8, 28u8, 99u8, 146u8, 126u8, 81u8, 89u8, 94u8, 54u8, 211u8,
        219u8, 95u8, 122u8, 57u8, 253u8, 51u8, 111u8, 16u8, 180u8, 119u8, 69u8, 151u8, 37u8, 127u8,
        158u8, 224u8, 210u8, 148u8, 99u8, 163u8, 160u8, 251u8, 134u8, 189u8, 126u8, 218u8, 180u8,
        102u8, 60u8, 233u8, 191u8, 14u8, 195u8, 82u8, 102u8, 254u8, 15u8, 70u8, 160u8, 215u8,
        242u8, 15u8, 252u8, 219u8,
    ],
    vk_delta_g2: [
        33u8, 20u8, 216u8, 48u8, 43u8, 211u8, 92u8, 126u8, 113u8, 47u8, 238u8, 138u8, 90u8, 245u8,
        249u8, 133u8, 246u8, 41u8, 165u8, 228u8, 101u8, 255u8, 246u8, 104u8, 145u8, 250u8, 6u8,
        247u8, 138u8, 89u8, 165u8, 15u8, 43u8, 217u8, 104u8, 75u8, 115u8, 166u8, 89u8, 30u8, 210u8,
        124u8, 154u8, 220u8, 189u8, 171u8, 238u8, 59u8, 66u8, 197u8, 180u8, 195u8, 150u8, 196u8,
        227u8, 12u8, 217u8, 145u8, 148u8, 186u8, 150u8, 38u8, 249u8, 6u8, 30u8, 139u8, 96u8, 31u8,
        189u8, 30u8, 252u8, 107u8, 251u8, 19u8, 215u8, 47u8, 57u8, 135u8, 251u8, 141u8, 94u8,
        172u8, 43u8, 195u8, 22u8, 232u8, 25u8, 23u8, 32u8, 192u8, 120u8, 243u8, 74u8, 93u8, 59u8,
        202u8, 2u8, 215u8, 136u8, 207u8, 151u8, 1u8, 144u8, 2u8, 89u8, 98u8, 140u8, 145u8, 73u8,
        21u8, 99u8, 209u8, 155u8, 212u8, 240u8, 146u8, 248u8, 48u8, 152u8, 238u8, 63u8, 84u8, 4u8,
        193u8, 19u8, 50u8, 142u8, 217u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [185u8, 132u8, 33u8, 20u8, 128u8, 160u8, 84u8, 126u8, 195u8, 134u8, 38u8, 252u8, 209u8, 240u8, 159u8, 159u8, 222u8, 14u8, 217u8, 165u8, 214u8, 26u8, 98u8, 179u8, 243u8, 136u8, 4u8, 67u8, 84u8, 11u8, 223u8, 36u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_5cd30f3cc5899561")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00b984211480a0547ec38626fcd1f09f9fde0ed9a5d61a62b3f3880443540bdf24\x00=======END GROTH16 VK SETUP V1=======\x00";
