// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        24u8, 41u8, 201u8, 144u8, 195u8, 201u8, 201u8, 235u8, 111u8, 246u8, 86u8, 152u8, 252u8,
        19u8, 169u8, 174u8, 173u8, 198u8, 44u8, 90u8, 6u8, 71u8, 10u8, 83u8, 74u8, 130u8, 204u8,
        155u8, 43u8, 64u8, 113u8, 99u8, 11u8, 84u8, 209u8, 49u8, 17u8, 174u8, 251u8, 117u8, 249u8,
        236u8, 110u8, 28u8, 115u8, 220u8, 219u8, 32u8, 61u8, 138u8, 180u8, 193u8, 201u8, 53u8,
        11u8, 91u8, 172u8, 251u8, 119u8, 98u8, 211u8, 12u8, 99u8, 210u8,
    ],
    [
        35u8, 243u8, 130u8, 194u8, 167u8, 139u8, 181u8, 10u8, 108u8, 90u8, 176u8, 158u8, 67u8,
        246u8, 77u8, 149u8, 157u8, 68u8, 196u8, 156u8, 63u8, 163u8, 73u8, 1u8, 235u8, 206u8, 64u8,
        59u8, 205u8, 228u8, 230u8, 75u8, 20u8, 26u8, 196u8, 135u8, 174u8, 184u8, 54u8, 227u8,
        141u8, 34u8, 27u8, 239u8, 18u8, 107u8, 145u8, 178u8, 216u8, 229u8, 152u8, 46u8, 146u8,
        197u8, 112u8, 157u8, 151u8, 139u8, 107u8, 172u8, 200u8, 57u8, 5u8, 204u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        12u8, 232u8, 247u8, 185u8, 197u8, 28u8, 224u8, 170u8, 93u8, 164u8, 128u8, 104u8, 31u8,
        28u8, 247u8, 238u8, 91u8, 37u8, 210u8, 36u8, 144u8, 76u8, 77u8, 233u8, 168u8, 54u8, 223u8,
        198u8, 203u8, 49u8, 203u8, 159u8, 23u8, 106u8, 249u8, 71u8, 60u8, 255u8, 226u8, 199u8,
        143u8, 155u8, 126u8, 148u8, 236u8, 182u8, 86u8, 214u8, 67u8, 195u8, 166u8, 245u8, 215u8,
        85u8, 115u8, 39u8, 72u8, 195u8, 126u8, 184u8, 25u8, 180u8, 221u8, 87u8,
    ],
    vk_beta_g2: [
        46u8, 42u8, 78u8, 22u8, 66u8, 204u8, 154u8, 120u8, 71u8, 84u8, 128u8, 150u8, 190u8, 251u8,
        26u8, 32u8, 111u8, 79u8, 21u8, 4u8, 14u8, 163u8, 199u8, 216u8, 51u8, 44u8, 16u8, 27u8,
        11u8, 211u8, 54u8, 234u8, 40u8, 210u8, 45u8, 199u8, 156u8, 171u8, 149u8, 84u8, 126u8,
        119u8, 121u8, 147u8, 82u8, 32u8, 197u8, 188u8, 247u8, 206u8, 222u8, 149u8, 128u8, 180u8,
        4u8, 226u8, 82u8, 67u8, 84u8, 28u8, 201u8, 98u8, 120u8, 168u8, 14u8, 142u8, 203u8, 143u8,
        28u8, 3u8, 152u8, 136u8, 138u8, 40u8, 3u8, 146u8, 191u8, 85u8, 144u8, 9u8, 42u8, 221u8,
        169u8, 114u8, 48u8, 175u8, 158u8, 194u8, 137u8, 71u8, 97u8, 111u8, 99u8, 120u8, 117u8,
        107u8, 26u8, 37u8, 36u8, 57u8, 103u8, 63u8, 143u8, 85u8, 166u8, 250u8, 130u8, 173u8, 254u8,
        24u8, 157u8, 50u8, 115u8, 143u8, 14u8, 245u8, 108u8, 151u8, 60u8, 117u8, 28u8, 93u8, 223u8,
        83u8, 44u8, 205u8, 9u8, 32u8,
    ],
    vk_gamma_g2: [
        38u8, 141u8, 197u8, 225u8, 46u8, 233u8, 193u8, 60u8, 231u8, 110u8, 42u8, 23u8, 214u8, 24u8,
        28u8, 172u8, 229u8, 76u8, 238u8, 138u8, 11u8, 23u8, 94u8, 22u8, 211u8, 212u8, 138u8, 236u8,
        6u8, 94u8, 55u8, 73u8, 40u8, 86u8, 55u8, 208u8, 184u8, 49u8, 153u8, 167u8, 224u8, 40u8,
        32u8, 150u8, 191u8, 183u8, 142u8, 107u8, 122u8, 4u8, 225u8, 130u8, 229u8, 246u8, 171u8,
        38u8, 177u8, 23u8, 211u8, 109u8, 192u8, 178u8, 253u8, 56u8, 23u8, 24u8, 13u8, 70u8, 56u8,
        135u8, 74u8, 254u8, 100u8, 162u8, 77u8, 62u8, 250u8, 251u8, 224u8, 251u8, 128u8, 208u8,
        38u8, 5u8, 177u8, 68u8, 201u8, 112u8, 19u8, 131u8, 189u8, 205u8, 107u8, 199u8, 18u8, 37u8,
        8u8, 135u8, 17u8, 163u8, 209u8, 164u8, 110u8, 207u8, 38u8, 96u8, 104u8, 172u8, 104u8,
        166u8, 198u8, 64u8, 123u8, 87u8, 114u8, 35u8, 188u8, 132u8, 213u8, 145u8, 53u8, 234u8,
        66u8, 16u8, 108u8, 241u8, 209u8, 16u8,
    ],
    vk_delta_g2: [
        44u8, 245u8, 150u8, 114u8, 161u8, 60u8, 130u8, 221u8, 131u8, 242u8, 23u8, 95u8, 111u8,
        231u8, 22u8, 85u8, 129u8, 161u8, 11u8, 82u8, 82u8, 14u8, 233u8, 199u8, 252u8, 244u8, 105u8,
        239u8, 89u8, 238u8, 174u8, 6u8, 46u8, 241u8, 59u8, 56u8, 10u8, 51u8, 47u8, 102u8, 133u8,
        89u8, 251u8, 185u8, 49u8, 109u8, 179u8, 136u8, 203u8, 49u8, 1u8, 83u8, 160u8, 213u8, 136u8,
        170u8, 181u8, 201u8, 238u8, 62u8, 193u8, 220u8, 228u8, 28u8, 12u8, 1u8, 61u8, 137u8, 130u8,
        30u8, 231u8, 92u8, 219u8, 192u8, 88u8, 173u8, 53u8, 222u8, 218u8, 0u8, 138u8, 151u8, 241u8,
        93u8, 44u8, 236u8, 255u8, 88u8, 0u8, 231u8, 216u8, 48u8, 185u8, 11u8, 238u8, 94u8, 27u8,
        227u8, 201u8, 22u8, 209u8, 128u8, 105u8, 208u8, 205u8, 176u8, 55u8, 255u8, 12u8, 111u8,
        145u8, 246u8, 156u8, 230u8, 80u8, 144u8, 43u8, 161u8, 94u8, 35u8, 121u8, 14u8, 31u8, 18u8,
        133u8, 132u8, 86u8, 114u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [86u8, 4u8, 44u8, 214u8, 75u8, 184u8, 206u8, 201u8, 116u8, 247u8, 226u8, 180u8, 182u8, 74u8, 63u8, 123u8, 238u8, 245u8, 8u8, 55u8, 88u8, 228u8, 111u8, 57u8, 109u8, 85u8, 67u8, 180u8, 191u8, 202u8, 99u8, 89u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_cc40be9d7365d16c")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x0056042cd64bb8cec974f7e2b4b64a3f7beef5083758e46f396d5543b4bfca6359\x00=======END GROTH16 VK SETUP V1=======\x00";
