// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        0u8, 55u8, 183u8, 16u8, 194u8, 1u8, 94u8, 84u8, 62u8, 52u8, 209u8, 145u8, 33u8, 67u8,
        223u8, 15u8, 203u8, 212u8, 180u8, 220u8, 219u8, 144u8, 70u8, 118u8, 12u8, 32u8, 225u8,
        179u8, 238u8, 70u8, 178u8, 183u8, 31u8, 17u8, 28u8, 212u8, 126u8, 124u8, 100u8, 226u8,
        241u8, 115u8, 90u8, 52u8, 202u8, 118u8, 127u8, 152u8, 52u8, 115u8, 241u8, 195u8, 248u8,
        207u8, 204u8, 225u8, 119u8, 26u8, 13u8, 64u8, 229u8, 49u8, 212u8, 101u8,
    ],
    [
        17u8, 196u8, 24u8, 137u8, 206u8, 115u8, 16u8, 23u8, 135u8, 24u8, 134u8, 245u8, 115u8,
        124u8, 44u8, 226u8, 71u8, 243u8, 164u8, 34u8, 187u8, 193u8, 232u8, 217u8, 146u8, 145u8,
        228u8, 220u8, 130u8, 134u8, 97u8, 120u8, 9u8, 198u8, 239u8, 80u8, 93u8, 229u8, 146u8,
        237u8, 40u8, 14u8, 254u8, 77u8, 197u8, 11u8, 96u8, 83u8, 178u8, 250u8, 40u8, 68u8, 247u8,
        186u8, 115u8, 63u8, 49u8, 35u8, 187u8, 77u8, 93u8, 248u8, 87u8, 99u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        12u8, 216u8, 75u8, 106u8, 22u8, 107u8, 137u8, 48u8, 3u8, 62u8, 207u8, 199u8, 90u8, 93u8,
        146u8, 53u8, 7u8, 21u8, 237u8, 38u8, 241u8, 39u8, 175u8, 133u8, 219u8, 124u8, 244u8, 210u8,
        246u8, 125u8, 105u8, 159u8, 5u8, 84u8, 83u8, 80u8, 81u8, 210u8, 69u8, 214u8, 171u8, 225u8,
        95u8, 33u8, 226u8, 130u8, 231u8, 129u8, 192u8, 62u8, 139u8, 78u8, 130u8, 139u8, 97u8,
        116u8, 168u8, 128u8, 162u8, 89u8, 65u8, 29u8, 115u8, 148u8,
    ],
    vk_beta_g2: [
        35u8, 242u8, 247u8, 30u8, 239u8, 139u8, 8u8, 20u8, 202u8, 207u8, 187u8, 180u8, 112u8,
        201u8, 185u8, 60u8, 196u8, 7u8, 236u8, 68u8, 160u8, 121u8, 242u8, 18u8, 178u8, 213u8, 5u8,
        157u8, 198u8, 56u8, 13u8, 216u8, 20u8, 154u8, 182u8, 57u8, 14u8, 162u8, 106u8, 251u8,
        249u8, 27u8, 247u8, 114u8, 169u8, 170u8, 207u8, 106u8, 196u8, 238u8, 253u8, 7u8, 98u8,
        147u8, 20u8, 127u8, 28u8, 8u8, 31u8, 3u8, 207u8, 56u8, 40u8, 93u8, 26u8, 15u8, 176u8, 31u8,
        229u8, 76u8, 98u8, 100u8, 115u8, 213u8, 193u8, 45u8, 123u8, 17u8, 4u8, 58u8, 139u8, 64u8,
        95u8, 48u8, 224u8, 192u8, 205u8, 16u8, 222u8, 11u8, 240u8, 131u8, 219u8, 105u8, 188u8,
        235u8, 42u8, 169u8, 110u8, 120u8, 242u8, 159u8, 111u8, 35u8, 215u8, 215u8, 220u8, 72u8,
        96u8, 46u8, 241u8, 46u8, 68u8, 219u8, 202u8, 88u8, 204u8, 44u8, 194u8, 93u8, 0u8, 174u8,
        59u8, 120u8, 212u8, 146u8, 126u8, 230u8,
    ],
    vk_gamma_g2: [
        26u8, 111u8, 129u8, 216u8, 160u8, 14u8, 77u8, 136u8, 250u8, 158u8, 137u8, 129u8, 40u8,
        198u8, 88u8, 178u8, 97u8, 41u8, 132u8, 62u8, 50u8, 238u8, 250u8, 159u8, 31u8, 78u8, 199u8,
        128u8, 225u8, 11u8, 183u8, 192u8, 22u8, 172u8, 60u8, 10u8, 215u8, 156u8, 166u8, 223u8,
        38u8, 244u8, 201u8, 181u8, 48u8, 211u8, 7u8, 137u8, 190u8, 83u8, 187u8, 70u8, 30u8, 166u8,
        121u8, 19u8, 90u8, 62u8, 170u8, 48u8, 30u8, 194u8, 199u8, 108u8, 19u8, 24u8, 31u8, 166u8,
        250u8, 204u8, 185u8, 83u8, 205u8, 58u8, 120u8, 181u8, 220u8, 117u8, 50u8, 80u8, 56u8,
        133u8, 89u8, 45u8, 148u8, 100u8, 10u8, 234u8, 250u8, 245u8, 149u8, 147u8, 163u8, 187u8,
        115u8, 46u8, 45u8, 35u8, 9u8, 105u8, 139u8, 114u8, 161u8, 164u8, 204u8, 241u8, 100u8, 40u8,
        160u8, 118u8, 101u8, 107u8, 190u8, 60u8, 207u8, 41u8, 164u8, 48u8, 245u8, 124u8, 58u8,
        174u8, 169u8, 124u8, 201u8, 34u8, 173u8, 83u8,
    ],
    vk_delta_g2: [
        12u8, 8u8, 21u8, 159u8, 90u8, 154u8, 234u8, 154u8, 48u8, 101u8, 85u8, 131u8, 176u8, 25u8,
        94u8, 244u8, 67u8, 186u8, 113u8, 155u8, 231u8, 54u8, 90u8, 184u8, 59u8, 131u8, 189u8,
        245u8, 59u8, 58u8, 18u8, 35u8, 46u8, 104u8, 139u8, 60u8, 66u8, 82u8, 235u8, 72u8, 62u8,
        186u8, 211u8, 72u8, 91u8, 248u8, 215u8, 58u8, 202u8, 6u8, 80u8, 212u8, 228u8, 125u8, 77u8,
        161u8, 43u8, 47u8, 97u8, 243u8, 209u8, 142u8, 208u8, 76u8, 43u8, 245u8, 75u8, 233u8, 33u8,
        176u8, 103u8, 76u8, 141u8, 57u8, 96u8, 229u8, 101u8, 37u8, 38u8, 81u8, 116u8, 208u8, 129u8,
        196u8, 203u8, 219u8, 211u8, 48u8, 169u8, 157u8, 54u8, 24u8, 192u8, 82u8, 180u8, 246u8, 0u8,
        195u8, 47u8, 0u8, 53u8, 28u8, 62u8, 13u8, 124u8, 71u8, 18u8, 120u8, 22u8, 187u8, 33u8,
        121u8, 190u8, 150u8, 105u8, 84u8, 252u8, 73u8, 204u8, 216u8, 121u8, 178u8, 115u8, 46u8,
        60u8, 131u8, 143u8, 134u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [133u8, 21u8, 254u8, 52u8, 124u8, 212u8, 28u8, 213u8, 66u8, 139u8, 31u8, 100u8, 101u8, 55u8, 71u8, 53u8, 56u8, 72u8, 249u8, 150u8, 226u8, 180u8, 76u8, 203u8, 147u8, 253u8, 183u8, 146u8, 18u8, 70u8, 225u8, 124u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_926deb24cf318c6f")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x008515fe347cd41cd5428b1f64653747353848f996e2b44ccb93fdb7921246e17c\x00=======END GROTH16 VK SETUP V1=======\x00";
