// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        32u8, 54u8, 211u8, 12u8, 136u8, 81u8, 93u8, 211u8, 25u8, 252u8, 247u8, 23u8, 55u8, 233u8,
        72u8, 41u8, 235u8, 64u8, 36u8, 175u8, 2u8, 145u8, 45u8, 234u8, 103u8, 129u8, 252u8, 230u8,
        160u8, 207u8, 104u8, 71u8, 41u8, 135u8, 49u8, 194u8, 29u8, 26u8, 32u8, 99u8, 93u8, 75u8,
        14u8, 30u8, 61u8, 184u8, 50u8, 128u8, 222u8, 82u8, 49u8, 86u8, 98u8, 239u8, 63u8, 243u8,
        193u8, 152u8, 31u8, 141u8, 82u8, 153u8, 37u8, 142u8,
    ],
    [
        39u8, 182u8, 59u8, 143u8, 148u8, 126u8, 118u8, 182u8, 124u8, 28u8, 211u8, 48u8, 144u8,
        248u8, 113u8, 124u8, 247u8, 184u8, 12u8, 222u8, 21u8, 59u8, 246u8, 209u8, 219u8, 200u8,
        239u8, 196u8, 76u8, 52u8, 207u8, 252u8, 11u8, 17u8, 231u8, 97u8, 58u8, 183u8, 53u8, 102u8,
        161u8, 206u8, 191u8, 101u8, 237u8, 137u8, 164u8, 138u8, 26u8, 103u8, 45u8, 166u8, 109u8,
        91u8, 196u8, 33u8, 42u8, 208u8, 111u8, 44u8, 247u8, 34u8, 1u8, 232u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        6u8, 186u8, 192u8, 139u8, 83u8, 97u8, 121u8, 33u8, 239u8, 106u8, 186u8, 87u8, 186u8, 206u8,
        153u8, 188u8, 139u8, 15u8, 111u8, 73u8, 186u8, 116u8, 133u8, 211u8, 126u8, 37u8, 64u8,
        93u8, 19u8, 113u8, 84u8, 136u8, 40u8, 239u8, 189u8, 177u8, 239u8, 230u8, 49u8, 71u8, 63u8,
        246u8, 50u8, 63u8, 115u8, 181u8, 209u8, 220u8, 117u8, 9u8, 18u8, 44u8, 236u8, 6u8, 130u8,
        154u8, 122u8, 53u8, 27u8, 171u8, 58u8, 25u8, 178u8, 143u8,
    ],
    vk_beta_g2: [
        43u8, 251u8, 202u8, 209u8, 141u8, 156u8, 229u8, 140u8, 63u8, 4u8, 183u8, 41u8, 79u8, 22u8,
        152u8, 18u8, 93u8, 43u8, 40u8, 243u8, 200u8, 151u8, 50u8, 74u8, 143u8, 120u8, 223u8, 136u8,
        197u8, 132u8, 198u8, 90u8, 11u8, 176u8, 154u8, 195u8, 178u8, 54u8, 37u8, 108u8, 225u8,
        220u8, 114u8, 189u8, 106u8, 63u8, 62u8, 101u8, 210u8, 129u8, 201u8, 157u8, 223u8, 168u8,
        119u8, 199u8, 123u8, 40u8, 65u8, 175u8, 95u8, 143u8, 49u8, 237u8, 41u8, 22u8, 230u8, 155u8,
        26u8, 1u8, 101u8, 127u8, 78u8, 187u8, 167u8, 153u8, 181u8, 208u8, 233u8, 213u8, 68u8,
        196u8, 200u8, 118u8, 150u8, 175u8, 115u8, 136u8, 161u8, 109u8, 156u8, 189u8, 43u8, 197u8,
        37u8, 183u8, 41u8, 152u8, 94u8, 209u8, 120u8, 127u8, 102u8, 191u8, 132u8, 54u8, 170u8,
        72u8, 49u8, 119u8, 108u8, 98u8, 174u8, 242u8, 66u8, 141u8, 2u8, 132u8, 220u8, 49u8, 185u8,
        151u8, 164u8, 164u8, 107u8, 144u8, 163u8, 234u8,
    ],
    vk_gamma_g2: [
        35u8, 237u8, 202u8, 201u8, 98u8, 210u8, 227u8, 111u8, 255u8, 229u8, 161u8, 148u8, 50u8,
        80u8, 15u8, 166u8, 118u8, 245u8, 129u8, 244u8, 155u8, 196u8, 249u8, 200u8, 135u8, 96u8,
        147u8, 199u8, 4u8, 213u8, 142u8, 22u8, 43u8, 38u8, 106u8, 80u8, 107u8, 121u8, 115u8, 203u8,
        217u8, 161u8, 99u8, 237u8, 63u8, 237u8, 175u8, 205u8, 201u8, 25u8, 22u8, 87u8, 161u8,
        117u8, 213u8, 27u8, 116u8, 174u8, 124u8, 50u8, 133u8, 68u8, 207u8, 207u8, 46u8, 146u8,
        240u8, 63u8, 161u8, 253u8, 83u8, 169u8, 179u8, 169u8, 175u8, 95u8, 49u8, 151u8, 14u8,
        198u8, 94u8, 144u8, 252u8, 89u8, 33u8, 179u8, 79u8, 16u8, 65u8, 215u8, 49u8, 118u8, 217u8,
        149u8, 123u8, 162u8, 32u8, 171u8, 191u8, 127u8, 64u8, 249u8, 156u8, 141u8, 147u8, 198u8,
        18u8, 224u8, 156u8, 214u8, 147u8, 101u8, 32u8, 65u8, 209u8, 63u8, 5u8, 133u8, 205u8, 40u8,
        64u8, 97u8, 252u8, 171u8, 97u8, 192u8, 48u8, 31u8,
    ],
    vk_delta_g2: [
        9u8, 72u8, 220u8, 74u8, 172u8, 48u8, 229u8, 114u8, 213u8, 122u8, 184u8, 201u8, 184u8, 86u8,
        221u8, 173u8, 254u8, 12u8, 232u8, 150u8, 92u8, 203u8, 108u8, 7u8, 48u8, 129u8, 54u8, 253u8,
        218u8, 210u8, 30u8, 79u8, 37u8, 247u8, 32u8, 165u8, 28u8, 146u8, 196u8, 232u8, 43u8, 113u8,
        75u8, 78u8, 97u8, 203u8, 27u8, 91u8, 119u8, 183u8, 28u8, 216u8, 158u8, 31u8, 212u8, 202u8,
        172u8, 188u8, 227u8, 23u8, 54u8, 154u8, 28u8, 110u8, 5u8, 187u8, 54u8, 83u8, 42u8, 198u8,
        72u8, 205u8, 54u8, 169u8, 142u8, 225u8, 230u8, 139u8, 101u8, 149u8, 208u8, 250u8, 104u8,
        119u8, 49u8, 220u8, 137u8, 130u8, 127u8, 227u8, 130u8, 189u8, 208u8, 170u8, 216u8, 232u8,
        33u8, 169u8, 49u8, 204u8, 3u8, 112u8, 206u8, 236u8, 232u8, 176u8, 144u8, 175u8, 138u8,
        127u8, 101u8, 75u8, 136u8, 142u8, 15u8, 206u8, 67u8, 87u8, 213u8, 126u8, 121u8, 55u8,
        218u8, 43u8, 115u8, 167u8, 158u8, 56u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [163u8, 147u8, 54u8, 74u8, 71u8, 22u8, 216u8, 21u8, 127u8, 84u8, 207u8, 40u8, 177u8, 157u8, 0u8, 33u8, 201u8, 248u8, 224u8, 209u8, 111u8, 190u8, 160u8, 133u8, 121u8, 51u8, 188u8, 67u8, 74u8, 138u8, 251u8, 163u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_b288c0df78bb7427")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00a393364a4716d8157f54cf28b19d0021c9f8e0d16fbea0857933bc434a8afba3\x00=======END GROTH16 VK SETUP V1=======\x00";
