// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        4u8, 64u8, 40u8, 60u8, 245u8, 42u8, 106u8, 58u8, 173u8, 12u8, 41u8, 199u8, 95u8, 167u8,
        43u8, 108u8, 239u8, 158u8, 240u8, 169u8, 90u8, 109u8, 81u8, 236u8, 189u8, 219u8, 86u8,
        199u8, 101u8, 178u8, 172u8, 175u8, 5u8, 7u8, 22u8, 97u8, 131u8, 44u8, 42u8, 88u8, 74u8,
        212u8, 253u8, 55u8, 222u8, 95u8, 214u8, 55u8, 170u8, 187u8, 242u8, 171u8, 245u8, 177u8,
        251u8, 167u8, 253u8, 209u8, 234u8, 82u8, 164u8, 91u8, 156u8, 246u8,
    ],
    [
        17u8, 69u8, 134u8, 79u8, 215u8, 207u8, 199u8, 189u8, 23u8, 232u8, 105u8, 210u8, 83u8, 9u8,
        29u8, 14u8, 34u8, 157u8, 88u8, 25u8, 56u8, 50u8, 25u8, 124u8, 27u8, 129u8, 147u8, 108u8,
        169u8, 76u8, 222u8, 57u8, 39u8, 20u8, 161u8, 152u8, 168u8, 99u8, 244u8, 33u8, 219u8, 58u8,
        199u8, 202u8, 18u8, 172u8, 226u8, 64u8, 93u8, 174u8, 180u8, 53u8, 183u8, 168u8, 14u8,
        234u8, 242u8, 171u8, 20u8, 145u8, 150u8, 27u8, 237u8, 243u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        29u8, 41u8, 240u8, 204u8, 212u8, 53u8, 209u8, 109u8, 4u8, 49u8, 29u8, 220u8, 171u8, 119u8,
        116u8, 58u8, 239u8, 146u8, 249u8, 97u8, 111u8, 131u8, 121u8, 80u8, 102u8, 217u8, 153u8,
        149u8, 10u8, 59u8, 162u8, 172u8, 2u8, 61u8, 188u8, 193u8, 160u8, 9u8, 0u8, 94u8, 138u8,
        62u8, 126u8, 215u8, 14u8, 178u8, 254u8, 146u8, 245u8, 108u8, 83u8, 67u8, 225u8, 186u8,
        16u8, 142u8, 42u8, 174u8, 4u8, 195u8, 10u8, 135u8, 10u8, 123u8,
    ],
    vk_beta_g2: [
        15u8, 43u8, 30u8, 254u8, 94u8, 186u8, 83u8, 57u8, 85u8, 47u8, 241u8, 213u8, 115u8, 13u8,
        12u8, 185u8, 5u8, 7u8, 170u8, 0u8, 6u8, 190u8, 96u8, 134u8, 130u8, 145u8, 195u8, 198u8,
        33u8, 90u8, 79u8, 179u8, 31u8, 250u8, 189u8, 90u8, 117u8, 255u8, 127u8, 79u8, 131u8, 161u8,
        216u8, 181u8, 76u8, 62u8, 238u8, 118u8, 72u8, 19u8, 74u8, 13u8, 145u8, 228u8, 30u8, 126u8,
        179u8, 190u8, 210u8, 139u8, 229u8, 177u8, 68u8, 45u8, 4u8, 46u8, 155u8, 229u8, 39u8, 7u8,
        117u8, 55u8, 64u8, 220u8, 38u8, 72u8, 75u8, 75u8, 223u8, 40u8, 215u8, 233u8, 28u8, 14u8,
        66u8, 251u8, 89u8, 200u8, 176u8, 119u8, 135u8, 224u8, 116u8, 108u8, 22u8, 115u8, 8u8, 78u8,
        99u8, 114u8, 59u8, 66u8, 39u8, 4u8, 48u8, 88u8, 57u8, 213u8, 66u8, 245u8, 143u8, 167u8,
        49u8, 232u8, 229u8, 115u8, 211u8, 61u8, 250u8, 49u8, 6u8, 14u8, 50u8, 209u8, 157u8, 14u8,
        206u8, 229u8,
    ],
    vk_gamma_g2: [
        46u8, 49u8, 30u8, 141u8, 205u8, 24u8, 176u8, 38u8, 134u8, 53u8, 153u8, 197u8, 5u8, 88u8,
        125u8, 11u8, 100u8, 142u8, 254u8, 147u8, 186u8, 105u8, 232u8, 124u8, 240u8, 225u8, 43u8,
        138u8, 195u8, 131u8, 181u8, 1u8, 6u8, 180u8, 193u8, 139u8, 116u8, 156u8, 215u8, 228u8,
        79u8, 104u8, 99u8, 51u8, 104u8, 17u8, 169u8, 135u8, 243u8, 211u8, 148u8, 151u8, 59u8,
        138u8, 226u8, 112u8, 40u8, 54u8, 34u8, 14u8, 123u8, 189u8, 167u8, 18u8, 33u8, 30u8, 142u8,
        82u8, 188u8, 9u8, 100u8, 205u8, 178u8, 181u8, 85u8, 223u8, 50u8, 244u8, 1u8, 32u8, 50u8,
        36u8, 238u8, 225u8, 182u8, 187u8, 164u8, 53u8, 105u8, 220u8, 66u8, 81u8, 144u8, 37u8, 96u8,
        252u8, 30u8, 1u8, 122u8, 218u8, 201u8, 112u8, 121u8, 111u8, 181u8, 204u8, 82u8, 20u8,
        194u8, 171u8, 223u8, 52u8, 13u8, 159u8, 42u8, 130u8, 48u8, 87u8, 9u8, 91u8, 83u8, 10u8,
        171u8, 94u8, 225u8, 74u8, 93u8, 203u8,
    ],
    vk_delta_g2: [
        43u8, 216u8, 186u8, 246u8, 105u8, 247u8, 16u8, 158u8, 93u8, 10u8, 156u8, 85u8, 92u8, 194u8,
        170u8, 144u8, 62u8, 164u8, 120u8, 153u8, 248u8, 167u8, 159u8, 180u8, 66u8, 150u8, 121u8,
        164u8, 213u8, 56u8, 163u8, 243u8, 0u8, 87u8, 64u8, 118u8, 49u8, 80u8, 198u8, 136u8, 201u8,
        23u8, 47u8, 109u8, 1u8, 10u8, 225u8, 30u8, 55u8, 89u8, 151u8, 80u8, 4u8, 212u8, 71u8, 75u8,
        112u8, 24u8, 148u8, 105u8, 107u8, 149u8, 157u8, 216u8, 37u8, 239u8, 251u8, 179u8, 204u8,
        215u8, 111u8, 96u8, 134u8, 233u8, 183u8, 57u8, 163u8, 136u8, 250u8, 18u8, 109u8, 140u8,
        17u8, 117u8, 182u8, 193u8, 87u8, 72u8, 254u8, 205u8, 0u8, 73u8, 214u8, 203u8, 166u8, 61u8,
        2u8, 113u8, 139u8, 174u8, 192u8, 77u8, 140u8, 128u8, 97u8, 5u8, 77u8, 152u8, 61u8, 32u8,
        150u8, 21u8, 117u8, 210u8, 122u8, 39u8, 25u8, 1u8, 82u8, 71u8, 133u8, 203u8, 180u8, 236u8,
        34u8, 214u8, 213u8, 191u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [168u8, 163u8, 44u8, 135u8, 198u8, 183u8, 209u8, 53u8, 206u8, 214u8, 30u8, 74u8, 12u8, 12u8, 94u8, 81u8, 39u8, 176u8, 239u8, 42u8, 55u8, 117u8, 236u8, 74u8, 96u8, 226u8, 133u8, 228u8, 27u8, 215u8, 91u8, 206u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_45ef59216c75501d")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00a8a32c87c6b7d135ced61e4a0c0c5e5127b0ef2a3775ec4a60e285e41bd75bce\x00=======END GROTH16 VK SETUP V1=======\x00";
