// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        14u8, 157u8, 115u8, 100u8, 63u8, 28u8, 175u8, 26u8, 126u8, 196u8, 202u8, 251u8, 11u8, 23u8,
        200u8, 213u8, 82u8, 126u8, 65u8, 183u8, 4u8, 222u8, 106u8, 176u8, 253u8, 51u8, 106u8, 98u8,
        209u8, 55u8, 154u8, 201u8, 30u8, 160u8, 65u8, 126u8, 170u8, 126u8, 172u8, 225u8, 55u8,
        197u8, 78u8, 239u8, 172u8, 123u8, 72u8, 172u8, 231u8, 108u8, 85u8, 155u8, 221u8, 184u8,
        24u8, 124u8, 170u8, 156u8, 247u8, 168u8, 56u8, 208u8, 255u8, 204u8,
    ],
    [
        8u8, 105u8, 14u8, 184u8, 166u8, 208u8, 52u8, 206u8, 61u8, 181u8, 219u8, 81u8, 147u8, 61u8,
        30u8, 212u8, 13u8, 95u8, 225u8, 239u8, 89u8, 32u8, 143u8, 213u8, 54u8, 32u8, 160u8, 236u8,
        113u8, 223u8, 82u8, 133u8, 1u8, 183u8, 255u8, 16u8, 164u8, 94u8, 58u8, 65u8, 49u8, 180u8,
        32u8, 56u8, 18u8, 195u8, 173u8, 250u8, 101u8, 44u8, 137u8, 179u8, 161u8, 87u8, 92u8, 136u8,
        139u8, 7u8, 221u8, 2u8, 40u8, 23u8, 19u8, 236u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        34u8, 22u8, 121u8, 146u8, 15u8, 138u8, 202u8, 240u8, 123u8, 114u8, 161u8, 44u8, 145u8,
        234u8, 106u8, 77u8, 208u8, 60u8, 174u8, 161u8, 47u8, 142u8, 0u8, 13u8, 254u8, 26u8, 223u8,
        214u8, 70u8, 162u8, 80u8, 235u8, 37u8, 103u8, 91u8, 24u8, 205u8, 47u8, 6u8, 0u8, 46u8,
        79u8, 243u8, 153u8, 244u8, 242u8, 126u8, 236u8, 143u8, 94u8, 244u8, 38u8, 220u8, 161u8,
        168u8, 93u8, 2u8, 100u8, 145u8, 170u8, 211u8, 50u8, 234u8, 241u8,
    ],
    vk_beta_g2: [
        34u8, 209u8, 246u8, 116u8, 210u8, 50u8, 95u8, 158u8, 46u8, 207u8, 203u8, 240u8, 131u8,
        232u8, 5u8, 3u8, 7u8, 185u8, 152u8, 96u8, 6u8, 133u8, 24u8, 212u8, 239u8, 30u8, 28u8,
        188u8, 7u8, 255u8, 62u8, 46u8, 29u8, 142u8, 239u8, 191u8, 148u8, 172u8, 200u8, 58u8, 155u8,
        214u8, 172u8, 157u8, 165u8, 190u8, 98u8, 66u8, 121u8, 225u8, 230u8, 212u8, 65u8, 171u8,
        104u8, 182u8, 95u8, 158u8, 45u8, 104u8, 248u8, 165u8, 22u8, 166u8, 39u8, 67u8, 242u8,
        251u8, 74u8, 197u8, 97u8, 108u8, 162u8, 161u8, 231u8, 102u8, 38u8, 139u8, 90u8, 109u8,
        168u8, 228u8, 174u8, 217u8, 118u8, 155u8, 18u8, 94u8, 123u8, 9u8, 47u8, 45u8, 70u8, 215u8,
        165u8, 143u8, 29u8, 36u8, 251u8, 39u8, 71u8, 6u8, 34u8, 6u8, 96u8, 90u8, 95u8, 248u8,
        100u8, 183u8, 45u8, 144u8, 120u8, 45u8, 14u8, 179u8, 191u8, 177u8, 183u8, 74u8, 93u8, 44u8,
        164u8, 231u8, 84u8, 211u8, 45u8, 235u8,
    ],
    vk_gamma_g2: [
        15u8, 116u8, 81u8, 140u8, 0u8, 194u8, 143u8, 215u8, 15u8, 166u8, 63u8, 9u8, 211u8, 103u8,
        61u8, 110u8, 118u8, 181u8, 17u8, 22u8, 172u8, 147u8, 108u8, 60u8, 147u8, 46u8, 144u8,
        238u8, 26u8, 128u8, 26u8, 215u8, 10u8, 145u8, 117u8, 196u8, 42u8, 67u8, 21u8, 94u8, 235u8,
        111u8, 2u8, 64u8, 192u8, 254u8, 192u8, 104u8, 169u8, 90u8, 88u8, 209u8, 148u8, 225u8, 63u8,
        70u8, 1u8, 213u8, 47u8, 114u8, 92u8, 245u8, 195u8, 22u8, 6u8, 175u8, 139u8, 218u8, 254u8,
        200u8, 227u8, 56u8, 162u8, 122u8, 35u8, 137u8, 180u8, 95u8, 75u8, 176u8, 43u8, 208u8, 25u8,
        98u8, 192u8, 100u8, 136u8, 99u8, 38u8, 99u8, 25u8, 116u8, 148u8, 49u8, 219u8, 213u8, 14u8,
        81u8, 188u8, 84u8, 238u8, 252u8, 99u8, 125u8, 50u8, 190u8, 6u8, 102u8, 88u8, 183u8, 12u8,
        85u8, 204u8, 75u8, 27u8, 67u8, 166u8, 192u8, 235u8, 233u8, 140u8, 250u8, 209u8, 230u8,
        70u8, 70u8, 3u8, 98u8,
    ],
    vk_delta_g2: [
        4u8, 22u8, 181u8, 200u8, 92u8, 14u8, 71u8, 32u8, 173u8, 110u8, 136u8, 19u8, 238u8, 30u8,
        14u8, 86u8, 166u8, 51u8, 63u8, 17u8, 129u8, 112u8, 95u8, 43u8, 246u8, 19u8, 10u8, 84u8,
        96u8, 43u8, 190u8, 210u8, 14u8, 7u8, 85u8, 162u8, 50u8, 38u8, 72u8, 210u8, 44u8, 73u8,
        166u8, 88u8, 36u8, 115u8, 102u8, 112u8, 84u8, 28u8, 148u8, 82u8, 185u8, 125u8, 237u8, 46u8,
        161u8, 237u8, 169u8, 63u8, 249u8, 97u8, 1u8, 130u8, 19u8, 235u8, 181u8, 21u8, 129u8, 105u8,
        102u8, 176u8, 30u8, 89u8, 188u8, 245u8, 95u8, 106u8, 208u8, 109u8, 189u8, 233u8, 109u8,
        170u8, 107u8, 252u8, 129u8, 10u8, 61u8, 113u8, 30u8, 105u8, 248u8, 184u8, 92u8, 157u8, 2u8,
        185u8, 78u8, 165u8, 68u8, 254u8, 112u8, 119u8, 13u8, 5u8, 3u8, 201u8, 169u8, 157u8, 231u8,
        19u8, 219u8, 190u8, 193u8, 119u8, 158u8, 249u8, 37u8, 151u8, 115u8, 119u8, 231u8, 185u8,
        48u8, 94u8, 117u8, 114u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [72u8, 32u8, 14u8, 150u8, 106u8, 245u8, 90u8, 195u8, 112u8, 18u8, 142u8, 158u8, 121u8, 214u8, 165u8, 180u8, 34u8, 190u8, 4u8, 141u8, 155u8, 236u8, 45u8, 195u8, 240u8, 249u8, 29u8, 32u8, 146u8, 1u8, 60u8, 153u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_cc80f7be96ebbef7")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x0048200e966af55ac370128e9e79d6a5b422be048d9bec2dc3f0f91d2092013c99\x00=======END GROTH16 VK SETUP V1=======\x00";
