// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        15u8, 68u8, 37u8, 10u8, 74u8, 220u8, 159u8, 83u8, 161u8, 245u8, 219u8, 85u8, 93u8, 140u8,
        169u8, 124u8, 52u8, 121u8, 66u8, 81u8, 55u8, 13u8, 37u8, 208u8, 17u8, 61u8, 148u8, 28u8,
        158u8, 247u8, 31u8, 74u8, 35u8, 69u8, 35u8, 61u8, 141u8, 239u8, 6u8, 12u8, 136u8, 126u8,
        81u8, 215u8, 144u8, 124u8, 41u8, 92u8, 13u8, 7u8, 190u8, 21u8, 61u8, 29u8, 67u8, 38u8,
        209u8, 254u8, 66u8, 117u8, 183u8, 27u8, 31u8, 184u8,
    ],
    [
        21u8, 146u8, 4u8, 89u8, 154u8, 79u8, 242u8, 116u8, 191u8, 56u8, 125u8, 86u8, 242u8, 230u8,
        133u8, 118u8, 138u8, 255u8, 198u8, 30u8, 170u8, 186u8, 24u8, 129u8, 180u8, 239u8, 179u8,
        39u8, 196u8, 80u8, 118u8, 95u8, 35u8, 70u8, 20u8, 44u8, 236u8, 75u8, 19u8, 207u8, 58u8,
        20u8, 16u8, 203u8, 53u8, 120u8, 135u8, 237u8, 99u8, 202u8, 43u8, 173u8, 141u8, 62u8, 94u8,
        135u8, 181u8, 129u8, 213u8, 133u8, 138u8, 57u8, 34u8, 117u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        36u8, 92u8, 225u8, 207u8, 183u8, 99u8, 67u8, 134u8, 10u8, 48u8, 95u8, 246u8, 133u8, 163u8,
        87u8, 78u8, 71u8, 12u8, 149u8, 166u8, 251u8, 34u8, 11u8, 108u8, 167u8, 165u8, 76u8, 84u8,
        153u8, 200u8, 209u8, 14u8, 20u8, 245u8, 235u8, 41u8, 93u8, 102u8, 151u8, 56u8, 118u8, 73u8,
        163u8, 191u8, 198u8, 74u8, 124u8, 171u8, 119u8, 46u8, 237u8, 104u8, 43u8, 17u8, 98u8,
        167u8, 237u8, 162u8, 167u8, 123u8, 65u8, 145u8, 80u8, 198u8,
    ],
    vk_beta_g2: [
        46u8, 217u8, 215u8, 161u8, 96u8, 22u8, 168u8, 213u8, 244u8, 238u8, 177u8, 139u8, 141u8,
        181u8, 182u8, 57u8, 140u8, 55u8, 145u8, 248u8, 220u8, 98u8, 183u8, 56u8, 59u8, 229u8, 82u8,
        13u8, 161u8, 4u8, 125u8, 172u8, 40u8, 12u8, 89u8, 133u8, 165u8, 207u8, 109u8, 146u8, 77u8,
        73u8, 177u8, 140u8, 237u8, 145u8, 168u8, 160u8, 129u8, 48u8, 200u8, 183u8, 250u8, 42u8,
        73u8, 83u8, 212u8, 254u8, 197u8, 13u8, 200u8, 227u8, 248u8, 70u8, 37u8, 161u8, 222u8, 35u8,
        53u8, 22u8, 9u8, 238u8, 245u8, 35u8, 147u8, 158u8, 7u8, 191u8, 76u8, 138u8, 15u8, 75u8,
        43u8, 200u8, 179u8, 8u8, 30u8, 238u8, 83u8, 50u8, 86u8, 101u8, 148u8, 18u8, 103u8, 170u8,
        35u8, 69u8, 143u8, 7u8, 126u8, 223u8, 237u8, 0u8, 87u8, 49u8, 83u8, 214u8, 25u8, 96u8,
        181u8, 204u8, 38u8, 67u8, 198u8, 75u8, 215u8, 246u8, 71u8, 2u8, 154u8, 118u8, 88u8, 151u8,
        68u8, 41u8, 60u8, 253u8,
    ],
    vk_gamma_g2: [
        7u8, 177u8, 198u8, 141u8, 131u8, 0u8, 253u8, 50u8, 76u8, 112u8, 242u8, 227u8, 165u8, 6u8,
        244u8, 95u8, 225u8, 252u8, 76u8, 131u8, 180u8, 5u8, 157u8, 26u8, 49u8, 122u8, 167u8, 229u8,
        52u8, 62u8, 133u8, 222u8, 16u8, 60u8, 128u8, 183u8, 8u8, 125u8, 223u8, 174u8, 1u8, 21u8,
        152u8, 9u8, 203u8, 236u8, 192u8, 65u8, 196u8, 148u8, 9u8, 217u8, 239u8, 183u8, 125u8, 60u8,
        33u8, 86u8, 40u8, 195u8, 96u8, 220u8, 5u8, 135u8, 9u8, 67u8, 240u8, 89u8, 12u8, 213u8,
        141u8, 133u8, 154u8, 84u8, 158u8, 89u8, 73u8, 86u8, 63u8, 179u8, 165u8, 105u8, 44u8, 218u8,
        37u8, 47u8, 161u8, 169u8, 26u8, 161u8, 178u8, 57u8, 131u8, 217u8, 106u8, 217u8, 42u8, 98u8,
        226u8, 119u8, 200u8, 45u8, 33u8, 37u8, 221u8, 138u8, 11u8, 155u8, 110u8, 250u8, 89u8, 94u8,
        132u8, 149u8, 142u8, 196u8, 25u8, 20u8, 153u8, 177u8, 214u8, 144u8, 238u8, 167u8, 211u8,
        103u8, 71u8, 184u8,
    ],
    vk_delta_g2: [
        33u8, 215u8, 81u8, 246u8, 178u8, 21u8, 126u8, 5u8, 36u8, 154u8, 207u8, 112u8, 112u8, 239u8,
        107u8, 4u8, 8u8, 43u8, 247u8, 135u8, 146u8, 11u8, 81u8, 48u8, 88u8, 119u8, 79u8, 31u8,
        214u8, 240u8, 201u8, 12u8, 21u8, 16u8, 150u8, 253u8, 31u8, 161u8, 17u8, 247u8, 22u8, 227u8,
        132u8, 8u8, 220u8, 119u8, 145u8, 161u8, 98u8, 251u8, 44u8, 72u8, 128u8, 148u8, 134u8,
        201u8, 189u8, 240u8, 159u8, 206u8, 19u8, 39u8, 134u8, 214u8, 26u8, 8u8, 169u8, 251u8,
        222u8, 89u8, 111u8, 67u8, 155u8, 99u8, 87u8, 41u8, 234u8, 128u8, 123u8, 185u8, 11u8, 103u8,
        205u8, 181u8, 31u8, 215u8, 127u8, 210u8, 112u8, 172u8, 175u8, 239u8, 218u8, 10u8, 229u8,
        95u8, 35u8, 40u8, 81u8, 89u8, 74u8, 59u8, 181u8, 93u8, 31u8, 144u8, 49u8, 228u8, 237u8,
        24u8, 159u8, 44u8, 170u8, 197u8, 170u8, 37u8, 254u8, 148u8, 212u8, 81u8, 101u8, 94u8,
        174u8, 25u8, 232u8, 181u8, 196u8, 211u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [182u8, 135u8, 44u8, 0u8, 193u8, 193u8, 85u8, 124u8, 165u8, 77u8, 41u8, 118u8, 209u8, 196u8, 156u8, 203u8, 187u8, 84u8, 86u8, 118u8, 55u8, 38u8, 73u8, 58u8, 84u8, 61u8, 245u8, 60u8, 42u8, 7u8, 205u8, 173u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_44e435e1be0ff2ab")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00b6872c00c1c1557ca54d2976d1c49ccbbb5456763726493a543df53c2a07cdad\x00=======END GROTH16 VK SETUP V1=======\x00";
