// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        3u8, 220u8, 23u8, 200u8, 154u8, 103u8, 109u8, 187u8, 43u8, 226u8, 46u8, 37u8, 215u8, 152u8,
        206u8, 50u8, 157u8, 89u8, 248u8, 189u8, 45u8, 210u8, 182u8, 154u8, 68u8, 209u8, 87u8, 67u8,
        14u8, 244u8, 209u8, 150u8, 45u8, 37u8, 201u8, 12u8, 136u8, 206u8, 221u8, 26u8, 26u8, 230u8,
        209u8, 105u8, 61u8, 162u8, 206u8, 140u8, 65u8, 193u8, 22u8, 50u8, 214u8, 119u8, 137u8,
        77u8, 164u8, 198u8, 46u8, 127u8, 115u8, 197u8, 229u8, 56u8,
    ],
    [
        30u8, 218u8, 169u8, 56u8, 101u8, 23u8, 36u8, 153u8, 67u8, 98u8, 158u8, 74u8, 144u8, 190u8,
        15u8, 51u8, 179u8, 105u8, 35u8, 221u8, 216u8, 5u8, 156u8, 251u8, 170u8, 138u8, 247u8,
        223u8, 46u8, 130u8, 28u8, 67u8, 34u8, 47u8, 18u8, 149u8, 86u8, 7u8, 168u8, 118u8, 253u8,
        211u8, 215u8, 204u8, 107u8, 115u8, 57u8, 42u8, 227u8, 75u8, 168u8, 189u8, 118u8, 134u8,
        245u8, 184u8, 187u8, 102u8, 190u8, 128u8, 142u8, 204u8, 113u8, 59u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        1u8, 147u8, 54u8, 66u8, 222u8, 36u8, 251u8, 39u8, 165u8, 42u8, 193u8, 104u8, 28u8, 95u8,
        241u8, 139u8, 109u8, 189u8, 1u8, 126u8, 157u8, 122u8, 238u8, 79u8, 146u8, 185u8, 220u8,
        119u8, 241u8, 169u8, 115u8, 4u8, 20u8, 52u8, 147u8, 13u8, 125u8, 166u8, 100u8, 66u8, 14u8,
        61u8, 179u8, 142u8, 55u8, 59u8, 205u8, 218u8, 38u8, 56u8, 208u8, 8u8, 205u8, 87u8, 181u8,
        207u8, 131u8, 21u8, 158u8, 8u8, 64u8, 196u8, 21u8, 123u8,
    ],
    vk_beta_g2: [
        21u8, 205u8, 96u8, 27u8, 97u8, 36u8, 198u8, 172u8, 116u8, 84u8, 32u8, 86u8, 9u8, 162u8,
        109u8, 230u8, 61u8, 236u8, 38u8, 132u8, 135u8, 110u8, 148u8, 69u8, 1u8, 82u8, 154u8, 174u8,
        50u8, 190u8, 179u8, 103u8, 40u8, 176u8, 147u8, 89u8, 170u8, 136u8, 205u8, 224u8, 43u8,
        208u8, 145u8, 76u8, 66u8, 74u8, 121u8, 148u8, 196u8, 149u8, 162u8, 200u8, 145u8, 107u8,
        237u8, 66u8, 207u8, 5u8, 247u8, 162u8, 92u8, 141u8, 56u8, 128u8, 48u8, 9u8, 48u8, 212u8,
        98u8, 174u8, 222u8, 117u8, 149u8, 61u8, 166u8, 11u8, 241u8, 121u8, 69u8, 222u8, 71u8, 26u8,
        134u8, 214u8, 191u8, 71u8, 121u8, 38u8, 150u8, 16u8, 47u8, 31u8, 188u8, 180u8, 150u8, 91u8,
        32u8, 77u8, 127u8, 160u8, 28u8, 34u8, 134u8, 68u8, 80u8, 242u8, 60u8, 157u8, 18u8, 110u8,
        21u8, 59u8, 251u8, 6u8, 34u8, 207u8, 218u8, 70u8, 60u8, 236u8, 144u8, 178u8, 197u8, 80u8,
        232u8, 187u8, 186u8, 255u8,
    ],
    vk_gamma_g2: [
        12u8, 182u8, 203u8, 143u8, 135u8, 27u8, 212u8, 63u8, 76u8, 159u8, 30u8, 216u8, 138u8,
        164u8, 132u8, 111u8, 254u8, 148u8, 100u8, 25u8, 46u8, 42u8, 47u8, 12u8, 221u8, 69u8, 208u8,
        175u8, 123u8, 136u8, 212u8, 74u8, 28u8, 141u8, 205u8, 199u8, 241u8, 235u8, 81u8, 97u8,
        121u8, 252u8, 226u8, 219u8, 113u8, 185u8, 135u8, 121u8, 187u8, 67u8, 133u8, 111u8, 189u8,
        55u8, 42u8, 17u8, 23u8, 14u8, 159u8, 208u8, 24u8, 213u8, 210u8, 52u8, 45u8, 125u8, 84u8,
        167u8, 177u8, 86u8, 33u8, 11u8, 44u8, 188u8, 250u8, 165u8, 250u8, 247u8, 215u8, 135u8,
        145u8, 64u8, 92u8, 238u8, 140u8, 255u8, 116u8, 162u8, 64u8, 110u8, 115u8, 210u8, 122u8,
        147u8, 213u8, 53u8, 44u8, 84u8, 111u8, 86u8, 205u8, 248u8, 164u8, 229u8, 212u8, 95u8,
        195u8, 19u8, 253u8, 117u8, 5u8, 122u8, 64u8, 1u8, 61u8, 64u8, 32u8, 7u8, 120u8, 124u8,
        63u8, 38u8, 112u8, 68u8, 112u8, 181u8, 122u8, 47u8,
    ],
    vk_delta_g2: [
        10u8, 76u8, 200u8, 99u8, 61u8, 217u8, 217u8, 224u8, 193u8, 178u8, 109u8, 251u8, 97u8,
        241u8, 48u8, 71u8, 163u8, 120u8, 236u8, 156u8, 237u8, 90u8, 38u8, 249u8, 48u8, 203u8,
        147u8, 50u8, 68u8, 92u8, 111u8, 215u8, 11u8, 246u8, 247u8, 207u8, 225u8, 213u8, 140u8,
        218u8, 182u8, 12u8, 213u8, 93u8, 102u8, 82u8, 17u8, 92u8, 126u8, 192u8, 231u8, 224u8, 49u8,
        135u8, 49u8, 200u8, 51u8, 86u8, 233u8, 91u8, 168u8, 179u8, 93u8, 179u8, 24u8, 230u8, 156u8,
        76u8, 137u8, 137u8, 217u8, 150u8, 54u8, 210u8, 120u8, 207u8, 0u8, 223u8, 79u8, 126u8,
        137u8, 206u8, 62u8, 10u8, 11u8, 176u8, 75u8, 198u8, 89u8, 191u8, 82u8, 117u8, 189u8, 207u8,
        119u8, 67u8, 10u8, 89u8, 208u8, 11u8, 196u8, 171u8, 120u8, 168u8, 10u8, 41u8, 159u8, 93u8,
        108u8, 77u8, 17u8, 180u8, 184u8, 37u8, 52u8, 82u8, 56u8, 240u8, 150u8, 78u8, 51u8, 205u8,
        113u8, 112u8, 201u8, 76u8, 173u8, 202u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [78u8, 77u8, 236u8, 212u8, 144u8, 82u8, 141u8, 241u8, 239u8, 79u8, 227u8, 253u8, 180u8, 187u8, 85u8, 215u8, 193u8, 62u8, 140u8, 52u8, 142u8, 178u8, 3u8, 80u8, 224u8, 255u8, 227u8, 206u8, 64u8, 99u8, 69u8, 116u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_b4b05ad4b7a8e041")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x004e4decd490528df1ef4fe3fdb4bb55d7c13e8c348eb20350e0ffe3ce40634574\x00=======END GROTH16 VK SETUP V1=======\x00";
