// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        31u8, 38u8, 60u8, 211u8, 159u8, 225u8, 238u8, 157u8, 3u8, 100u8, 19u8, 188u8, 194u8, 162u8,
        206u8, 235u8, 225u8, 108u8, 165u8, 100u8, 233u8, 7u8, 117u8, 20u8, 32u8, 200u8, 151u8,
        116u8, 69u8, 239u8, 237u8, 202u8, 25u8, 29u8, 109u8, 77u8, 212u8, 141u8, 5u8, 234u8, 215u8,
        205u8, 56u8, 248u8, 109u8, 6u8, 220u8, 129u8, 249u8, 180u8, 111u8, 0u8, 192u8, 13u8, 35u8,
        201u8, 6u8, 169u8, 158u8, 59u8, 91u8, 122u8, 9u8, 40u8,
    ],
    [
        4u8, 102u8, 135u8, 175u8, 59u8, 186u8, 77u8, 125u8, 223u8, 32u8, 40u8, 157u8, 22u8, 192u8,
        82u8, 1u8, 182u8, 100u8, 253u8, 115u8, 21u8, 214u8, 186u8, 230u8, 131u8, 120u8, 206u8,
        54u8, 237u8, 235u8, 77u8, 228u8, 42u8, 244u8, 93u8, 149u8, 86u8, 46u8, 4u8, 120u8, 47u8,
        32u8, 141u8, 235u8, 84u8, 76u8, 61u8, 68u8, 153u8, 141u8, 4u8, 126u8, 149u8, 63u8, 184u8,
        97u8, 164u8, 227u8, 19u8, 157u8, 254u8, 158u8, 206u8, 145u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        27u8, 235u8, 142u8, 55u8, 54u8, 154u8, 179u8, 185u8, 249u8, 157u8, 63u8, 253u8, 186u8,
        121u8, 133u8, 164u8, 186u8, 158u8, 36u8, 21u8, 137u8, 30u8, 119u8, 189u8, 26u8, 1u8, 113u8,
        79u8, 235u8, 163u8, 109u8, 121u8, 14u8, 167u8, 178u8, 64u8, 203u8, 62u8, 254u8, 149u8,
        39u8, 45u8, 132u8, 190u8, 129u8, 12u8, 229u8, 247u8, 245u8, 131u8, 34u8, 255u8, 215u8,
        179u8, 155u8, 249u8, 213u8, 7u8, 188u8, 212u8, 145u8, 53u8, 111u8, 96u8,
    ],
    vk_beta_g2: [
        26u8, 111u8, 150u8, 220u8, 76u8, 204u8, 235u8, 10u8, 148u8, 162u8, 232u8, 63u8, 92u8,
        227u8, 11u8, 118u8, 228u8, 160u8, 76u8, 27u8, 234u8, 134u8, 129u8, 83u8, 18u8, 114u8, 74u8,
        251u8, 42u8, 170u8, 105u8, 156u8, 13u8, 66u8, 21u8, 119u8, 40u8, 80u8, 235u8, 92u8, 233u8,
        146u8, 102u8, 106u8, 95u8, 46u8, 116u8, 30u8, 58u8, 30u8, 145u8, 110u8, 69u8, 187u8, 177u8,
        24u8, 59u8, 130u8, 83u8, 186u8, 15u8, 0u8, 191u8, 126u8, 1u8, 102u8, 85u8, 249u8, 168u8,
        78u8, 28u8, 217u8, 115u8, 154u8, 18u8, 105u8, 107u8, 90u8, 134u8, 135u8, 77u8, 75u8, 211u8,
        168u8, 86u8, 8u8, 128u8, 201u8, 224u8, 216u8, 223u8, 90u8, 57u8, 184u8, 239u8, 45u8, 5u8,
        103u8, 240u8, 129u8, 46u8, 180u8, 188u8, 180u8, 35u8, 150u8, 37u8, 247u8, 53u8, 184u8,
        218u8, 38u8, 96u8, 9u8, 7u8, 91u8, 114u8, 184u8, 61u8, 75u8, 88u8, 165u8, 101u8, 180u8,
        181u8, 180u8, 181u8, 185u8,
    ],
    vk_gamma_g2: [
        30u8, 71u8, 0u8, 209u8, 85u8, 218u8, 188u8, 243u8, 254u8, 91u8, 124u8, 50u8, 191u8, 170u8,
        3u8, 224u8, 225u8, 208u8, 200u8, 207u8, 118u8, 240u8, 82u8, 26u8, 176u8, 32u8, 58u8, 168u8,
        170u8, 201u8, 90u8, 155u8, 28u8, 222u8, 206u8, 70u8, 163u8, 173u8, 63u8, 53u8, 207u8,
        241u8, 33u8, 154u8, 29u8, 178u8, 72u8, 231u8, 217u8, 85u8, 56u8, 44u8, 218u8, 254u8, 252u8,
        253u8, 105u8, 199u8, 130u8, 137u8, 35u8, 252u8, 140u8, 37u8, 43u8, 144u8, 177u8, 196u8,
        150u8, 97u8, 230u8, 172u8, 43u8, 253u8, 103u8, 17u8, 143u8, 133u8, 99u8, 194u8, 27u8,
        241u8, 224u8, 195u8, 247u8, 9u8, 57u8, 31u8, 194u8, 166u8, 105u8, 36u8, 65u8, 86u8, 206u8,
        184u8, 30u8, 197u8, 155u8, 28u8, 244u8, 169u8, 34u8, 253u8, 41u8, 78u8, 130u8, 65u8, 125u8,
        128u8, 79u8, 20u8, 162u8, 252u8, 26u8, 51u8, 144u8, 55u8, 204u8, 112u8, 52u8, 204u8, 231u8,
        195u8, 33u8, 126u8, 174u8, 30u8,
    ],
    vk_delta_g2: [
        35u8, 206u8, 114u8, 151u8, 169u8, 82u8, 31u8, 105u8, 147u8, 102u8, 221u8, 126u8, 135u8,
        224u8, 16u8, 35u8, 147u8, 117u8, 243u8, 40u8, 250u8, 32u8, 75u8, 163u8, 237u8, 142u8, 59u8,
        63u8, 251u8, 73u8, 113u8, 5u8, 46u8, 102u8, 22u8, 9u8, 57u8, 74u8, 249u8, 212u8, 143u8,
        143u8, 134u8, 18u8, 35u8, 193u8, 43u8, 242u8, 164u8, 140u8, 84u8, 155u8, 207u8, 64u8,
        223u8, 18u8, 105u8, 78u8, 93u8, 148u8, 91u8, 123u8, 96u8, 52u8, 16u8, 111u8, 52u8, 112u8,
        5u8, 230u8, 28u8, 28u8, 185u8, 66u8, 225u8, 216u8, 244u8, 0u8, 108u8, 212u8, 199u8, 116u8,
        192u8, 245u8, 211u8, 177u8, 140u8, 29u8, 145u8, 207u8, 147u8, 46u8, 141u8, 247u8, 150u8,
        163u8, 14u8, 70u8, 224u8, 235u8, 226u8, 106u8, 186u8, 39u8, 60u8, 182u8, 105u8, 117u8,
        17u8, 216u8, 82u8, 160u8, 0u8, 109u8, 126u8, 72u8, 136u8, 32u8, 42u8, 57u8, 79u8, 103u8,
        8u8, 52u8, 45u8, 17u8, 86u8, 46u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [143u8, 23u8, 241u8, 145u8, 197u8, 3u8, 41u8, 194u8, 145u8, 47u8, 169u8, 181u8, 117u8, 254u8, 110u8, 238u8, 75u8, 216u8, 133u8, 171u8, 168u8, 138u8, 55u8, 74u8, 37u8, 123u8, 236u8, 174u8, 74u8, 126u8, 223u8, 10u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_14573ce6afc466ac")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x008f17f191c50329c2912fa9b575fe6eee4bd885aba88a374a257becae4a7edf0a\x00=======END GROTH16 VK SETUP V1=======\x00";
