// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        15u8, 149u8, 2u8, 222u8, 239u8, 202u8, 97u8, 161u8, 176u8, 13u8, 117u8, 193u8, 214u8, 18u8,
        57u8, 120u8, 203u8, 253u8, 229u8, 154u8, 176u8, 245u8, 157u8, 252u8, 3u8, 163u8, 116u8,
        15u8, 192u8, 114u8, 167u8, 21u8, 3u8, 101u8, 217u8, 45u8, 246u8, 187u8, 197u8, 5u8, 51u8,
        182u8, 127u8, 32u8, 43u8, 36u8, 35u8, 247u8, 182u8, 124u8, 109u8, 161u8, 37u8, 61u8, 167u8,
        134u8, 201u8, 34u8, 17u8, 150u8, 15u8, 246u8, 162u8, 4u8,
    ],
    [
        17u8, 238u8, 150u8, 86u8, 166u8, 158u8, 226u8, 243u8, 60u8, 76u8, 17u8, 46u8, 170u8, 111u8,
        52u8, 222u8, 96u8, 251u8, 55u8, 116u8, 111u8, 87u8, 132u8, 55u8, 130u8, 120u8, 220u8,
        120u8, 33u8, 240u8, 168u8, 210u8, 17u8, 153u8, 169u8, 174u8, 137u8, 136u8, 137u8, 154u8,
        145u8, 142u8, 89u8, 202u8, 255u8, 11u8, 79u8, 214u8, 155u8, 1u8, 52u8, 162u8, 109u8, 158u8,
        122u8, 75u8, 155u8, 206u8, 117u8, 52u8, 42u8, 196u8, 134u8, 65u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        41u8, 79u8, 4u8, 147u8, 242u8, 250u8, 222u8, 106u8, 101u8, 221u8, 24u8, 124u8, 10u8, 148u8,
        98u8, 198u8, 227u8, 57u8, 68u8, 22u8, 84u8, 209u8, 172u8, 211u8, 201u8, 72u8, 144u8, 100u8,
        218u8, 12u8, 135u8, 1u8, 20u8, 29u8, 34u8, 40u8, 208u8, 62u8, 228u8, 95u8, 237u8, 222u8,
        55u8, 103u8, 183u8, 207u8, 11u8, 119u8, 13u8, 113u8, 24u8, 94u8, 159u8, 240u8, 251u8, 45u8,
        46u8, 79u8, 47u8, 200u8, 194u8, 207u8, 215u8, 230u8,
    ],
    vk_beta_g2: [
        39u8, 7u8, 208u8, 251u8, 111u8, 73u8, 246u8, 23u8, 204u8, 45u8, 135u8, 104u8, 138u8, 81u8,
        121u8, 181u8, 217u8, 22u8, 23u8, 19u8, 37u8, 241u8, 89u8, 130u8, 236u8, 66u8, 83u8, 57u8,
        74u8, 224u8, 21u8, 88u8, 41u8, 161u8, 164u8, 162u8, 58u8, 14u8, 176u8, 2u8, 134u8, 162u8,
        160u8, 106u8, 186u8, 25u8, 0u8, 42u8, 93u8, 208u8, 49u8, 224u8, 88u8, 233u8, 167u8, 234u8,
        148u8, 44u8, 128u8, 60u8, 197u8, 115u8, 128u8, 189u8, 32u8, 205u8, 14u8, 234u8, 58u8,
        245u8, 36u8, 132u8, 126u8, 5u8, 12u8, 33u8, 140u8, 110u8, 245u8, 52u8, 73u8, 14u8, 201u8,
        213u8, 69u8, 73u8, 29u8, 113u8, 21u8, 119u8, 168u8, 125u8, 193u8, 46u8, 167u8, 149u8, 8u8,
        66u8, 102u8, 94u8, 28u8, 70u8, 70u8, 211u8, 144u8, 114u8, 88u8, 122u8, 216u8, 219u8, 79u8,
        170u8, 48u8, 165u8, 150u8, 160u8, 194u8, 140u8, 233u8, 127u8, 73u8, 56u8, 179u8, 253u8,
        183u8, 245u8, 254u8, 11u8,
    ],
    vk_gamma_g2: [
        17u8, 108u8, 215u8, 130u8, 243u8, 202u8, 239u8, 238u8, 160u8, 109u8, 127u8, 200u8, 9u8,
        202u8, 163u8, 11u8, 201u8, 5u8, 0u8, 220u8, 36u8, 139u8, 210u8, 244u8, 25u8, 106u8, 89u8,
        45u8, 151u8, 251u8, 36u8, 63u8, 38u8, 191u8, 72u8, 51u8, 38u8, 220u8, 228u8, 99u8, 143u8,
        99u8, 201u8, 112u8, 11u8, 179u8, 27u8, 213u8, 128u8, 36u8, 172u8, 21u8, 208u8, 3u8, 41u8,
        162u8, 130u8, 117u8, 143u8, 106u8, 223u8, 137u8, 86u8, 227u8, 5u8, 75u8, 40u8, 163u8, 94u8,
        87u8, 99u8, 169u8, 210u8, 70u8, 58u8, 114u8, 255u8, 107u8, 86u8, 53u8, 156u8, 233u8, 59u8,
        111u8, 111u8, 246u8, 247u8, 120u8, 214u8, 166u8, 164u8, 63u8, 21u8, 172u8, 225u8, 206u8,
        39u8, 50u8, 132u8, 178u8, 12u8, 78u8, 51u8, 120u8, 128u8, 224u8, 231u8, 19u8, 240u8, 165u8,
        77u8, 96u8, 150u8, 153u8, 89u8, 62u8, 245u8, 50u8, 24u8, 220u8, 157u8, 173u8, 60u8, 16u8,
        142u8, 49u8, 75u8, 25u8,
    ],
    vk_delta_g2: [
        8u8, 162u8, 205u8, 157u8, 34u8, 133u8, 251u8, 69u8, 210u8, 240u8, 189u8, 216u8, 83u8, 67u8,
        233u8, 248u8, 183u8, 135u8, 107u8, 156u8, 205u8, 223u8, 9u8, 20u8, 155u8, 198u8, 194u8,
        31u8, 37u8, 24u8, 88u8, 95u8, 14u8, 202u8, 192u8, 64u8, 220u8, 214u8, 115u8, 106u8, 219u8,
        159u8, 17u8, 64u8, 184u8, 171u8, 117u8, 155u8, 241u8, 162u8, 188u8, 37u8, 59u8, 22u8,
        107u8, 82u8, 20u8, 83u8, 46u8, 222u8, 238u8, 142u8, 184u8, 235u8, 43u8, 8u8, 186u8, 200u8,
        20u8, 243u8, 115u8, 5u8, 105u8, 132u8, 181u8, 251u8, 217u8, 228u8, 132u8, 251u8, 75u8,
        21u8, 253u8, 196u8, 4u8, 110u8, 100u8, 238u8, 33u8, 36u8, 33u8, 226u8, 16u8, 49u8, 0u8,
        121u8, 5u8, 41u8, 236u8, 204u8, 63u8, 35u8, 116u8, 211u8, 226u8, 193u8, 240u8, 246u8,
        195u8, 95u8, 100u8, 174u8, 0u8, 101u8, 66u8, 28u8, 152u8, 141u8, 158u8, 231u8, 109u8,
        184u8, 120u8, 165u8, 103u8, 74u8, 98u8, 234u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [132u8, 173u8, 8u8, 213u8, 227u8, 148u8, 112u8, 187u8, 76u8, 87u8, 108u8, 50u8, 110u8, 29u8, 45u8, 143u8, 104u8, 203u8, 121u8, 94u8, 34u8, 251u8, 19u8, 66u8, 92u8, 199u8, 160u8, 63u8, 232u8, 19u8, 43u8, 82u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_c8711ecc0ddf59c6")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x0084ad08d5e39470bb4c576c326e1d2d8f68cb795e22fb13425cc7a03fe8132b52\x00=======END GROTH16 VK SETUP V1=======\x00";
