// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        14u8, 147u8, 218u8, 37u8, 19u8, 62u8, 222u8, 18u8, 165u8, 21u8, 88u8, 87u8, 84u8, 15u8,
        216u8, 21u8, 5u8, 181u8, 229u8, 78u8, 244u8, 123u8, 77u8, 229u8, 66u8, 147u8, 183u8, 56u8,
        37u8, 111u8, 239u8, 169u8, 30u8, 56u8, 153u8, 211u8, 88u8, 81u8, 84u8, 153u8, 159u8, 103u8,
        210u8, 129u8, 179u8, 245u8, 4u8, 202u8, 12u8, 212u8, 99u8, 89u8, 186u8, 100u8, 12u8, 155u8,
        14u8, 246u8, 207u8, 30u8, 151u8, 40u8, 190u8, 223u8,
    ],
    [
        31u8, 125u8, 39u8, 138u8, 6u8, 90u8, 209u8, 133u8, 171u8, 109u8, 237u8, 146u8, 197u8,
        221u8, 120u8, 233u8, 242u8, 126u8, 77u8, 39u8, 72u8, 34u8, 9u8, 193u8, 57u8, 34u8, 103u8,
        79u8, 17u8, 84u8, 254u8, 244u8, 25u8, 4u8, 165u8, 196u8, 48u8, 125u8, 43u8, 74u8, 78u8,
        187u8, 237u8, 33u8, 80u8, 64u8, 233u8, 143u8, 199u8, 102u8, 248u8, 134u8, 180u8, 40u8,
        64u8, 192u8, 223u8, 103u8, 129u8, 143u8, 35u8, 245u8, 207u8, 104u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        36u8, 211u8, 15u8, 67u8, 133u8, 170u8, 16u8, 120u8, 204u8, 137u8, 190u8, 15u8, 229u8, 76u8,
        73u8, 102u8, 231u8, 56u8, 178u8, 68u8, 83u8, 101u8, 184u8, 2u8, 69u8, 213u8, 212u8, 4u8,
        118u8, 98u8, 111u8, 249u8, 21u8, 91u8, 194u8, 140u8, 5u8, 151u8, 246u8, 166u8, 137u8,
        173u8, 51u8, 51u8, 198u8, 59u8, 193u8, 43u8, 99u8, 246u8, 94u8, 231u8, 216u8, 111u8, 83u8,
        15u8, 222u8, 11u8, 112u8, 36u8, 162u8, 140u8, 228u8, 193u8,
    ],
    vk_beta_g2: [
        27u8, 139u8, 4u8, 27u8, 0u8, 65u8, 196u8, 87u8, 217u8, 72u8, 170u8, 228u8, 51u8, 66u8,
        226u8, 188u8, 173u8, 208u8, 194u8, 221u8, 67u8, 53u8, 8u8, 226u8, 238u8, 252u8, 29u8,
        233u8, 199u8, 80u8, 74u8, 202u8, 15u8, 197u8, 180u8, 76u8, 55u8, 198u8, 106u8, 91u8, 43u8,
        154u8, 48u8, 196u8, 92u8, 185u8, 127u8, 108u8, 195u8, 143u8, 240u8, 66u8, 197u8, 200u8,
        100u8, 128u8, 255u8, 120u8, 84u8, 62u8, 16u8, 28u8, 23u8, 138u8, 42u8, 10u8, 36u8, 204u8,
        199u8, 150u8, 148u8, 230u8, 178u8, 39u8, 79u8, 21u8, 204u8, 209u8, 143u8, 53u8, 253u8,
        171u8, 161u8, 215u8, 140u8, 157u8, 187u8, 190u8, 36u8, 62u8, 193u8, 172u8, 255u8, 239u8,
        67u8, 96u8, 14u8, 177u8, 198u8, 254u8, 119u8, 58u8, 42u8, 109u8, 194u8, 144u8, 53u8, 156u8,
        250u8, 77u8, 255u8, 152u8, 60u8, 76u8, 135u8, 185u8, 22u8, 8u8, 217u8, 0u8, 9u8, 126u8,
        236u8, 217u8, 18u8, 3u8, 19u8, 89u8,
    ],
    vk_gamma_g2: [
        0u8, 65u8, 212u8, 58u8, 120u8, 112u8, 108u8, 57u8, 90u8, 108u8, 231u8, 48u8, 78u8, 237u8,
        237u8, 50u8, 246u8, 84u8, 50u8, 145u8, 249u8, 57u8, 19u8, 135u8, 183u8, 90u8, 105u8, 204u8,
        203u8, 37u8, 218u8, 180u8, 9u8, 215u8, 88u8, 110u8, 172u8, 202u8, 20u8, 188u8, 20u8, 251u8,
        62u8, 235u8, 47u8, 100u8, 243u8, 232u8, 71u8, 163u8, 173u8, 251u8, 203u8, 208u8, 107u8,
        199u8, 20u8, 219u8, 126u8, 104u8, 105u8, 134u8, 155u8, 205u8, 28u8, 14u8, 225u8, 229u8,
        117u8, 174u8, 91u8, 51u8, 176u8, 90u8, 137u8, 62u8, 57u8, 108u8, 119u8, 74u8, 248u8, 102u8,
        38u8, 126u8, 159u8, 196u8, 108u8, 176u8, 118u8, 141u8, 236u8, 51u8, 140u8, 121u8, 17u8,
        208u8, 11u8, 53u8, 45u8, 160u8, 250u8, 154u8, 90u8, 16u8, 149u8, 144u8, 189u8, 150u8,
        102u8, 37u8, 213u8, 23u8, 70u8, 106u8, 234u8, 57u8, 133u8, 230u8, 235u8, 14u8, 6u8, 97u8,
        38u8, 46u8, 108u8, 186u8, 49u8, 118u8,
    ],
    vk_delta_g2: [
        22u8, 11u8, 52u8, 184u8, 69u8, 113u8, 102u8, 163u8, 6u8, 183u8, 254u8, 39u8, 246u8, 72u8,
        86u8, 227u8, 163u8, 159u8, 113u8, 123u8, 3u8, 83u8, 58u8, 96u8, 120u8, 187u8, 44u8, 5u8,
        254u8, 182u8, 141u8, 181u8, 26u8, 0u8, 121u8, 250u8, 146u8, 148u8, 16u8, 220u8, 34u8,
        114u8, 75u8, 6u8, 231u8, 228u8, 181u8, 214u8, 99u8, 240u8, 221u8, 16u8, 144u8, 193u8,
        125u8, 235u8, 162u8, 20u8, 78u8, 151u8, 186u8, 31u8, 203u8, 141u8, 17u8, 133u8, 139u8,
        223u8, 247u8, 71u8, 146u8, 113u8, 175u8, 48u8, 195u8, 225u8, 209u8, 140u8, 118u8, 81u8,
        222u8, 228u8, 234u8, 101u8, 75u8, 73u8, 101u8, 118u8, 181u8, 1u8, 89u8, 144u8, 178u8, 59u8,
        162u8, 255u8, 4u8, 218u8, 130u8, 184u8, 34u8, 133u8, 21u8, 158u8, 253u8, 214u8, 43u8,
        151u8, 62u8, 63u8, 34u8, 132u8, 126u8, 70u8, 146u8, 240u8, 12u8, 91u8, 226u8, 244u8, 198u8,
        115u8, 118u8, 156u8, 123u8, 32u8, 170u8, 241u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [124u8, 20u8, 75u8, 174u8, 171u8, 10u8, 149u8, 221u8, 249u8, 151u8, 189u8, 218u8, 239u8, 155u8, 164u8, 144u8, 209u8, 30u8, 4u8, 201u8, 250u8, 15u8, 163u8, 158u8, 181u8, 70u8, 109u8, 58u8, 119u8, 26u8, 220u8, 146u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_ea625e6df77853b4")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x007c144baeab0a95ddf997bddaef9ba490d11e04c9fa0fa39eb5466d3a771adc92\x00=======END GROTH16 VK SETUP V1=======\x00";
