// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        6u8, 2u8, 182u8, 13u8, 208u8, 137u8, 158u8, 131u8, 45u8, 233u8, 26u8, 167u8, 126u8, 193u8,
        232u8, 236u8, 230u8, 139u8, 11u8, 101u8, 46u8, 152u8, 38u8, 132u8, 154u8, 165u8, 239u8,
        252u8, 224u8, 53u8, 240u8, 46u8, 12u8, 72u8, 100u8, 97u8, 234u8, 39u8, 93u8, 133u8, 51u8,
        59u8, 247u8, 246u8, 62u8, 102u8, 37u8, 17u8, 119u8, 149u8, 210u8, 33u8, 109u8, 50u8, 120u8,
        22u8, 62u8, 217u8, 130u8, 5u8, 255u8, 197u8, 237u8, 174u8,
    ],
    [
        25u8, 90u8, 232u8, 6u8, 27u8, 250u8, 117u8, 128u8, 242u8, 158u8, 174u8, 217u8, 34u8, 114u8,
        92u8, 36u8, 28u8, 192u8, 134u8, 36u8, 58u8, 29u8, 197u8, 251u8, 146u8, 194u8, 33u8, 29u8,
        45u8, 95u8, 219u8, 27u8, 10u8, 251u8, 136u8, 120u8, 152u8, 213u8, 190u8, 221u8, 233u8,
        66u8, 53u8, 164u8, 82u8, 16u8, 26u8, 61u8, 170u8, 205u8, 234u8, 146u8, 10u8, 102u8, 137u8,
        195u8, 18u8, 179u8, 11u8, 115u8, 176u8, 68u8, 140u8, 238u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        1u8, 71u8, 47u8, 45u8, 176u8, 172u8, 26u8, 205u8, 138u8, 230u8, 69u8, 17u8, 100u8, 203u8,
        174u8, 250u8, 11u8, 198u8, 177u8, 40u8, 160u8, 76u8, 124u8, 215u8, 15u8, 155u8, 115u8,
        150u8, 34u8, 73u8, 244u8, 35u8, 37u8, 28u8, 100u8, 231u8, 114u8, 171u8, 198u8, 65u8, 204u8,
        142u8, 84u8, 40u8, 8u8, 84u8, 98u8, 47u8, 104u8, 189u8, 19u8, 137u8, 175u8, 206u8, 134u8,
        154u8, 33u8, 93u8, 79u8, 18u8, 203u8, 67u8, 229u8, 44u8,
    ],
    vk_beta_g2: [
        29u8, 88u8, 33u8, 18u8, 217u8, 13u8, 24u8, 181u8, 22u8, 186u8, 98u8, 23u8, 181u8, 7u8,
        60u8, 138u8, 59u8, 1u8, 181u8, 5u8, 175u8, 133u8, 243u8, 126u8, 123u8, 106u8, 114u8, 239u8,
        157u8, 87u8, 171u8, 93u8, 4u8, 239u8, 254u8, 12u8, 81u8, 122u8, 130u8, 202u8, 99u8, 153u8,
        35u8, 146u8, 118u8, 237u8, 234u8, 113u8, 218u8, 95u8, 141u8, 20u8, 132u8, 204u8, 227u8,
        109u8, 211u8, 43u8, 77u8, 233u8, 89u8, 129u8, 171u8, 110u8, 38u8, 175u8, 180u8, 128u8,
        229u8, 111u8, 11u8, 204u8, 3u8, 125u8, 60u8, 174u8, 122u8, 18u8, 211u8, 84u8, 69u8, 65u8,
        229u8, 26u8, 56u8, 181u8, 98u8, 100u8, 240u8, 116u8, 33u8, 172u8, 73u8, 25u8, 219u8, 155u8,
        40u8, 88u8, 171u8, 126u8, 40u8, 249u8, 51u8, 117u8, 86u8, 218u8, 82u8, 121u8, 62u8, 86u8,
        140u8, 215u8, 119u8, 116u8, 197u8, 233u8, 177u8, 60u8, 49u8, 158u8, 118u8, 42u8, 255u8,
        92u8, 201u8, 123u8, 22u8, 210u8,
    ],
    vk_gamma_g2: [
        16u8, 194u8, 34u8, 207u8, 233u8, 157u8, 50u8, 79u8, 121u8, 55u8, 40u8, 118u8, 167u8, 111u8,
        190u8, 225u8, 5u8, 161u8, 48u8, 178u8, 218u8, 148u8, 15u8, 102u8, 127u8, 193u8, 235u8,
        83u8, 24u8, 200u8, 130u8, 115u8, 23u8, 104u8, 68u8, 211u8, 66u8, 59u8, 15u8, 235u8, 58u8,
        232u8, 80u8, 246u8, 139u8, 0u8, 151u8, 54u8, 241u8, 110u8, 211u8, 192u8, 207u8, 111u8,
        190u8, 184u8, 215u8, 195u8, 226u8, 214u8, 216u8, 250u8, 209u8, 131u8, 17u8, 103u8, 116u8,
        3u8, 56u8, 165u8, 168u8, 145u8, 70u8, 82u8, 76u8, 193u8, 29u8, 207u8, 9u8, 25u8, 18u8,
        154u8, 194u8, 253u8, 140u8, 211u8, 86u8, 213u8, 214u8, 85u8, 69u8, 65u8, 114u8, 66u8,
        241u8, 100u8, 29u8, 73u8, 13u8, 232u8, 17u8, 14u8, 144u8, 90u8, 227u8, 55u8, 29u8, 98u8,
        206u8, 121u8, 155u8, 175u8, 1u8, 195u8, 62u8, 38u8, 132u8, 86u8, 65u8, 229u8, 69u8, 186u8,
        99u8, 14u8, 116u8, 115u8, 182u8, 67u8,
    ],
    vk_delta_g2: [
        44u8, 220u8, 90u8, 7u8, 53u8, 154u8, 97u8, 42u8, 12u8, 95u8, 8u8, 193u8, 10u8, 103u8,
        116u8, 50u8, 215u8, 2u8, 56u8, 4u8, 176u8, 194u8, 129u8, 254u8, 98u8, 53u8, 28u8, 70u8,
        50u8, 123u8, 113u8, 88u8, 24u8, 247u8, 155u8, 153u8, 7u8, 38u8, 162u8, 49u8, 210u8, 185u8,
        229u8, 250u8, 28u8, 186u8, 178u8, 27u8, 158u8, 173u8, 130u8, 78u8, 62u8, 47u8, 80u8, 183u8,
        58u8, 61u8, 100u8, 163u8, 85u8, 49u8, 107u8, 221u8, 8u8, 213u8, 237u8, 54u8, 160u8, 167u8,
        200u8, 100u8, 129u8, 119u8, 183u8, 200u8, 66u8, 185u8, 239u8, 120u8, 7u8, 27u8, 5u8, 164u8,
        211u8, 107u8, 30u8, 16u8, 36u8, 201u8, 230u8, 86u8, 84u8, 122u8, 166u8, 120u8, 33u8, 217u8,
        44u8, 194u8, 70u8, 33u8, 148u8, 56u8, 214u8, 211u8, 49u8, 201u8, 94u8, 110u8, 238u8, 177u8,
        126u8, 118u8, 194u8, 130u8, 106u8, 70u8, 185u8, 190u8, 144u8, 24u8, 165u8, 56u8, 22u8,
        220u8, 154u8, 35u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [216u8, 241u8, 33u8, 79u8, 8u8, 36u8, 35u8, 59u8, 173u8, 82u8, 242u8, 218u8, 173u8, 157u8, 232u8, 82u8, 73u8, 124u8, 151u8, 233u8, 40u8, 152u8, 84u8, 39u8, 249u8, 41u8, 20u8, 134u8, 234u8, 137u8, 183u8, 179u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_06eddb9b391783ea")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00d8f1214f0824233bad52f2daad9de852497c97e928985427f9291486ea89b7b3\x00=======END GROTH16 VK SETUP V1=======\x00";
