// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        39u8, 255u8, 182u8, 83u8, 36u8, 30u8, 4u8, 27u8, 70u8, 79u8, 230u8, 23u8, 16u8, 115u8,
        79u8, 20u8, 190u8, 178u8, 116u8, 53u8, 34u8, 24u8, 39u8, 65u8, 76u8, 103u8, 244u8, 56u8,
        1u8, 17u8, 232u8, 244u8, 6u8, 62u8, 79u8, 252u8, 191u8, 110u8, 118u8, 49u8, 233u8, 122u8,
        86u8, 2u8, 134u8, 96u8, 16u8, 70u8, 13u8, 108u8, 57u8, 111u8, 76u8, 136u8, 108u8, 75u8,
        169u8, 108u8, 48u8, 91u8, 195u8, 72u8, 193u8, 116u8,
    ],
    [
        33u8, 109u8, 194u8, 120u8, 153u8, 50u8, 78u8, 177u8, 230u8, 202u8, 56u8, 234u8, 168u8,
        51u8, 241u8, 249u8, 69u8, 51u8, 201u8, 150u8, 50u8, 50u8, 252u8, 124u8, 219u8, 142u8, 22u8,
        98u8, 218u8, 1u8, 199u8, 106u8, 31u8, 221u8, 196u8, 144u8, 77u8, 94u8, 94u8, 34u8, 7u8,
        153u8, 54u8, 245u8, 247u8, 56u8, 242u8, 231u8, 233u8, 165u8, 203u8, 63u8, 252u8, 142u8,
        105u8, 206u8, 99u8, 146u8, 91u8, 10u8, 225u8, 63u8, 7u8, 7u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        46u8, 21u8, 212u8, 220u8, 181u8, 64u8, 238u8, 231u8, 123u8, 48u8, 165u8, 194u8, 173u8,
        143u8, 144u8, 66u8, 59u8, 169u8, 201u8, 171u8, 228u8, 99u8, 64u8, 97u8, 218u8, 254u8,
        157u8, 111u8, 157u8, 147u8, 80u8, 200u8, 33u8, 20u8, 28u8, 106u8, 110u8, 4u8, 226u8, 242u8,
        157u8, 17u8, 67u8, 236u8, 169u8, 81u8, 191u8, 40u8, 251u8, 189u8, 121u8, 156u8, 53u8, 57u8,
        227u8, 219u8, 175u8, 173u8, 220u8, 204u8, 40u8, 79u8, 121u8, 32u8,
    ],
    vk_beta_g2: [
        45u8, 48u8, 157u8, 166u8, 116u8, 77u8, 68u8, 98u8, 101u8, 63u8, 228u8, 202u8, 30u8, 203u8,
        4u8, 187u8, 71u8, 22u8, 39u8, 159u8, 127u8, 79u8, 12u8, 160u8, 67u8, 20u8, 22u8, 182u8,
        131u8, 107u8, 94u8, 70u8, 25u8, 244u8, 237u8, 158u8, 23u8, 11u8, 152u8, 204u8, 26u8, 238u8,
        29u8, 50u8, 121u8, 229u8, 153u8, 29u8, 51u8, 175u8, 10u8, 192u8, 137u8, 237u8, 39u8, 232u8,
        42u8, 116u8, 38u8, 146u8, 12u8, 244u8, 106u8, 133u8, 39u8, 66u8, 78u8, 245u8, 166u8, 43u8,
        196u8, 188u8, 112u8, 17u8, 14u8, 137u8, 228u8, 49u8, 28u8, 97u8, 243u8, 16u8, 126u8, 137u8,
        35u8, 133u8, 56u8, 162u8, 30u8, 177u8, 160u8, 40u8, 148u8, 149u8, 146u8, 104u8, 7u8, 38u8,
        17u8, 246u8, 39u8, 183u8, 225u8, 99u8, 234u8, 246u8, 235u8, 221u8, 145u8, 229u8, 117u8,
        76u8, 80u8, 118u8, 19u8, 157u8, 85u8, 224u8, 209u8, 45u8, 70u8, 250u8, 95u8, 222u8, 76u8,
        176u8, 37u8, 128u8,
    ],
    vk_gamma_g2: [
        12u8, 104u8, 118u8, 41u8, 79u8, 117u8, 68u8, 78u8, 37u8, 251u8, 149u8, 181u8, 64u8, 76u8,
        199u8, 194u8, 211u8, 22u8, 46u8, 150u8, 38u8, 35u8, 9u8, 81u8, 51u8, 103u8, 159u8, 9u8,
        110u8, 205u8, 83u8, 230u8, 24u8, 189u8, 98u8, 91u8, 26u8, 16u8, 180u8, 117u8, 31u8, 73u8,
        194u8, 59u8, 249u8, 111u8, 141u8, 159u8, 79u8, 22u8, 185u8, 59u8, 35u8, 183u8, 2u8, 55u8,
        250u8, 119u8, 141u8, 251u8, 103u8, 129u8, 247u8, 192u8, 47u8, 129u8, 162u8, 47u8, 68u8,
        239u8, 22u8, 133u8, 68u8, 76u8, 26u8, 65u8, 42u8, 127u8, 164u8, 7u8, 165u8, 202u8, 160u8,
        0u8, 33u8, 237u8, 215u8, 254u8, 164u8, 60u8, 7u8, 234u8, 19u8, 141u8, 74u8, 49u8, 36u8,
        49u8, 78u8, 22u8, 30u8, 206u8, 99u8, 27u8, 99u8, 12u8, 254u8, 13u8, 173u8, 151u8, 6u8,
        222u8, 70u8, 35u8, 24u8, 160u8, 255u8, 181u8, 184u8, 61u8, 219u8, 121u8, 95u8, 85u8, 29u8,
        50u8, 227u8, 226u8,
    ],
    vk_delta_g2: [
        26u8, 61u8, 41u8, 81u8, 219u8, 237u8, 128u8, 244u8, 254u8, 35u8, 25u8, 235u8, 165u8, 146u8,
        174u8, 20u8, 252u8, 251u8, 228u8, 22u8, 146u8, 178u8, 170u8, 69u8, 86u8, 224u8, 33u8, 72u8,
        139u8, 226u8, 200u8, 194u8, 34u8, 9u8, 77u8, 86u8, 235u8, 72u8, 193u8, 5u8, 235u8, 116u8,
        101u8, 212u8, 156u8, 252u8, 125u8, 21u8, 122u8, 244u8, 171u8, 147u8, 248u8, 169u8, 175u8,
        177u8, 87u8, 240u8, 170u8, 113u8, 103u8, 3u8, 42u8, 87u8, 1u8, 235u8, 136u8, 78u8, 18u8,
        30u8, 143u8, 14u8, 240u8, 116u8, 125u8, 131u8, 219u8, 227u8, 12u8, 148u8, 201u8, 161u8,
        170u8, 230u8, 236u8, 222u8, 243u8, 113u8, 82u8, 135u8, 72u8, 2u8, 218u8, 85u8, 170u8, 73u8,
        31u8, 202u8, 2u8, 211u8, 115u8, 141u8, 109u8, 7u8, 64u8, 32u8, 208u8, 6u8, 110u8, 23u8,
        239u8, 112u8, 174u8, 65u8, 30u8, 131u8, 184u8, 137u8, 65u8, 179u8, 69u8, 13u8, 91u8, 226u8,
        170u8, 215u8, 107u8, 7u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [203u8, 113u8, 24u8, 251u8, 218u8, 54u8, 14u8, 59u8, 95u8, 115u8, 119u8, 98u8, 102u8, 25u8, 164u8, 245u8, 96u8, 249u8, 207u8, 37u8, 201u8, 123u8, 141u8, 230u8, 150u8, 117u8, 150u8, 131u8, 33u8, 165u8, 179u8, 54u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_463ab463b320e379")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00cb7118fbda360e3b5f7377626619a4f560f9cf25c97b8de69675968321a5b336\x00=======END GROTH16 VK SETUP V1=======\x00";
