// INSECURE TEST KEY -- UNSAFE FOR PRODUCTION.
// Generated with `--insecure-test-keys`: the Groth16 setup randomness comes
// from a fixed public seed, so anyone can forge proofs this key accepts. Use
// it only in tests and never deploy a program that verifies against it.
// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

// INSECURE TEST SETUP: the secret setup randomness is public or
// untrusted. Whoever knows it can make this verifying key accept a
// proof for any public inputs without a valid witness. Do not deploy
// it to devnet or mainnet.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        38u8, 23u8, 10u8, 14u8, 17u8, 171u8, 2u8, 163u8, 114u8, 51u8, 112u8, 172u8, 158u8, 202u8,
        135u8, 230u8, 26u8, 174u8, 49u8, 193u8, 121u8, 130u8, 121u8, 127u8, 246u8, 153u8, 168u8,
        8u8, 101u8, 118u8, 145u8, 7u8, 7u8, 228u8, 152u8, 73u8, 13u8, 81u8, 58u8, 69u8, 64u8,
        108u8, 107u8, 123u8, 252u8, 44u8, 216u8, 194u8, 118u8, 160u8, 100u8, 67u8, 83u8, 108u8,
        20u8, 9u8, 194u8, 241u8, 124u8, 96u8, 18u8, 153u8, 78u8, 46u8,
    ],
    [
        0u8, 182u8, 100u8, 73u8, 211u8, 165u8, 72u8, 149u8, 41u8, 222u8, 154u8, 153u8, 136u8,
        231u8, 116u8, 253u8, 77u8, 248u8, 143u8, 76u8, 10u8, 6u8, 240u8, 201u8, 42u8, 156u8, 107u8,
        8u8, 9u8, 193u8, 120u8, 134u8, 6u8, 40u8, 133u8, 160u8, 110u8, 89u8, 224u8, 118u8, 144u8,
        195u8, 31u8, 55u8, 235u8, 62u8, 52u8, 93u8, 105u8, 26u8, 233u8, 221u8, 206u8, 255u8, 158u8,
        1u8, 165u8, 227u8, 95u8, 225u8, 129u8, 163u8, 161u8, 135u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        43u8, 226u8, 196u8, 120u8, 150u8, 27u8, 53u8, 67u8, 237u8, 4u8, 164u8, 253u8, 84u8, 183u8,
        60u8, 144u8, 149u8, 75u8, 139u8, 153u8, 21u8, 217u8, 119u8, 24u8, 42u8, 254u8, 239u8,
        244u8, 15u8, 227u8, 122u8, 125u8, 27u8, 151u8, 194u8, 175u8, 191u8, 142u8, 175u8, 108u8,
        222u8, 230u8, 91u8, 241u8, 230u8, 198u8, 51u8, 125u8, 79u8, 194u8, 77u8, 95u8, 57u8, 76u8,
        142u8, 73u8, 238u8, 82u8, 125u8, 199u8, 164u8, 228u8, 151u8, 64u8,
    ],
    vk_beta_g2: [
        35u8, 255u8, 222u8, 128u8, 133u8, 235u8, 103u8, 210u8, 127u8, 83u8, 201u8, 183u8, 88u8,
        52u8, 13u8, 235u8, 77u8, 204u8, 38u8, 47u8, 93u8, 65u8, 7u8, 91u8, 223u8, 221u8, 248u8,
        237u8, 21u8, 4u8, 189u8, 16u8, 30u8, 28u8, 238u8, 207u8, 137u8, 238u8, 38u8, 128u8, 158u8,
        13u8, 171u8, 212u8, 37u8, 123u8, 187u8, 42u8, 207u8, 131u8, 184u8, 140u8, 60u8, 214u8,
        198u8, 208u8, 165u8, 104u8, 86u8, 175u8, 158u8, 129u8, 244u8, 205u8, 7u8, 60u8, 195u8,
        173u8, 6u8, 26u8, 148u8, 220u8, 234u8, 170u8, 139u8, 233u8, 220u8, 9u8, 19u8, 142u8, 41u8,
        59u8, 161u8, 198u8, 7u8, 233u8, 119u8, 83u8, 21u8, 19u8, 212u8, 170u8, 81u8, 57u8, 28u8,
        16u8, 0u8, 60u8, 229u8, 80u8, 19u8, 29u8, 228u8, 25u8, 198u8, 93u8, 208u8, 121u8, 86u8,
        140u8, 152u8, 131u8, 150u8, 51u8, 144u8, 156u8, 127u8, 181u8, 132u8, 48u8, 104u8, 113u8,
        202u8, 119u8, 157u8, 231u8, 221u8, 188u8,
    ],
    vk_gamma_g2: [
        26u8, 217u8, 26u8, 69u8, 139u8, 194u8, 183u8, 34u8, 201u8, 105u8, 221u8, 38u8, 29u8, 43u8,
        102u8, 201u8, 252u8, 112u8, 0u8, 33u8, 188u8, 244u8, 36u8, 89u8, 17u8, 219u8, 86u8, 127u8,
        4u8, 59u8, 129u8, 185u8, 15u8, 56u8, 216u8, 243u8, 50u8, 220u8, 201u8, 14u8, 180u8, 150u8,
        42u8, 167u8, 176u8, 206u8, 160u8, 245u8, 202u8, 182u8, 213u8, 164u8, 230u8, 20u8, 16u8,
        103u8, 26u8, 87u8, 68u8, 45u8, 201u8, 117u8, 103u8, 143u8, 31u8, 7u8, 144u8, 87u8, 202u8,
        111u8, 161u8, 21u8, 254u8, 212u8, 245u8, 244u8, 109u8, 105u8, 1u8, 64u8, 7u8, 105u8, 177u8,
        49u8, 153u8, 28u8, 200u8, 0u8, 89u8, 249u8, 173u8, 232u8, 40u8, 43u8, 38u8, 71u8, 40u8,
        65u8, 148u8, 84u8, 140u8, 250u8, 8u8, 73u8, 188u8, 176u8, 179u8, 95u8, 195u8, 116u8, 205u8,
        89u8, 68u8, 179u8, 42u8, 251u8, 8u8, 66u8, 232u8, 73u8, 103u8, 24u8, 68u8, 166u8, 138u8,
        1u8, 149u8, 118u8,
    ],
    vk_delta_g2: [
        11u8, 199u8, 222u8, 113u8, 72u8, 187u8, 31u8, 179u8, 87u8, 131u8, 144u8, 153u8, 56u8,
        230u8, 136u8, 49u8, 30u8, 195u8, 129u8, 181u8, 251u8, 75u8, 213u8, 95u8, 72u8, 105u8,
        200u8, 225u8, 155u8, 204u8, 142u8, 54u8, 38u8, 29u8, 121u8, 33u8, 232u8, 91u8, 206u8,
        100u8, 120u8, 136u8, 170u8, 170u8, 235u8, 119u8, 181u8, 249u8, 100u8, 170u8, 117u8, 133u8,
        170u8, 88u8, 116u8, 29u8, 156u8, 220u8, 84u8, 200u8, 104u8, 34u8, 210u8, 246u8, 8u8, 151u8,
        71u8, 8u8, 232u8, 244u8, 228u8, 124u8, 208u8, 177u8, 235u8, 95u8, 134u8, 24u8, 250u8,
        163u8, 211u8, 27u8, 227u8, 242u8, 128u8, 162u8, 231u8, 81u8, 46u8, 154u8, 83u8, 13u8,
        200u8, 51u8, 132u8, 118u8, 22u8, 81u8, 165u8, 227u8, 127u8, 34u8, 167u8, 26u8, 191u8, 85u8,
        219u8, 37u8, 16u8, 94u8, 104u8, 162u8, 65u8, 240u8, 248u8, 95u8, 141u8, 126u8, 55u8, 90u8,
        111u8, 244u8, 63u8, 113u8, 139u8, 52u8, 142u8, 108u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [212u8, 65u8, 242u8, 180u8, 8u8, 119u8, 217u8, 118u8, 212u8, 41u8, 85u8, 116u8, 226u8, 225u8, 34u8, 184u8, 191u8, 26u8, 153u8, 42u8, 44u8, 130u8, 238u8, 163u8, 142u8, 117u8, 156u8, 207u8, 156u8, 174u8, 74u8, 57u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = true;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_04a759c35f774cea")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00true\x00proving_key_sha256\x00d441f2b40877d976d4295574e2e122b8bf1a992a2c82eea38e759ccf9cae4a39\x00=======END GROTH16 VK SETUP V1=======\x00";

#[cfg(not(feature = "insecure-test-setup"))]
compile_error!("VERIFYINGKEY comes from an insecure test setup: whoever knows its setup randomness can make it accept a proof for any public inputs. Enable the `insecure-test-setup` feature only in test builds, not for a devnet or mainnet deployment.");
