// INSECURE TEST KEY -- UNSAFE FOR PRODUCTION.
// Generated with `--insecure-test-keys`: the Groth16 setup randomness comes
// from a fixed public seed, so anyone can forge proofs this key accepts. Use
// it only in tests and never deploy a program that verifies against it.
// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

// INSECURE TEST SETUP: the secret setup randomness is public or
// untrusted. Whoever knows it can make this verifying key accept a
// proof for any public inputs without a valid witness. Do not deploy
// it to devnet or mainnet.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        0u8, 118u8, 124u8, 205u8, 182u8, 240u8, 186u8, 30u8, 102u8, 2u8, 198u8, 213u8, 155u8, 79u8,
        148u8, 86u8, 184u8, 213u8, 175u8, 56u8, 107u8, 248u8, 172u8, 127u8, 52u8, 219u8, 135u8,
        46u8, 109u8, 113u8, 170u8, 119u8, 42u8, 30u8, 56u8, 149u8, 93u8, 78u8, 173u8, 224u8, 67u8,
        90u8, 140u8, 68u8, 221u8, 228u8, 174u8, 145u8, 137u8, 86u8, 29u8, 99u8, 44u8, 247u8, 184u8,
        110u8, 144u8, 61u8, 61u8, 50u8, 199u8, 33u8, 11u8, 164u8,
    ],
    [
        25u8, 149u8, 194u8, 207u8, 60u8, 167u8, 228u8, 173u8, 229u8, 54u8, 27u8, 118u8, 110u8,
        143u8, 84u8, 63u8, 116u8, 64u8, 21u8, 92u8, 152u8, 158u8, 19u8, 93u8, 40u8, 207u8, 104u8,
        109u8, 194u8, 15u8, 144u8, 169u8, 36u8, 178u8, 82u8, 182u8, 246u8, 128u8, 231u8, 52u8,
        53u8, 186u8, 226u8, 140u8, 141u8, 235u8, 170u8, 234u8, 113u8, 177u8, 169u8, 154u8, 97u8,
        100u8, 82u8, 194u8, 194u8, 17u8, 131u8, 153u8, 156u8, 2u8, 76u8, 12u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        39u8, 69u8, 230u8, 1u8, 188u8, 17u8, 15u8, 194u8, 246u8, 26u8, 36u8, 136u8, 136u8, 193u8,
        97u8, 170u8, 164u8, 41u8, 18u8, 111u8, 120u8, 150u8, 207u8, 151u8, 216u8, 23u8, 117u8,
        232u8, 9u8, 111u8, 9u8, 14u8, 46u8, 214u8, 27u8, 193u8, 128u8, 25u8, 70u8, 135u8, 221u8,
        153u8, 161u8, 233u8, 36u8, 159u8, 240u8, 63u8, 25u8, 17u8, 147u8, 248u8, 67u8, 4u8, 61u8,
        236u8, 18u8, 141u8, 117u8, 103u8, 70u8, 7u8, 233u8, 174u8,
    ],
    vk_beta_g2: [
        29u8, 242u8, 97u8, 146u8, 81u8, 66u8, 175u8, 2u8, 4u8, 194u8, 101u8, 255u8, 181u8, 94u8,
        66u8, 45u8, 118u8, 188u8, 192u8, 187u8, 132u8, 157u8, 197u8, 216u8, 141u8, 204u8, 64u8,
        9u8, 43u8, 86u8, 190u8, 230u8, 23u8, 80u8, 66u8, 2u8, 34u8, 227u8, 132u8, 10u8, 238u8,
        249u8, 144u8, 33u8, 179u8, 30u8, 90u8, 84u8, 32u8, 103u8, 45u8, 216u8, 133u8, 77u8, 42u8,
        144u8, 72u8, 235u8, 7u8, 185u8, 122u8, 70u8, 171u8, 115u8, 47u8, 154u8, 46u8, 209u8, 134u8,
        231u8, 116u8, 22u8, 229u8, 50u8, 60u8, 111u8, 219u8, 6u8, 142u8, 140u8, 163u8, 89u8, 162u8,
        192u8, 64u8, 32u8, 81u8, 185u8, 222u8, 121u8, 96u8, 230u8, 199u8, 88u8, 63u8, 56u8, 41u8,
        24u8, 222u8, 209u8, 7u8, 238u8, 8u8, 124u8, 165u8, 185u8, 174u8, 189u8, 218u8, 237u8, 58u8,
        75u8, 204u8, 54u8, 109u8, 139u8, 196u8, 192u8, 163u8, 164u8, 125u8, 220u8, 229u8, 94u8,
        95u8, 148u8, 153u8, 61u8,
    ],
    vk_gamma_g2: [
        38u8, 19u8, 62u8, 28u8, 235u8, 119u8, 101u8, 197u8, 67u8, 228u8, 2u8, 129u8, 215u8, 220u8,
        137u8, 74u8, 128u8, 242u8, 236u8, 78u8, 221u8, 34u8, 212u8, 210u8, 17u8, 212u8, 7u8, 70u8,
        181u8, 243u8, 97u8, 91u8, 27u8, 87u8, 34u8, 214u8, 10u8, 27u8, 225u8, 165u8, 42u8, 214u8,
        124u8, 155u8, 174u8, 195u8, 91u8, 47u8, 98u8, 86u8, 54u8, 173u8, 163u8, 114u8, 119u8, 2u8,
        237u8, 71u8, 191u8, 35u8, 1u8, 84u8, 221u8, 204u8, 32u8, 62u8, 252u8, 164u8, 232u8, 228u8,
        27u8, 212u8, 70u8, 49u8, 224u8, 240u8, 229u8, 226u8, 160u8, 58u8, 24u8, 92u8, 101u8, 124u8,
        222u8, 23u8, 104u8, 221u8, 7u8, 38u8, 223u8, 122u8, 66u8, 111u8, 221u8, 201u8, 9u8, 69u8,
        37u8, 83u8, 125u8, 125u8, 38u8, 194u8, 19u8, 239u8, 215u8, 126u8, 248u8, 151u8, 188u8,
        154u8, 105u8, 220u8, 68u8, 200u8, 125u8, 63u8, 219u8, 112u8, 35u8, 59u8, 56u8, 151u8,
        124u8, 5u8, 123u8, 198u8,
    ],
    vk_delta_g2: [
        21u8, 20u8, 58u8, 135u8, 216u8, 76u8, 104u8, 19u8, 127u8, 41u8, 250u8, 128u8, 191u8, 136u8,
        238u8, 61u8, 58u8, 72u8, 243u8, 162u8, 130u8, 156u8, 140u8, 14u8, 212u8, 132u8, 3u8, 250u8,
        235u8, 106u8, 138u8, 226u8, 22u8, 221u8, 140u8, 36u8, 76u8, 111u8, 60u8, 88u8, 64u8, 209u8,
        173u8, 253u8, 248u8, 54u8, 69u8, 134u8, 95u8, 73u8, 142u8, 247u8, 221u8, 236u8, 98u8, 92u8,
        2u8, 115u8, 120u8, 146u8, 53u8, 83u8, 214u8, 129u8, 13u8, 169u8, 240u8, 155u8, 5u8, 121u8,
        6u8, 229u8, 110u8, 105u8, 128u8, 118u8, 86u8, 180u8, 242u8, 11u8, 188u8, 190u8, 143u8,
        52u8, 108u8, 154u8, 85u8, 74u8, 104u8, 249u8, 56u8, 66u8, 198u8, 91u8, 100u8, 188u8, 3u8,
        187u8, 137u8, 248u8, 47u8, 59u8, 38u8, 134u8, 243u8, 138u8, 214u8, 131u8, 55u8, 138u8,
        202u8, 153u8, 177u8, 107u8, 77u8, 10u8, 180u8, 23u8, 45u8, 112u8, 166u8, 74u8, 126u8, 81u8,
        206u8, 205u8, 141u8, 217u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [102u8, 62u8, 109u8, 152u8, 104u8, 182u8, 215u8, 161u8, 202u8, 13u8, 46u8, 199u8, 242u8, 236u8, 96u8, 45u8, 44u8, 145u8, 22u8, 29u8, 162u8, 206u8, 134u8, 63u8, 35u8, 88u8, 116u8, 60u8, 33u8, 231u8, 32u8, 158u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = true;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_2bd44010ec9fd125")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00true\x00proving_key_sha256\x00663e6d9868b6d7a1ca0d2ec7f2ec602d2c91161da2ce863f2358743c21e7209e\x00=======END GROTH16 VK SETUP V1=======\x00";

#[cfg(not(feature = "insecure-test-setup"))]
compile_error!("VERIFYINGKEY comes from an insecure test setup: whoever knows its setup randomness can make it accept a proof for any public inputs. Enable the `insecure-test-setup` feature only in test builds, not for a devnet or mainnet deployment.");
