// INSECURE TEST KEY -- UNSAFE FOR PRODUCTION.
// Generated with `--insecure-test-keys`: the Groth16 setup randomness comes
// from a fixed public seed, so anyone can forge proofs this key accepts. Use
// it only in tests and never deploy a program that verifies against it.
// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

// INSECURE TEST SETUP: the secret setup randomness is public or
// untrusted. Whoever knows it can make this verifying key accept a
// proof for any public inputs without a valid witness. Do not deploy
// it to devnet or mainnet.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        44u8, 182u8, 207u8, 211u8, 44u8, 82u8, 206u8, 217u8, 83u8, 140u8, 148u8, 224u8, 2u8, 113u8,
        202u8, 164u8, 126u8, 127u8, 158u8, 5u8, 50u8, 47u8, 71u8, 227u8, 245u8, 200u8, 188u8,
        241u8, 130u8, 239u8, 245u8, 0u8, 44u8, 85u8, 94u8, 174u8, 103u8, 198u8, 16u8, 135u8, 146u8,
        166u8, 185u8, 39u8, 93u8, 149u8, 125u8, 182u8, 183u8, 192u8, 109u8, 227u8, 3u8, 252u8,
        58u8, 16u8, 92u8, 25u8, 201u8, 226u8, 95u8, 54u8, 153u8, 255u8,
    ],
    [
        5u8, 164u8, 173u8, 84u8, 232u8, 99u8, 50u8, 36u8, 210u8, 145u8, 21u8, 133u8, 112u8, 91u8,
        70u8, 230u8, 148u8, 44u8, 57u8, 136u8, 146u8, 253u8, 53u8, 65u8, 176u8, 253u8, 200u8,
        142u8, 165u8, 221u8, 224u8, 71u8, 40u8, 99u8, 246u8, 55u8, 75u8, 2u8, 190u8, 127u8, 200u8,
        242u8, 21u8, 193u8, 66u8, 122u8, 141u8, 218u8, 174u8, 20u8, 135u8, 201u8, 100u8, 241u8,
        23u8, 53u8, 205u8, 91u8, 194u8, 47u8, 70u8, 4u8, 136u8, 163u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        36u8, 117u8, 32u8, 28u8, 34u8, 94u8, 4u8, 189u8, 175u8, 120u8, 26u8, 201u8, 242u8, 49u8,
        37u8, 75u8, 46u8, 55u8, 221u8, 253u8, 221u8, 162u8, 224u8, 120u8, 64u8, 195u8, 213u8,
        238u8, 247u8, 247u8, 172u8, 227u8, 47u8, 158u8, 71u8, 172u8, 8u8, 25u8, 18u8, 94u8, 229u8,
        208u8, 199u8, 125u8, 235u8, 218u8, 243u8, 255u8, 32u8, 198u8, 29u8, 226u8, 20u8, 26u8,
        53u8, 189u8, 222u8, 140u8, 219u8, 132u8, 97u8, 221u8, 31u8, 213u8,
    ],
    vk_beta_g2: [
        30u8, 94u8, 239u8, 127u8, 205u8, 141u8, 139u8, 252u8, 207u8, 54u8, 130u8, 224u8, 77u8,
        114u8, 183u8, 62u8, 97u8, 251u8, 246u8, 19u8, 248u8, 53u8, 71u8, 144u8, 106u8, 251u8,
        244u8, 205u8, 215u8, 241u8, 172u8, 218u8, 0u8, 170u8, 149u8, 77u8, 139u8, 224u8, 73u8,
        231u8, 53u8, 21u8, 168u8, 74u8, 120u8, 66u8, 21u8, 22u8, 160u8, 205u8, 20u8, 31u8, 203u8,
        128u8, 30u8, 1u8, 66u8, 229u8, 212u8, 214u8, 211u8, 255u8, 101u8, 150u8, 7u8, 51u8, 76u8,
        135u8, 182u8, 6u8, 188u8, 25u8, 100u8, 165u8, 57u8, 209u8, 229u8, 33u8, 245u8, 115u8, 54u8,
        95u8, 240u8, 18u8, 187u8, 109u8, 94u8, 149u8, 8u8, 67u8, 248u8, 194u8, 123u8, 88u8, 39u8,
        108u8, 6u8, 131u8, 243u8, 63u8, 104u8, 176u8, 169u8, 160u8, 255u8, 14u8, 180u8, 71u8,
        146u8, 104u8, 244u8, 32u8, 120u8, 73u8, 82u8, 191u8, 242u8, 221u8, 240u8, 127u8, 32u8,
        177u8, 62u8, 58u8, 102u8, 36u8, 186u8, 247u8,
    ],
    vk_gamma_g2: [
        47u8, 69u8, 89u8, 235u8, 253u8, 33u8, 163u8, 88u8, 2u8, 45u8, 221u8, 108u8, 15u8, 182u8,
        153u8, 81u8, 118u8, 11u8, 79u8, 17u8, 123u8, 239u8, 78u8, 94u8, 113u8, 121u8, 142u8, 11u8,
        248u8, 32u8, 134u8, 66u8, 40u8, 195u8, 250u8, 4u8, 211u8, 194u8, 182u8, 84u8, 23u8, 155u8,
        186u8, 189u8, 173u8, 254u8, 109u8, 141u8, 38u8, 131u8, 241u8, 238u8, 42u8, 73u8, 71u8,
        232u8, 187u8, 60u8, 200u8, 208u8, 199u8, 209u8, 196u8, 208u8, 10u8, 136u8, 118u8, 215u8,
        196u8, 46u8, 10u8, 119u8, 171u8, 114u8, 251u8, 186u8, 16u8, 154u8, 214u8, 131u8, 37u8,
        200u8, 224u8, 71u8, 237u8, 210u8, 117u8, 235u8, 125u8, 251u8, 24u8, 148u8, 50u8, 55u8,
        32u8, 178u8, 40u8, 153u8, 237u8, 119u8, 143u8, 244u8, 130u8, 182u8, 234u8, 229u8, 166u8,
        232u8, 71u8, 83u8, 56u8, 22u8, 99u8, 19u8, 251u8, 40u8, 155u8, 71u8, 222u8, 55u8, 157u8,
        124u8, 154u8, 0u8, 204u8, 167u8, 250u8, 88u8,
    ],
    vk_delta_g2: [
        18u8, 117u8, 195u8, 112u8, 61u8, 125u8, 244u8, 75u8, 180u8, 191u8, 230u8, 148u8, 238u8,
        166u8, 219u8, 1u8, 90u8, 14u8, 152u8, 50u8, 211u8, 91u8, 106u8, 85u8, 55u8, 52u8, 204u8,
        52u8, 110u8, 125u8, 153u8, 166u8, 6u8, 241u8, 239u8, 2u8, 29u8, 77u8, 31u8, 50u8, 131u8,
        248u8, 42u8, 33u8, 164u8, 64u8, 233u8, 28u8, 205u8, 25u8, 205u8, 26u8, 240u8, 186u8, 124u8,
        49u8, 66u8, 103u8, 251u8, 102u8, 190u8, 133u8, 201u8, 32u8, 4u8, 88u8, 45u8, 197u8, 215u8,
        252u8, 101u8, 62u8, 153u8, 249u8, 131u8, 141u8, 29u8, 139u8, 50u8, 166u8, 252u8, 171u8,
        34u8, 175u8, 173u8, 40u8, 3u8, 61u8, 231u8, 84u8, 111u8, 195u8, 133u8, 59u8, 74u8, 171u8,
        47u8, 133u8, 59u8, 19u8, 131u8, 8u8, 215u8, 221u8, 88u8, 143u8, 158u8, 99u8, 122u8, 6u8,
        207u8, 101u8, 94u8, 163u8, 196u8, 113u8, 142u8, 34u8, 182u8, 221u8, 211u8, 237u8, 178u8,
        75u8, 223u8, 161u8, 47u8, 8u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [35u8, 73u8, 66u8, 114u8, 151u8, 33u8, 208u8, 41u8, 228u8, 145u8, 250u8, 168u8, 113u8, 190u8, 226u8, 185u8, 164u8, 122u8, 83u8, 110u8, 47u8, 210u8, 114u8, 51u8, 233u8, 137u8, 167u8, 100u8, 148u8, 79u8, 155u8, 25u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = true;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_61f71e1491f00c14")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00true\x00proving_key_sha256\x00234942729721d029e491faa871bee2b9a47a536e2fd27233e989a764944f9b19\x00=======END GROTH16 VK SETUP V1=======\x00";

#[cfg(not(feature = "insecure-test-setup"))]
compile_error!("VERIFYINGKEY comes from an insecure test setup: whoever knows its setup randomness can make it accept a proof for any public inputs. Enable the `insecure-test-setup` feature only in test builds, not for a devnet or mainnet deployment.");
