// INSECURE TEST KEY -- UNSAFE FOR PRODUCTION.
// Generated with `--insecure-test-keys`: the Groth16 setup randomness comes
// from a fixed public seed, so anyone can forge proofs this key accepts. Use
// it only in tests and never deploy a program that verifies against it.
// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

// INSECURE TEST SETUP: the secret setup randomness is public or
// untrusted. Whoever knows it can make this verifying key accept a
// proof for any public inputs without a valid witness. Do not deploy
// it to devnet or mainnet.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        37u8, 165u8, 140u8, 229u8, 242u8, 10u8, 53u8, 160u8, 19u8, 12u8, 55u8, 19u8, 207u8, 207u8,
        55u8, 112u8, 128u8, 250u8, 23u8, 200u8, 152u8, 110u8, 40u8, 70u8, 85u8, 147u8, 216u8, 13u8,
        134u8, 212u8, 114u8, 248u8, 9u8, 248u8, 253u8, 125u8, 70u8, 238u8, 188u8, 42u8, 87u8, 25u8,
        220u8, 157u8, 27u8, 250u8, 163u8, 238u8, 133u8, 188u8, 26u8, 222u8, 214u8, 51u8, 110u8,
        217u8, 60u8, 174u8, 121u8, 139u8, 64u8, 129u8, 147u8, 130u8,
    ],
    [
        39u8, 154u8, 135u8, 194u8, 217u8, 4u8, 206u8, 102u8, 113u8, 18u8, 28u8, 216u8, 24u8, 184u8,
        143u8, 169u8, 183u8, 138u8, 78u8, 235u8, 221u8, 226u8, 194u8, 96u8, 43u8, 253u8, 164u8,
        127u8, 13u8, 3u8, 240u8, 239u8, 25u8, 160u8, 145u8, 160u8, 176u8, 155u8, 251u8, 105u8,
        10u8, 196u8, 243u8, 184u8, 125u8, 213u8, 206u8, 230u8, 58u8, 101u8, 210u8, 158u8, 131u8,
        232u8, 224u8, 65u8, 82u8, 211u8, 200u8, 25u8, 65u8, 206u8, 87u8, 13u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        7u8, 233u8, 249u8, 65u8, 52u8, 81u8, 247u8, 241u8, 234u8, 220u8, 155u8, 8u8, 63u8, 38u8,
        196u8, 12u8, 116u8, 206u8, 14u8, 215u8, 120u8, 186u8, 104u8, 207u8, 57u8, 244u8, 0u8,
        233u8, 230u8, 203u8, 92u8, 181u8, 3u8, 129u8, 161u8, 97u8, 176u8, 244u8, 232u8, 241u8,
        152u8, 222u8, 24u8, 18u8, 222u8, 194u8, 171u8, 159u8, 119u8, 116u8, 246u8, 141u8, 155u8,
        4u8, 52u8, 123u8, 167u8, 219u8, 149u8, 231u8, 178u8, 27u8, 190u8, 230u8,
    ],
    vk_beta_g2: [
        25u8, 179u8, 59u8, 151u8, 208u8, 66u8, 131u8, 130u8, 129u8, 66u8, 97u8, 3u8, 137u8, 227u8,
        147u8, 17u8, 20u8, 207u8, 173u8, 10u8, 229u8, 27u8, 221u8, 3u8, 64u8, 245u8, 231u8, 50u8,
        121u8, 158u8, 57u8, 7u8, 32u8, 228u8, 251u8, 14u8, 255u8, 38u8, 126u8, 207u8, 210u8, 20u8,
        147u8, 227u8, 142u8, 42u8, 62u8, 172u8, 189u8, 145u8, 131u8, 32u8, 43u8, 205u8, 194u8,
        145u8, 176u8, 71u8, 202u8, 219u8, 24u8, 83u8, 152u8, 209u8, 31u8, 69u8, 246u8, 146u8,
        233u8, 110u8, 225u8, 198u8, 178u8, 193u8, 63u8, 243u8, 70u8, 31u8, 105u8, 238u8, 253u8,
        77u8, 253u8, 237u8, 86u8, 124u8, 74u8, 51u8, 206u8, 228u8, 180u8, 193u8, 215u8, 31u8,
        188u8, 160u8, 24u8, 110u8, 165u8, 0u8, 93u8, 215u8, 77u8, 173u8, 34u8, 166u8, 182u8, 197u8,
        123u8, 84u8, 234u8, 166u8, 56u8, 82u8, 250u8, 77u8, 226u8, 209u8, 16u8, 51u8, 146u8, 64u8,
        102u8, 211u8, 27u8, 189u8, 141u8, 229u8,
    ],
    vk_gamma_g2: [
        29u8, 196u8, 93u8, 153u8, 250u8, 116u8, 146u8, 222u8, 82u8, 0u8, 180u8, 181u8, 96u8, 72u8,
        251u8, 173u8, 223u8, 204u8, 176u8, 250u8, 8u8, 252u8, 7u8, 58u8, 33u8, 195u8, 247u8, 47u8,
        229u8, 176u8, 124u8, 18u8, 3u8, 210u8, 194u8, 77u8, 208u8, 239u8, 65u8, 107u8, 183u8,
        253u8, 43u8, 62u8, 168u8, 238u8, 49u8, 145u8, 91u8, 93u8, 234u8, 179u8, 42u8, 213u8, 91u8,
        16u8, 91u8, 161u8, 124u8, 85u8, 143u8, 51u8, 66u8, 157u8, 1u8, 128u8, 77u8, 121u8, 224u8,
        27u8, 111u8, 155u8, 212u8, 164u8, 153u8, 106u8, 37u8, 233u8, 207u8, 67u8, 152u8, 70u8,
        161u8, 97u8, 194u8, 151u8, 46u8, 59u8, 119u8, 62u8, 236u8, 61u8, 214u8, 39u8, 158u8, 187u8,
        26u8, 98u8, 101u8, 45u8, 81u8, 102u8, 148u8, 150u8, 62u8, 57u8, 115u8, 120u8, 27u8, 82u8,
        195u8, 221u8, 131u8, 8u8, 201u8, 72u8, 137u8, 197u8, 152u8, 158u8, 47u8, 1u8, 87u8, 137u8,
        245u8, 173u8, 88u8, 36u8,
    ],
    vk_delta_g2: [
        3u8, 167u8, 94u8, 221u8, 198u8, 108u8, 18u8, 40u8, 92u8, 18u8, 92u8, 36u8, 23u8, 48u8,
        95u8, 86u8, 55u8, 106u8, 18u8, 255u8, 42u8, 45u8, 181u8, 202u8, 139u8, 88u8, 46u8, 56u8,
        0u8, 190u8, 99u8, 229u8, 18u8, 246u8, 40u8, 39u8, 1u8, 110u8, 57u8, 38u8, 251u8, 11u8,
        23u8, 109u8, 49u8, 14u8, 253u8, 79u8, 203u8, 227u8, 138u8, 72u8, 240u8, 98u8, 206u8, 0u8,
        32u8, 150u8, 241u8, 146u8, 10u8, 4u8, 89u8, 64u8, 23u8, 204u8, 77u8, 17u8, 119u8, 217u8,
        239u8, 59u8, 1u8, 158u8, 67u8, 177u8, 112u8, 127u8, 145u8, 14u8, 16u8, 103u8, 88u8, 18u8,
        159u8, 247u8, 181u8, 211u8, 45u8, 228u8, 238u8, 33u8, 196u8, 253u8, 219u8, 20u8, 45u8, 2u8,
        213u8, 179u8, 65u8, 54u8, 149u8, 178u8, 109u8, 74u8, 232u8, 177u8, 13u8, 255u8, 252u8,
        56u8, 190u8, 70u8, 96u8, 140u8, 180u8, 173u8, 56u8, 142u8, 253u8, 207u8, 39u8, 130u8, 51u8,
        40u8, 36u8, 208u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [160u8, 148u8, 154u8, 11u8, 98u8, 89u8, 157u8, 34u8, 152u8, 160u8, 60u8, 33u8, 169u8, 237u8, 103u8, 236u8, 194u8, 188u8, 143u8, 120u8, 1u8, 171u8, 111u8, 185u8, 62u8, 156u8, 84u8, 250u8, 239u8, 53u8, 248u8, 62u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = true;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_467e3d9419449bc3")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00true\x00proving_key_sha256\x00a0949a0b62599d2298a03c21a9ed67ecc2bc8f7801ab6fb93e9c54faef35f83e\x00=======END GROTH16 VK SETUP V1=======\x00";

#[cfg(not(feature = "insecure-test-setup"))]
compile_error!("VERIFYINGKEY comes from an insecure test setup: whoever knows its setup randomness can make it accept a proof for any public inputs. Enable the `insecure-test-setup` feature only in test builds, not for a devnet or mainnet deployment.");
