// INSECURE TEST KEY -- UNSAFE FOR PRODUCTION.
// Generated with `--insecure-test-keys`: the Groth16 setup randomness comes
// from a fixed public seed, so anyone can forge proofs this key accepts. Use
// it only in tests and never deploy a program that verifies against it.
// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

// INSECURE TEST SETUP: the secret setup randomness is public or
// untrusted. Whoever knows it can make this verifying key accept a
// proof for any public inputs without a valid witness. Do not deploy
// it to devnet or mainnet.

use groth16_solana::groth16::{CommitmentVerifyingKey, Groth16Verifyingkey};

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        6u8, 16u8, 164u8, 159u8, 47u8, 159u8, 5u8, 236u8, 84u8, 201u8, 212u8, 133u8, 53u8, 203u8,
        81u8, 244u8, 51u8, 103u8, 108u8, 170u8, 181u8, 109u8, 142u8, 167u8, 248u8, 80u8, 230u8,
        82u8, 212u8, 168u8, 75u8, 194u8, 39u8, 197u8, 70u8, 32u8, 164u8, 67u8, 119u8, 12u8, 121u8,
        122u8, 116u8, 243u8, 120u8, 154u8, 47u8, 16u8, 215u8, 220u8, 163u8, 71u8, 109u8, 238u8,
        163u8, 128u8, 255u8, 185u8, 13u8, 118u8, 25u8, 218u8, 121u8, 108u8,
    ],
    [
        19u8, 15u8, 190u8, 35u8, 198u8, 79u8, 47u8, 184u8, 184u8, 10u8, 27u8, 28u8, 111u8, 3u8,
        36u8, 64u8, 120u8, 108u8, 125u8, 123u8, 61u8, 254u8, 227u8, 44u8, 33u8, 193u8, 111u8,
        217u8, 214u8, 61u8, 232u8, 230u8, 30u8, 115u8, 110u8, 242u8, 97u8, 115u8, 176u8, 167u8,
        103u8, 165u8, 208u8, 90u8, 40u8, 185u8, 85u8, 129u8, 240u8, 10u8, 46u8, 123u8, 152u8,
        105u8, 21u8, 213u8, 122u8, 43u8, 99u8, 72u8, 3u8, 126u8, 168u8, 39u8,
    ],
    [
        1u8, 183u8, 234u8, 207u8, 164u8, 222u8, 147u8, 24u8, 142u8, 102u8, 176u8, 61u8, 55u8,
        115u8, 191u8, 17u8, 157u8, 240u8, 69u8, 76u8, 190u8, 149u8, 214u8, 175u8, 119u8, 72u8,
        81u8, 136u8, 45u8, 144u8, 42u8, 182u8, 12u8, 79u8, 115u8, 125u8, 82u8, 181u8, 220u8, 207u8,
        170u8, 27u8, 108u8, 124u8, 209u8, 141u8, 6u8, 145u8, 27u8, 129u8, 182u8, 242u8, 231u8,
        59u8, 107u8, 88u8, 139u8, 170u8, 81u8, 134u8, 153u8, 58u8, 241u8, 171u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        12u8, 36u8, 150u8, 7u8, 67u8, 196u8, 53u8, 192u8, 3u8, 73u8, 39u8, 12u8, 98u8, 100u8, 0u8,
        236u8, 179u8, 174u8, 150u8, 196u8, 198u8, 17u8, 41u8, 139u8, 198u8, 245u8, 65u8, 136u8,
        131u8, 80u8, 184u8, 83u8, 19u8, 195u8, 218u8, 128u8, 241u8, 25u8, 171u8, 210u8, 21u8,
        240u8, 166u8, 31u8, 107u8, 142u8, 11u8, 231u8, 207u8, 78u8, 199u8, 22u8, 228u8, 148u8,
        172u8, 250u8, 35u8, 190u8, 231u8, 24u8, 90u8, 97u8, 179u8, 53u8,
    ],
    vk_beta_g2: [
        17u8, 52u8, 75u8, 85u8, 101u8, 195u8, 49u8, 234u8, 3u8, 247u8, 179u8, 27u8, 34u8, 126u8,
        43u8, 96u8, 137u8, 134u8, 54u8, 250u8, 63u8, 91u8, 6u8, 38u8, 230u8, 153u8, 198u8, 170u8,
        149u8, 244u8, 2u8, 189u8, 44u8, 183u8, 72u8, 46u8, 26u8, 93u8, 15u8, 196u8, 182u8, 137u8,
        123u8, 0u8, 163u8, 157u8, 228u8, 124u8, 200u8, 143u8, 206u8, 17u8, 169u8, 180u8, 244u8,
        90u8, 172u8, 217u8, 26u8, 80u8, 122u8, 148u8, 177u8, 185u8, 35u8, 159u8, 74u8, 194u8, 66u8,
        215u8, 224u8, 211u8, 43u8, 103u8, 201u8, 207u8, 235u8, 193u8, 233u8, 54u8, 148u8, 44u8,
        255u8, 169u8, 188u8, 10u8, 107u8, 14u8, 212u8, 137u8, 40u8, 35u8, 103u8, 22u8, 40u8, 130u8,
        36u8, 24u8, 8u8, 189u8, 120u8, 191u8, 116u8, 123u8, 79u8, 67u8, 225u8, 2u8, 182u8, 87u8,
        16u8, 211u8, 190u8, 174u8, 222u8, 193u8, 101u8, 213u8, 95u8, 94u8, 59u8, 122u8, 245u8,
        213u8, 243u8, 119u8, 63u8, 203u8,
    ],
    vk_gamma_g2: [
        5u8, 130u8, 52u8, 188u8, 142u8, 99u8, 255u8, 25u8, 191u8, 241u8, 40u8, 203u8, 15u8, 37u8,
        116u8, 57u8, 162u8, 21u8, 44u8, 127u8, 189u8, 159u8, 248u8, 254u8, 76u8, 184u8, 110u8,
        41u8, 229u8, 164u8, 187u8, 22u8, 30u8, 125u8, 83u8, 128u8, 2u8, 94u8, 123u8, 199u8, 94u8,
        126u8, 197u8, 99u8, 21u8, 95u8, 103u8, 59u8, 234u8, 138u8, 78u8, 3u8, 116u8, 57u8, 200u8,
        79u8, 172u8, 72u8, 50u8, 114u8, 203u8, 139u8, 177u8, 210u8, 11u8, 25u8, 231u8, 17u8, 139u8,
        172u8, 147u8, 220u8, 107u8, 3u8, 101u8, 110u8, 66u8, 4u8, 145u8, 222u8, 208u8, 215u8,
        101u8, 218u8, 112u8, 202u8, 168u8, 1u8, 18u8, 190u8, 1u8, 164u8, 225u8, 196u8, 210u8,
        181u8, 31u8, 136u8, 145u8, 27u8, 198u8, 110u8, 73u8, 210u8, 119u8, 250u8, 18u8, 241u8,
        78u8, 23u8, 36u8, 141u8, 67u8, 5u8, 229u8, 233u8, 222u8, 220u8, 11u8, 252u8, 145u8, 82u8,
        52u8, 3u8, 30u8, 58u8, 43u8, 114u8,
    ],
    vk_delta_g2: [
        27u8, 8u8, 10u8, 197u8, 91u8, 154u8, 44u8, 247u8, 217u8, 0u8, 54u8, 89u8, 100u8, 158u8,
        178u8, 8u8, 192u8, 215u8, 46u8, 149u8, 51u8, 182u8, 51u8, 248u8, 255u8, 57u8, 223u8, 160u8,
        31u8, 244u8, 246u8, 44u8, 10u8, 170u8, 248u8, 37u8, 159u8, 140u8, 90u8, 11u8, 239u8, 84u8,
        245u8, 73u8, 162u8, 45u8, 198u8, 158u8, 21u8, 237u8, 211u8, 230u8, 219u8, 129u8, 147u8,
        59u8, 240u8, 173u8, 112u8, 40u8, 92u8, 172u8, 70u8, 118u8, 3u8, 23u8, 175u8, 99u8, 18u8,
        69u8, 18u8, 91u8, 151u8, 234u8, 225u8, 82u8, 221u8, 20u8, 73u8, 183u8, 39u8, 22u8, 59u8,
        230u8, 125u8, 112u8, 38u8, 234u8, 42u8, 136u8, 69u8, 11u8, 105u8, 53u8, 1u8, 231u8, 36u8,
        36u8, 219u8, 197u8, 125u8, 11u8, 108u8, 63u8, 33u8, 45u8, 216u8, 28u8, 17u8, 139u8, 217u8,
        209u8, 92u8, 207u8, 237u8, 80u8, 26u8, 108u8, 110u8, 103u8, 229u8, 232u8, 27u8, 0u8, 134u8,
        231u8, 9u8, 236u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: Some(CommitmentVerifyingKey {
        g2: [
            28u8, 126u8, 180u8, 231u8, 30u8, 207u8, 107u8, 45u8, 217u8, 32u8, 124u8, 251u8, 80u8,
            69u8, 13u8, 174u8, 224u8, 6u8, 236u8, 38u8, 230u8, 211u8, 111u8, 68u8, 244u8, 116u8,
            251u8, 226u8, 247u8, 178u8, 123u8, 66u8, 41u8, 228u8, 78u8, 102u8, 62u8, 158u8, 224u8,
            235u8, 135u8, 241u8, 149u8, 98u8, 81u8, 163u8, 87u8, 115u8, 113u8, 251u8, 213u8, 117u8,
            185u8, 10u8, 67u8, 186u8, 213u8, 172u8, 134u8, 196u8, 82u8, 32u8, 242u8, 14u8, 10u8,
            223u8, 210u8, 203u8, 33u8, 48u8, 36u8, 5u8, 55u8, 149u8, 106u8, 231u8, 214u8, 189u8,
            49u8, 113u8, 41u8, 232u8, 117u8, 218u8, 194u8, 96u8, 79u8, 70u8, 141u8, 19u8, 124u8,
            56u8, 47u8, 181u8, 188u8, 37u8, 47u8, 200u8, 88u8, 133u8, 149u8, 147u8, 139u8, 74u8,
            95u8, 213u8, 0u8, 38u8, 140u8, 46u8, 102u8, 147u8, 92u8, 103u8, 78u8, 180u8, 22u8,
            171u8, 233u8, 98u8, 242u8, 171u8, 23u8, 5u8, 22u8, 122u8, 136u8, 132u8,
        ],
        g_sigma_neg_g2: [
            21u8, 67u8, 134u8, 130u8, 146u8, 88u8, 20u8, 107u8, 39u8, 225u8, 204u8, 97u8, 140u8,
            151u8, 38u8, 8u8, 126u8, 89u8, 207u8, 244u8, 46u8, 76u8, 64u8, 229u8, 89u8, 166u8,
            120u8, 113u8, 232u8, 45u8, 20u8, 190u8, 28u8, 255u8, 105u8, 23u8, 254u8, 40u8, 6u8,
            179u8, 156u8, 55u8, 49u8, 216u8, 49u8, 243u8, 86u8, 106u8, 43u8, 153u8, 20u8, 66u8,
            26u8, 142u8, 33u8, 56u8, 126u8, 39u8, 35u8, 220u8, 156u8, 54u8, 196u8, 65u8, 11u8,
            11u8, 98u8, 38u8, 37u8, 185u8, 153u8, 57u8, 168u8, 102u8, 202u8, 221u8, 219u8, 19u8,
            160u8, 18u8, 230u8, 25u8, 203u8, 12u8, 241u8, 129u8, 44u8, 96u8, 39u8, 172u8, 156u8,
            183u8, 165u8, 204u8, 193u8, 219u8, 23u8, 56u8, 139u8, 99u8, 59u8, 76u8, 152u8, 61u8,
            108u8, 142u8, 115u8, 82u8, 255u8, 89u8, 78u8, 98u8, 183u8, 96u8, 145u8, 246u8, 204u8,
            250u8, 18u8, 156u8, 136u8, 4u8, 41u8, 63u8, 55u8, 58u8, 139u8, 159u8,
        ],
    }),
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [22u8, 24u8, 120u8, 114u8, 141u8, 4u8, 93u8, 207u8, 91u8, 22u8, 229u8, 175u8, 107u8, 16u8, 249u8, 113u8, 132u8, 173u8, 64u8, 87u8, 117u8, 76u8, 98u8, 116u8, 218u8, 119u8, 41u8, 213u8, 35u8, 161u8, 111u8, 135u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = true;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_04da6365aa4a576d")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00true\x00proving_key_sha256\x00161878728d045dcf5b16e5af6b10f97184ad4057754c6274da7729d523a16f87\x00=======END GROTH16 VK SETUP V1=======\x00";

#[cfg(not(feature = "insecure-test-setup"))]
compile_error!("VERIFYINGKEY comes from an insecure test setup: whoever knows its setup randomness can make it accept a proof for any public inputs. Enable the `insecure-test-setup` feature only in test builds, not for a devnet or mainnet deployment.");
