[package]
name = "compression-example-program"
version = "0.1.0"
edition.workspace = true
publish = false

[lib]
name = "compression_example_program"
crate-type = ["cdylib", "lib"]

[features]
default = []
bpf-entrypoint = []
no-entrypoint = []
cpi = ["no-entrypoint"]
test-sbf = []
profile-program = ["light-program-profiler/profile-program"]

[dependencies]
borsh = { workspace = true }
light-program-profiler = { workspace = true }
pinocchio = { workspace = true, features = ["cpi"] }
solana-address = { workspace = true }
solana-program-error = { workspace = true }
thiserror = { workspace = true }
wincode = { workspace = true }
zolana-account-checks = { workspace = true }
zolana-hasher = { workspace = true }
zolana-interface = { workspace = true }
zolana-program = { workspace = true }

[dev-dependencies]
hex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
zolana-client = { workspace = true }
zolana-keypair = { workspace = true }
zolana-transaction = { workspace = true }

[lints.rust.unexpected_cfgs]
level = "allow"
check-cfg = [
    'cfg(target_os, values("solana"))',
    'cfg(feature, values("frozen-abi", "no-entrypoint"))',
]
