//! Shared cross-language key-derivation vectors.
//!
//! `test-vectors/key_derivation.json` pins the derivation tree for every
//! implementation (Rust here, TypeScript in `sdk-libs/ts`). The values are
//! generated by this crate: run the ignored printer and commit its output
//! whenever a new section is added:
//!
//! ```bash
//! cargo test -p zolana-keypair --test vectors print_key_derivation_vectors -- --ignored --nocapture
//! ```
//!
//! The `merge_recovery` section is computed by `zolana-transaction` (the merge
//! derivations live there); this file carries it through unchanged and
//! `sdk-libs/transaction/tests/merge.rs` asserts it.

use serde::{Deserialize, Serialize};
use zolana_keypair::{
    derivation::{ed25519_derivation_message, is_derivation_input, MERGE_INFO},
    symmetric_apply, ShieldedKeypair, SigningKey, ViewingKey,
};

const VECTORS_JSON: &str = include_str!("../../../test-vectors/key_derivation.json");

#[derive(Serialize, Deserialize, PartialEq, Debug, Clone)]
struct KeyDerivationVectors {
    ed25519_rail: Ed25519Rail,
    p256_rail: P256Rail,
    tx_viewing: TxViewing,
    hpke_utxo: HpkeUtxo,
    owner: Owner,
    key_schedule: KeySchedule,
    merge_recovery: MergeRecovery,
    derivation_input_guard: Vec<GuardCase>,
}

#[derive(Serialize, Deserialize, PartialEq, Debug, Clone)]
struct Ed25519Rail {
    signing_secret: String,
    signer_pubkey: String,
    derivation_message: String,
    derivation_seed: String,
    nullifier_secret: String,
    nullifier_pubkey: String,
    viewing_secret: String,
    viewing_pubkey: String,
}

#[derive(Serialize, Deserialize, PartialEq, Debug, Clone)]
struct P256Rail {
    signing_secret: String,
    derivation_seed: String,
    nullifier_secret: String,
    nullifier_pubkey: String,
    viewing_secret: String,
    viewing_pubkey: String,
}

#[derive(Serialize, Deserialize, PartialEq, Debug, Clone)]
struct TxViewing {
    viewing_secret: String,
    first_nullifier: String,
    tx_viewing_secret: String,
    tx_viewing_pubkey: String,
}

#[derive(Serialize, Deserialize, PartialEq, Debug, Clone)]
struct HpkeUtxo {
    recipient_secret: String,
    ephemeral_secret: String,
    salt: String,
    slot_index: u32,
    plaintext: String,
    ciphertext: String,
}

#[derive(Serialize, Deserialize, PartialEq, Debug, Clone)]
struct Owner {
    signing_secret: String,
    owner_proof_input_hash: String,
    nullifier_pubkey: String,
    viewing_pubkey: String,
    owner_hash: String,
    compressed_address_hash: String,
}

#[derive(Serialize, Deserialize, PartialEq, Debug, Clone)]
struct KeySchedule {
    shared_secret: String,
    info: String,
    plaintext: String,
    ciphertext: String,
}

#[derive(Serialize, Deserialize, PartialEq, Debug, Clone)]
struct MergeRecovery {
    nullifier_secret: String,
    first_nullifier: String,
    output_blinding: String,
    dummy_slot_index: u8,
    dummy_nullifier: String,
    private_tx_blinding: String,
}

#[derive(Serialize, Deserialize, PartialEq, Debug, Clone)]
struct GuardCase {
    name: String,
    message: String,
    is_derivation_input: bool,
}

fn scalar_bytes(n: u8) -> [u8; 32] {
    let mut scalar = [0u8; 32];
    scalar[31] = n;
    scalar
}

fn compute_ed25519_rail() -> Ed25519Rail {
    let signing_secret = [7u8; 32];
    let signing_key = SigningKey::from_ed25519_bytes(&signing_secret);
    let signer_pubkey = signing_key.pubkey().as_ed25519().unwrap();
    let derivation_message = ed25519_derivation_message(&signer_pubkey);
    let derivation_seed = signing_key.derivation_seed().unwrap();
    let keypair = ShieldedKeypair::from_keypair(signing_key).unwrap();
    Ed25519Rail {
        signing_secret: hex::encode(signing_secret),
        signer_pubkey: hex::encode(signer_pubkey),
        derivation_message: hex::encode(derivation_message),
        derivation_seed: hex::encode(derivation_seed.as_slice()),
        nullifier_secret: hex::encode(keypair.nullifier_key.secret().as_slice()),
        nullifier_pubkey: hex::encode(keypair.nullifier_key.pubkey().unwrap()),
        viewing_secret: hex::encode(keypair.viewing_key.secret_bytes().as_slice()),
        viewing_pubkey: hex::encode(keypair.viewing_pubkey().as_bytes()),
    }
}

fn compute_p256_rail() -> P256Rail {
    let signing_secret = scalar_bytes(9);
    let signing_key = SigningKey::from_p256_bytes(&signing_secret).unwrap();
    let derivation_seed = signing_key.derivation_seed().unwrap();
    let keypair = ShieldedKeypair::from_keypair(signing_key).unwrap();
    P256Rail {
        signing_secret: hex::encode(signing_secret),
        derivation_seed: hex::encode(derivation_seed.as_slice()),
        nullifier_secret: hex::encode(keypair.nullifier_key.secret().as_slice()),
        nullifier_pubkey: hex::encode(keypair.nullifier_key.pubkey().unwrap()),
        viewing_secret: hex::encode(keypair.viewing_key.secret_bytes().as_slice()),
        viewing_pubkey: hex::encode(keypair.viewing_pubkey().as_bytes()),
    }
}

fn compute_tx_viewing() -> TxViewing {
    let viewing_secret = scalar_bytes(3);
    let viewing_key = ViewingKey::from_bytes(&viewing_secret).unwrap();
    let first_nullifier = scalar_bytes(11);
    let tx_viewing_key = viewing_key
        .get_transaction_viewing_key(&first_nullifier)
        .unwrap();
    TxViewing {
        viewing_secret: hex::encode(viewing_secret),
        first_nullifier: hex::encode(first_nullifier),
        tx_viewing_secret: hex::encode(tx_viewing_key.secret_bytes().as_slice()),
        tx_viewing_pubkey: hex::encode(tx_viewing_key.pubkey().as_bytes()),
    }
}

fn compute_hpke_utxo() -> HpkeUtxo {
    let recipient_secret = scalar_bytes(2);
    let ephemeral_secret = scalar_bytes(1);
    let recipient = ViewingKey::from_bytes(&recipient_secret).unwrap();
    let ephemeral = ViewingKey::from_bytes(&ephemeral_secret).unwrap();
    let salt = [0u8; 16];
    let slot_index = 0;
    let plaintext = b"deterministic";
    let ciphertext = ephemeral
        .encrypt_slot(&recipient.pubkey(), plaintext, salt, slot_index)
        .unwrap();
    HpkeUtxo {
        recipient_secret: hex::encode(recipient_secret),
        ephemeral_secret: hex::encode(ephemeral_secret),
        salt: hex::encode(salt),
        slot_index,
        plaintext: hex::encode(plaintext),
        ciphertext: hex::encode(ciphertext),
    }
}

fn compute_owner() -> Owner {
    let signing_secret = scalar_bytes(1);
    let signing_key = SigningKey::from_p256_bytes(&signing_secret).unwrap();
    let keypair = ShieldedKeypair::from_keypair(signing_key).unwrap();
    Owner {
        signing_secret: hex::encode(signing_secret),
        owner_proof_input_hash: hex::encode(
            keypair.signing_pubkey().owner_proof_input_hash().unwrap(),
        ),
        nullifier_pubkey: hex::encode(keypair.nullifier_key.pubkey().unwrap()),
        viewing_pubkey: hex::encode(keypair.viewing_pubkey().as_bytes()),
        owner_hash: hex::encode(keypair.owner_hash().unwrap()),
        compressed_address_hash: hex::encode(keypair.compressed_address().unwrap().hash().unwrap()),
    }
}

fn compute_key_schedule() -> KeySchedule {
    let mut shared_secret = [0x11u8; 32];
    shared_secret[0] = 0;
    let plaintext = b"deterministic";
    let mut ciphertext = plaintext.to_vec();
    symmetric_apply(&shared_secret, MERGE_INFO, &mut ciphertext).unwrap();
    KeySchedule {
        shared_secret: hex::encode(shared_secret),
        info: hex::encode(MERGE_INFO),
        plaintext: hex::encode(plaintext),
        ciphertext: hex::encode(ciphertext),
    }
}

fn compute_derivation_input_guard() -> Vec<GuardCase> {
    let signer_pubkey = [7u8; 32];
    let wrapped = ed25519_derivation_message(&signer_pubkey);
    let truncated = wrapped
        .get(..wrapped.len() - 1)
        .expect("message is non-empty")
        .to_vec();
    let mut bad_version = wrapped.clone();
    if let Some(version) = bad_version.get_mut(16) {
        *version = 1;
    }
    let cases: Vec<(&str, Vec<u8>)> = vec![
        ("bare_payload", b"TSPP/derive/v1".to_vec()),
        ("bare_prefix_future_version", b"TSPP/derive/v2".to_vec()),
        ("offchain_wrapped", wrapped),
        ("offchain_truncated", truncated),
        ("offchain_bad_version", bad_version),
        ("prefix_without_slash", b"TSPP/derive".to_vec()),
        ("plain_message", b"hello world".to_vec()),
    ];
    cases
        .into_iter()
        .map(|(name, message)| GuardCase {
            name: name.to_string(),
            is_derivation_input: is_derivation_input(&message),
            message: hex::encode(message),
        })
        .collect()
}

fn compute(merge_recovery: MergeRecovery) -> KeyDerivationVectors {
    KeyDerivationVectors {
        ed25519_rail: compute_ed25519_rail(),
        p256_rail: compute_p256_rail(),
        tx_viewing: compute_tx_viewing(),
        hpke_utxo: compute_hpke_utxo(),
        owner: compute_owner(),
        key_schedule: compute_key_schedule(),
        merge_recovery,
        derivation_input_guard: compute_derivation_input_guard(),
    }
}

#[test]
fn shared_vectors_match() {
    let committed: KeyDerivationVectors = serde_json::from_str(VECTORS_JSON).unwrap();
    let recomputed = compute(committed.merge_recovery.clone());
    assert_eq!(committed, recomputed);

    let recipient_secret: [u8; 32] = hex::decode(&committed.hpke_utxo.recipient_secret)
        .unwrap()
        .try_into()
        .unwrap();
    let ephemeral_secret: [u8; 32] = hex::decode(&committed.hpke_utxo.ephemeral_secret)
        .unwrap()
        .try_into()
        .unwrap();
    let salt: [u8; 16] = hex::decode(&committed.hpke_utxo.salt)
        .unwrap()
        .try_into()
        .unwrap();
    let recipient = ViewingKey::from_bytes(&recipient_secret).unwrap();
    let ephemeral = ViewingKey::from_bytes(&ephemeral_secret).unwrap();
    let ciphertext = hex::decode(&committed.hpke_utxo.ciphertext).unwrap();
    let decrypted = recipient
        .decrypt_utxo(
            &ciphertext,
            &ephemeral.pubkey(),
            salt,
            committed.hpke_utxo.slot_index,
        )
        .unwrap();
    assert_eq!(hex::encode(decrypted), committed.hpke_utxo.plaintext);

    let shared_secret: [u8; 32] = hex::decode(&committed.key_schedule.shared_secret)
        .unwrap()
        .try_into()
        .unwrap();
    let mut round_trip = hex::decode(&committed.key_schedule.ciphertext).unwrap();
    symmetric_apply(&shared_secret, MERGE_INFO, &mut round_trip).unwrap();
    assert_eq!(hex::encode(round_trip), committed.key_schedule.plaintext);
}

#[test]
#[ignore = "regenerates test-vectors/key_derivation.json; run with --nocapture and commit the output"]
fn print_key_derivation_vectors() {
    let committed: KeyDerivationVectors = serde_json::from_str(VECTORS_JSON).unwrap();
    let recomputed = compute(committed.merge_recovery);
    println!("{}", serde_json::to_string_pretty(&recomputed).unwrap());
}
