// INSECURE TEST KEY -- UNSAFE FOR PRODUCTION.
// Generated with `--insecure-test-keys`: the Groth16 setup randomness comes
// from a fixed public seed, so anyone can forge proofs this key accepts. Use
// it only in tests and never deploy a program that verifies against it.
// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

// INSECURE TEST SETUP: the secret setup randomness is public or
// untrusted. Whoever knows it can make this verifying key accept a
// proof for any public inputs without a valid witness. Do not deploy
// it to devnet or mainnet.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        42u8, 21u8, 37u8, 127u8, 3u8, 162u8, 38u8, 179u8, 141u8, 152u8, 99u8, 194u8, 148u8, 28u8,
        66u8, 198u8, 143u8, 64u8, 168u8, 17u8, 178u8, 52u8, 127u8, 53u8, 94u8, 35u8, 54u8, 111u8,
        41u8, 97u8, 103u8, 174u8, 20u8, 6u8, 126u8, 227u8, 113u8, 37u8, 203u8, 63u8, 194u8, 234u8,
        31u8, 16u8, 91u8, 10u8, 49u8, 107u8, 197u8, 139u8, 177u8, 122u8, 76u8, 141u8, 37u8, 222u8,
        220u8, 235u8, 138u8, 220u8, 162u8, 254u8, 118u8, 82u8,
    ],
    [
        28u8, 25u8, 180u8, 244u8, 48u8, 181u8, 71u8, 189u8, 33u8, 57u8, 1u8, 153u8, 104u8, 212u8,
        216u8, 214u8, 224u8, 185u8, 100u8, 85u8, 198u8, 115u8, 5u8, 22u8, 147u8, 189u8, 251u8,
        64u8, 134u8, 28u8, 222u8, 116u8, 38u8, 242u8, 119u8, 35u8, 247u8, 241u8, 16u8, 231u8,
        183u8, 204u8, 132u8, 183u8, 162u8, 107u8, 104u8, 131u8, 138u8, 38u8, 200u8, 124u8, 62u8,
        196u8, 31u8, 137u8, 112u8, 26u8, 99u8, 48u8, 201u8, 223u8, 146u8, 41u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        15u8, 116u8, 103u8, 209u8, 82u8, 28u8, 213u8, 153u8, 141u8, 136u8, 60u8, 126u8, 193u8,
        252u8, 220u8, 161u8, 222u8, 203u8, 61u8, 122u8, 133u8, 89u8, 81u8, 4u8, 150u8, 61u8, 237u8,
        118u8, 60u8, 48u8, 109u8, 48u8, 30u8, 207u8, 175u8, 193u8, 108u8, 70u8, 232u8, 78u8, 235u8,
        147u8, 102u8, 179u8, 162u8, 54u8, 196u8, 137u8, 112u8, 58u8, 177u8, 27u8, 254u8, 34u8,
        167u8, 146u8, 86u8, 108u8, 232u8, 177u8, 115u8, 94u8, 14u8, 208u8,
    ],
    vk_beta_g2: [
        25u8, 174u8, 68u8, 6u8, 97u8, 76u8, 110u8, 240u8, 112u8, 50u8, 75u8, 121u8, 119u8, 213u8,
        16u8, 255u8, 184u8, 48u8, 133u8, 108u8, 45u8, 130u8, 203u8, 40u8, 86u8, 254u8, 103u8,
        248u8, 196u8, 26u8, 212u8, 205u8, 9u8, 3u8, 212u8, 226u8, 239u8, 79u8, 171u8, 36u8, 4u8,
        71u8, 127u8, 182u8, 114u8, 27u8, 153u8, 91u8, 53u8, 242u8, 72u8, 11u8, 114u8, 154u8, 23u8,
        92u8, 76u8, 5u8, 117u8, 212u8, 43u8, 241u8, 27u8, 39u8, 26u8, 209u8, 27u8, 143u8, 251u8,
        20u8, 3u8, 133u8, 134u8, 236u8, 137u8, 235u8, 118u8, 18u8, 242u8, 64u8, 1u8, 67u8, 49u8,
        229u8, 17u8, 149u8, 144u8, 191u8, 219u8, 190u8, 202u8, 33u8, 41u8, 134u8, 51u8, 20u8, 17u8,
        69u8, 144u8, 38u8, 13u8, 50u8, 7u8, 108u8, 59u8, 120u8, 184u8, 78u8, 218u8, 148u8, 145u8,
        182u8, 110u8, 236u8, 244u8, 112u8, 152u8, 15u8, 34u8, 205u8, 8u8, 167u8, 213u8, 115u8,
        27u8, 131u8, 50u8, 56u8,
    ],
    vk_gamma_g2: [
        18u8, 159u8, 188u8, 251u8, 242u8, 0u8, 2u8, 39u8, 145u8, 207u8, 222u8, 233u8, 224u8, 202u8,
        170u8, 243u8, 190u8, 61u8, 234u8, 175u8, 80u8, 23u8, 211u8, 86u8, 72u8, 151u8, 221u8,
        219u8, 86u8, 71u8, 229u8, 107u8, 28u8, 15u8, 155u8, 152u8, 48u8, 71u8, 19u8, 120u8, 47u8,
        156u8, 188u8, 149u8, 11u8, 245u8, 206u8, 60u8, 98u8, 120u8, 98u8, 76u8, 245u8, 63u8, 28u8,
        82u8, 158u8, 56u8, 50u8, 217u8, 26u8, 56u8, 30u8, 243u8, 38u8, 215u8, 115u8, 134u8, 82u8,
        181u8, 147u8, 37u8, 159u8, 134u8, 251u8, 72u8, 144u8, 141u8, 135u8, 5u8, 114u8, 228u8, 9u8,
        237u8, 13u8, 20u8, 121u8, 162u8, 236u8, 176u8, 146u8, 65u8, 144u8, 110u8, 48u8, 111u8,
        23u8, 1u8, 96u8, 94u8, 234u8, 77u8, 147u8, 57u8, 124u8, 216u8, 219u8, 53u8, 171u8, 11u8,
        7u8, 47u8, 116u8, 49u8, 245u8, 249u8, 235u8, 232u8, 62u8, 39u8, 215u8, 20u8, 178u8, 11u8,
        39u8, 245u8, 214u8, 192u8,
    ],
    vk_delta_g2: [
        23u8, 65u8, 157u8, 70u8, 132u8, 215u8, 113u8, 2u8, 135u8, 84u8, 17u8, 132u8, 154u8, 254u8,
        191u8, 99u8, 251u8, 202u8, 227u8, 227u8, 8u8, 144u8, 58u8, 157u8, 192u8, 230u8, 157u8,
        36u8, 153u8, 4u8, 208u8, 242u8, 20u8, 221u8, 252u8, 207u8, 178u8, 165u8, 224u8, 142u8,
        242u8, 60u8, 249u8, 243u8, 153u8, 54u8, 112u8, 138u8, 111u8, 69u8, 118u8, 7u8, 101u8,
        139u8, 209u8, 202u8, 171u8, 138u8, 107u8, 152u8, 248u8, 114u8, 212u8, 177u8, 17u8, 209u8,
        141u8, 191u8, 82u8, 173u8, 192u8, 239u8, 73u8, 67u8, 5u8, 94u8, 253u8, 9u8, 218u8, 24u8,
        23u8, 185u8, 129u8, 166u8, 69u8, 51u8, 247u8, 194u8, 54u8, 125u8, 159u8, 255u8, 171u8,
        195u8, 251u8, 115u8, 43u8, 248u8, 244u8, 233u8, 229u8, 45u8, 239u8, 23u8, 186u8, 108u8,
        107u8, 242u8, 138u8, 156u8, 170u8, 192u8, 62u8, 44u8, 192u8, 114u8, 115u8, 229u8, 22u8,
        231u8, 216u8, 162u8, 130u8, 204u8, 192u8, 75u8, 139u8, 229u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [247u8, 82u8, 8u8, 160u8, 127u8, 196u8, 46u8, 86u8, 241u8, 155u8, 241u8, 127u8, 181u8, 242u8, 226u8, 116u8, 132u8, 71u8, 57u8, 157u8, 127u8, 9u8, 156u8, 22u8, 3u8, 212u8, 86u8, 162u8, 238u8, 220u8, 223u8, 147u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = true;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_c317a1601c94837b")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00true\x00proving_key_sha256\x00f75208a07fc42e56f19bf17fb5f2e2748447399d7f099c1603d456a2eedcdf93\x00=======END GROTH16 VK SETUP V1=======\x00";

#[cfg(not(feature = "insecure-test-setup"))]
compile_error!("VERIFYINGKEY comes from an insecure test setup: whoever knows its setup randomness can make it accept a proof for any public inputs. Enable the `insecure-test-setup` feature only in test builds, not for a devnet or mainnet deployment.");
