// INSECURE TEST KEY -- UNSAFE FOR PRODUCTION.
// Generated with `--insecure-test-keys`: the Groth16 setup randomness comes
// from a fixed public seed, so anyone can forge proofs this key accepts. Use
// it only in tests and never deploy a program that verifies against it.
// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

// INSECURE TEST SETUP: the secret setup randomness is public or
// untrusted. Whoever knows it can make this verifying key accept a
// proof for any public inputs without a valid witness. Do not deploy
// it to devnet or mainnet.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        5u8, 245u8, 138u8, 96u8, 192u8, 133u8, 194u8, 55u8, 12u8, 72u8, 219u8, 154u8, 6u8, 67u8,
        128u8, 66u8, 163u8, 50u8, 124u8, 252u8, 241u8, 247u8, 81u8, 243u8, 224u8, 77u8, 198u8,
        190u8, 85u8, 112u8, 72u8, 55u8, 47u8, 29u8, 63u8, 9u8, 160u8, 185u8, 226u8, 182u8, 40u8,
        81u8, 236u8, 168u8, 141u8, 38u8, 229u8, 102u8, 139u8, 95u8, 205u8, 42u8, 143u8, 3u8, 95u8,
        126u8, 8u8, 24u8, 119u8, 153u8, 144u8, 68u8, 134u8, 197u8,
    ],
    [
        29u8, 48u8, 185u8, 140u8, 96u8, 15u8, 155u8, 44u8, 73u8, 187u8, 208u8, 83u8, 52u8, 31u8,
        26u8, 30u8, 181u8, 9u8, 24u8, 14u8, 252u8, 46u8, 241u8, 34u8, 104u8, 30u8, 195u8, 99u8,
        177u8, 121u8, 242u8, 222u8, 0u8, 15u8, 48u8, 60u8, 163u8, 32u8, 61u8, 186u8, 163u8, 242u8,
        92u8, 83u8, 31u8, 38u8, 225u8, 162u8, 93u8, 140u8, 178u8, 164u8, 205u8, 67u8, 203u8, 13u8,
        187u8, 153u8, 210u8, 75u8, 145u8, 104u8, 51u8, 91u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        27u8, 49u8, 10u8, 15u8, 86u8, 160u8, 5u8, 1u8, 144u8, 78u8, 131u8, 162u8, 3u8, 21u8, 5u8,
        119u8, 169u8, 195u8, 39u8, 74u8, 101u8, 35u8, 108u8, 8u8, 73u8, 109u8, 15u8, 61u8, 108u8,
        239u8, 74u8, 37u8, 38u8, 24u8, 174u8, 7u8, 178u8, 20u8, 225u8, 94u8, 137u8, 174u8, 8u8,
        248u8, 194u8, 14u8, 157u8, 240u8, 254u8, 45u8, 57u8, 89u8, 119u8, 187u8, 66u8, 91u8, 233u8,
        252u8, 239u8, 212u8, 130u8, 153u8, 128u8, 65u8,
    ],
    vk_beta_g2: [
        19u8, 182u8, 129u8, 63u8, 214u8, 70u8, 138u8, 203u8, 96u8, 153u8, 147u8, 219u8, 41u8,
        212u8, 83u8, 41u8, 5u8, 91u8, 153u8, 75u8, 106u8, 159u8, 45u8, 95u8, 138u8, 168u8, 34u8,
        210u8, 171u8, 98u8, 127u8, 216u8, 26u8, 169u8, 138u8, 151u8, 56u8, 99u8, 87u8, 38u8, 222u8,
        156u8, 64u8, 70u8, 143u8, 141u8, 50u8, 173u8, 199u8, 113u8, 46u8, 227u8, 107u8, 244u8,
        186u8, 67u8, 44u8, 137u8, 57u8, 170u8, 151u8, 245u8, 247u8, 115u8, 26u8, 18u8, 147u8,
        138u8, 121u8, 237u8, 190u8, 35u8, 217u8, 182u8, 105u8, 84u8, 63u8, 2u8, 70u8, 123u8, 228u8,
        138u8, 139u8, 117u8, 30u8, 137u8, 122u8, 177u8, 245u8, 207u8, 238u8, 154u8, 153u8, 141u8,
        0u8, 141u8, 43u8, 184u8, 179u8, 26u8, 202u8, 171u8, 74u8, 224u8, 80u8, 92u8, 187u8, 113u8,
        199u8, 179u8, 132u8, 113u8, 8u8, 101u8, 212u8, 163u8, 80u8, 228u8, 23u8, 238u8, 209u8,
        35u8, 38u8, 170u8, 190u8, 11u8, 179u8, 77u8,
    ],
    vk_gamma_g2: [
        39u8, 29u8, 43u8, 30u8, 247u8, 40u8, 150u8, 28u8, 61u8, 190u8, 97u8, 41u8, 15u8, 135u8,
        48u8, 208u8, 10u8, 237u8, 36u8, 21u8, 6u8, 19u8, 116u8, 202u8, 156u8, 71u8, 161u8, 108u8,
        117u8, 63u8, 153u8, 184u8, 25u8, 153u8, 215u8, 34u8, 27u8, 5u8, 34u8, 160u8, 41u8, 188u8,
        237u8, 65u8, 132u8, 176u8, 121u8, 6u8, 139u8, 161u8, 43u8, 23u8, 111u8, 166u8, 216u8, 7u8,
        60u8, 251u8, 159u8, 153u8, 81u8, 46u8, 118u8, 8u8, 21u8, 34u8, 122u8, 46u8, 76u8, 217u8,
        253u8, 9u8, 197u8, 66u8, 151u8, 244u8, 7u8, 241u8, 220u8, 252u8, 50u8, 237u8, 255u8, 89u8,
        161u8, 31u8, 52u8, 190u8, 34u8, 136u8, 132u8, 51u8, 170u8, 121u8, 154u8, 37u8, 45u8, 46u8,
        210u8, 222u8, 29u8, 67u8, 149u8, 13u8, 179u8, 179u8, 210u8, 206u8, 126u8, 155u8, 181u8,
        162u8, 223u8, 215u8, 123u8, 115u8, 29u8, 85u8, 116u8, 207u8, 18u8, 122u8, 127u8, 151u8,
        146u8, 228u8, 217u8, 165u8,
    ],
    vk_delta_g2: [
        31u8, 115u8, 105u8, 229u8, 175u8, 54u8, 90u8, 63u8, 68u8, 200u8, 56u8, 12u8, 9u8, 113u8,
        101u8, 1u8, 155u8, 55u8, 150u8, 62u8, 104u8, 248u8, 181u8, 44u8, 58u8, 141u8, 174u8, 131u8,
        108u8, 166u8, 121u8, 54u8, 2u8, 39u8, 206u8, 170u8, 198u8, 42u8, 131u8, 67u8, 171u8, 147u8,
        14u8, 51u8, 68u8, 124u8, 113u8, 240u8, 35u8, 60u8, 106u8, 72u8, 55u8, 221u8, 5u8, 51u8,
        183u8, 99u8, 193u8, 251u8, 172u8, 209u8, 84u8, 237u8, 27u8, 244u8, 161u8, 230u8, 111u8,
        105u8, 135u8, 6u8, 81u8, 2u8, 65u8, 71u8, 234u8, 51u8, 243u8, 184u8, 96u8, 99u8, 149u8,
        247u8, 253u8, 235u8, 221u8, 41u8, 12u8, 83u8, 134u8, 127u8, 140u8, 209u8, 17u8, 24u8, 9u8,
        152u8, 222u8, 142u8, 157u8, 166u8, 92u8, 202u8, 98u8, 31u8, 166u8, 37u8, 44u8, 199u8, 85u8,
        220u8, 93u8, 37u8, 10u8, 64u8, 109u8, 43u8, 83u8, 101u8, 119u8, 128u8, 195u8, 244u8, 131u8,
        24u8, 242u8, 171u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [112u8, 153u8, 206u8, 26u8, 121u8, 68u8, 69u8, 156u8, 171u8, 14u8, 154u8, 19u8, 147u8, 210u8, 156u8, 179u8, 77u8, 168u8, 28u8, 215u8, 195u8, 50u8, 12u8, 194u8, 246u8, 93u8, 3u8, 142u8, 8u8, 188u8, 19u8, 67u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = true;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_a8b9928be3ac411f")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00true\x00proving_key_sha256\x007099ce1a7944459cab0e9a1393d29cb34da81cd7c3320cc2f65d038e08bc1343\x00=======END GROTH16 VK SETUP V1=======\x00";

#[cfg(not(feature = "insecure-test-setup"))]
compile_error!("VERIFYINGKEY comes from an insecure test setup: whoever knows its setup randomness can make it accept a proof for any public inputs. Enable the `insecure-test-setup` feature only in test builds, not for a devnet or mainnet deployment.");
